### ISSUE TITLE
Attachments not appearing in logs

### ISSUE THREAD

**Issue by AlexO-123** [reportportal/reportportal#2162] opened 2023-10-20 14:17 UTC
We send multiple attachments (screenshots png) to a launch.

The HTTP request seem to be successful giving a 2xx response with an Array of ids:

```
{"responses":[{"id":"7eb06df5-b7cc-47c2-a11e-0bbe2ae320e0"},{"id":"a7942a0a-d18d-4f9f-81bd-62a72b011126"},{"id":"6bef7531-4d04-4973-998f-c381c00c4db3"},{"id":"12850ca6-8b39-4fec-8dc6-cfd2806b0878"},{"id":"2f8f4157-7ccf-4112-bf22-e82f123ed596"}]}
```

However, these attachments do not always appear on the launch: 

![image](https://github.com/reportportal/reportportal/assets/16059884/64086c17-b0b5-480b-9b2c-5e7827d14185)

This is very consistent when we have approx. > 3 attachments.

These files are not large ~ 267 KB

...

Expect all attachments to appear within a launch
...

**Screenshots**
If applicable

**Versions:**
- RP UI and API 5.8.0

**Comment by HardNorth** [comment] 2023-10-20 19:18
@AlexO-123 Which framework do you use and which agent version?

**Comment by AlexO-123** [comment] 2023-10-23 08:40
@HardNorth 
Thanks for the speedy response! 

We use Ruby and integrate with RP using the [parallel_report_portal gem](https://rubygems.org/gems/parallel_report_portal) (which we maintain)

This issue can be replicated by making a multipart curl request to the RP API.

**Comment by DzmitryHumianiuk** [comment] 2023-10-24 18:22
Hi @AlexO-123, just to clarify, you're saying that when you send a multipart request with more than three lines of logs, and each log has an attachment, the attachment doesn't always appear in some instances. Is that correct?

**Comment by AlexO-123** [comment] 2023-10-27 08:37
Hey @DzmitryHumianiuk 
Yup that's right.
We have seen attachments not pop up when attaching even less however three seems to cause the most inconsistencies

**Comment by DzmitryHumianiuk** [comment] 2023-10-30 21:49
@VolhaKarenko @alena-babrova could you please verify this?
seems to be a strange bug.

**Comment by alena-babrova** [comment] 2023-10-31 18:09
Hello @AlexO-123,
Yes, the bug is reproduced. This happens when sending several **identical** files (3+ in a row as you mentioned above).
I've created a bug into our backlog. 
Thank you for highlighting it!

**Comment by alena-babrova** [comment] 2024-05-15 09:19
Hello @AlexO-123,
I'm pleased to let you know that the fix has been released.
https://github.com/reportportal/reportportal/releases/tag/v24.1

**Closed by alena-babrova** 2024-05-15 09:19 UTC
Labels: bug
