### ISSUE TITLE
I need aggregated statistics for launch groups

### ISSUE THREAD

**Issue by JustasM11** [reportportal/reportportal#44] opened 2016-12-19 14:02 UTC
I have several Jenkins job groups that report results into separate launches. Currently I don't see way to have aggregated statistics
I have 3 types of jobs:
- Several nightly CentOS6 jobs
- Several nightly CentOS7 jobs
- Several weekly long-running/performance jobs scheduled for different week days

I need accumulated statistics for job groups above.
So I need to:

- Have timeline mode for all Widgets (currently only few have such mode)
- Ability to adjust time window and window start for timeline mode (for weekly jobs)
- Ability to group launches into expandable hierarchical view on Launches page basing on following criteria:
  - Time: group launches for specific time period. I want to set period length and when period starts to group  my daily and weekly jobs (time is not aligned with Report Portal timezone)
  -  Tag: group launches by specific tags
  - Name (with regexp support): group launches by name pattern

**Comment by DzmitryHumianiuk** [comment] 2016-12-19 20:41
@JustasM11 Thank you for the request.
this will be discussed with the team

**Comment by evjlobanova** [comment] 2020-03-18 15:58
Closed as duplicate of https://github.com/reportportal/reportportal/issues/269

**Closed by evjlobanova** 2020-03-18 15:58 UTC
Labels: Feature: Widget, enhancement
