### ISSUE TITLE
[v5] Launch page goes to infinite load, when Command+Click on 'To Investigate' icon

### ISSUE THREAD

**Issue by movigit** [reportportal/reportportal#1269] opened 2021-01-13 14:09 UTC
**Describe the bug**
When trying to open 'To Investigate' issues in a new tab by doing Command+Click on the element, current page goes to infinite load (common UI loader element appears, but page never loads again, until page refreshed)

**To Reproduce**
1. Open https://reportportal.svc.ring.com/ui/#{project}/launches/all/{id}
2. Command+Click on To Investigate icon (circle icon, which is a donut chart)

**Actual behavior**
Current (Launch) tab goes to infinite load (not as expected)
New tab with "To Investigate" items opened (as expected)

**Expected behavior**
Current tab remains unchanged
New tab with "To Investigate" items opened

**Desktop (please complete the following information):**
 - MacOS Catalina
 - Chrome
 - Version 87.0.4280.88 (Official Build) (x86_64)

**Comment by VolhaKarenko** [comment] 2021-01-14 08:44
Didn't manage to reproduce the issue.
@movigit could you please give some details about the launch structure and total number of To investigate items?
Do you have the same actual behavior when right click on To investigate -> open link in new tab?

**Comment by movigit** [comment] 2021-01-14 09:18
@VolhaKarenko 
Number of To Investigate items doesn't impact, as it's reproduced on runs with 1-1000 items

RP version: Build: 5.3.3
My colleague is also able to reproduce it in chrome Version 87.0.4280.88 (Official Build) (x86_64)
When make right lick + open link in new tab everything is fine. 

So basically page is refreshed on the source page upon click (though it's with Command and shouldn't have an impact), maybe some onClick listener still works on element, idk. Opened page is fine, the problem is with the page ON WHICH click was performed. 

Issue is not reproduced on all launches page: /ui/#{project}/launches/all , but only on a specific launch, like that:
ui/#{project}/launches/all/{id}

Launch structure is the following: 
launch -> suites 
suite -> before suite , classes, after suite
class -> before class ,  before method, test, after method, after class

the whole url for an item look like this: 
/ui/#{project}/launches/all/{launch_id}/{suite_id}/{class_id}/{method_id}/log

for beforeSuite item which does not belong to a class structure is the following:
/ui/#{project}//launches/all/{launch_id}/{suite_id}/{before_suite_id}/log

Issue is also reproduced by clicking on any other Defect Type donut bar, not only on "To investigate".

**Comment by VolhaKarenko** [comment] 2021-01-14 11:43
The issue is reproducible, bug is added to backlog

**Comment by VolhaKarenko** [comment] 2021-01-26 00:02
The issue is fixed in version 5.3.5

**Closed by VolhaKarenko** 2021-01-26 00:02 UTC
Labels: bug
