### ISSUE TITLE
LDAP Manager passsword is in plain text

### ISSUE THREAD

**Issue by ofir2006** [reportportal/reportportal#1681] opened 2022-02-22 08:36 UTC
In the LDAP plugin configuration, the manager password appears to be in plain text

![LDAPO](https://user-images.githubusercontent.com/2917161/155094345-b1b66cd2-eaab-4f58-a305-32e071c0faca.jpeg)

**Comment by VolhaKarenko** [comment] 2022-02-24 14:01
The issue is added to backlog, planned to be fixed in version 5.8

**Comment by Kozovskaya** [comment] 2024-03-07 09:33
Hello @ofir2006 
I'm pleased to let you know that the fix is already released!
https://github.com/reportportal/reportportal/releases/tag/v24.1

**Closed by Kozovskaya** 2024-03-07 09:33 UTC
Labels: bug, component:ui
