### ISSUE TITLE
[v5.3.3] Exceptions with testng file dataprovider using excel, test methods are getting ignored and not being shown in UI

### ISSUE THREAD

**Issue by Priyanghaa** [reportportal/reportportal#1316] opened 2021-02-19 05:59 UTC
**Describe the bug**
Exceptions with testng file dataprovider using excel, test methods are getting ignored and not being shown in UI.
Same was working before with V4.3. After upgrade, it is not being shown

Exceptions in the docker logs :
org.springframework.web.bind.MethodArgumentNotValidException: Validation failed for argument [3] in public com.epam.ta.reportportal.ws.model.EntryCreatedAsyncRS com.epam.ta.reportportal.ws.controller.TestItemController.startChildItem(java.lang.String,com.epam.ta.reportportal.commons.ReportPortalUser,java.lang.String,com.epam.ta.reportportal.ws.model.StartTestItemRQ): [Field error in object 'startTestItemRQ' on field 'attributes[].value': rejected value [ProxyPDPValuePropTestData(testDescription=null, valuePropCaseId=[FREE_COD_DISABLED_BYUSERCODCHARGES, HYGENIC, LPGDISABLED_BYUSERATTR], client=android, appVersion=360, proxyPDPRequest=ProxyPDP(context_value=null, context=main, id=502933))]; codes [Size.startTestItemRQ.attributes[].value,Size.startTestItemRQ.attributes.value,Size.attributes[].value,Size.attributes.value,Size.value,Size]; arguments [org.springframework.context.support.DefaultMessageSourceResolvable: codes [startTestItemRQ.attributes[].value,attributes[].value]; arguments []; default message [attributes[].value],128,1]; default message [size must be between 1 and 128]]
	at org.springframework.web.servlet.mvc.method.annotation.RequestResponseBodyMethodProcessor.resolveArgument(RequestResponseBodyMethodProcessor.java:139)
	at org.springframework.web.method.support.HandlerMethodArgumentResolverComposite.resolveArgument(HandlerMethodArgumentResolverComposite.java:121)
	at org.springframework.web.method.support.InvocableHandlerMethod.getMethodArgumentValues(InvocableHandlerMethod.java:167)
	at org.springframework.web.method.support.InvocableHandlerMethod.invokeForRequest(InvocableHandlerMethod.java:134)
	at org.springframework.web.servlet.mvc.method.annotation.ServletInvocableHandlerMethod.invokeAndHandle(ServletInvocableHandlerMethod.java:106)
	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.invokeHandlerMethod(RequestMappingHandlerAdapter.java:879)
	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.handleInternal(RequestMappingHandlerAdapter.java:793)
	at org.springframework.web.servlet.mvc.method.AbstractHandlerMethodAdapter.handle(AbstractHandlerMethodAdapter.java:87)
	at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:1040)
	at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:943)
	at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:1006)
	at org.springframework.web.servlet.FrameworkServlet.doPost(FrameworkServlet.java:909)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:652)
	at org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:883)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:733)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:231)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:53)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.springframework.web.multipart.support.MultipartFilter.doFilterInternal(MultipartFilter.java:125)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:320)
	at org.springframework.security.web.access.intercept.FilterSecurityInterceptor.invoke(FilterSecurityInterceptor.java:126)
	at org.springframework.security.web.access.intercept.FilterSecurityInterceptor.doFilter(FilterSecurityInterceptor.java:90)
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:334)
	at org.springframework.security.web.access.ExceptionTranslationFilter.doFilter(ExceptionTranslationFilter.java:118)
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:334)
	at org.springframework.security.web.session.SessionManagementFilter.doFilter(SessionManagementFilter.java:137)
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:334)
	at org.springframework.security.web.authentication.AnonymousAuthenticationFilter.doFilter(AnonymousAuthenticationFilter.java:111)
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:334)
	at org.springframework.security.web.servletapi.SecurityContextHolderAwareRequestFilter.doFilter(SecurityContextHolderAwareRequestFilter.java:158)
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:334)
	at org.springframework.security.web.savedrequest.RequestCacheAwareFilter.doFilter(RequestCacheAwareFilter.java:63)
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:334)
	at org.springframework.security.oauth2.provider.authentication.OAuth2AuthenticationProcessingFilter.doFilter(OAuth2AuthenticationProcessingFilter.java:180)
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:334)
	at org.springframework.security.web.authentication.logout.LogoutFilter.doFilter(LogoutFilter.java:116)
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:334)
	at org.springframework.security.web.header.HeaderWriterFilter.doHeadersAfter(HeaderWriterFilter.java:92)
	at org.springframework.security.web.header.HeaderWriterFilter.doFilterInternal(HeaderWriterFilter.java:77)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119)
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:334)
	at org.springframework.security.web.context.SecurityContextPersistenceFilter.doFilter(SecurityContextPersistenceFilter.java:105)
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:334)
	at org.springframework.security.web.context.request.async.WebAsyncManagerIntegrationFilter.doFilterInternal(WebAsyncManagerIntegrationFilter.java:56)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119)
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:334)
	at org.springframework.security.web.FilterChainProxy.doFilterInternal(FilterChainProxy.java:215)
	at org.springframework.security.web.FilterChainProxy.doFilter(FilterChainProxy.java:178)
	at org.springframework.web.filter.DelegatingFilterProxy.invokeDelegate(DelegatingFilterProxy.java:358)
	at org.springframework.web.filter.DelegatingFilterProxy.doFilter(DelegatingFilterProxy.java:271)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.springframework.web.filter.RequestContextFilter.doFilterInternal(RequestContextFilter.java:100)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.springframework.web.filter.FormContentFilter.doFilterInternal(FormContentFilter.java:93)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.springframework.boot.actuate.metrics.web.servlet.WebMvcMetricsFilter.doFilterInternal(WebMvcMetricsFilter.java:109)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.springframework.web.filter.CharacterEncodingFilter.doFilterInternal(CharacterEncodingFilter.java:201)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:202)
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:96)
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:541)
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:139)
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:92)
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:74)
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:343)
	at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:373)
	at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:65)
	at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:868)
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1589)
	at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
	at java.base/java.lang.Thread.run(Unknown Source)

2021-02-19 05:38:13.650  WARN 5 --- [8585-exec-16231] c.e.t.r.c.e.rest.RestExceptionHandler    : Resolved [org.springframework.web.bind.MethodArgumentNotValidException: Validation failed for argument [3] in public com.epam.ta.reportportal.ws.model.EntryCreatedAsyncRS com.epam.ta.reportportal.ws.controller.TestItemController.startChildItem(java.lang.String,com.epam.ta.reportportal.commons.ReportPortalUser,java.lang.String,com.epam.ta.reportportal.ws.model.StartTestItemRQ): [Field error in object 'startTestItemRQ' on field 'attributes[].value': rejected value [ProxyPDPValuePropTestData(testDescription=null, valuePropCaseId=[FREE_COD_ENABLED_BYPSMATTRENABLED, NON_HYGENIC, LPGENABLED_BYNULLPRODATTR], client=android, appVersion=360, proxyPDPRequest=ProxyPDP(context_value=null, context=main, id=502933))]; codes [Size.startTestItemRQ.attributes[].value,Size.startTestItemRQ.attributes.value,Size.attributes[].value,Size.attributes.value,Size.value,Size]; arguments [org.springframework.context.support.DefaultMessageSourceResolvable: codes [startTestItemRQ.attributes[].value,attributes[].value]; arguments []; default message [attributes[].value],128,1]; default message [size must be between 1 and 128]] ]
2021-02-19 05:38:14.486 ERROR 5 --- [8585-exec-16292] c.e.t.r.c.e.rest.RestExceptionHandler    : Handled error:

**Comment by HardNorth** [comment] 2021-02-19 06:48
@Priyanghaa Can you please provide example code how you use that provider?

**Comment by Priyanghaa** [comment] 2021-02-19 07:02
> @Priyanghaa Can you please provide example code how you use that provider?

Ex:
    @DataProviderArguments("filePath="abc/xyz.xlsx":sheetname")
    @Test(groups = {"india"},priority = 1,enabled = true,dataProvider = "fileDataProvider",dataProviderClass = FileDataProvider.class)
    public void validateTest(Object obj) {
}

**filedataprovider :** 
    @DataProvider
    public static Iterator<Object[]> fileDataProvider(ITestContext context, Method method) {
        List<Object[]> testData = null;
        Map arguments = null;

        try {
            arguments = DataProviderUtils.resolveDataProviderArguments(method);
        } catch (Exception var6) {
            var6.printStackTrace();
        }

        String inputFile;
        if (arguments.get("filePath") != null) {
            inputFile = (String)arguments.get("filePath");
        } else {
            inputFile = context.getCurrentXmlTest().getParameter("filePath");
        }

        if (inputFile == null) {
            throw new RuntimeException("Provide data file path for running test");
        } else {
            testData = getFileContentList(inputFile, method.getName());
            return testData.iterator();
        }
    }

**Comment by HardNorth** [comment] 2021-02-23 12:22
@Priyanghaa It says you that you are bypassing too long or too short attribute(s):
`default message [attributes[].value],128,1]; default message [size must be between 1 and 128]]`
So it looks like DataProvider is nothing to do with that. Please examine which attributes you send.

**Comment by Priyanghaa** [comment] 2021-02-24 07:39
> @Priyanghaa It says you that you are bypassing too long or too short attribute(s):
> `default message [attributes[].value],128,1]; default message [size must be between 1 and 128]]`
> So it looks like DataProvider is nothing to do with that. Please examine which attributes you send.
> 
> You can use postman of the latest versions to capture requests you send.

@HardNorth Total number of attributes is around 10 only

**Comment by HardNorth** [comment] 2021-02-24 10:47
@Priyanghaa Not number, but value length.

**Comment by HardNorth** [comment] 2021-03-09 13:15
Abandoned

**Comment by HardNorth** [comment] 2021-03-09 15:07
@Priyanghaa Could you please compile that into an example project including an XLSX file with example data?

**Comment by Priyanghaa** [comment] 2021-03-09 15:14
sure will do that and share with you

**Comment by Priyanghaa** [comment] 2021-03-10 10:18
@HardNorth Please let me know Is it possible if we connect via call and do screenshare ? I can show the error and we can discuss the details then and there

**Comment by HardNorth** [comment] 2021-03-11 06:12
@Priyanghaa we do such call only in exceptional cases. Because 99% of them it's people can't deal with their own code and trying to involve us into this.

**Comment by Priyanghaa** [comment] 2021-03-12 04:42
okay sure will prepare and give the jar

**Comment by Priyanghaa** [comment] 2021-03-16 05:06
@HardNorth Have put some sample code here https://github.com/Priyanghaa/SampleReport. Please check

**Comment by HardNorth** [comment] 2021-05-31 09:09
@Priyanghaa Sorry, missed your invite. Could you send it again?

**Comment by Priyanghaa** [comment] 2021-05-31 09:18
Sample code is here https://github.com/Priyanghaa/SampleReport

**Comment by HardNorth** [comment] 2021-05-31 09:27
@Priyanghaa 
![Screen Shot 2021-05-31 at 12 25 50 PM](https://user-images.githubusercontent.com/4364466/120172225-7ba87b00-c20b-11eb-9984-212d3efa4ea4.png)

**Comment by Priyanghaa** [comment] 2021-05-31 11:22
Access is given

**Comment by HardNorth** [comment] 2021-05-31 13:40
@Priyanghaa I do not see any issues you mentioned. It works as expected for me:
![Screen Shot 2021-05-31 at 4 39 01 PM](https://user-images.githubusercontent.com/4364466/120202105-dacbb700-c22e-11eb-8f85-50fdeea091d0.png)

**Comment by Priyanghaa** [comment] 2021-05-31 13:45
Is it the same report portal version ? Any idea about the exception which we face ?

**Comment by HardNorth** [comment] 2021-05-31 14:04
@Priyanghaa Yes, I use v5.3.3.
As I see from your code you use `rp.tags` property. Please check that no tag value is longer than 128. This is limitation of RP v5, since it uses different DB.

**Comment by Priyanghaa** [comment] 2021-06-03 04:56
yeah cross checked , it is just few letters and not more than 128 but in exceptions also it is default message [size must be between 1 and 128]]

**Comment by HardNorth** [comment] 2021-06-03 05:01
@Priyanghaa So, you say we have lower limit for a tag length? That's odd. We should definetely update error message or cancel this limit.
@evjlobanova @VolhaKarenko Please comment and check.

**Comment by ashishmeesho** [comment] 2021-06-14 10:20
@HardNorth and @Priyanghaa, the issue is with test parameter value length, it parameter value length is more than 128 char, it is breaking, but in most of the cases, it will be more than 128. Wherever we will pass an object with more fields, its toString value is more than 128 char.

**Comment by MaryiaRymarchyk** [comment] 2023-03-03 13:36
@Priyanghaa  hi,
long time no hear from you, so we'll close the issue for now.
Just in case you still have the issue, please, provide more details as described in comment above.

**Closed by MaryiaRymarchyk** 2023-03-03 13:36 UTC
Labels: Waiting Info From Requestor
