### ISSUE TITLE
Component health check (table view) widget for HotProd filter does not load results and keeps spinning

### ISSUE THREAD

**Issue by Mahesh-TR** [reportportal/reportportal#1616] opened 2021-12-18 11:47 UTC
When we view/create the Component health check (table view) widget with HotProd filter the results do not load and the spinning image is shown. Is there a way to tell why this is occurring or is this a known issue of this widget?

![hp_widget](https://user-images.githubusercontent.com/62328004/146639813-ecb282ca-fd8b-49bc-8703-603b0182fa6e.JPG)

**Comment by Mahesh-TR** [comment] 2021-12-22 07:35
@evjlobanova : Could you please check on this and provide an update ?

**Comment by evjlobanova** [comment] 2021-12-22 13:39
Hello @Mahesh-TR 
Which version of ReportPortal do you use?
Please share a filter options you are using for filter

**Comment by Mahesh-TR** [comment] 2021-12-23 10:49
@evjlobanova ... Please find the response below

Which version of ReportPortal do you use?
Current version:API Service: 5.6.0;Jobs Service: 5.6.0;Authorization Service: 5.6.0;Service UI: 5.6.0;

Please share a filter options you are using for filter
Filter Name : HOTPROD
Attribute : any : HOTPROD
Sort by : Start time

**Comment by Mahesh-TR** [comment] 2021-12-23 10:51
> Hello @Mahesh-TR Which version of ReportPortal do you use? Please share a filter options you are using for filter

@evjlobanova : Please find the response below

Which version of ReportPortal do you use?
Current version:API Service: 5.6.0;Jobs Service: 5.6.0;Authorization Service: 5.6.0;Service UI: 5.6.0;

Please share a filter options you are using for filter
Filter Name : HOTPROD
Attribute : any : HOTPROD
Sort by : Start time

**Comment by Mahesh-TR** [comment] 2022-01-05 06:08
> @evjlobanova : Could you please check on this and provide an update ?

@evjlobanova : Do you have any further updates on my below reply.

Which version of ReportPortal do you use?
Current version:API Service: 5.6.0;Jobs Service: 5.6.0;Authorization Service: 5.6.0;Service UI: 5.6.0;

Please share a filter options you are using for filter
Filter Name : HOTPROD
Attribute : any : HOTPROD
Sort by : Start time

**Comment by Mahesh-TR** [comment] 2022-01-11 08:52
@evjlobanova : Do you have any further updates on this with the requested version details provided by us earlier ?

**Comment by evjlobanova** [comment] 2022-01-17 17:44
Hello @Mahesh-TR 

The problem relates to the filter. It seems that you filter contains "any or without any" options.  So the problem for now the problem can be fixed by removing "any" option from the filter.

In version 5.7 we have fixed this bug. 5.7 will be released in Feb 2022

**Comment by Mahesh-TR** [comment] 2022-01-19 10:39
> Hello @Mahesh-TR
> 
> The problem relates to the filter. It seems that you filter contains "any or without any" options. So the problem for now the problem can be fixed by removing "any" option from the filter.
> 
> In version 5.7 we have fixed this bug. 5.7 will be released in Feb 2022

@evjlobanova : I tried to use "All" filter option instead of "any" and the widget results says no data available.

![image](https://user-images.githubusercontent.com/62328004/150114253-eb90d656-5760-4d67-9226-e6c81de0ef04.png)

**Comment by Mahesh-TR** [comment] 2022-01-22 08:29
> > Hello @Mahesh-TR
> > The problem relates to the filter. It seems that you filter contains "any or without any" options. So the problem for now the problem can be fixed by removing "any" option from the filter.
> > In version 5.7 we have fixed this bug. 5.7 will be released in Feb 2022
> 
> @evjlobanova : I tried to use "All" filter option instead of "any" and the widget results says no data available.
> 
> ![image](https://user-images.githubusercontent.com/62328004/150114253-eb90d656-5760-4d67-9226-e6c81de0ef04.png)

@evjlobanova : Were you able to check on my above response and update ?

**Comment by Mahesh-TR** [comment] 2022-02-03 09:47
> > > Hello @Mahesh-TR
> > > The problem relates to the filter. It seems that you filter contains "any or without any" options. So the problem for now the problem can be fixed by removing "any" option from the filter.
> > > In version 5.7 we have fixed this bug. 5.7 will be released in Feb 2022
> > 
> > 
> > @evjlobanova : I tried to use "All" filter option instead of "any" and the widget results says no data available.
> > ![image](https://user-images.githubusercontent.com/62328004/150114253-eb90d656-5760-4d67-9226-e6c81de0ef04.png)
> 
> @evjlobanova : Were you able to check on my above response and update ?

@evjlobanova : Did you get any chance to check and update on my reply ?

**Comment by Mahesh-TR** [comment] 2022-02-08 10:29
@evjlobanova : Did you get any chance to review and update on my latest reply ?

**Comment by Mahesh-TR** [comment] 2022-03-09 05:00
> Hello @Mahesh-TR
> 
> The problem relates to the filter. It seems that you filter contains "any or without any" options. So the problem for now the problem can be fixed by removing "any" option from the filter.
> 
> In version 5.7 we have fixed this bug. 5.7 will be released in Feb 2022

@evjlobanova : I see report portal is still at 5.6.2 version and as per your previous update 5.7 version was supposed to be released in Feb 2022. Can you check and advise ?

**Comment by VolhaKarenko** [comment] 2022-08-23 04:57
The issue is fixed in version 5.7

**Closed by VolhaKarenko** 2022-08-23 04:57 UTC
Labels: help wanted, Waiting Info From Requestor
