### ISSUE TITLE
[v5] rp.skipped.issue=true doesn't mark "Skipped" tests as "To Investigate"

### ISSUE THREAD

**Issue by DeNNyA19** [reportportal/reportportal#1535] opened 2021-09-24 09:34 UTC
According to the documentation rp.skipped.issue should mark skipped tests as 'To Investigate' if set to true. 
![image](https://user-images.githubusercontent.com/21055259/134650367-da3c5383-5dac-412e-a41d-d4285bc21bae.png)

In the version 4.3.6 it was configurable, example of the run with rp.skipped.issue=true is below
![image](https://user-images.githubusercontent.com/21055259/134651591-a9e81685-3390-4b26-812e-1fb67e25f477.png)

In the latest version rp.skipped.issue=true doesn't work accordingly to the documentation
![image](https://user-images.githubusercontent.com/21055259/134651509-2a275a27-8d0b-4519-9c3c-65ced9dc49b3.png)

There is an existing closed issue which descibed the same problem but it was answered that it is designed such way.
[Unable to investigate skipped tests](https://github.com/reportportal/reportportal/issues/1328)

For me it looks like the issue because we migrated from 4.3.6 to 5.5.0 and this functionality stopped to work.

**Comment by HardNorth** [comment] 2021-09-24 10:15
@DeNNyA19 Could you explain your case please? It doesn't make much sense for me, since your test was skipped because of failed `Before Method`. There is no many things to investigate and there is 'To Investigate' on `Before Method`. `rp.skipped.issue=true` is for the case when someone intentionally skipping tests in code.

**Comment by DeNNyA19** [comment] 2021-09-24 14:14
@HardNorth  Main idea of the "To Investigate" label is also to confirm that all skipped tests must be re-executed and confirmed that there is no any issues, with "To Investigate" label we can do local run of the cases and confirm that those cases do not have any app issues. 
Additionally we can easly control whole distributed team's review process - during review of "To Investigate" for Skip we change status from "To Investigate" to "Skip" manually and do not worry that some tests were suddently skipped during review.

This process was organized during usage of v4 where `rp.skipped.issue=true` was working such way, we expected that after migration such logic won't be changed

**Comment by mbryl6** [comment] 2023-12-20 13:48
Hello @DeNNyA19,
In reporting launch for skipped item to get "To Investigate" issue type after finishing the launch per request it's required to:
   1) add following in the launch start request: "attributes": [{
      "key": "skippedIssue",
      "value": true
     }]
   2) in the finish item request to set status 'Skipped'.

For skipped item to get "To Investigate" issue type after manually changing status on RPP UI following sequence of actions is required:
   1-2) as above
   3) in the finish item request also add following: "issue": { "issueType": "NOT_ISSUE" }
In this case after finishing launch no defect type will be applied to the skipped item, but if status is changed from 'Skipped' to 'Failed' and then back to 'Skipped' again, then "To Investigate" will be applied to the item.

Could you please try both mentioned ways and tell if the issue is still there for you?

**Comment by MaryiaRymarchyk** [comment] 2024-01-26 12:00
@DeNNyA19, as we haven't received a reply from you, we'll close the issue for now.
In case you still have the issue - just get in touch.

**Closed by MaryiaRymarchyk** 2024-01-26 12:00 UTC
Labels: Waiting Investigations From Team
