### ISSUE TITLE
Launch is hang on and AA doesn't work

### ISSUE THREAD

**Issue by irinakhaptanova** [reportportal/reportportal#324] opened 2018-01-18 13:31 UTC
We use Jenkins to run autotests and also use Specflow.
We develop Autotests on C# lang.
Job in Jeknins took ~6 hours but Launche in Report Portal is hang and AA doesn't work

**Comment by nvborisenko** [comment] 2018-01-24 17:28
Please share versions of nuget packages. And do you see any errors in console output?

**Comment by 132u** [comment] 2018-01-30 15:24
@nvborisenko . Jenkins doesn't contain any errors
<packages>
  <package id="EntityFramework" version="6.1.3" targetFramework="net452" />
  <package id="MailSystem.NET" version="2.0.1" targetFramework="net452" />
  <package id="MSGReader" version="2.0.1" targetFramework="net452" />
  <package id="Newtonsoft.Json" version="9.0.1" targetFramework="net452" />
  <package id="NLog" version="4.3.11" targetFramework="net452" />
  <package id="NLog.Config" version="4.3.11" targetFramework="net452" />
  <package id="NLog.Schema" version="4.3.11" targetFramework="net452" />
  <package id="NUnit" version="3.5.0" targetFramework="net452" />
  <package id="NUnit3TestAdapter" version="3.6.0" targetFramework="net452" />
  <package id="ReportPortal.Client" version="1.2.8" targetFramework="net452" />
  <package id="ReportPortal.NLog" version="1.1.8" targetFramework="net452" />
  <package id="ReportPortal.Shared" version="1.4.2" targetFramework="net452" />
  <package id="ReportPortal.SpecFlow" version="1.2.1" targetFramework="net452" />
  <package id="RestSharp" version="105.2.3" targetFramework="net452" />
  <package id="Selenium.Chrome.WebDriver" version="2.33" targetFramework="net452" />
  <package id="Selenium.Support" version="3.7.0" targetFramework="net452" />
  <package id="Selenium.WebDriver" version="3.7.0" targetFramework="net452" />
  <package id="Selenium.WebDriver.ChromeDriver" version="2.33.0" targetFramework="net452" />
  <package id="SlowCheetah" version="2.5.15" targetFramework="net452" />
  <package id="SpecFlow" version="2.1.0" targetFramework="net452" />
  <package id="SpecFlow.CustomPlugin" version="2.1.0" targetFramework="net452" />
  <package id="SpecFlow.NUnit" version="2.1.0" targetFramework="net452" />
</packages>

**Comment by evjlobanova** [comment] 2018-02-20 14:33
@nvborisenko could you please look at this issue once again?

**Comment by DzmitryHumianiuk** [comment] 2018-03-14 13:37
@nvborisenko could you assist here?

@irinakhaptanova is issue still actual?

**Comment by nvborisenko** [comment] 2018-03-21 14:00
@irinakhaptanova please update RP packages and try to reproduce the issue. At least now we will be able to see some error messages in console output.

**Comment by Kuzukaze** [comment] 2018-04-11 15:49
@nvborisenko
packages updated, problem still exist.

**Comment by nvborisenko** [comment] 2018-04-12 00:36
Please update specflow plugin to the latest beta version and try again. Thx in advance.

**Comment by Kuzukaze** [comment] 2018-04-12 10:44
@nvborisenko 
we have ReportPortal.SpecFlow 1.2.2-beta-23.
If I try to update to Latest version
![image](https://user-images.githubusercontent.com/31167096/38672576-4f50de84-3e57-11e8-8a9b-446b0d76d280.png)

**Comment by nvborisenko** [comment] 2018-04-13 11:26
ReportPortal.SpecFlow 1.2.2-beta-23 is the latest. Could you please share full console output from your jenkins. I am interesting in RP logs. And which runner do you use to execute specflow tests?

**Comment by Kuzukaze** [comment] 2018-04-16 14:06
Add console output from jenkins.  Use nunit3.

from Jenkins



  Test Count: 633, Passed: 509, Failed: 124, Inconclusive: 0, Skipped: 0
    Failed Tests - Failures: 23, Errors: 101, Invalid: 0
  Start time: 2018-04-16 00:24:40Z
    End time: 2018-04-16 04:06:27Z
    Duration: 13306.779 seconds

[JenkinsConsoleLog.zip](https://github.com/reportportal/reportportal/files/1915550/JenkinsConsoleLog.zip)

![image](https://user-images.githubusercontent.com/31167096/38813741-7857b750-4198-11e8-9e14-a7d307bd2922.png)

**Comment by nvborisenko** [comment] 2018-04-18 11:51
Did you manually finish the launch? If not, please verify your project settings in web interface like:
![screenshot_1](https://user-images.githubusercontent.com/22616990/38930241-e509f5e0-4317-11e8-8ee2-89e1da93f8b9.png)
May be you have short period of launch's inactivity.

**Comment by Kuzukaze** [comment] 2018-04-18 12:53
@nvborisenko 
Launch interrupted by timeout.
We have 3 hour timeout.
As you can see from previous post jenkins finish work in 3-4 hours, if RP stuck we get INTERRUPTED status in about 7 housr(~jenkins time + 3 hour timeout).
I can try set timeout for 1 week, but looks like it just will be INTERRUPTED in 1 week.

**Comment by evjlobanova** [comment] 2018-07-16 14:20
@Kuzukaze do you still have a problem?

**Comment by DzmitryHumianiuk** [comment] 2019-03-13 21:49
@nvborisenko thank you.

btw, we plan to add **Launch logs**, so this information can be pushed there later


@irinakhaptanova @132u @Kuzukaze closing since no response recieved

**Closed by DzmitryHumianiuk** 2019-03-13 21:49 UTC
Labels: component:agent, help wanted
