### ISSUE TITLE
Test fails, RP shows it's runnung

### ISSUE THREAD

**Issue by ksuglotova** [reportportal/reportportal#159] opened 2017-06-23 16:03 UTC
Received from @kiryl, Slack/reportportal/russian

If test fails (cucumber), then RP shows that test is running and user has to force finish test
Last agent version

**Comment by avarabyeu** [comment] 2017-06-30 11:41
@ksuglotova agent, version, example?

**Comment by Gidroid** [comment] 2017-06-30 11:47
agent -java -cucumber, version 3.0.0-BETA-2
For example need help with gradle

**Comment by avarabyeu** [comment] 2017-06-30 11:49
@Gidroid  feel free to create the same example based on maven. You can even send it to me via email

**Comment by DzmitryHumianiuk** [comment] 2017-07-07 15:57
@Gidroid ?

**Comment by Gidroid** [comment] 2017-07-07 16:14
Right now I can't reproduce this error on our project. I will add code when error come up again

**Comment by avarabyeu** [comment] 2017-07-07 19:40
@Gidroid OK. closing for now. Feel free to re-open or create new issue if problem appears again

**Closed by avarabyeu** 2017-07-07 19:40 UTC
Labels: component:agent, help wanted
