### ISSUE TITLE
Share edit rights for dashboards

### ISSUE THREAD

**Issue by Kira-Lappo** [reportportal/reportportal#537] opened 2018-12-10 15:30 UTC
Currentlly noone can edit dashboard except its creator.
Could you add possibiltiy to edit dashborad for many users?

**Comment by evjlobanova** [comment] 2018-12-11 12:43
@Kira-Lappo Hello, now we don`t have such possibility, and do not plan to implement yet. As a workaround, you can create a special user for creating and editing  dashboards.
Anyway I was wondering, in which case you want to edit dashboards, why they are needed to be updated.

**Comment by Kira-Lappo** [comment] 2018-12-13 22:23
@evjlobanova  We have several teams and each one has its own automation scopes and dashboards as well. 
Dashboard are supported by AQAs in the teams, so we want to easily share edit rights or even just change the owner of each dashboard in case of changes in the teams.
For now, yeah, we created special "dashboard overseer" user.

**Comment by evjlobanova** [comment] 2020-04-06 07:51
Closed as duplicate of #603 
We add a permissions table, where PM or Admin will be able to customize the roles for every team member.

In version 5.0 we added a possibility for PM to edit not-own shared dashboard

**Closed by evjlobanova** 2020-04-06 07:51 UTC
Labels: Feature: Custom Roles, enhancement
