### ISSUE TITLE
Not able to Edit or Delete Notification Rule

### ISSUE THREAD

**Issue by paresh-celigo** [reportportal/reportportal#2200] opened 2023-12-26 06:35 UTC
Hi Team, I have added notification rules and by mistake I added duplicates rules So I wanted to delete those duplicate rules but when i click on delete button and confirm delete i am getting following error: 
<img width="1375" alt="image" src="https://github.com/reportportal/reportportal/assets/141011973/28610a69-04d7-4172-8c0d-d0eb7802adc7">

Please suggest me what should I do, or any solution for this.?

**Comment by Pink-Bumblebee** [comment] 2023-12-26 06:53
Hello @paresh-celigo ,
Just for interest, how you've created duplicated notification rule? 
And in your case is it possible to change or delete some attributes in duplicated or original rule and save it?

**Comment by paresh-celigo** [comment] 2023-12-26 14:54
HI @Pink-Bumblebee , while creating rules it wont check for duplicate you can create multiple rule with same emails for notification,but I am not able to delete or edit once rule is created

**Comment by alena-babrova** [comment] 2023-12-26 17:50
Hello @paresh-celigo,

Indeed, we know about the issue on this page when trying to modify rules after one of the existing rule became invalid.
The issue is already fixed in the next version 24.1, which will be available in January 2024.

If the issue blocks you right now, please send me a screenshot with the full list of rules you have on the project right now and the list of project members.

**Comment by Kozovskaya** [comment] 2024-03-07 09:31
Hello, @paresh-celigo 
I'm pleased to let you know that the fix is already released! There should be no problem in updating or deleting the rule!
https://github.com/reportportal/reportportal/releases/tag/v24.1

**Closed by Kozovskaya** 2024-03-07 09:31 UTC
Labels: help wanted
