### ISSUE TITLE
Issue with ImportData

### ISSUE THREAD

**Issue by priyankachaturvedi30** [reportportal/reportportal#1006] opened 2020-06-09 12:35 UTC
**Describe the bug**
At times it is been observed that the data is not imported successfully. Screenshot for such a case when I try to navigate into a particular scenario
![image](https://user-images.githubusercontent.com/50797731/84147649-61fea880-aa7b-11ea-8ab6-dd305dec39a4.png)

**To Reproduce**
Attached log file where there are 3 failure; out of which log data is not properly imported for 1 failure (Scenario 0008: Validate the grid filtering on Entitlements tab when rows are Expanded - Part 1)

**Expected behavior**
Log Data should be imported successfully as for the rest of the 2 failure cases
**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser - Chrome
 - Version 83

[Error_Import.zip](https://github.com/reportportal/reportportal/files/4752151/Error_Import.zip)

Please check.

**Comment by evjlobanova** [comment] 2020-06-09 13:01
@priyankachaturvedi30 Does your file ner requirements for imported fileshttps://reportportal.io/docs/Import-data-to ?

**Comment by priyankachaturvedi30** [comment] 2020-06-09 13:35
Yes @evjlobanova : Its surprising as log data for 2 cases got imported from the same file and 1 did not. While the structure and format is exactly as expected.

**Comment by evjlobanova** [comment] 2020-06-09 13:59
As far as our tool posses real-time analytics, an import feature has very limited capabilities.
Could you please tell me your use case. Why do you decide to use Import? Do you use import instead of reporting or do you try to use both options?

**Comment by priyankachaturvedi30** [comment] 2020-06-09 14:07
I use both @evjlobanova . This was one of the little use case for which I wanted to validate few logs so therefore I used the import feature for quick analysis. This usecase comprises of few testcases and not much of a framework..so I preferred taking a Junit import of logs directly through the import feature. it worked for most of the cases expect for some where the logs are not imported properly. (Sample file shared in comment #1 in case you want to reproduce the scenario.)

**Comment by evjlobanova** [comment] 2020-06-10 08:37
Got it

**Comment by e-olga** [comment] 2020-07-02 07:16
The issue in RP backlog submitted

**Comment by alena-babrova** [comment] 2023-01-09 13:28
Hello @priyankachaturvedi30 
Could you please tell me if the issue is still relevant?

**Comment by alena-babrova** [comment] 2023-05-03 13:37
Dear @priyankachaturvedi30 
As we haven't received a reply from you, we'll close the issue for now.
Just in case you still have the issue, please, do not hesitate to get in touch.

**Closed by alena-babrova** 2023-05-03 13:37 UTC
Labels: bug
