### ISSUE TITLE
Possibility of saving a filter at first drill down level

### ISSUE THREAD

**Issue by priyankachaturvedi30** [reportportal/reportportal#1487] opened 2021-08-02 08:55 UTC
Currently, we have an option to create a filter at the launch level and save it to filter out results. Can we have a similar filter that we can save for later use as a first/second level drill-downs (when we navigate inside from launches)?

**Comment by evjlobanova** [comment] 2021-08-19 06:40
Duplicate of #74
@priyankachaturvedi30 I closed your issue as a duplicate, please check the mentioned thread. 
I will update this issue in case of any progress

**Closed by evjlobanova** 2021-08-19 06:40 UTC
Labels: help wanted

**Comment by Kamala-Priyanka** [comment] 2022-06-30 17:44
@evjlobanova , have seen the duplicate but have some queries which are not covered. They asked to add attributes as filter level but when I am trying to provide tage name as attribute value, widget is not able to launchs or tests accordingly, can you please explain if I have to add any changes in implementation
