### ISSUE TITLE
TypeError: Cannot read property 'split' of undefined [v5] Issue with filters

### ISSUE THREAD

**Issue by jay-espiritu** [reportportal/reportportal#808] opened 2020-02-03 23:01 UTC
**Describe the bug**
I've manage to implement report portal in my nunit project and ran it fine. However when I'm trying to create a dashboard to display data and results it wouldn't let me add any widgets and keeps returning me to a blank screen.

When I check the browser console it shows that it's returning couple of errors (screenshot attached).

> TypeError: Cannot read property 'split' of undefined

and 

> uncaught at S TypeError: Cannot read property 'split' of undefined

When I create a dashboard/widget on my RP personal_project it works fine. 

**To Reproduce**
1. Open up RP - localhost:8080/ui/
2. Create a project dashboard > Click 'Add new widget'
3. Select any of the widget > Click 'Next' button

**Expected behavior**
This feature was working few days ago and suddenly start returning me this error. The expected behaviour is to provide options to configure the dashboard and to display the dashboard

**Screenshots**
![image](https://user-images.githubusercontent.com/57969265/73697375-80057680-4732-11ea-844a-5eda0dfc0ad1.png)

**Desktop (please complete the following information):**
 - OS: macOS catalina v10.15.2
 - Browser Chrome
 - v79.0.3945.130

**Comment by DzmitryHumianiuk** [comment] 2020-02-07 17:20
![image](https://user-images.githubusercontent.com/11332788/74050533-53c65000-49e7-11ea-8199-c15a2319ce96.png)

**Comment by DiscoElevator** [comment] 2020-02-13 10:20
@jay-espiritu Hello. Could you please provide the following information?
1. Which exact RP version do you use?
2. Does Filters page open without errors on this project?
3. Are there any filters?
4. If there any filters, could you please provide '/filters' response from the browser Devtools Network tab?

**Comment by evjlobanova** [comment] 2020-02-18 13:58
@jay-espiritu ^

**Comment by evjlobanova** [comment] 2020-03-03 16:46
Closed because of no response, feel free to reopen issue

**Comment by smerberg** [comment] 2020-10-02 15:47
I'm getting this same error - everything was working fine a few minutes ago. To answer the questions above -

1. I'm using 5.3.1
2. The Filters page throws the same error
![image](https://user-images.githubusercontent.com/3135561/94942741-b3a4c600-04a4-11eb-8518-1ccbd606acf4.png)
3. I did previously create some filters. I was able to do so without issue.
4. Here's the /filter response
`{"content":[{"owner":"superadmin","share":true,"id":2,"name":"Registration","conditions":[{}],"orders":[{"sortingColumn":"startTime","isAsc":false},{"sortingColumn":"number","isAsc":false}],"type":"Launch"},{"owner":"superadmin","share":true,"id":7,"name":"Web Services","conditions":[{"filteringField":"name","condition":"cnt","value":"WebService"}],"orders":[{"sortingColumn":"startTime","isAsc":false},{"sortingColumn":"number","isAsc":false}],"type":"Launch"}],"page":{"number":1,"size":50,"totalElements":2,"totalPages":1}}`

**Comment by smerberg** [comment] 2020-10-02 16:49
I think I fixed this by deleting the filter with ID 2 through the API. The "Filters" page is working again, so fingers crossed

**Comment by AmsterGet** [comment] 2020-10-02 20:42
It seems that this issue is still reproducible and sometimes occurs in version 5. *.

**Comment by AmsterGet** [comment] 2020-10-02 20:48
As I understand the core problem is that the required `conditions` field leads epmty.
It's also important to note that the problem occurred with the shared filter.
From my point of view, this can happen in two ways:
1) Editing filter data directly in the database.
2) The issue with shared filters in the core API.

**Comment by VolhaKarenko** [comment] 2020-10-14 09:21
The issue is added to backlog

**Comment by wlad** [comment] 2020-11-17 08:13
I ran into the same issue. I'm using the docker-compose up setup.

![image](https://user-images.githubusercontent.com/64201310/99363363-ecfa8f00-28b4-11eb-9adf-5291b8523624.png)

**Comment by pbortnik** [comment] 2020-12-02 12:10
@smerberg  @wlad 
Hi guys, 
Can you describe how you created filter? Did you use api or ui? What conditions did you add to the filter ?

**Comment by VolhaKarenko** [comment] 2021-01-16 21:36
Closed as outdated and not reproducible. Feel free to reopen, providing some details on the issue

**Closed by VolhaKarenko** 2021-01-16 21:36 UTC
Labels: bug
