### ISSUE TITLE
Launch does not complete or Finish(running state )

### ISSUE THREAD

**Issue by rajgopalrajesh** [reportportal/reportportal#1490] opened 2021-08-03 14:51 UTC
Running  docker report portal 5.4 

configured project and reporting via cucumber adapter jvm5 

![image](https://user-images.githubusercontent.com/16475965/128036668-4d0f6533-f19b-4db9-94fb-a5ec28b6163f.png)

launch will be on running state (up to 2 days ), the test execution has been completed with in 3 hrs 

error in logs
021-07-30 14:55:00.003 ERROR 6 --- [   scheduling-1] o.s.s.s.TaskUtils$LoggingErrorHandler    : Unexpected error occurred in scheduled task

org.springframework.jdbc.BadSqlGrammarException: PreparedStatementCallback; bad SQL grammar [UPDATE shedlock SET lock_until = timezone('utc', CURRENT_TIMESTAMP) + cast(? as interval), locked_at = timezone('utc', CURRENT_TIMESTAMP), locked_by = ? WHERE shedlock.name = ? AND shedlock.lock_until <= timezone('utc', CURRENT_TIMESTAMP)]; nested exception is org.postgresql.util.PSQLException: ERROR: relation "shedlock" does not exist
  Position: 8
        at org.springframework.jdbc.support.SQLErrorCodeSQLExceptionTranslator.doTranslate(SQLErrorCodeSQLExceptionTranslator.java:239) ~[spring-jdbc-5.3.4.jar!/:5.3.4]
        at org.springframework.jdbc.support.AbstractFallbackSQLExceptionTranslator.translate(AbstractFallbackSQLExceptionTranslator.java:70) ~[spring-jdbc-5.3.4.jar!/:5.3.4]
        at org.springframework.jdbc.core.JdbcTemplate.translateException(JdbcTemplate.java:1541) ~[spring-jdbc-5.3.4.jar!/:5.3.4]
        at org.springframework.jdbc.core.JdbcTemplate.execute(JdbcTemplate.java:667) ~[spring-jdbc-5.3.4.jar!/:5.3.4]
        at org.springframework.jdbc.core.JdbcTemplate.update(JdbcTemplate.java:960) ~[spring-jdbc-5.3.4.jar!/:5.3.4]
        at org.springframework.jdbc.core.JdbcTemplate.update(JdbcTemplate.java:981) ~[spring-jdbc-5.3.4.jar!/:5.3.4]
        at org.springframework.jdbc.core.namedparam.NamedParameterJdbcTemplate.update(NamedParameterJdbcTemplate.java:328) ~[spring-jdbc-5.3.4.jar!/:5.3.4]
        at org.springframework.jdbc.core.namedparam.NamedParameterJdbcTemplate.update(NamedParameterJdbcTemplate.java:333) ~[spring-jdbc-5.3.4.jar!/:5.3.4]
        at net.javacrumbs.shedlock.provider.jdbctemplate.JdbcTemplateStorageAccessor.lambda$updateRecord$1(JdbcTemplateStorageAccessor.java:82) ~[shedlock-provider-jdbc-template-4.21.0.jar!/:na]
        at org.springframework.transaction.support.TransactionTemplate.execute(TransactionTemplate.java:140) ~[spring-tx-5.3.4.jar!/:5.3.4]
        at net.javacrumbs.shedlock.provider.jdbctemplate.JdbcTemplateStorageAccessor.updateRecord(JdbcTemplateStorageAccessor.java:81) ~[shedlock-provider-jdbc-template-4.21.0.jar!/:na]
        at net.javacrumbs.shedlock.support.StorageBasedLockProvider.doLock(StorageBasedLockProvider.java:91) ~[shedlock-core-4.21.0.jar!/:na]
        at net.javacrumbs.shedlock.support.StorageBasedLockProvider.lock(StorageBasedLockProvider.java:65) ~[shedlock-core-4.21.0.jar!/:na]
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:na]
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[na:na]
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[na:na]
        at java.base/java.lang.reflect.Method.invoke(Unknown Source) ~[na:na]
        at org.springframework.aop.support.AopUtils.invokeJoinpointUsingReflection(AopUtils.java:344) ~[spring-aop-5.3.4.jar!/:5.3.4]
        at org.springframework.aop.framework.JdkDynamicAopProxy.invoke(JdkDynamicAopProxy.java:208) ~[spring-aop-5.3.4.jar!/:5.3.4]
        at com.sun.proxy.$Proxy44.lock(Unknown Source) ~[na:na]
        at net.javacrumbs.shedlock.core.DefaultLockingTaskExecutor.executeWithLock(DefaultLockingTaskExecutor.java:63) ~[shedlock-core-4.21.0.jar!/:na]
        at net.javacrumbs.shedlock.spring.aop.MethodProxyScheduledLockAdvisor$LockingInterceptor.invoke(MethodProxyScheduledLockAdvisor.java:86) ~[shedlock-spring-4.21.0.jar!/:na]
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186) ~[spring-aop-5.3.4.jar!/:5.3.4]
        at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:750) ~[spring-aop-5.3.4.jar!/:5.3.4]
        at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:692) ~[spring-aop-5.3.4.jar!/:5.3.4]
        at com.epam.reportportal.jobs.storage.CalculateAllocatedStorageJob$$EnhancerBySpringCGLIB$$c0abd0bd.calculate(<generated>) ~[classes!/:na]
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:na]
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[na:na]
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[na:na]
        at java.base/java.lang.reflect.Method.invoke(Unknown Source) ~[na:na]
        at org.springframework.scheduling.support.ScheduledMethodRunnable.run(ScheduledMethodRunnable.java:84) ~[spring-context-5.3.4.jar!/:5.3.4]
        at org.springframework.scheduling.support.DelegatingErrorHandlingRunnable.run(DelegatingErrorHandlingRunnable.java:54) ~[spring-context-5.3.4.jar!/:5.3.4]
        at org.springframework.scheduling.concurrent.ReschedulingRunnable.run(ReschedulingRunnable.java:95) ~[spring-context-5.3.4.jar!/:5.3.4]
        at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) ~[na:na]
        at java.base/java.util.concurrent.FutureTask.run(Unknown Source) ~[na:na]
        at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(Unknown Source) ~[na:na]
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) ~[na:na]
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) ~[na:na]
        at java.base/java.lang.Thread.run(Unknown Source) ~[na:na]
Caused by: org.postgresql.util.PSQLException: ERROR: relation "shedlock" does not exist
  Position: 8

![image](https://user-images.githubusercontent.com/16475965/128402212-520d66cb-ec0b-46fe-bc87-aaa08311c753.png)

**Comment by HardNorth** [comment] 2021-08-03 15:22
Java 5 is out of support already

**Comment by HardNorth** [comment] 2021-08-03 15:24
Opps, looks like it's not a client issue

**Comment by HardNorth** [comment] 2021-08-03 15:25
@pbortnik, @miracle8484 Could you please take a look?

**Comment by rajgopalrajesh** [comment] 2021-08-04 12:57
> Java 5 is out of support already

this is cucumber adapter version JVM5  not java version

**Comment by rajgopalrajesh** [comment] 2021-08-06 04:49
updated agent 
dependency>
			<groupId>com.epam.reportportal</groupId>
			<artifactId>agent-java-cucumber5</artifactId>
			<version>5.1.0-RC-6</version>
		</dependency>

getting below error



[ec2-user@ip-10-158-89-196 ~]$ docker run -it  rajeshrajagopaldocker/apibddimage                                                                                        :tenthmvnupdate sh
Checking running
Aug 06, 2021 4:36:56 AM io.cucumber.core.cli.Main run
WARNING: By default Cucumber is running in --non-strict mode.
This default will change to --strict and --non-strict will be removed.
You can use --strict to suppress this warning
Exception in thread "main" java.lang.IllegalArgumentException: bound must be pos                                                                                        itive
        at java.util.Random.nextInt(Random.java:388)
        at com.epam.reportportal.service.launch.AbstractJoinedLaunch.getUpdateTa                                                                                        sk(AbstractJoinedLaunch.java:43)
        at com.epam.reportportal.service.launch.AbstractJoinedLaunch.<init>(Abst                                                                                        ractJoinedLaunch.java:57)
        at com.epam.reportportal.service.launch.PrimaryLaunch.<init>(PrimaryLaun                                                                                        ch.java:41)
        at com.epam.reportportal.service.ReportPortal.newLaunch(ReportPortal.jav                                                                                        a:128)
        at com.epam.reportportal.cucumber.AbstractReporter$1.get(AbstractReporte                                                                                        r.java:280)
        at com.epam.reportportal.cucumber.AbstractReporter$1.get(AbstractReporte                                                                                        r.java:249)
        at com.epam.reportportal.utils.MemoizingSupplier.get(MemoizingSupplier.j                                                                                        ava:42)
        at com.epam.reportportal.cucumber.AbstractReporter.beforeLaunch(Abstract                                                                                        Reporter.java:150)
        at com.epam.reportportal.cucumber.AbstractReporter.lambda$getTestRunStar                                                                                        tedHandler$9(AbstractReporter.java:553)
        at io.cucumber.core.eventbus.AbstractEventPublisher.send(AbstractEventPu                                                                                        blisher.java:45)
        at io.cucumber.core.eventbus.AbstractEventBus.send(AbstractEventBus.java                                                                                        :9)
        at io.cucumber.core.runtime.Runtime.run(Runtime.java:89)
        at io.cucumber.core.cli.Main.run(Main.java:75)

**Comment by HardNorth** [comment] 2021-08-06 09:33
> 5.1.0-RC-6
there is no such version of `agent-java-cucumber5`
The latest one is [5.1.0-RC-2](https://search.maven.org/artifact/com.epam.reportportal/agent-java-cucumber5/5.1.0-RC-2/jar)
Please use it, there is a fix for exactly this.

**Comment by rajgopalrajesh** [comment] 2021-08-06 09:49
![image](https://user-images.githubusercontent.com/16475965/128492317-0494d32d-efc8-4b7f-9e12-4eb4acb66a72.png)

have used the same

**Comment by HardNorth** [comment] 2021-08-06 13:11
@rajgopalrajesh Then this should be fixed already.

**Comment by rajgopalrajesh** [comment] 2021-08-09 06:12
> @rajgopalrajesh Then this should be fixed already.

no still issue is there

**Comment by HardNorth** [comment] 2021-08-09 20:00
Very strange, I need to debug it, could you please provide me an example project to reproduce?

**Comment by rajgopalrajesh** [comment] 2021-08-10 07:36
After upgrading cucumber to version 6 and agent below 
<dependency>
			<groupId>com.epam.reportportal</groupId>
			<artifactId>agent-java-cucumber6</artifactId>
			<version>5.1.0-RC-3</version>
		</dependency>

Working fine

**Comment by HardNorth** [comment] 2021-08-10 09:31
OK, closing this

**Closed by HardNorth** 2021-08-10 09:31 UTC
Labels: help wanted
