### ISSUE TITLE
Widget table column width (Most failed test-cases table (TOP-20))

### ISSUE THREAD

**Issue by shaburov** [reportportal/reportportal#906] opened 2020-04-03 14:48 UTC
Current version: API Service: 5.0.0;Index Service: 5.0.5;Authorization Service: 5.0.0;Service UI: 5.0.0;

**Need to do Right Alignment**
![image](https://user-images.githubusercontent.com/15269131/78373584-7635ad80-75d3-11ea-889e-322a22d4506f.png)

**Comment by svettsova** [comment] 2020-10-14 06:00
The issue is fixed in 5.3.3

**Closed by svettsova** 2020-10-14 06:00 UTC
Labels: bug, component:ui
