### ISSUE TITLE
[v5] JIRA Cloud Integration Fails - Impossible interact with Integration. Connection Refused.

### ISSUE THREAD

**Issue by shishir19** [reportportal/reportportal#935] opened 2020-04-27 10:58 UTC
**Describe the bug**
After adding JIRA Plugin, I tried to integrate Report Portal with JIRA cloud. However, its throwing an error:

An error occurred while connecting to server: Impossible interact with Integration. Connection Refused.

**To Reproduce**
Deploy Report Portal on Ubuntu 18.04 (Azure machine)
Start the docker containers and enable incoming connection to azure (port 8080)
Login to ReportPortal and create a project
Upload JIRA plugin (latest)
Integrate with JIRA cloud instance

**Expected behavior**
Integration should be successful

**Desktop (please complete the following information):**
OS- Ubuntu 18.04
Browser - Accessing from Windows 10, Google Chrome

![jira-integration](https://user-images.githubusercontent.com/5175282/80364746-0c43b780-88a4-11ea-813f-3bdf03d51613.png)

**Comment by shishir19** [comment] 2020-04-27 18:55
Any update on this?

**Comment by shishir19** [comment] 2020-04-28 06:47
Tried with jira-bts-plugin 5.1.0-RC-2 but still getting same error.

I also tried with installation of jira server on my azure system and then tried connecting the plugin, but it gives me same error.

**Comment by pbortnik** [comment] 2020-04-29 08:07
@shishir19 
Hi, what is the version of RP do you use?
Have you tried with the latest versions of RP an JIra (5.1.0)?

**Comment by shishir19** [comment] 2020-04-29 13:26
Hi, I am using latest version 5.1.0.

Few updates - I was able to make the integration with locally installed JIRA server. I was providing full project name instead of key. But with JIRA Cloud instance, the integration still does not work. I have tried with latest JIRA plugin too.

JIRA cloud requires specifying email address as username. Maybe that could be causing the integration to fail?

**Comment by daveedwards123** [comment] 2020-06-04 00:50
Is there any update on this?

I am having the same problem:
ReportPortal: 5.2
Plugin-bts-Jira: 5.1

**Comment by Vaibhavshukla08** [comment] 2020-06-05 09:17
@evjlobanova I am also facing the issue is there any update on this?

**Comment by Yumfriez** [comment] 2020-07-21 14:24
@evjlobanova As for now we don't have integration with Jira Cloud. So we should probably investigate and implement it

**Comment by evjlobanova** [comment] 2020-07-22 07:57
Will be fixed in a scope of refactoring Jira integration. We will implement integration with Jira Cloud.
Approximate estimations - winter 2020 (can be changed)

**Comment by sebastienmascha** [comment] 2020-10-23 08:39
@evjlobanova happy to help if needed 👍 
Any suggestion where I can help without duplicate the current work https://github.com/reportportal/plugin-bts-jira/blob/develop/src/main/java/com/epam/reportportal/extension/bugtracking/jira/JiraStrategy.java ?

**Comment by iKozzz** [comment] 2020-12-23 14:57
api_1 | java.lang.RuntimeException: java.net.ConnectException: Timeout connecting to [jira.mycompany.io/666.66.666.66:443]

So I suppose this issue because JIRA host can not be resolved from docker network (rp_network)

**Comment by lewispoe** [comment] 2021-01-04 15:13
I wanted to check if this feature for Cloud JIRA integration will be included in an upcoming release? We are finding RP platform an excellent tool, but the Cloud JIRA will be vital to our needs. Thanks!

**Comment by evjlobanova** [comment] 2021-01-05 11:39
Hello 
We are planning integration with Cloud Jira ±to spring 2021.
You can use an existing Jira plugin for integration with Cloud Jira. Use a token instead of a password. 
In this case, you will be able to use link issue functionality. 

I will update this issue when we start the implementation of integration with Cloud Jira

**Comment by mironandrei94** [comment] 2021-01-06 12:12
Hi @evjlobanova ,

How can we I use the token?
Tried also the lates jira plug-in with the latest report portal and I am still unable to integrate it.

Thank you,
Andrei

**Comment by lewispoe** [comment] 2021-01-15 16:18
Hi, the token for a password is still failing with a connection refused, echoing @mironandrei94 findings. I've been using the bts jira plugin recommended on your docs, is there another jira integration library you had in mind?

Many Thanks
Lewis

**Comment by joelpramos** [comment] 2021-01-16 00:40
@lewispoe which version did you use? I tried 5.1.0-RC-2 from here https://bintray.com/beta/#/epam/reportportal/plugin-bts-jira?tab=files and didn't work.

**Comment by mironandrei94** [comment] 2021-01-16 10:03
I managed to do it. I used the jira token instead of password. I think that
the documentation could use a little improvement.

Thank you for your reply and have a nice day,
Andrei Miron

În sâm., 16 ian. 2021 la 02:40, Joel Ramos <notifications@github.com> a
scris:

**Comment by joelpramos** [comment] 2021-01-19 00:26
Seems like my problem is exactly the same reported here: https://github.com/reportportal/service-jira/issues/19

Connection setup works but I always get the [ErrorCollectionstatus=400, errors=reporter=Reporter is required., errorMessages=[]]] error message. I've tried with the account ID (as seen in the [deprecation notice](https://developer.atlassian.com/cloud/jira/platform/deprecation-notice-user-privacy-api-migration-guide/)) and also with email/username .

**Comment by MungThai** [comment] 2021-04-07 01:01
I am using plugin-bts-jira-5.1.0-all.jar and seems same problem as @joelpramos

**Comment by MungThai** [comment] 2021-04-07 14:45
> Seems like my problem is exactly the same reported here: [reportportal/service-jira#19](https://github.com/reportportal/service-jira/issues/19)
> 
> Connection setup works but I always get the [ErrorCollectionstatus=400, errors=reporter=Reporter is required., errorMessages=[]]] error message. I've tried with the account ID (as seen in the [deprecation notice](https://developer.atlassian.com/cloud/jira/platform/deprecation-notice-user-privacy-api-migration-guide/)) and also with email/username .

Work around: 
- Login JIRA
- Click on "<Project>" -> "Project settings"
- In "Project setting": click on "Issue type" -> "Bug"
- In "Field Tab", select "Reporter" then click "Remove"

**Comment by sunshine69** [comment] 2021-08-10 08:43
Hi, is there any update or work around on this? I hit the exact same issues. Ta

**Comment by lewispoe** [comment] 2021-08-10 08:57
> Hi, is there any update or work around on this? I hit the exact same issues. Ta

@sunshine69 - if I remember correctly (was awhile back!), the solution was trying to login with Jira username (my email), but **not** your normal password, instead you need to generate an API token in Jira and use that as the password. 

I believe some instructions are here to generate a token in Jira - https://support.atlassian.com/atlassian-account/docs/manage-api-tokens-for-your-atlassian-account/

**Comment by sunshine69** [comment] 2021-08-10 10:52
Thank you but I did it and it does not work for me, still the same error message when I submit the configuration dialog.

**Comment by mhotsiy** [comment] 2022-02-11 19:20
The same issue. Any updates?

**Comment by omaro-kr** [comment] 2022-06-30 21:27
Any Updates?

**Comment by mukesh90hz** [comment] 2023-03-07 05:34
Even I am getting the same error. Any update on this?

**Comment by subha0990** [comment] 2023-08-21 06:38
Any update on this Team ?

**Comment by alena-babrova** [comment] 2023-12-11 11:48
Hello guys,
Starting from version 5.7.0 ReportPortal supports integration with Jira Cloud. 
Please, use an appropriate Jira Cloud plugin to integrate with Cloud version: https://github.com/reportportal/plugin-bts-jira-cloud
I am closing the original ticket based on the information above. Please, don't hesitate to contact if still have any questions.

**Closed by alena-babrova** 2023-12-11 11:48 UTC
Labels: feature request, Plugins: BTS, Feature: Jira Cloud
