### ISSUE TITLE
API - create items (type "step") service creating "test" item 

### ISSUE THREAD

**Issue by skmvali** [reportportal/reportportal#1476] opened 2021-07-23 13:23 UTC
**Describe the bug**
create "step" api creating "test" item in report portal ui

**To Reproduce**
Create launch with "/launch" api
Created Suite with "/item" with (type --> suite)
Create Test with "/item/<suite uuid>" with (type --> test)
Create Step with "/item/<test uuid>" with (type-->step)
**End Point**
**http://localhost:8080/api/v1/deafult_personal/7a656fb4-f9be-4053-8124-9f5b671c0a23**
 
**payload**

{
  "name": "When admin creates a new User",
  "startTime": "1627027006511",
  "type": "step",
  "launchUuid": "febf3771-c270-489f-ba6d-4c73fc626e85",
  "description": "welcome"
}

**Expected behavior**
Step type item should be created instead of test item again under test

**Screenshots**
![image](https://user-images.githubusercontent.com/10713393/126787739-7cd200b4-5b8d-40d0-af72-3bf5d1ae601f.png)

**Desktop (please complete the following information):**
 - OS: Win 10
 - Browser NA
 - Version 

**Additional context**

**Comment by Greesh1** [comment] 2021-07-25 00:57
this issue is happening for me as well.

**Comment by rathod-deep** [comment] 2021-07-27 05:31
It's happening for me 
![image](https://user-images.githubusercontent.com/50038708/127100716-74621f0b-48fb-4996-a829-94d6a243aa8c.png)

**Comment by rathod-deep** [comment] 2021-07-30 05:06
@skmvali can you please add tags? Bugs and Help wanted, might be we can get update on it

**Comment by DzmitryHumianiuk** [comment] 2021-08-11 17:26
@skmvali @rathod-deep 
Hi,
**the simple answer** here: it works by design.

**The full answer**: it is a legacy, which should be considered while implementing own integrations.
We plan to refactor it with version 6.

There 2 main requests to build structure in ReportPortal.

- Launch Requests 
- TestItem Requests

Launch is a root, launch is a starting point, a container. You have a separate endpoint for it.
All the rest in launch structure will be created by `TestItem Requests`
please see for reference: [/DevGuides/reporting.md](https://github.com/reportportal/documentation/blob/master/src/md/src/DevGuides/reporting.md) 

In `TestItem Requests` you control the type with attribute `type`
```
Allowable values: "suite", "story", "test", "scenario", "step", "before_class", "before_groups", "before_method", "before_suite",      "before_test", "after_class", "after_groups", "after_method", "after_suite", "after_test" 
```

### **There is a difference of type which you see on UI and in back-end calls! ⚠️**

> this is a legacy, which was aimed to address BDD structure, but then abandoned, since require refactoring of all integrations at once.

| TestItem type  | What you see on UI |
|------------|----------|
| `suite` or `story`         | Suite      |
| `test` or `scenario` | Test Class or Suite       |
| `step` | **Test**       |
| `step` or `before_class`, `before_groups`, `before_method`, `before_suite`, `before_test`, `after_class`, `after_groups`, `after_method`, `after_suite`, `after_test` |  BeforeClass method, BeforeGroups method, Before method, BeforeSuite method, BeforeTest method, AfterClass method, AfteGroups method, After method, After suite method, AfterTest method      |
| `step` + `"hasStats": false,` |  Nested Step in logs      |


Please read carefully at https://github.com/reportportal/documentation/blob/master/src/md/src/DevGuides/reporting.md

**Comment by MaryiaRymarchyk** [comment] 2023-04-27 14:18
Hi @skmvali, are there any open questions?  
If information above was helpful - can we close the issue?

**Closed** 2023-04-27 14:47 UTC
Labels: help wanted, Waiting Info From Requestor, Feature: Reporting
