### ISSUE TITLE
Admin can't remove shared dashboard or widget

### ISSUE THREAD

**Issue by iKozzz** [reportportal/reportportal#94] opened 2017-04-03 15:27 UTC
Error appears when admin tries to remove shared dashboard or widget
```
"error_code":40014,"
message":"Unable modify sharable resource. User Admin isn't owner of CoolDashboard resource."
```

**Comment by DzmitryHumianiuk** [comment] 2017-04-04 11:00
fix in 3.0beta

**Comment by avarabyeu** [comment] 2017-04-05 20:34
Actually, the problem is still under discussion. There are two types of roles in ReportPortal:
1) User roles
2) Project roles
The mentioned action requires project role higher than 'LEAD'. Not sure if we need mix logic and give administrator project-based permissions. The way i would suggest to workaround the issue is to assign admin to project with 'lead' role and only then allow to remove project-related resources. 
This way we would keep strong separation between project-level resources (project roles area) and system-level resources (user roles area)

**Comment by DzmitryHumianiuk** [comment] 2017-04-07 14:31
@iKozzz 
resolved with the next:
admin will have PM role at project, when assigned.

to avoid `if/else` workarounds in permission's code line.

**Closed by DzmitryHumianiuk** 2017-04-07 14:31 UTC
Labels: beta:3.0, bug
