### ISSUE TITLE
service-index 5.8.0 runs as root and cannot be deployed to OpenShift/OKD

### ISSUE THREAD

**Issue by kevinwhiteFSR** [reportportal/reportportal#2075] opened 2023-08-03 14:29 UTC
My enterprise uses OpenShift for hosting containers, and we want to deploy ReportPortal into our corporate openshift environment. 5.7.4 was able to install successfully, but we want to upgrade to 5.8.0 for some report changes. However, we cannot do that because the latest service-index tries to run as root and openshift does not allow that. It is not possible for us to work around that; this is running in a production environment and forcing it to allow root is against OpenShift's security design and our company policy.

It seems that running out of /root/ for the WORKDIR is the culprit (though I am not an expert). 

Can this be changed to better support running as arbitrary user IDs per OpenShift's documentation?

**Comment by bond-** [comment] 2023-08-03 16:41
The source of the problem is assuming /root as the workdir here: https://github.com/reportportal/service-index/commit/531cea86643b592045857ffe15180d25141bd654#diff-dd2c0eb6ea5cfc6c4bd4eac30934e2d5746747af48fef6da689e85b752f39557R26

Our organization has it pretty locked down, so we cannot access `/root/app`.

If no objections I can try to change /root to something less restrictive and make it allowed by arbitrary user/group. Ref: https://docs.okd.io/4.13/openshift_images/create-images.html#images-create-guide-openshift_create-images

**Comment by DzmitryHumianiuk** [comment] 2023-08-17 17:55
Merged.
most probably will be included in 23.2

**Closed** 2023-08-18 17:39 UTC
Labels: bug
