### ISSUE TITLE
Couldn't start Report Portal due to Couldn't start RabbitMQ in background

### ISSUE THREAD

**Issue by luckhiem** [reportportal/reportportal#2085] opened 2023-08-11 03:30 UTC
**Describe the bug**
RabbitMQ Service - Couldn't start RabbitMQ in background.

**Expected behavior**
...

**Screenshots**

**Versions:**
 - OS: MacOS 13.5 (22G74)
 - Chip: Apple M1 Pro
```2023-08-11 10:23:53 rabbitmq 03:23:53.90 
2023-08-11 10:23:53 rabbitmq 03:23:53.94 Welcome to the Bitnami rabbitmq container
2023-08-11 10:23:53 rabbitmq 03:23:53.98 Subscribe to project updates by watching https://github.com/bitnami/containers
2023-08-11 10:23:54 rabbitmq 03:23:54.02 Submit issues and feature requests at https://github.com/bitnami/containers/issues
2023-08-11 10:23:54 rabbitmq 03:23:54.07 
2023-08-11 10:23:54 rabbitmq 03:23:54.11 INFO  ==> ** Starting RabbitMQ setup **
2023-08-11 10:23:54 rabbitmq 03:23:54.38 INFO  ==> Validating settings in RABBITMQ_* env vars..
2023-08-11 10:23:54 rabbitmq 03:23:54.89 INFO  ==> Initializing RabbitMQ...
2023-08-11 10:23:55 rabbitmq 03:23:55.27 INFO  ==> Generating random cookie
2023-08-11 10:23:55 rabbitmq 03:23:55.67 INFO  ==> Starting RabbitMQ in background...
2023-08-11 10:23:57 /opt/bitnami/scripts/libos.sh: line 344:   147 Segmentation fault      "$@" > /dev/null 2>&1
2023-08-11 10:24:07 /opt/bitnami/scripts/libos.sh: line 344:   246 Segmentation fault      "$@" > /dev/null 2>&1
2023-08-11 10:24:18 /opt/bitnami/scripts/libos.sh: line 344:   294 Segmentation fault      "$@" > /dev/null 2>&1
2023-08-11 10:24:28 /opt/bitnami/scripts/libos.sh: line 344:   391 Segmentation fault      "$@" > /dev/null 2>&1
2023-08-11 10:24:39 /opt/bitnami/scripts/libos.sh: line 344:   439 Segmentation fault      "$@" > /dev/null 2>&1
2023-08-11 10:24:49 /opt/bitnami/scripts/libos.sh: line 344:   487 Segmentation fault      "$@" > /dev/null 2>&1
2023-08-11 10:25:00 /opt/bitnami/scripts/libos.sh: line 344:   584 Segmentation fault      "$@" > /dev/null 2>&1
2023-08-11 10:25:11 /opt/bitnami/scripts/libos.sh: line 344:   632 Segmentation fault      "$@" > /dev/null 2>&1
2023-08-11 10:25:21 /opt/bitnami/scripts/libos.sh: line 344:   680 Segmentation fault      "$@" > /dev/null 2>&1
2023-08-11 10:25:32 /opt/bitnami/scripts/libos.sh: line 344:   777 Segmentation fault      "$@" > /dev/null 2>&1
2023-08-11 10:25:42 rabbitmq 03:25:42.09 ERROR ==> Couldn't start RabbitMQ in background.
2023-08-11 10:25:42 rabbitmq 03:25:42.61 
2023-08-11 10:25:42 rabbitmq 03:25:42.64 Welcome to the Bitnami rabbitmq container
2023-08-11 10:25:42 rabbitmq 03:25:42.66 Subscribe to project updates by watching https://github.com/bitnami/containers
2023-08-11 10:25:42 rabbitmq 03:25:42.69 Submit issues and feature requests at https://github.com/bitnami/containers/issues
2023-08-11 10:25:42 rabbitmq 03:25:42.71 
2023-08-11 10:25:42 rabbitmq 03:25:42.73 INFO  ==> ** Starting RabbitMQ setup **
2023-08-11 10:25:42 rabbitmq 03:25:42.86 INFO  ==> Validating settings in RABBITMQ_* env vars..
2023-08-11 10:25:43 rabbitmq 03:25:43.07 INFO  ==> Initializing RabbitMQ...
2023-08-11 10:25:43 rabbitmq 03:25:43.31 INFO  ==> Starting RabbitMQ in background...
2023-08-11 10:25:43 /opt/bitnami/scripts/libos.sh: line 344:   109 Segmentation fault      "$@" > /dev/null 2>&1
2023-08-11 10:25:54 /opt/bitnami/scripts/libos.sh: line 344:   205 Segmentation fault      "$@" > /dev/null 2>&1
2023-08-11 10:26:04 /opt/bitnami/scripts/libos.sh: line 344:   253 Segmentation fault      "$@" > /dev/null 2>&1
2023-08-11 10:26:15 /opt/bitnami/scripts/libos.sh: line 344:   350 Segmentation fault      "$@" > /dev/null 2>&1
2023-08-11 10:26:25 /opt/bitnami/scripts/libos.sh: line 344:   398 Segmentation fault      "$@" > /dev/null 2>&1
2023-08-11 10:26:36 /opt/bitnami/scripts/libos.sh: line 344:   446 Segmentation fault      "$@" > /dev/null 2>&1
2023-08-11 10:26:46 /opt/bitnami/scripts/libos.sh: line 344:   543 Segmentation fault      "$@" > /dev/null 2>&1
2023-08-11 10:26:57 /opt/bitnami/scripts/libos.sh: line 344:   591 Segmentation fault      "$@" > /dev/null 2>&1
2023-08-11 10:27:07 /opt/bitnami/scripts/libos.sh: line 344:   639 Segmentation fault      "$@" > /dev/null 2>&1
2023-08-11 10:27:18 /opt/bitnami/scripts/libos.sh: line 344:   736 Segmentation fault      "$@" > /dev/null 2>&1
2023-08-11 10:27:28 rabbitmq 03:27:28.19 ERROR ==> Couldn't start RabbitMQ in background.
2023-08-11 10:27:28 rabbitmq 03:27:28.66 
2023-08-11 10:27:28 rabbitmq 03:27:28.69 Welcome to the Bitnami rabbitmq container
2023-08-11 10:27:28 rabbitmq 03:27:28.71 Subscribe to project updates by watching https://github.com/bitnami/containers
2023-08-11 10:27:28 rabbitmq 03:27:28.73 Submit issues and feature requests at https://github.com/bitnami/containers/issues
2023-08-11 10:27:28 rabbitmq 03:27:28.75 
2023-08-11 10:27:28 rabbitmq 03:27:28.77 INFO  ==> ** Starting RabbitMQ setup **
2023-08-11 10:27:28 rabbitmq 03:27:28.90 INFO  ==> Validating settings in RABBITMQ_* env vars..
2023-08-11 10:27:29 rabbitmq 03:27:29.10 INFO  ==> Initializing RabbitMQ...
2023-08-11 10:27:29 rabbitmq 03:27:29.36 INFO  ==> Starting RabbitMQ in background...
2023-08-11 10:27:29 /opt/bitnami/scripts/libos.sh: line 344:   109 Segmentation fault      "$@" > /dev/null 2>&1
2023-08-11 10:27:40 /opt/bitnami/scripts/libos.sh: line 344:   205 Segmentation fault      "$@" > /dev/null 2>&1
2023-08-11 10:27:50 /opt/bitnami/scripts/libos.sh: line 344:   253 Segmentation fault      "$@" > /dev/null 2>&1
2023-08-11 10:28:01 /opt/bitnami/scripts/libos.sh: line 344:   350 Segmentation fault      "$@" > /dev/null 2>&1
2023-08-11 10:28:11 /opt/bitnami/scripts/libos.sh: line 344:   398 Segmentation fault      "$@" > /dev/null 2>&1
2023-08-11 10:28:22 /opt/bitnami/scripts/libos.sh: line 344:   446 Segmentation fault      "$@" > /dev/null 2>&1
2023-08-11 10:28:32 /opt/bitnami/scripts/libos.sh: line 344:   543 Segmentation fault      "$@" > /dev/null 2>&1
2023-08-11 10:28:43 /opt/bitnami/scripts/libos.sh: line 344:   591 Segmentation fault      "$@" > /dev/null 2>&1
2023-08-11 10:28:53 /opt/bitnami/scripts/libos.sh: line 344:   639 Segmentation fault      "$@" > /dev/null 2>&1

**Comment by alena-babrova** [comment] 2024-03-18 16:14
Hello @luckhiem,

Could you please tell me if the issue is still relevant for you?

**Comment by alena-babrova** [comment] 2024-04-26 11:50
Dear @luckhiem,

As we haven't received a reply from you, we'll close the issue for now.
Just in case you still have the issue, please, do not hesitate to get in touch.

**Closed by alena-babrova** 2024-04-26 11:50 UTC
Labels: bug
