### ISSUE TITLE
[v5] Data retention (Cleanup) jobs does not work very well

### ISSUE THREAD

**Issue by coufalja** [reportportal/reportportal#1231] opened 2020-11-30 10:22 UTC
**Describe the bug**
The data retention does not work very well.
- Dubious default values
  - in the `application.yaml` sets the initial delay of all Cleanup jobs to 7Days, that in practice means that the process has to survive 7D in order to launch the job. The counter is reset each time the process is restarted which in a dynamic environment like K8s could mean *never* in practice.
  - Another weird default setting is that the period is set to 7 and 14D respectively. Cleaning up launches once 14 days could mean you need to go through thousands of launches.
- Together with another issue where the whole <Whatever>CleanupJob run is run in a single large transaction e.g. `com.epam.ta.reportportal.job.service.impl.LaunchCleanerServiceImpl#cleanOutdatedLaunches` leads to the situation when the cleanup could take days generating tons of temporary data in the Postgres (due to being in a single large transaction and Postgres having to create duplicates to ensure transaction isolation)

**To Reproduce**

**Expected behaviour**
* Sane default values built-in
* Not using single huge transactions to cleanup all launches etc... at once so there is a chance to finish the Job

**Additional context**
* We run reportportal in K8s v5.3.2

**Comment by coufalja** [comment] 2020-11-30 10:23
As #1223 got closed I rephrased the issue without the frontend one.

**Comment by evjlobanova** [comment] 2020-11-30 10:47
Thank you for opening it again.
Yes, we have already thought about these issues. 
Now back-end team is in the progress of preparing possible solutions on how to resolve issues. 

@pbortnik Pasha, could you please check and confirm if we have changed the default values?

**Comment by coufalja** [comment] 2020-11-30 10:54
@evjlobanova We (my company @wandera) would gladly help/contribute a PR but given the change will not be trivial we would like to discuss it first so we follow the right architecture path. So feel free to contact us on your slack which a couple of our engineers joined (`Jakub Coufal` or `Ondřej Hájek`) OFC if you have some plan already we won't interfere as too many cooks spoil the broth.

**Comment by pbortnik** [comment] 2020-12-02 09:07
Hi, @coufalja 
We have changed default periods for cleaning jobs. Also, it can be configured by env. variables 
```
- name: RP_ENVIRONMENT_VARIABLE_CLEAN_ATTACH
  value: "PT40M"
- name: RP_ENVIRONMENT_VARIABLE_CLEAN_LOGS
  value: "PT30M"
- name: RP_ENVIRONMENT_VARIABLE_CLEAN_LAUNCHES
  value: "PT20M"
```

Also, we have some ideas how to improve those jobs and planning to do it very soon. Than you for the issue!

**Comment by coufalja** [comment] 2020-12-02 14:21
Thanks, we have tried changing the periods by the ENV props a while ago sadly we already have months of data in so the cleanup never finishes and eats the DB alive.

**Comment by evjlobanova** [comment] 2020-12-03 09:13
@coufalja We has a meeting regarding this topic, in the next sprint, we will take investigations and preparing possible options for resolving. And as soon as we define the final option, I will inform you.

We can create a channel in slack in order to discuss detail and possible contribution to this issue with you and your team.

**Comment by coufalja** [comment] 2020-12-03 09:59
@evjlobanova That is great to hear, we still want to help so If you don't mind invite us (the usernames above) into the channel.

**Comment by NoReflexness** [comment] 2020-12-03 14:08
> Thanks, we have tried changing the periods by the ENV props a while ago sadly we already have months of data in so the cleanup never finishes and eats the DB alive.

We are in the same boat, putting in extraordinary maintenance windows in tomorrow to expand the postgres persistent volume as we are currently eating 2% pr. day with no end in sight. Thank you guys for working in it.

**Comment by DzmitryHumianiuk** [comment] 2020-12-03 15:29
@coufalja that's a good catch, BTW.
discussion will address our architectural strategy, since we need to make it both flexible for single-container setup and multiply in k8s.

**Comment by evjlobanova** [comment] 2020-12-10 11:05
@coufalja We have found one of the problems, that can help to resolve the problem partly. Now the delay for job run is 7 day.
You can change this period by providing an env variable. 

RP_ENVIRONMENT_VARIABLE_JOB_DELAY=PT1M

**Comment by pbortnik** [comment] 2020-12-10 11:06
Hi @coufalja ,
5.3.3 have a misconfiguration. Jobs beginning have delay in 7 days. 
You can provide a 
`RP_ENVIRONMENT_VARIABLE_JOB_DELAY=PT1M `
It will change the delay to 1 minute. And then job will be started according scheduler provided in other env varibales.

```

- name: RP_ENVIRONMENT_VARIABLE_CLEAN_ATTACH
  value: "PT40M"
- name: RP_ENVIRONMENT_VARIABLE_CLEAN_LOGS
  value: "PT30M"
- name: RP_ENVIRONMENT_VARIABLE_CLEAN_LAUNCHES
  value: "PT20M"

```

From the version 5.3.4 the delay will be the same as provided scheduler.

**Comment by coufalja** [comment] 2020-12-15 21:30
Hi, @pbortnik that is actually what I did even before filing the issue. It is defo a great idea to set the variables this way for the future releases and it will most probably help to someone with not too much of a data in the DB already. Unfortunately, that is not our case, we have thousands of launches that should be deleted via the retention policy but due to RP deleting all launches falling to the "to be deleted by retention" period in a single DB transaction it is not working for us. The code is running for hours eventually depleting resources in a DB and crashing (due to huge transaction). What we might do is to shut down all of our periodic launches of test suites closing down access to the RP for a couple of Hours/Days possibly and let it finish the Cleanup job if we achieve a successful finish of a first one all subsequent ones should be a piece of cake as they will deal with far fewer data.

**Comment by ValeriiVozniuk** [comment] 2020-12-16 08:33
> 5.3.3 have a misconfiguration. Jobs beginning have delay in 7 days.
> You can provide a
> `RP_ENVIRONMENT_VARIABLE_JOB_DELAY=PT1M `
> It will change the delay to 1 minute. And then job will be started according scheduler provided in other env varibales.

Hi @pbortnik ,
I've stumbled upon this issue in our Report Portal deployment, but as I'm not familiar enough with it yet, it is not clear for me where/for which component I need to set up this variable, could you please tell me it?

I've assumed that this should be reportportal-api component, and set it on that pod
```
    Environment:
      RP_ENVIRONMENT_VARIABLE_JOB_DELAY:  PT1M
```
, but I still see files which should be cleared in minio
```/export/prj-4/2020-12 $ ls -larth
total 160M
drwxrwsr-x    2 1000     1000      296.0K Dec  1 18:34 7e4df69a-ea47-429a-9fa4-6c64002685b5
drwxrwsr-x    2 1000     1000       36.0K Dec  1 18:34 1d434ad2-bbf3-4e88-af2a-9c241bada521
drwxrwsr-x    2 1000     1000       60.0K Dec  1 18:34 9d579dec-058b-4296-b47f-8a3e9b22c22b
drwxrwsr-x    2 1000     1000      244.0K Dec  1 18:34 9edc4e42-c559-4938-ac00-186035916023
drwxrwsr-x    2 1000     1000        8.0K Dec  2 01:39 e1bfd3da-0da2-4b7d-9d35-2d38d5084706
```
, could you please advice?

**Comment by narayan-meesho** [comment] 2020-12-17 04:13
Hi, @pbortnik , I am also getting issue where Data deletion job is consuming all cpu resources and even after letting it run , data is not getting deleted as @coufalja @ValeriiVozniuk  has mentioned. This is First deletion.

**Comment by narayan-meesho** [comment] 2020-12-17 11:22
@evjlobanova can some from team help on this .

**Comment by ValeriiVozniuk** [comment] 2020-12-30 11:28
So, I've updated to 5.3.4 on Monday, and finally started seeing cleanup messages in api logs. Unfortunately, cleanup still does not work for me, as it throws a bunch of errors this time:
```
2020-12-29 22:40:39.243  WARN 6 --- [portal_Worker-1] com.zaxxer.hikari.pool.ProxyConnection   : HikariPool-1 - Connection org.postgresql.jdbc.PgConnection@a5ab018 marked as broken because of SQLSTATE(08006), ErrorCode(0)

org.postgresql.util.PSQLException: An I/O error occurred while sending to the backend.
...
2020-12-29 22:40:39.250 ERROR 6 --- [portal_Worker-1] e.t.r.j.s.i.AttachmentCleanerServiceImpl : Error during cleaning project attachments

org.jooq.exception.DataAccessException: SQL [select "public"."test_item"."item_id" from "public"."test_item" left outer join "public"."test_item" as "retry_parent" on "public"."test_item"."retry_of" = "retry_parent"."item_id" where ("public"."test_item"."launch_id" = ? or "retry_parent"."launch_id" = ?) order by "public"."test_item"."item_id" limit ?]; An I/O error occurred while sending to the backend.
...
2020-12-29 22:40:39.252 ERROR 6 --- [portal_Worker-1] c.e.t.r.job.CleanScreenshotsJob          : Cleaning outdated screenshots for project 4 has been failed

org.springframework.orm.jpa.JpaSystemException: Unable to commit against JDBC Connection; nested exception is org.hibernate.TransactionException: Unable to commit against JDBC Connection
...
2020-12-29 22:40:39.255  WARN 6 --- [portal_Worker-1] o.h.engine.jdbc.spi.SqlExceptionHelper   : SQL Error: 0, SQLState: 08006
2020-12-29 22:40:39.255 ERROR 6 --- [portal_Worker-1] o.h.engine.jdbc.spi.SqlExceptionHelper   : An I/O error occurred while sending to the backend.
2020-12-29 22:40:39.259 ERROR 6 --- [portal_Worker-1] e.t.r.j.s.i.AttachmentCleanerServiceImpl : Error during cleaning project attachments

org.hibernate.exception.JDBCConnectionException: could not extract ResultSet
``` 
Any advice how I can troubleshoot this?

**Comment by evgenytkachenko** [comment] 2021-01-04 22:23
I have the same issue with logs and outdated launches not being deleted. I have RP 5.3.3 installed via docker

**Comment by evjlobanova** [comment] 2021-01-05 11:41
We have made a small fix in version 5.3.4. So please update to the latest version 
And in a future versions, we are preparing a refactoring of retention jobs.

**Comment by evjlobanova** [comment] 2021-01-05 11:42
@pbortnik could you please check a message from @ValeriiVozniuk

**Comment by evjlobanova** [comment] 2021-01-14 09:40
Hello @coufalja @evgenytkachenko @ValeriiVozniuk @narayan-meesho 


В след версию возьмем POC на переписание джоб на спринг бач.
Пока юзерам из всех возможных воркароундов можно предлагать только самостоятельное мануальное удаление.

I want to update you regarding this issue so you can understand what is going on.

We are investigating this issue carefully. For now, we can not reproduce this issue on our test envs.  But for big instances (+400 Gb) the problems start reproducing. So that our first assumption is that problems with jobs correlate with DB size.

We divided this issue into 2 parts:
1. Quick fix for minor 5.3.5 version - we will make transactions, not for all projects, but for one launch. It helps us to reduce time on one transaction. ETA for release - the end of the next week

2. Refactoring on job logic  -  add a defined schedule for jobs. the first should be the work Attachments job, then logs, and in the end launches job. Now we are working on POC for the new jobs. At the end of the next week, we will be ready to share our vision. ETA for release with new jobs ± 5.4 beginning of March 2021

**Comment by evgenytkachenko** [comment] 2021-01-14 12:51
Thanks @evjlobanova for the update
You mentioned the only workaround is to delete manually. Does it mean the only way is to delete the launches from the RP UI or is there a script that could delete all outdated launches in the DB?

**Comment by evjlobanova** [comment] 2021-01-15 11:55
Hello @coufalja @evgenytkachenko @ValeriiVozniuk @narayan-meesho
I would like to share some results of the performance testing of the attachments job run. For now, the fix is on the testing, but the results are pretty inspiring.

Please find performance in numbers:
before fix - deleting 10Gb in 10 hours
after fix - deleting 18Gb in 10 minutes

Performance in DB load stats(instance with 2 CPU's):
before fix - 100% CPU load during job execution
after fix - up 10 10% CPU load during job execution

AWS RDS Performance Insights monitoring stats:

![image](https://user-images.githubusercontent.com/30413511/104722779-34e63880-56e3-11eb-8cd0-cc5e392ed251.png)

As I said the fix is in progress, and these are preliminary results. We should finalize our regression process, and test results on a big instance. 

I suppose we will be ready to share a patch with a fix for your testing (not for production usage) on the next week. 
And after that, we will release 5.3.5. 

I will be glad to answer all questions, in case of any. 

Best regards,
Yauheniya

cc @DzmitryHumianiuk @irynakozak2 @Yumfriez @pbortnik @

**Comment by evjlobanova** [comment] 2021-01-15 12:02
@evgenytkachenko both options are available.  For now, we concentrate all our attention on fixing so that there is no script out of the box. 

Also, I should highlight one important thing regarding removal from DB.
In case data is removed from DB, it is not removed from Minio. 
So that you should clean Minio separately. 
The team is working under the creation of API endpoint that  receives CSV file with attachments that should be removed from Minio, and removes them. 

This endpoint is also will be available in version 5.3.5

**Comment by DzmitryHumianiuk** [comment] 2021-01-16 19:49
I've posted in Gist a simple script in bash to delete launches via API 
_(for ReportPortal of versions 5.3+)_
you can run it on Mac and Linux.

https://gist.github.com/DzmitryHumianiuk/8e2622b582924c4339619cbb1dfec0f5

Consist of 2 files:

- `sc_clean.sh`
- `projects.txt`

Place both files in same directory.
** File `projects.txt` should alway have additional empty line.
** Projects in `projects.txt` should be in lower case.

**Configuring:**

1. [Line 1](https://gist.github.com/DzmitryHumianiuk/8e2622b582924c4339619cbb1dfec0f5#file-sc_clean-sh-L1): Add your admin TOKEN
2. [Line 2](https://gist.github.com/DzmitryHumianiuk/8e2622b582924c4339619cbb1dfec0f5#file-sc_clean-sh-L2): Add server address
3. [Line 78](https://gist.github.com/DzmitryHumianiuk/8e2622b582924c4339619cbb1dfec0f5#file-sc_clean-sh-L78): Add filtering conditions as `&filter.btw.startTime=1583010000000%2C1606770000000`
** if you put `FILTER_TIME=""` it means no filtering applied, thus all launches will be deleted
** [Lines 76-82](https://gist.github.com/DzmitryHumianiuk/8e2622b582924c4339619cbb1dfec0f5#file-sc_clean-sh-L76-L82) responsible for configuration of Regular launches
** [Lines 83-89](https://gist.github.com/DzmitryHumianiuk/8e2622b582924c4339619cbb1dfec0f5#file-sc_clean-sh-L83-L89) for Debug section
** Most convenient way to create a filter is to open your ReportPortal, open launches, create filter and set time period on UI. Then open Developer Tools > Network tab and see launch request. Copy `filter.btw.startTime` param value. Please see screen below for reference.


**Execution:**
** _please try the script with dummy project first_
```shell
    sh sc_clean.sh projects.txt
```

**Parameters:**
$1 file name with list of projects to work with
$2 number of launches in one page of filter, i.e. page.size
$3 filtering direction `DESC|ASC`
$4 pages to offset 
$5 flag to remove project list after the job completion `"remove"|any`

Parameters 2-3-4-5 used for multithreaded execution. Full command will look like:
```shell
    sh sc_clean.sh projects.txt 30 ASC 2 remove
```


Screen below for reference: how to find TIME filter parameters
<img width="1209" alt="Screen Shot 2021-01-16 at 10 46 39 PM" src="https://user-images.githubusercontent.com/11332788/104821436-e9e83480-584c-11eb-91f8-f056e44296d5.png">

**Closed** 2021-02-12 18:17 UTC
Labels: Check: BackEnd

**Comment by gpapadakis** [comment] 2021-05-12 07:23
Hi guys we recently upgraded to v5.3.5 but the cleaup policy at least for the attachments so far is not working. Can you elaborate on this?

**Comment by evjlobanova** [comment] 2021-05-12 14:12
@gpapadakis in the version 5.3.5 we have made a small fix for jobs, it should help basically. In version 5.4 we rewrote jobs.  The release will be this month. 
It is difficult to tell you what exactly is a reason for unworking jobs. You can check the job table in DB and check the start time for jobs and define when it should run.
