### ISSUE TITLE
Unable to add new widgets and also unable to edit existing widgets in Reportportal 5.4.0 version.

### ISSUE THREAD

**Issue by krishnaPedd** [reportportal/reportportal#1481] opened 2021-07-28 13:01 UTC
**Describe the bug**
Unable to add new widgets and unable to edit existing widgets in Report portal dashboard. 
1.After selected on particular widget name then clicking on next button after that it is navigating to blank screen.
2.In existing widgets if i am trying to clicked on edit button in EditWidget page, it is navigating to blank screen.

**Expected behavior**
1.After selecting the widget name and clicked next button then it should navigate to widget filter page.
2.In existing widgets, After clicked on  edit button in EditWidget page, it should show the page  with search text box and existing filter names.

<img width="1246" alt="Screenshot 2021-07-28 at 6 02 41 PM" src="https://user-images.githubusercontent.com/70696677/127324122-6e75d159-b927-45bb-8250-f003c287da7f.png">

**Screenshots**
If applicable

**Versions:**
 - OS, Browser: Mac OS catalina, chrome 83
 - Version of RP [find it under Login form, copy as is]:5.4.0

Thanks,
Krishna

**Comment by VolhaKarenko** [comment] 2021-08-19 06:26
Hi @krishnaPedd, it seems that the issue is connected with one of the filters on your project, that’s why when you open “Edit widget” modal, it fails on the step, when filter list should be provided. Could you please check if the Filters tab is available?

**Comment by MaryiaRymarchyk** [comment] 2023-03-03 12:28
As we haven't received a reply from you, we'll close the issue for now.
Just in case you still have the issue, please, do not hesitate to get in touch.

**Closed by MaryiaRymarchyk** 2023-03-03 12:28 UTC
