### ISSUE TITLE
Automatic cleaning up of launches doesn't work

### ISSUE THREAD

**Issue by dmzorin** [reportportal/reportportal#1885] opened 2022-11-21 11:14 UTC
Hello, I set up "Keep launches" to 90 days. When I navigate to Launches I saw 2 years old launches. May be someone faced such problem and knows what the reason is? Thanks in advance

**Comment by Oleksii-kh89** [comment] 2022-12-08 15:35
Hi @dmzorin 
What RP version do you use? If you use the version below 5.4 please update RP to the latest released version.
If you use version 5.5 and above, please share data from shedlock table and your cron for jobs environment variables.

**Comment by dmzorin** [comment] 2022-12-15 12:23
Hello @Oleksii-kh89, we are using RP version 5.7.0. For deployment we used this compose file https://raw.githubusercontent.com/reportportal/reportportal/5.7.0/docker-compose.yml. In report portal UI we set up setting "Keep launches" to 90 days. In my understanding it should remove launches older than 90 days. Please correct me if I wrong here. But I can see may launches from the past year. 
Unfortunately I don't know what is shedlock table and haven't configured any additional cron jobs.

**Comment by samagarw** [comment] 2023-01-02 06:45
@Oleksii-kh89  : 

I am using RP version - 5.7 

Following data are in shedlock table : 

calculateAllocatedStorage	2022-10-14 15:25:00	2022-10-14 15:25:00	reportportal1-jobs-584d5b6785-72zxhcleanLog
cleanLog	2022-10-14 00:00:24	2022-10-14 00:00:00	reportportal1-jobs-584d5b6785-g5kpr
cleanLaunch	2022-10-14 00:01:19	2022-10-14 00:00:24	reportportal1-jobs-584d5b6785-g5kpr
cleanStorage	2022-10-14 00:01:23	2022-10-14 00:01:19	reportportal1-jobs-584d5b6785-g5kpr
cleanAttachment	2022-10-14 00:01:23	2022-10-14 00:01:23	reportportal1-jobs-584d5b6785-g5kpr
cleanMaterializedView	2022-10-14 00:01:23	2022-10-14 00:01:23	reportportal1-jobs-584d5b6785-g5kpr

I have added the persistent volume of 100 GB and it is still getting full . 

Also the details for service-jobs pod with cron variables. 

env:
        - name: RP_ENVIRONMENT_VARIABLE_CLEAN_ATTACHMENT_CRON
          value: 0 0 */24 * * *
        - name: RP_ENVIRONMENT_VARIABLE_CLEAN_LOG_CRON
          value: 0 0 */24 * * *
        - name: RP_ENVIRONMENT_VARIABLE_CLEAN_LAUNCH_CRON
          value: 0 0 */24 * * *
        - name: RP_ENVIRONMENT_VARIABLE_CLEAN_STORAGE_CRON
          value: 0 0 */24 * * *
        - name: RP_ENVIRONMENT_VARIABLE_STORAGE_PROJECT_CRON
          value: 0 */5 * * * *
        - name: RP_ENVIRONMENT_VARIABLE_CLEAN_STORAGE_CHUNKSIZE
          value: '1000'
          
          Also the service-jobs is throwing following error : 
          
          Caused by: org.springframework.beans.BeanInstantiationException: Failed to instantiate [org.springframework.amqp.rabbit.connection.ConnectionFactory]: Factory method 'processingConnectionFactory' threw exception; nested exception is java.lang.ArrayIndexOutOfBoundsException: Index 0 out of bounds for length 0
	at org.springframework.beans.factory.support.SimpleInstantiationStrategy.instantiate(SimpleInstantiationStrategy.java:185) ~[spring-beans-5.3.4.jar!/:5.3.4]
	at org.springframework.beans.factory.support.ConstructorResolver.instantiate(ConstructorResolver.java:653) ~[spring-beans-5.3.4.jar!/:5.3.4]
	... 54 common frames omitted
Caused by: java.lang.ArrayIndexOutOfBoundsException: Index 0 out of bounds for length 0
	at com.rabbitmq.client.ConnectionFactory.setUri(ConnectionFactory.java:339) ~[amqp-client-5.10.0.jar!/:5.10.0]
	at org.springframework.amqp.rabbit.connection.AbstractConnectionFactory.setUri(AbstractConnectionFactory.java:284) ~[spring-rabbit-2.3.5.jar!/:2.3.5]
	at org.springframework.amqp.rabbit.connection.CachingConnectionFactory.<init>(CachingConnectionFactory.java:269) ~[spring-rabbit-2.3.5.jar!/:2.3.5]
	at com.epam.reportportal.config.rabbit.ProcessingRabbitMqConfiguration.processingConnectionFactory(ProcessingRabbitMqConfiguration.java:43) ~[classes!/:na]
	at com.epam.reportportal.config.rabbit.ProcessingRabbitMqConfiguration$$EnhancerBySpringCGLIB$$fa54c034.CGLIB$processingConnectionFactory$1(<generated>) ~[classes!/:na]
	at com.epam.reportportal.config.rabbit.ProcessingRabbitMqConfiguration$$EnhancerBySpringCGLIB$$fa54c034$$FastClassBySpringCGLIB$$8cc89828.invoke(<generated>) ~[classes!/:na]
	at org.springframework.cglib.proxy.MethodProxy.invokeSuper(MethodProxy.java:244) ~[spring-core-5.3.4.jar!/:5.3.4]
	at org.springframework.context.annotation.ConfigurationClassEnhancer$BeanMethodInterceptor.intercept(ConfigurationClassEnhancer.java:331) ~[spring-context-5.3.4.jar!/:5.3.4]
	at com.epam.reportportal.config.rabbit.ProcessingRabbitMqConfiguration$$EnhancerBySpringCGLIB$$fa54c034.processingConnectionFactory(<generated>) ~[classes!/:na]
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:na]
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:na]
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:na]
	at java.base/java.lang.reflect.Method.invoke(Method.java:566) ~[na:na]
	at org.springframework.beans.factory.support.SimpleInstantiationStrategy.instantiate(SimpleInstantiationStrategy.java:154) ~[spring-beans-5.3.4.jar!/:5.3.4]
	... 55 common frames omitted
2023-01-02T06:43:57.278944164Z

**Comment by Oleksii-kh89** [comment] 2023-01-05 15:22
@samagarw, according to the data from your shedlock table it's seen that cleanLaunch job works. I see that variable RP_ENVIRONMENT_VARIABLE_CLEAN_STORAGE_CHUNKSIZE has the value 1000. I recommend you increase this value up to 200000. Also, I advise you to perform vacuum full regarding our tutorial [https://reportportal.io/docs/How-to-clean](url)

**Comment by Oleksii-kh89** [comment] 2023-01-05 15:25
@miracle8484 could you check the error which was mentioned in this issue?

**Comment by miracle8484** [comment] 2023-02-08 10:02
Thx you for your question.
1. Errors looks like related to connection wtih rabbitmq - please recheck you configs to it and availability of service.
2. As @Oleksii-kh89 have mentioned before, you can set bigger value of RP_ENVIRONMENT_VARIABLE_CLEAN_STORAGE_CHUNKSIZE - it's amount of things will be delete per one launch of jobs. And with simple calculation you can get how many times you need to launch it to clean your storage completly.

**Comment by irynakozak2** [comment] 2023-03-09 13:43
@samagarw hi!
long time no hear from you, so we'll close the issue for now.
Just in case you still have the issue, please, provide more details as describes in comment above.

**Closed by irynakozak2** 2023-03-09 13:43 UTC
Labels: help wanted, Waiting Info From Requestor, Check: Performance
