### ISSUE TITLE
[v5.2.3] - Flaky Test Widget Creation using Postman API Calls fail to add Name to widget UI elements

### ISSUE THREAD

**Issue by sspieker-cc** [reportportal/reportportal#1140] opened 2020-09-09 03:17 UTC
**Describe the bug**
When using Creating a widget of type "flakyTestCases" utilizing API only, adding shared widget through UI or API results in a UI widget with no name or edit abilities through the UI.

**To Reproduce**
Create Postman API call including the following:
Headers:
- content-type: application/json
- authorization bearer <token>
Body:
{
    "widgetType": "flakyTestCases",
    "contentParameters": {
        "itemsCount": "100",
        "widgetOptions": {
            "includeMethods": false,
            "launchNameFilter": "cucumber-flows"
        }
    },
    "filters": [],
    "name": "Cucumber Flows - ALL - Top 20 Most Flaky Tests",
    "description": "Flaky Tests - Top 20",
    "share": true,
    "filterIds": []
}

**Expected behavior**
All other widgets defined in this way (using API calls) function and display normally.
API Calls to retrieve shared Flaky Tests widgets information confirms that the name, itemCount and launchNameFilter values are as defined when submitted through API call above.

**Screenshots**
<img width="1410" alt="Screen Shot 2020-09-08 at 11 00 32 PM" src="https://user-images.githubusercontent.com/49696592/92550222-0930de80-f229-11ea-83ab-49bfff320542.png">
<img width="603" alt="Screen Shot 2020-09-08 at 11 00 47 PM" src="https://user-images.githubusercontent.com/49696592/92550223-0afaa200-f229-11ea-9ce5-1413e360c7ac.png">

**Desktop (please complete the following information):**
 - OS: OSX 10.14.6
 - Browser: Chrome 84
 - RP Version 5.2.3

**Additional context**
Manually creating the widget using the UI works as expected.  The creation of the flaky tests widget using the API specifically has an issue within the UI representation of the widget created in this way.

**Comment by sspieker-cc** [comment] 2020-09-14 17:23
This behavior is persistent within the UI until there is data that meets the filter criteria.  Once there is data, the title and description information appears as 'normal'.

Running API calls to setup 'standardized' dashboards allows for our organization to be prepared for new test suites being added and tracked.  This behavior just seems to be a bug in how the widget behaves when there is no data to be displayed since it is working off of a launch name criteria.

**Comment by VolhaKarenko** [comment] 2020-10-02 05:37
The issue is reproducible, a ticket in Jira is created.

**Comment by VolhaKarenko** [comment] 2021-03-01 08:12
Fixed in version 5.4

**Closed by VolhaKarenko** 2021-03-01 08:12 UTC
