### ISSUE TITLE
Error when trying to invite any new member to a project or when trying to unassign a member

### ISSUE THREAD

**Issue by MamounH** [reportportal/reportportal#1882] opened 2022-11-15 20:48 UTC
**Describe the bug**

i get this error Whenever I try to add/invite any new member to a RP project;

`An error occurred while connecting to server:
`

Also i cant remove users from this project. the only thing i can do successfully inside the project is updating users roles. 

i can add and remove the same users for other projects, but for this one i cant add or remove users. 

**Expected behavior**

able to invite and remove users to/from a project.
...

**Screenshots**
![invite](https://user-images.githubusercontent.com/43816611/202021175-ff1858ea-b8ad-49e3-9d01-00456c4763b3.jpg)

**Versions:**
 - Version of RP: 
     - API Service: 5.7.1
     - Jobs Service: 5.7.1
     - Authorization Service: 5.7.0
     - Service UI: 5.7.0

**Comment by alena-babrova** [comment] 2022-12-05 13:24
Hello @MamounH,
If I understood you correctly, the issue is reproduced only on one project, is it so? But you can assign/unassign users on other project on instance, right?
Is it possible to get and share with us API logs to see the error and understand the problem.
Because so far we have not been able to reproduce such a problem on our side.

**Comment by alena-babrova** [comment] 2022-12-26 13:30
As we haven't received a reply from you, we'll close the issue for now.
Just in case you still have the issue, please, do not hesitate to get in touch.

**Closed by alena-babrova** 2022-12-26 13:30 UTC
Labels: bug, Waiting Info From Requestor, Check: Test
