### ISSUE TITLE
service is not getting started and failing with exception . 

### ISSUE THREAD

**Issue by samagarw** [reportportal/reportportal#2095] opened 2023-08-18 06:57 UTC
Service is not getting started and we are getting following exception  . Can anyone please help ? 

2023-08-18 06:57:06.187 ERROR 1 --- [ult-task-sched2] c.e.t.r.f.distributed.s3.S3DataStore     : Unable to find file 'Azure DevOps-5.7.1.jar'

java.lang.NullPointerException: null
	at com.epam.ta.reportportal.filesystem.distributed.s3.S3DataStore.load(S3DataStore.java:89)
	at com.epam.ta.reportportal.job.LoadPluginsJob.lambda$execute$1(LoadPluginsJob.java:79)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1541)
	at com.epam.ta.reportportal.job.LoadPluginsJob.execute(LoadPluginsJob.java:78)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.springframework.scheduling.support.ScheduledMethodRunnable.run(ScheduledMethodRunnable.java:84)
	at org.springframework.scheduling.support.DelegatingErrorHandlingRunnable.run(DelegatingErrorHandlingRunnable.java:54)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.runAndReset(FutureTask.java:305)
	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:305)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:829)

2023-08-18 06:57:06.188 ERROR 1 --- [ult-task-sched2] o.s.s.s.TaskUtils$LoggingErrorHandler    : Unexpected error occurred in scheduled task

com.epam.ta.reportportal.exception.ReportPortalException: Unable to load binary data by id 'Unable to find file'
	at com.epam.ta.reportportal.filesystem.distributed.s3.S3DataStore.load(S3DataStore.java:92)
	at com.epam.ta.reportportal.job.LoadPluginsJob.lambda$execute$1(LoadPluginsJob.java:79)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1541)
	at com.epam.ta.reportportal.job.LoadPluginsJob.execute(LoadPluginsJob.java:78)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.springframework.scheduling.support.ScheduledMethodRunnable.run(ScheduledMethodRunnable.java:84)
	at org.springframework.scheduling.support.DelegatingErrorHandlingRunnable.run(DelegatingErrorHandlingRunnable.java:54)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.runAndReset(FutureTask.java:305)
	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:305)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:829)

2023-08-18 06:57:06.294  INFO 1 --- [portal_Worker-1] c.e.t.r.job.CleanExpiredCreationBidsJob  : Cleaning expired user creation bids finished. Deleted 0 bids
2023-08-18 06:57:06.298  INFO 1 --- [           main] c.e.t.r.core.configs.ReportPortalApp     : Started ReportPortalApp in 59.191 seconds (JVM running for 61.108)
2023-08-18 06:57:06.776 ERROR 1 --- [           main] o.s.boot.SpringApplication               : Application run failed

org.jasypt.exceptions.EncryptionOperationNotPossibleException: null
	at org.jasypt.encryption.pbe.StandardPBEByteEncryptor.decrypt(StandardPBEByteEncryptor.java:1169)
	at org.jasypt.encryption.pbe.StandardPBEStringEncryptor.decrypt(StandardPBEStringEncryptor.java:738)
	at org.jasypt.util.text.BasicTextEncryptor.decrypt(BasicTextEncryptor.java:112)
	at com.epam.ta.reportportal.core.integration.migration.JiraEmailSecretMigrationService.lambda$migrate$1(JiraEmailSecretMigrationService.java:55)
	at java.base/java.util.Optional.ifPresent(Optional.java:183)
	at com.epam.ta.reportportal.core.integration.migration.JiraEmailSecretMigrationService.lambda$migrate$2(JiraEmailSecretMigrationService.java:54)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1541)
	at com.epam.ta.reportportal.core.integration.migration.JiraEmailSecretMigrationService.migrate(JiraEmailSecretMigrationService.java:52)
	at com.epam.ta.reportportal.core.integration.migration.JiraEmailSecretMigrationService$$FastClassBySpringCGLIB$$4bc27873.invoke(<generated>)
	at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:218)
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.invokeJoinpoint(CglibAopProxy.java:783)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:163)
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:753)
	at org.springframework.transaction.interceptor.TransactionInterceptor$1.proceedWithInvocation(TransactionInterceptor.java:123)
	at org.springframework.transaction.interceptor.TransactionAspectSupport.invokeWithinTransaction(TransactionAspectSupport.java:388)
	at org.springframework.transaction.interceptor.TransactionInterceptor.invoke(TransactionInterceptor.java:119)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186)
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:753)
	at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:698)
	at com.epam.ta.reportportal.core.integration.migration.JiraEmailSecretMigrationService$$EnhancerBySpringCGLIB$$9d750315.migrate(<generated>)
	at com.epam.ta.reportportal.core.events.handler.IntegrationSecretsMigrationHandler.migrate(IntegrationSecretsMigrationHandler.java:78)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.springframework.context.event.ApplicationListenerMethodAdapter.doInvoke(ApplicationListenerMethodAdapter.java:344)
	at org.springframework.context.event.ApplicationListenerMethodAdapter.processEvent(ApplicationListenerMethodAdapter.java:229)
	at org.springframework.context.event.ApplicationListenerMethodAdapter.onApplicationEvent(ApplicationListenerMethodAdapter.java:166)
	at com.epam.ta.reportportal.core.events.multicaster.DelegatingApplicationEventMulticaster.doInvokeListener(DelegatingApplicationEventMulticaster.java:59)
	at com.epam.ta.reportportal.core.events.multicaster.DelegatingApplicationEventMulticaster.lambda$invokeListener$2(DelegatingApplicationEventMulticaster.java:50)
	at java.base/java.util.Optional.ifPresentOrElse(Optional.java:203)
	at com.epam.ta.reportportal.core.events.multicaster.DelegatingApplicationEventMulticaster.invokeListener(DelegatingApplicationEventMulticaster.java:44)
	at org.springframework.context.event.SimpleApplicationEventMulticaster.multicastEvent(SimpleApplicationEventMulticaster.java:143)
	at org.springframework.context.support.AbstractApplicationContext.publishEvent(AbstractApplicationContext.java:421)
	at org.springframework.context.support.AbstractApplicationContext.publishEvent(AbstractApplicationContext.java:378)
	at org.springframework.boot.context.event.EventPublishingRunListener.running(EventPublishingRunListener.java:111)
	at org.springframework.boot.SpringApplicationRunListeners.lambda$running$6(SpringApplicationRunListeners.java:79)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1541)
	at org.springframework.boot.SpringApplicationRunListeners.doWithListeners(SpringApplicationRunListeners.java:117)
	at org.springframework.boot.SpringApplicationRunListeners.doWithListeners(SpringApplicationRunListeners.java:111)
	at org.springframework.boot.SpringApplicationRunListeners.running(SpringApplicationRunListeners.java:79)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:354)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1365)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1354)
	at com.epam.ta.reportportal.core.configs.ReportPortalApp.main(ReportPortalApp.java:37)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:49)
	at org.springframework.boot.loader.Launcher.launch(Launcher.java:108)
	at org.springframework.boot.loader.Launcher.launch(Launcher.java:58)
	at org.springframework.boot.loader.JarLauncher.main(JarLauncher.java:88)

2023-08-18 06:50:18.793  INFO 1 --- [a.Spring.bean-3] o.s.a.r.l.SimpleMessageListenerContainer : Restarting Consumer@1b820755: tags=[[]], channel=null, acknowledgeMode=AUTO local queue size=0
2023-08-18 06:50:18.797  INFO 1 --- [a.Spring.bean-3] o.s.a.r.l.SimpleMessageListenerContainer : Restarting Consumer@48fb757d: tags=[[]], channel=null, acknowledgeMode=AUTO local queue size=0
2023-08-18 06:50:18.801  INFO 1 --- [a.Spring.bean-3] o.s.a.r.l.SimpleMessageListenerContainer : Restarting Consumer@62780bc2: tags=[[]], channel=null, acknowledgeMode=AUTO local queue size=0
2023-08-18 06:50:18.802  INFO 1 --- [a.Spring.bean-3] o.s.a.r.l.SimpleMessageListenerContainer : Restarting Consumer@564fcf09: tags=[[]], channel=null, acknowledgeMode=AUTO local queue size=0
2023-08-18 06:50:18.804  INFO 1 --- [a.Spring.bean-3] o.s.a.r.l.SimpleMessageListenerContainer : Restarting Consumer@36c78ae3: tags=[[]], channel=null, acknowledgeMode=AUTO local queue size=0
2023-08-18 06:50:23.781  INFO 1 --- [a.Spring.bean-4] o.s.a.r.l.SimpleMessageListenerContainer : Restarting Consumer@696e728d: tags=[[]], channel=null, acknowledgeMode=AUTO local queue size=0
2023-08-18 06:50:23.782  INFO 1 --- [a.Spring.bean-4] o.s.a.r.l.SimpleMessageListenerContainer : Restarting Consumer@127e1345: tags=[[]], channel=null, acknowledgeMode=AUTO local queue size=0
2023-08-18 06:50:23.785  INFO 1 --- [a.Spring.bean-4] o.s.a.r.l.SimpleMessageListenerContainer : Restarting Consumer@4faae50: tags=[[]], channel=null, acknowledgeMode=AUTO local queue size=0
2023-08-18 06:50:23.789  INFO 1 --- [a.Spring.bean-4] o.s.a.r.l.SimpleMessageListenerContainer : Restarting Consumer@698b0cb9: tags=[[]], channel=null, acknowledgeMode=AUTO local queue size=0
2023-08-18 06:50:23.794  INFO 1 --- [a.Spring.bean-4] o.s.a.r.l.SimpleMessageListenerContainer : Restarting Consumer@59f333e4: tags=[[]], channel=null, acknowledgeMode=AUTO local queue size=0
2023-08-18 06:50:23.797  INFO 1 --- [a.Spring.bean-4] o.s.a.r.l.SimpleMessageListenerContainer : Restarting Consumer@5ae18417: tags=[[]], channel=null, acknowledgeMode=AUTO local queue size=0
2023-08-18 06:50:23.800  INFO 1 --- [a.Spring.bean-4] o.s.a.r.l.SimpleMessageListenerContainer : Restarting Consumer@60c5c4c9: tags=[[]], channel=null, acknowledgeMode=AUTO local queue size=0
2023-08-18 06:50:23.805  INFO 1 --- [a.Spring.bean-4] o.s.a.r.l.SimpleMessageListenerContainer : Restarting Consumer@2fec683c: tags=[[]], channel=null, acknowledgeMode=AUTO local queue size=0
2023-08-18 06:50:23.806  INFO 1 --- [a.Spring.bean-4] o.s.a.r.l.SimpleMessageListenerContainer : Restarting Consumer@6c352855: tags=[[]], channel=null, acknowledgeMode=AUTO local queue size=0
2023-08-18 06:50:23.808  INFO 1 --- [a.Spring.bean-4] o.s.a.r.l.SimpleMessageListenerContainer : Restarting Consumer@6a924b: tags=[[]], channel=null, acknowledgeMode=AUTO local queue size=0
2023-08-18 06:50:28.786  INFO 1 --- [a.Spring.bean-5] o.s.a.r.l.SimpleMessageListenerContainer : Restarting Consumer@68adae9f: tags=[[]], channel=null, acknowledgeMode=AUTO local queue size=0
2023-08-18 06:50:28.786  INFO 1 --- [a.Spring.bean-5] o.s.a.r.l.SimpleMessageListenerContainer : Restarting Consumer@204cbb89: tags=[[]], channel=null, acknowledgeMode=AUTO local queue size=0
2023-08-18 06:50:28.789  INFO 1 --- [a.Spring.bean-5] o.s.a.r.l.SimpleMessageListenerContainer : Restarting Consumer@e4de298: tags=[[]], channel=null, acknowledgeMode=AUTO local queue size=0
2023-08-18 06:50:28.794  INFO 1 --- [a.Spring.bean-5] o.s.a.r.l.SimpleMessageListenerContainer : Restarting Consumer@2902aeb: tags=[[]], channel=null, acknowledgeMode=AUTO local queue size=0
2023-08-18 06:50:28.799  INFO 1 --- [a.Spring.bean-5] o.s.a.r.l.SimpleMessageListenerContainer : Restarting Consumer@227cc7bb: tags=[[]], channel=null, acknowledgeMode=AUTO local queue size=0
2023-08-18 06:50:28.802  INFO 1 --- [a.Spring.bean-5] o.s.a.r.l.SimpleMessageListenerContainer : Restarting Consumer@4c6da9c1: tags=[[]], channel=null, acknowledgeMode=AUTO local queue size=0

**Comment by samagarw** [comment] 2023-08-18 09:04
This error i am getting after upgrading it to 5.7.4 version . I am not sure why it is still pull the 5.7.1 version of plugin and from where ?

**Comment by alena-babrova** [comment] 2023-08-21 13:07
Hello @samagarw,
According to the logs the problem is that ReportPortal cannot find .jar file in S3 storage.
Have you changed MinIO to S3 recently?
Maybe it makes sense to delete the Azure DevOps plugin integration from the DB level and reinstall it? You can do it by deleting records for "Azure DevOps" in "integration" and "integration_type" table of the ReportPortal database.

**Comment by alena-babrova** [comment] 2023-10-02 07:42
Hello @samagarw,
As we haven't received a reply from you, we'll close the issue for now.
Just in case you still have the issue, please, do not hesitate to get in touch.

**Closed by alena-babrova** 2023-10-02 07:42 UTC
Labels: bug, Waiting Info From Requestor
