### ISSUE TITLE
Reportportal-nightwatch agent throws incompatible status error

### ISSUE THREAD

**Issue by mchundi** [reportportal/reportportal#2289] opened 2024-06-11 21:07 UTC
**Describe the bug**
Error:
Request failed with status code 400: {"errorCode":4001,"message":"Incorrect Request. [Value is not allowed for field 'status'.] "}

As a workaround, we are updated the /node_modules/@reportportal/client-javascript/lib/rest.js with these lines:
let updatedData = data if(data.status !== undefined) { console.log("Status of test execution is --> " + updatedData.status) if (updatedData.status == 'pass') { updatedData.status = 'Passed' data = updatedData } else if (updatedData.status == 'fail') { updatedData.status = 'Failed' data = updatedData } else { updatedData.status = 'Skipped' data = updatedData } }

Can you please take a look at this error?
Is it possible to upgrade the client to use nightwatch 2.6.20?

**Versions:**
 reportportal version 5.0.2,
nightwatch version 2.6.20

**Comment by Pink-Bumblebee** [comment] 2024-06-12 07:54
Duplicate of https://github.com/reportportal/agent-js-nightwatch/issues/52

**Closed by Pink-Bumblebee** 2024-06-12 07:54 UTC
Labels: bug
