### ISSUE TITLE
Cucumber: data table separators are misaligned in reports (markdown issue?)

### ISSUE THREAD

**Issue by jurteg** [reportportal/reportportal#150] opened 2017-06-21 12:27 UTC
Data tables that come from cucumber-agent are missaligned in reports. Those tables alligned to the left and separators are come with different string positions, so tables look broken and difficult to read.

![rp_bug_1](https://user-images.githubusercontent.com/25842206/27384043-1732a446-5696-11e7-9a44-d9d1caeb2301.png)

**Comment by lexecon** [comment] 2017-07-06 11:54
We support another markdown syntax. Please see this [Guide](https://simplemde.com/markdown-guide).

**Comment by abotalov** [comment] 2017-07-06 12:36
@lexecon Such form of plaintext is standard in Cucumber - https://cucumber.io/docs/reference#data-tables

I do not think that it's a job of test framework integration to convert plaintext into markdown if one desires just to display this information as is.

**Comment by abotalov** [comment] 2017-07-06 12:38
I think the issue here is probably because several spaces are displayed as one HTML.

There is a white-space property in CSS that could possibly overcome this.
https://developer.mozilla.org/en/docs/Web/CSS/white-space

**Comment by jurteg** [comment] 2017-07-06 15:47
Agreed. Cucumber builds these tables in correct way and sends the informations as is. I didn't noticed any missaligned tables in different report plugins for cucumber.

**Comment by DzmitryHumianiuk** [comment] 2017-10-26 16:45
@jurteg can be closed?

**Comment by jurteg** [comment] 2017-10-27 08:57
@DzmitryHumianiuk are you going to fix that?

**Comment by DzmitryHumianiuk** [comment] 2017-10-27 09:30
@jurteg still reproducible?

**Comment by jurteg** [comment] 2017-10-27 09:46
@DzmitryHumianiuk yes.
agent-cucumber-2.6.2

**Comment by DzmitryHumianiuk** [comment] 2017-10-31 11:19
@jurteg you can enable markdown for your logs
just add `!!!MARKDOWN_MODE!!!` before the log string.

and according to this: https://simplemde.com/markdown-guide
it will be represented as table.

@lexecon @pbortnik please also check who remove extra whitespaces in text

**Comment by jurteg** [comment] 2017-11-06 12:53
@DzmitryHumianiuk , I've tried this option, but it doesn't work. Tables still broken.

**Comment by DzmitryHumianiuk** [comment] 2017-11-06 21:27
@jurteg looks like WS trims multi whitespaces.

**Comment by avarabyeu** [comment] 2017-11-10 12:58
@lexecon @DzmitryHumianiuk could you guys please provide me with example of request that being trimmed incorrectly

**Comment by DzmitryHumianiuk** [comment] 2017-11-10 15:09
Sent via DM


~Dzmitry H

On 10 Nov 2017, at 15:58, Andrei Varabyeu <notifications@github.com<mailto:notifications@github.com>> wrote:


@lexecon<https://github.com/lexecon> @DzmitryHumianiuk<https://github.com/dzmitryhumianiuk> could you guys please provide me with example of request that being trimmed incorrectly

**Comment by avarabyeu** [comment] 2017-11-10 16:48
@jurteg is it correct representation?
http://prntscr.com/h8rkdg

**Comment by jurteg** [comment] 2017-11-11 13:23
@avarabyeu no, it should look like this:
http://prntscr.com/h92n48

**Comment by avarabyeu** [comment] 2018-03-20 14:27
@evjlobanova plz add to 4.2

**Comment by e-olga** [comment] 2018-08-24 08:16
Hi @jurteg 
The issue is fixed.
Could you please check on your side?

Regards,
Olga

**Comment by abotalov** [comment] 2019-10-02 14:33
@e-olga Spaces are not preserved when I look at the table if they are present in raw HTML.
![Screenshot from 2019-10-02 17-26-28](https://user-images.githubusercontent.com/1497867/66052916-0f5b0d00-e53a-11e9-8ebf-31ce0a93cb67.png)
![Screenshot from 2019-10-02 17-26-35](https://user-images.githubusercontent.com/1497867/66052918-0ff3a380-e53a-11e9-9578-d646163f4a47.png)

It looks as expected if I add manually a CSS property `whitespace: pre` or `whitespace: pre-wrap` in the browser:
![Screenshot from 2019-10-02 17-32-42](https://user-images.githubusercontent.com/1497867/66053253-aa53e700-e53a-11e9-9407-02ef8ec411e3.png)
is added:

**Comment by AmsterGet** [comment] 2019-10-02 18:13
Fixed in [this](https://github.com/reportportal/service-ui/pull/2085) PR in the scope of RP version `5.0 Final`.

**Comment by DzmitryHumianiuk** [comment] 2019-11-06 21:10
2.5 year old bug )

**Closed** 2019-11-06 21:10 UTC
Labels: bug, resolution:fixed, v5beta
