### ISSUE TITLE
[v5.5] Unable to keep launches 'Forever' without keeping logs/attachments

### ISSUE THREAD

**Issue by daroshchanka** [reportportal/reportportal#1544] opened 2021-10-07 08:48 UTC
**Describe the bug**
It's not possible to save project settings with Keep launches 'Forever' and 'non-Forever' values for Keep logs, Keep attachments.

**To Reproduce**
Navigate to Project Settings -> General Tab, set the values as on screenshot, submit form.

**Expected behavior**
I'm able to keep logs 90 days, but launches Forever.

**Screenshots**
![image](https://user-images.githubusercontent.com/28945630/136349638-7eddc25a-de85-4f2d-b8f5-91de0326a655.png)

**Additional context**
This issue may lead to the old launches loss, e.g. if someone will set Keep launches '90 days' to workaround the form validation and to update some settings.

**Comment by VolhaKarenko** [comment] 2021-11-16 04:54
Hi @daroshchanka, the issue is fixed in version 5.6 that will be released soon

**Closed by VolhaKarenko** 2021-11-16 04:54 UTC
Labels: bug, Check: Test
