### ISSUE TITLE
[v5] Most Failed Tests and Most Flaky Tests widgets: wrong time is shown

### ISSUE THREAD

**Issue by vadzimBichan** [reportportal/reportportal#1181] opened 2020-10-19 11:35 UTC
**Describe the bug**
Please see the attached screenshots for two widgets. Last test execution time is shown instead of Last time of switch / Last time of failure

**To Reproduce**
Run some suite with red tests several times and analyze two widgets: Most Failed Tests and Most Flaky Tests

**Expected behavior**
Last time of switch (for Most Flaky Tests widget) and last time of failure (for Most Failed Tests widget) is expected

**Screenshots**
Two screenshot are added/ Suite is being executed once a day
![MostFlaky](https://user-images.githubusercontent.com/16800189/96445269-4ae57980-1218-11eb-8a76-5c794a4da594.png)
![MostFailed](https://user-images.githubusercontent.com/16800189/96445270-4b7e1000-1218-11eb-86c1-faf5bd510277.png)

**Version:**
https://rp.epam.com/info
{
  "build":{
      "version":"5.0.10",
      "branch":"ee97841",
      "build_date":"2020-07-31T11:59:44+0300",
      "name":"Index Service",
      "repo":"reportportal/service-index"
  }
}

**Additional context**
No

**Comment by evjlobanova** [comment] 2020-10-19 13:59
It is a known bug, will be fixed in version 5.4

**Comment by VolhaKarenko** [comment] 2022-01-20 14:43
The issue is fixed in version 5.7

**Closed by VolhaKarenko** 2022-01-20 14:43 UTC
Labels: bug
