### ISSUE TITLE
Failed Launches are not in a Defect Type

### ISSUE THREAD

**Issue by sysy69** [reportportal/reportportal#2392] opened 2024-10-30 13:06 UTC
Failed Launches are not in a Defect Type
...

Failed Launches should be automaticly in TO INVESTIGATE
...

**Screenshots**
<img width="632" alt="image" src="https://github.com/user-attachments/assets/5e98e0de-87e6-45ce-898a-e27c34949a06">

**Versions:**
 - Launches with codeceptjs Plugin, Running in a Kubernetes Cluster, Plain installation without modifies.
 - Version of RP Build: 5.12.0

**Comment by silverio82** [comment] 2024-10-31 00:55
@sysy69 it is a duplicate of my issue https://github.com/reportportal/reportportal/issues/2391

**Comment by alena-babrova** [comment] 2024-11-11 08:46
Dear @sysy69,

There is already a similar thread https://github.com/reportportal/reportportal/issues/2391. Let's discuss it there.
I am closing the ticket as duplicate.

**Closed by alena-babrova** 2024-11-11 08:46 UTC
Labels: bug
