### ISSUE TITLE
502 Bad Gateway when attempting to sign in

### ISSUE THREAD

**Issue by danreale** [reportportal/reportportal#1644] opened 2022-01-27 03:47 UTC
**Describe the bug**
I'm on macos and using the docker compose file to create a local environment. The docker build is successful. When I try to log in to report portal with either user, I am getting `An error occurred while connecting to server:` error. Upon further investigation, I am seeing a 502 Bad Gateway error on this endpoint `http://localhost:8080/uat/sso/oauth/token`.  I've tried a few different versions of the docker compose file to rule out breaking changes. 

**Expected behavior**
I am able to login 

**Screenshots**
![image](https://user-images.githubusercontent.com/37839370/151288381-e813592e-47a3-47b2-82a2-750a14ecadb9.png)

**Versions:**
 - MacOS Catalina, 10.15.6, Chrome
 - using latest version of dockerfile on master branch

**Comment by sreesankargm** [comment] 2022-01-27 04:53
I don't know if this will help. But I used to get the same. I suspect some service takes time to load/boot up. If you wait for some time and then try login - is it working? That seems to do the trick for me.

**Comment by danreale** [comment] 2022-01-27 20:25
@sreesankargm I waited a bit. Seems to be stuck on the `db_scripts` container. I am seeing:
```
error: pq: no pg_hba.conf entry for host "172.xx.x.xx", user "rpuser", database "reportportal", SSL off
wait-for-it.sh: waiting 15 seconds for postgres:5432
```

I wonder if this is related to the problem I am seeing with the login.

**Comment by VinGt22** [comment] 2022-02-23 21:44
This really appears to be a bug and seems multiple organizations and folks are facing this issue. At times the services do not recover for almost half a day leading to loss of time. Is there any update to get a fix for this?

**Comment by gregorygold** [comment] 2022-04-04 21:15
Do we have this running correctly with the older version of the application? Should we use it instead?

**Comment by steerpike100** [comment] 2022-04-28 15:52
This is an issue for me also, exactly as the OP described.  Any workaround?

**Comment by gregorygold** [comment] 2022-04-28 18:29
So the way I have solved it was to follow the steps mentioned updating S3 access

**Comment by VinGt22** [comment] 2022-04-28 18:38
@gregorygold Can you please provide some more insight into how you solved this.. can you share the steps or any link which you referred which you have mentioned--"updating S3 access"?

**Comment by gregorygold** [comment] 2022-04-28 18:42
Please follow this thread https://github.com/chhatbarjignesh/reportportal-aws-cfn/issues/3

I had a Cludformation deployment in AWS.

**Comment by steerpike100** [comment] 2022-04-29 07:47
I've tried the suggested solutions on this page with no luck.  This is a really bad first start from a company looking to potentially opt for a commercial licence for this tool.

**Comment by irynakozak2** [comment] 2022-11-11 15:14
Hi @danreale !
If the issue is still valid for you, my suggestion is to wait about a minute after successful deployment and giving the services up and running. If the issue would occur, please check if are there no errors in the service-API logs.

**Comment by swtestacademy** [comment] 2022-11-29 11:04
This problem still exists in 5.7.2 version on M1 machine, and I could not solve it. 
Current version:Service UI: 5.7.2;

**Comment by irynakozak2** [comment] 2022-11-30 13:54
@swtestacademy thank you for your response! Unfortunately, we still have a common issue with deploying ReportPortal on Apple Silicon Chips. It's currently in our backlog and we keep you updated on resolving it. Thank you!

**Comment by DzmitryHumianiuk** [comment] 2023-01-18 22:12
not sure if this is really related to ARM (m1) specifics.
especially what is related to the topic-starter @danreale

**Comment by akashchaudhary** [comment] 2023-02-14 04:35
@DzmitryHumianiuk @steerpike100 @swtestacademy @alizaidi96 @sreesankargm 
I think there is an issue with the S3 bucket when we deploy ReportPortal in AWS Cloudformation. This bucket is used to store prj-ketstore/secretIntegrationSalt by minio etc. I would suggest to use the deployment technique mentioned here https://medium.com/@chhatbarjignesh/deploy-reportportal-in-aws-with-aws-cloudformation-cd6553e27f74 . One can skip all the extra details and just use the https://github.com/chhatbarjignesh/reportportal-aws-cfn to upload into cloudformation stack . 
Do create a S3 bucket beforehand and pass its name in the param S3BucketName , Pass reportportal version as 5.2.2 and postgress version as 12.7(Other versions might not be available in AWS to install or Might not support db.t2.micro. To get the list of version try to install postgress as a ddb in AWS and you can the extensive list.) . Now just complete the stack creation with minimal or no extra details provided. Wait for sometime once the creation is complete . Then try to login.

**Comment by ramitd1995** [comment] 2023-04-10 18:00
> @swtestacademy thank you for your response! Unfortunately, we still have a common issue with deploying ReportPortal on Apple Silicon Chips. It's currently in our backlog and we keep you updated on resolving it. Thank you!

@irynakozak2 is there any update on this? We are still facing error 502 while logging into RP on macOS with M1 chip.
API : http://localhost:8080/uat/sso/oauth/token is failing.

**Comment by DzmitryHumianiuk** [comment] 2023-10-05 20:41
All ReportPortal images now support multiple platforms.: linux/amd64.

**Closed by DzmitryHumianiuk** 2023-10-05 20:41 UTC
Labels: bug, Waiting Info From Requestor
