### ISSUE TITLE
Import Newman JUNIT Report with Report Portal API

### ISSUE THREAD

**Issue by macifTest** [reportportal/reportportal#2245] opened 2024-03-06 13:11 UTC
With newman I generate a JUNIT report (XML file)
I try to import this results in report portal thought the API '/launch/import/'

**Expected behavior**
I have the message : 
Error while importing the file. 'Test item status is ambiguous. There is no status provided from request and there are no descendants to check statistics for test item id '393906''
I don't anderstand because, I use this report in jenkins and gitlab, and I have no problem.
I try another report and it's import is OK

**Screenshots**
Image in Attach files
![Capture](https://github.com/reportportal/reportportal/assets/32673960/88ecdd73-e3e3-47f8-8b73-f822951774f9)

**Versions:**
- newman 
 - Windows, Linux
 - Version of RP : 23.2
 - Current version:API Service: 5.10.1;Index Service: 5.10.1;Jobs Service: 5.10.0;Authorization Service: 5.10.0;Service UI: 5.10.0;

**Comment by Kozovskaya** [comment] 2024-03-07 12:05
Hello @macifTest 
Could you please send the example of the file you are trying to import?

**Comment by Kozovskaya** [comment] 2024-03-07 13:27
@macifTest Thanks,
I will ask the team to have look on it!
@MaryiaRymarchyk could you please check if it's reproduced on your side?

**Comment by MaryiaRymarchyk** [comment] 2024-03-11 09:34
@macifTest what is the logic behind this empty suites?  is it configurable on your side? maybe you can exclude empty suites from the report or convert such elements to before methods?

**Comment by macifTest** [comment] 2024-03-11 10:04
Hello @MaryiaRymarchyk 
I will ask the team that manages this POSTMAN project.
Thanks

**Comment by macifTest** [comment] 2024-03-11 10:09
According to the project team, if we talk about service calls without tests, it is because these are requests executed before certain service calls

**Comment by MaryiaRymarchyk** [comment] 2024-03-11 11:13
@macifTest thank you for the response, it seems that no remain actions for RP team fro now. Can we close the ticket? 
You may reopen it or create a new one if it become relevant.

**Comment by macifTest** [comment] 2024-03-11 13:34
@MaryiaRymarchyk, 
I don't understand. For me this is a "normal" case for POSTMAN tests, because there are technical "suites" which are used to carry out certain actions.
So this means that nothing will be done on report portal to correct this problem?
I find this a shame, because I don't see how to manage this problem other than modifying the xml file before each import.

**Comment by MaryiaRymarchyk** [comment] 2024-03-11 13:45
@macifTest sorry if i didn't make it clear.   RP app require for suite or status or child items, if you have none of it - error occurs - this is expected behavior.
Using postman you can easily send status for the suit and no any error will occur. 
Also you can send this technical "suites" in other format - BEFORE_METHOD, BEFORE_SUITE.
Both solutions are on your side.

**Comment by ChetanKolhe** [comment] 2024-07-08 11:32
@MaryiaRymarchyk @Kozovskaya 
I am facing issue , I need to upload different junit report result to report portal .  

API : /api/v1/greenplum/launch/import

most of the launches not get imported because of zero test in task suite.  

Framework: 
pytest , gotestsum and many more test framework result the same format . 

How To Generate empty test suite with pytest . 
 
 pip install pytest
 pytest --junitxml=report.xml

**Comment by Kozovskaya** [comment] 2024-07-08 12:06
Hello @ChetanKolhe 
Thanks for reaching us and sorry for the inconvinience for now. A ticket in our backlog is creted for fixing the issue. We will take it into work based on the priorities and team capasity. 
Thanks in advance for understanding

**Comment by Kozovskaya** [comment] 2024-08-02 12:07
Hello @macifTest @ChetanKolhe 
The issue is fixed and will be released in 24.2 - our next release that will take place later this year!

**Comment by ChetanKolhe** [comment] 2024-08-12 05:12
Thanks, @Kozovskaya!

It was really helpful to integrate different automation frameworks via import options without affecting or modifying  their code changes. Just uploading junit report .

**Comment by Kozovskaya** [comment] 2024-10-01 12:03
Hello @macifTest @ChetanKolhe 
The ReportPortal version 24.2 is already released! The fix is there!
I'm closing the issue.
Thank you for using ReportPortal!

**Closed by Kozovskaya** 2024-10-01 12:03 UTC
Labels: bug, Waiting Info From Requestor
