### ISSUE TITLE
I need to find Test Case/Suite by name/tag

### ISSUE THREAD

**Issue by JustasM11** [reportportal/reportportal#45] opened 2016-12-19 14:04 UTC
How can I find test case/suite by name/tag?
Currently even filter by tag works for top view only so I don't have way to find specific test except for via traversing test launch/test suites hierarchy down to test

**Comment by DzmitryHumianiuk** [comment] 2016-12-23 16:35
**for test cases**
1. click number in `TOTAL` column
2. use filter by `Test Item Name` or `tags`

but you should have populated tags for you test cases in this case.
you can try it via UI edit.
![image](https://cloud.githubusercontent.com/assets/11332788/21458336/c0fe6164-c946-11e6-9ab5-4e9176f91483.png)

**for test suite**
1. click launch name to drilldown
2. use filter by `Test Item Name` or `tags`

please also refer to #25, if it's not required view, which you need

**Comment by JustasM11** [comment] 2016-12-26 10:41
I'm sorry, but it works just for particular launch, right?
But I need way to find item by tag in all launches in my case one launch doesn't cover all TCs.

**Comment by DzmitryHumianiuk** [comment] 2017-08-16 08:52
@JustasM11 
take all needed launches
you can iterate each launch
find item in this launch.

that will work?

**Comment by DzmitryHumianiuk** [comment] 2017-10-26 15:36
#158 with full text search can be a solution for that.

advanced search will be considered as a part of it.

**Comment by evjlobanova** [comment] 2020-03-18 13:08
In version 5.0 we have added a clickable area for widgets which is based on filter.
For example Overall Statistics widget.
![image](https://user-images.githubusercontent.com/30413511/76962989-4d55bd00-6931-11ea-9f61-519b2f8179e0.png)

It shows summ information about filter.
When a user clicks on the widget.
Then system redirects user to the *list view for filter*
![image](https://user-images.githubusercontent.com/30413511/76963068-7d04c500-6931-11ea-9e21-46a0cbd9b282.png)
This view combines test cases from different launches.

So that partialy you problem can be solved, and you can find test cases between several launhces.

Such clickable area is also available for:
- Pattern widget
- Cumulative trend chart widget
- Overal statistics widget

In version 5.1 it will be available for all widgets which have statistics that based on several launhces.

**Comment by evjlobanova** [comment] 2020-03-18 15:21
Close as a duplicate of https://github.com/reportportal/reportportal/issues/45

**Closed by evjlobanova** 2020-03-18 15:21 UTC
Labels: Feature: AllureView/TreeView, component:server, component:ui, feature request
