### ISSUE TITLE
Actionable Pattern Analysis: defect will be logged automatically in Jira from report portal 

### ISSUE THREAD

**Issue by orvilia** [reportportal/reportportal#569] opened 2019-02-08 11:48 UTC
Hi,

We post the issue in Jira manually from reportportal. Is there way it post the defect automatically in Jira.

**Comment by evjlobanova** [comment] 2019-02-11 09:59
@orvilia hello! 
Now you can post issue to Jira via UI or API.
Also Auto-analysis can set defect type and a link the Jira  for the item.

In our plans we have an idea of pattern analysis. When user create strict pattern. F.e. it there is a pattern like this in stack trace, the system should open new bug in Jira.

But could you please provide more details? What is your desired behaiviour of the rp?

**Comment by DzmitryHumianiuk** [comment] 2019-04-10 17:28
@orvilia will be introduced with **Patterns**

**Comment by matt-richardson** [comment] 2023-02-26 22:55
This feature sounds pretty cool. 
Is this still on the radar?

(the linked issue suggested it would be targeted for 5.3)

**Comment by DzmitryHumianiuk** [comment] 2023-02-27 19:26
@matt-richardson it's a good one, but with limited capacity of the dev team and hundreds of other sweet features we are still keeping in with low priority.

If you company is interested in paid implementation, then we can take it with the highest priority.
let me know.

**Comment by Kozovskaya** [comment] 2024-02-28 15:49
a duplicate of https://github.com/reportportal/reportportal/issues/1746

**Closed by Kozovskaya** 2024-02-28 15:49 UTC
Labels: feature request, Feature: Analysis, Feature: Pattern Analysis
