### ISSUE TITLE
Be enable to change permission map

### ISSUE THREAD

**Issue by ohank** [reportportal/reportportal#1185] opened 2020-10-21 09:54 UTC
Superadmin or project manager can make a custom change on permission.
We like to have so that change status can't be done one test result. If this can be done another way we are open to it.

![image](https://user-images.githubusercontent.com/44366788/96704086-efd89180-1393-11eb-8fbb-42b435117ae8.png)

We want this not be enable to do:

![image](https://user-images.githubusercontent.com/44366788/96704227-22828a00-1394-11eb-877f-4636e20199e6.png)

**Comment by evjlobanova** [comment] 2020-10-22 08:02
Hello @ohank , thank you for the request!
Yes, it is a valid request and we are planning to introduce Custom roles. You can track progress on in ticket #603 .We will add a permissions table, where PM or Admin will be able to customize the roles for every team member. 
We are planning to introduce this feature in version 6.


I closed as a duplicate of #603

But we have also a paid support. So if this feature is crucial for your team, we can add it in a scope of contract with the first priority and it will be implemented earlier than version 6.

As a work around for now:

When a user changes a status for test, system automatically add an attribute "manually: passed/failed/skipped"
If user returns to the initial status, the system removes this attribute.

So that you can create a Component Health Check widget based on attribute key "manually"
So that you will be able to track how many items with changed status you have in your build for instance.
![image](https://user-images.githubusercontent.com/30413511/96842257-aa52ad80-1401-11eb-9fda-6d696a4b4c47.png)


And also I want to provide a use case how usually change status is using on other projects:
1. A test failed
2. QA checks this failure 
![image](https://user-images.githubusercontent.com/30413511/96842536-03224600-1402-11eb-88ac-fd7648db3b25.png)

3. Try to reproduce this issue manually
4. If test doesn't reproduce, QA changes status.
5.  Test lead check number of manually changed items on the widget

**Closed by evjlobanova** 2020-10-22 08:02 UTC
Labels: Feature: Custom Roles, feature request
