### ISSUE TITLE
Report portal is not functioning correctly. Response is not json 500 - not all data appears on the portal

### ISSUE THREAD

**Issue by KatiDem** [reportportal/reportportal#1531] opened 2021-09-20 13:27 UTC
**Describe the bug**
When trying to send logs to the report portal, the following errors pop up in the log:
```
188284 [rp-io-86] ERROR com.epam.reportportal.service.Launch - [114] ReportPortal execution error
com.epam.reportportal.exception.InternalReportPortalClientException: Report portal is not functioning correctly. Response is not json. Uri: [https://report-portal.xxx.com/api/v1/x/log/]; statusCode: [500]; statusMessage: [Internal Server Error];
	at com.epam.reportportal.service.ReportPortalErrorHandler.handleError(ReportPortalErrorHandler.java:88)
	at com.epam.reportportal.service.ReportPortalErrorHandler.handle(ReportPortalErrorHandler.java:61)
	at com.epam.reportportal.restendpoint.http.HttpClientRestEndpoint$1.subscribe(HttpClientRestEndpoint.java:526)
	at io.reactivex.internal.operators.maybe.MaybeCreate.subscribeActual(MaybeCreate.java:45)
	at io.reactivex.Maybe.subscribe(Maybe.java:4290)
	at io.reactivex.internal.operators.maybe.MaybeSubscribeOn$SubscribeTask.run(MaybeSubscribeOn.java:54)
	at io.reactivex.internal.schedulers.ScheduledDirectTask.call(ScheduledDirectTask.java:38)
	at io.reactivex.internal.schedulers.ScheduledDirectTask.call(ScheduledDirectTask.java:26)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:829)
188284 [rp-io-86] ERROR com.epam.reportportal.utils.SubscriptionUtils - Logging context completed with error 
com.epam.reportportal.exception.InternalReportPortalClientException: Report portal is not functioning correctly. Response is not json. Uri: [https://report-portal.xxx.com/api/v1/x/log/]; statusCode: [500]; statusMessage: [Internal Server Error];
	at com.epam.reportportal.service.ReportPortalErrorHandler.handleError(ReportPortalErrorHandler.java:88)
	at com.epam.reportportal.service.ReportPortalErrorHandler.handle(ReportPortalErrorHandler.java:61)
	at com.epam.reportportal.restendpoint.http.HttpClientRestEndpoint$1.subscribe(HttpClientRestEndpoint.java:526)
	at io.reactivex.internal.operators.maybe.MaybeCreate.subscribeActual(MaybeCreate.java:45)
	at io.reactivex.Maybe.subscribe(Maybe.java:4290)
	at io.reactivex.internal.operators.maybe.MaybeSubscribeOn$SubscribeTask.run(MaybeSubscribeOn.java:54)
	at io.reactivex.internal.schedulers.ScheduledDirectTask.call(ScheduledDirectTask.java:38)
	at io.reactivex.internal.schedulers.ScheduledDirectTask.call(ScheduledDirectTask.java:26)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:829)
```
Log partially gets to the report portal, but not completely. Launches and items are created, statuses are put down, the whole structure is in the portal, only logs do not reach report-portal.
There was already an assumption from the ReportPortal developers themselves that this was due to the request volume, which exceeds 50 MB, but we tried to limit this volume to various properties of the Report Portal itself, we did not get any results:

```
-Drp.batch.size.logs=2 -Drp.rx.buffer.size=45
```
Also strange logs was found at the report-portal itself:
```
2021-09-15 14:41:21,904 - analyzerApp.namespaceFinderService - INFO - Started updating chosen namespaces
2021-09-15 14:41:21,905 - analyzerApp.esclient - INFO - Indexing logs for 1 launches
2021-09-15 14:41:21,911 - analyzerApp.esclient - INFO - ES Url http://elasticsearch:9200
2021-09-15 14:41:21,925 - analyzerApp.minioClient - INFO - Minio intialized minio:9000
2021-09-15 14:41:21,959 - analyzerApp.minioClient - INFO - Minio intialized minio:9000
2021-09-15 14:41:21,987 - analyzerApp.minioClient - INFO - Minio intialized minio:9000
2021-09-15 14:41:21,995 - analyzerApp.namespaceFinderService - INFO - Finished updating chosen namespaces 0.09 s
2021-09-15 14:41:21,995 - analyzerApp.amqpHandler - ERROR - Failed to publish result
2021-09-15 14:41:21,995 - analyzerApp.amqpHandler - ERROR - A non-string value was supplied for self.routing_key
2021-09-15 14:41:22,005 - analyzerApp.amqp - INFO - Try connect to amqp://rabbitmq:5672/analyzer?heartbeat=600
2021-09-15 14:41:22,012 - analyzerApp.esclient - INFO - Finished indexing logs for 1 launches. It took 0.10 sec.
[pid: 9|app: 0|req: 39053/66296] 127.0.0.1 () {28 vars in 293 bytes} [Wed Sep 15 14:42:08 2021] GET / => generated 21 bytes in 5 msecs (HTTP/1.1 200) 3 headers in 103 bytes (1 switches on core 1)
[pid: 9|app: 0|req: 39054/66297] 127.0.0.1 () {28 vars in 294 bytes} [Wed Sep 15 14:43:08 2021] GET / => generated 21 bytes in 5 msecs (HTTP/1.1 200) 3 headers in 103 bytes (1 switches on core 7)
[pid: 9|app: 0|req: 39055/66298] 127.0.0.1 () {28 vars in 294 bytes} [Wed Sep 15 14:44:08 2021] GET / => generated 21 bytes in 5 msecs (HTTP/1.1 200) 3 headers in 103 bytes (1 switches on core 6)
[pid: 8|app: 0|req: 17143/66299] 127.0.0.1 () {28 vars in 294 bytes} [Wed Sep 15 14:45:08 2021] GET / => generated 21 bytes in 8 msecs (HTTP/1.1 200) 3 headers in 103 bytes (1 switches on core 6)
2021-09-15 14:46:01,422 - analyzerApp.esclient - INFO - Delete logs [321084942, 321033735, 321033748, 321055653, 321055654, 321051793, 321046541, 321046543, 321046544, 321051792, 321051675, 321049971, 321049973, 321049974, 321040419, 321049426, 321051677, 321051678, 321053447, 321054339, 321054341, 321054342, 321057335, 321057337, 321057338, 321055800, 321055801, 321055803, 321053802, 321053454, 321053460, 321057631, 321057634, 321057639, 321059962, 321059964, 321059965, 321059371, 321059372, 321059374, 321062093, 321065371, 321065363, 321062301, 321062303, 321062304, 321067095, 321063607, 321067358, 321065912, 321066250, 321065216, 321067069, 321180799, 321068950, 321175794, 321175723, 321204122, 321204123, 321204124, 321070218, 321152442, 321180800, 321180801, 321180802, 321180803, 321180805, 321180806, 321184862, 321186249, 321187017, 321196279, 321199998, 321198610, 321198607, 321198608, 321199999, 321200001, 321200005, 319145526, 321205109, 319145527, 319252956, 319245332, 319245333, 319245335, 319142672, 319142673, 319252957, 319252959, 319255320, 319255321, 319255323, 319261144, 319259033, 319194071, 319263342, 319172646, 319172647, 319172648, 319172649, 319172650, 319172652, 319172653, 319194072, 319194073, 319223529, 319225794, 319219271, 319289933, 319228214, 319323391, 319233139, 319290591, 319291277, 319323392, 319331122, 319322856, 319325462, 319283913, 319337016, 319170048, 319170049, 319170050, 319170051, 319170047, 319170053, 319170054, 319248164, 319248167, 319248169, 319329642, 319329186, 319287109, 319330097, 319285351, 319297987, 319291813, 319292279, 319292564, 319292906, 319241277, 319327429, 319327431] for the project 79
```
And then rabbitmq logs:
```
2021-09-15 14:49:29.286 [info] <0.18491.53> accepting AMQP connection <0.18491.53> (172.19.0.2:53980 -> 172.19.0.5:5672)
2021-09-15 14:49:29.290 [info] <0.18491.53> connection <0.18491.53> (172.19.0.2:53980 -> 172.19.0.5:5672): user 'rabbitmq' authenticated and granted access to vhost 'analyzer'
2021-09-15 14:49:31.153 [warning] <0.18462.53> closing AMQP connection <0.18462.53> (172.19.0.2:53922 -> 172.19.0.5:5672, vhost: 'analyzer', user: 'rabbitmq'):
client unexpectedly closed TCP connection
2021-09-15 14:49:31.247 [info] <0.18507.53> accepting AMQP connection <0.18507.53> (172.19.0.2:54008 -> 172.19.0.5:5672)
2021-09-15 14:49:31.251 [info] <0.18507.53> connection <0.18507.53> (172.19.0.2:54008 -> 172.19.0.5:5672): user 'rabbitmq' authenticated and granted access to vhost 'analyzer'
2021-09-15 14:57:46.525 [warning] <0.18507.53> closing AMQP connection <0.18507.53> (172.19.0.2:54008 -> 172.19.0.5:5672, vhost: 'analyzer', user: 'rabbitmq'):
client unexpectedly closed TCP connection
```
Parameters set in docker-compose for api service:
```
JAVA_OPTS=-Xmx2g -XX:+HeapDumpOnOutOfMemoryError -XX:HeapDumpPath=/tmp  -Dcom.sun.management.jmxremote.rmi.port=12349 -Dcom.sun.management.jmxremote -Dcom.sun.management.jmxremote.local.only=false  -Dcom.sun.management.jmxremote.port=9010 -Dcom.sun.management.jmxremote.authenticate=false -Dcom.sun.management.jmxremote.ssl=false -Djava.rmi.server.hostname=0.0.0.0
```

**Expected behavior**
It is expected to see all logs on the portal. 

**Screenshots**
The empty launch.
![image_2021_09_20T10_46_39_963Z](https://user-images.githubusercontent.com/56392180/134009298-a33c09b8-f62f-473e-8d96-9ae677c99f9f.png)

**Versions:**
 - Version of RP -  5.3.5

**Comment by evjlobanova** [comment] 2021-11-16 00:18
@HardNorth Vadzim could you please check this issue?

**Comment by HardNorth** [comment] 2021-12-13 12:35
@evjlobanova There is nothing to check in this issue from my side: server throws 500 error. It's always a backend error.

**Comment by samagarw** [comment] 2021-12-21 07:28
Getting similar error : 

2021-12-21T12:53:24.550+0530 [DEBUG] [TestEventLogger]     [rp-io-46] ERROR com.epam.reportportal.utils.SubscriptionUtils - Logging context completed with error 
2021-12-21T12:53:24.550+0530 [DEBUG] [TestEventLogger]     retrofit2.adapter.rxjava2.HttpException: HTTP 500 Internal Server Error


Logs are not reported for failed test while all logs are present for passed tests . Can anyone please help here . 

@HardNorth  @evjlobanova  .

**Comment by evjlobanova** [comment] 2021-12-22 13:59
Could you please send us API service logs? 
You have sent analyzer logs

**Comment by alena-babrova** [comment] 2022-12-26 20:35
Hello @KatiDem @gesmogast @samagarw 
Could you please tell me if the issue is still relevant?

**Comment by alena-babrova** [comment] 2023-01-18 13:30
As we haven't received a reply from you, we'll close the issue for now.
Just in case you still have the issue, please, do not hesitate to get in touch.

**Closed by alena-babrova** 2023-01-18 13:30 UTC
Labels: bug, Waiting Info From Requestor

**Comment by nikhilrajgarhia** [comment] 2025-03-13 18:39
ERROR com.epam.reportportal.service.Launch - [41] ReportPortal execution error
retrofit2.adapter.rxjava2.HttpException: HTTP 403 Forbidden
	at retrofit2.adapter.rxjava2.BodyObservable$BodyObserver.onNext(BodyObservable.java:57)
	at retrofit2.adapter.rxjava2.BodyObservable$BodyObserver.onNext(BodyObservable.java:38)
	at retrofit2.adapter.rxjava2.CallExecuteObservable.subscribeActual(CallExecuteObservable.java:48)
	at io.reactivex.Observable.subscribe(Observable.java:12267)
	at retrofit2.adapter.rxjava2.BodyObservable.subscribeActual(BodyObservable.java:35)
	at io.reactivex.Observable.subscribe(Observable.java:12267)
	at io.reactivex.internal.operators.observable.ObservableSubscribeOn$SubscribeTask.run(ObservableSubscribeOn.java:96)
	at io.reactivex.internal.schedulers.ScheduledDirectTask.call(ScheduledDirectTask.java:38)
	at io.reactivex.internal.schedulers.ScheduledDirectTask.call(ScheduledDirectTask.java:26)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
	at java.base/java.lang.Thread.run(Thread.java:1575)
2025-03-14 00:02:19,617 [rp-io-2] ERROR com.epam.reportportal.service.Launch - [41] ReportPortal execution error
retrofit2.adapter.rxjava2.HttpException: HTTP 403 Forbidden
	at retrofit2.adapter.rxjava2.BodyObservable$BodyObserver.onNext(BodyObservable.java:57)
	at retrofit2.adapter.rxjava2.BodyObservable$BodyObserver.onNext(BodyObservable.java:38)
	at retrofit2.adapter.rxjava2.CallExecuteObservable.subscribeActual(CallExecuteObservable.java:48)
	at io.reactivex.Observable.subscribe(Observable.java:12267)
	at retrofit2.adapter.rxjava2.BodyObservable.subscribeActual(BodyObservable.java:35)
	at io.reactivex.Observable.subscribe(Observable.java:12267)
	at io.reactivex.internal.operators.observable.ObservableSubscribeOn$SubscribeTask.run(ObservableSubscribeOn.java:96)
	at io.reactivex.internal.schedulers.ScheduledDirectTask.call(ScheduledDirectTask.java:38)
	at io.reactivex.internal.schedulers.ScheduledDirectTask.call(ScheduledDirectTask.java:26)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
	at java.base/java.lang.Thread.run(Thread.java:1575)

I git similar kind of error. Posted it here also: https://stackoverflow.com/questions/79495866/report-portal-is-not-publishing-the-reports-when-using-with-testng-project/79505896#79505896
