### ISSUE TITLE
Integrated link shortener

### ISSUE THREAD

**Issue by ailjushkin** [reportportal/reportportal#291] opened 2017-12-08 13:38 UTC
**Problem:**

Bad looking links while posting them manually anywhere.

**Example:**

http://xxxxxxx:8080/ui/?#tors/launches/all|page.page=1&page.size=50&page.sort=start_time%2CDESC/5a29c8ed6767c80001d9baf2|page.page=1&page.size=50&filter.eq.has_childs=false&filter.in.issue$issue_type=TI001&page.sort=start_time%2CASC?page.page=1&page.size=50&filter.eq.has_childs=false&filter.in.issue$issue_type=TI001&page.sort=start_time%2CASC&log.item=5a29cd286767c80001da3faa&log.history=5a29cd286767c80001da3faa

**Workaround:**

Use external markup. But markup for links is not everywhere implemented.

**Proposal:**

- Implement some sort of inner cache for shortened links to be used to post somewhere outside of report portal.

**Comment by evjlobanova** [comment] 2020-04-02 13:45
Duplicate of #885

**Closed by evjlobanova** 2020-04-02 13:45 UTC
Labels: Feature: Links/URL, enhancement
