### ISSUE TITLE
[v5bug]: 5.0.0-RC-2: Binary Attachment Delete Failed

### ISSUE THREAD

**Issue by arunkumar-muthusamy** [reportportal/reportportal#774] opened 2019-12-13 21:56 UTC
**Describe the bug**
While deleting the launch (with binary attachments) from UI, the delete operation of binary data on file system `minio` is failing in the API layer.

Here is the version of components deployed > `Current version:API Service: 5.0.0-RC-2;Index Service: 5.0.4;Authorization Service: 5.0;Service UI: 5.0.0-RC-3;`

**To Reproduce**
Tail the API logs `docker-compose -p reportportal logs --tail="all" -f  api` and delete a lunch (with binary attachments) from UI. Delete will be successful & we cannot see it it in UI. But, when we look at the console (API tail), the delete will be failed..
```
api_1            | 2019-12-13 21:26:10.378 ERROR 1 --- [io-8585-exec-76] .t.r.c.e.r.ReportPortalExceptionResolver : ReportPortalExceptionResolver > Incorrect Request. Unable to find file
api_1            | 
api_1            | com.epam.ta.reportportal.exception.ReportPortalException: Incorrect Request. Unable to find file
api_1            | 	at com.epam.ta.reportportal.filesystem.distributed.minio.MinioDataStore.load(MinioDataStore.java:85)
api_1            | 	at com.epam.ta.reportportal.binary.impl.CommonDataStoreService.load(CommonDataStoreService.java:57)
api_1            | 	at com.epam.ta.reportportal.binary.impl.UserBinaryDataServiceImpl.loadUserPhoto(UserBinaryDataServiceImpl.java:100)
api_1            | 	at com.epam.ta.reportportal.core.file.impl.GetFileHandlerImpl.getUserPhoto(GetFileHandlerImpl.java:61)
api_1            | 	at com.epam.ta.reportportal.ws.controller.FileStorageController.getMyPhoto(FileStorageController.java:77)
api_1            | 	at com.epam.ta.reportportal.ws.controller.FileStorageController$$FastClassBySpringCGLIB$$ba8a78c4.invoke(<generated>)
api_1            | 	at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:218)
api_1            | 	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.invokeJoinpoint(CglibAopProxy.java:749)
api_1            | 	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:163)
api_1            | 	at org.springframework.transaction.interceptor.TransactionAspectSupport.invokeWithinTransaction(TransactionAspectSupport.java:295)
api_1            | 	at org.springframework.transaction.interceptor.TransactionInterceptor.invoke(TransactionInterceptor.java:98)
api_1            | 	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186)
api_1            | 	at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:688)
api_1            | 	at com.epam.ta.reportportal.ws.controller.FileStorageController$$EnhancerBySpringCGLIB$$d5233b25.getMyPhoto(<generated>)
api_1            | 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
api_1            | 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
api_1            | 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
api_1            | 	at java.lang.reflect.Method.invoke(Method.java:498)
api_1            | 	at org.springframework.web.method.support.InvocableHandlerMethod.doInvoke(InvocableHandlerMethod.java:190)
api_1            | 	at org.springframework.web.method.support.InvocableHandlerMethod.invokeForRequest(InvocableHandlerMethod.java:138)
api_1            | 	at org.springframework.web.servlet.mvc.method.annotation.ServletInvocableHandlerMethod.invokeAndHandle(ServletInvocableHandlerMethod.java:104)
api_1            | 	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.invokeHandlerMethod(RequestMappingHandlerAdapter.java:892)
api_1            | 	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.handleInternal(RequestMappingHandlerAdapter.java:797)
api_1            | 	at org.springframework.web.servlet.mvc.method.AbstractHandlerMethodAdapter.handle(AbstractHandlerMethodAdapter.java:87)
api_1            | 	at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:1039)
api_1            | 	at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:942)
api_1            | 	at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:1005)
api_1            | 	at org.springframework.web.servlet.FrameworkServlet.doGet(FrameworkServlet.java:897)
api_1            | 	at javax.servlet.http.HttpServlet.service(HttpServlet.java:634)
api_1            | 	at org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:882)
api_1            | 	at javax.servlet.http.HttpServlet.service(HttpServlet.java:741)
api_1            | 	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:231)
api_1            | 	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
api_1            | 	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:53)
api_1            | 	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
api_1            | 	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
api_1            | 	at org.springframework.web.multipart.support.MultipartFilter.doFilterInternal(MultipartFilter.java:124)
api_1            | 	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:109)
api_1            | 	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
api_1            | 	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
api_1            | 	at org.springframework.boot.actuate.web.trace.servlet.HttpTraceFilter.doFilterInternal(HttpTraceFilter.java:88)
api_1            | 	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:109)
api_1            | 	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
api_1            | 	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
api_1            | 	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:320)
api_1            | 	at org.springframework.security.web.access.intercept.FilterSecurityInterceptor.invoke(FilterSecurityInterceptor.java:127)
api_1            | 	at org.springframework.security.web.access.intercept.FilterSecurityInterceptor.doFilter(FilterSecurityInterceptor.java:91)
api_1            | 	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:334)
api_1            | 	at org.springframework.security.web.access.ExceptionTranslationFilter.doFilter(ExceptionTranslationFilter.java:119)
api_1            | 	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:334)
api_1            | 	at org.springframework.security.web.session.SessionManagementFilter.doFilter(SessionManagementFilter.java:137)
api_1            | 	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:334)
api_1            | 	at org.springframework.security.web.authentication.AnonymousAuthenticationFilter.doFilter(AnonymousAuthenticationFilter.java:111)
api_1            | 	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:334)
api_1            | 	at org.springframework.security.web.servletapi.SecurityContextHolderAwareRequestFilter.doFilter(SecurityContextHolderAwareRequestFilter.java:170)
api_1            | 	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:334)
api_1            | 	at org.springframework.security.web.savedrequest.RequestCacheAwareFilter.doFilter(RequestCacheAwareFilter.java:63)
api_1            | 	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:334)
api_1            | 	at org.springframework.security.oauth2.provider.authentication.OAuth2AuthenticationProcessingFilter.doFilter(OAuth2AuthenticationProcessingFilter.java:176)
api_1            | 	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:334)
api_1            | 	at org.springframework.security.web.authentication.logout.LogoutFilter.doFilter(LogoutFilter.java:116)
api_1            | 	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:334)
api_1            | 	at org.springframework.security.web.header.HeaderWriterFilter.doFilterInternal(HeaderWriterFilter.java:74)
api_1            | 	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:109)
api_1            | 	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:334)
api_1            | 	at org.springframework.security.web.context.SecurityContextPersistenceFilter.doFilter(SecurityContextPersistenceFilter.java:105)
api_1            | 	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:334)
api_1            | 	at org.springframework.security.web.context.request.async.WebAsyncManagerIntegrationFilter.doFilterInternal(WebAsyncManagerIntegrationFilter.java:56)
api_1            | 	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:109)
api_1            | 	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:334)
api_1            | 	at org.springframework.security.web.FilterChainProxy.doFilterInternal(FilterChainProxy.java:215)
api_1            | 	at org.springframework.security.web.FilterChainProxy.doFilter(FilterChainProxy.java:178)
api_1            | 	at org.springframework.web.filter.DelegatingFilterProxy.invokeDelegate(DelegatingFilterProxy.java:357)
api_1            | 	at org.springframework.web.filter.DelegatingFilterProxy.doFilter(DelegatingFilterProxy.java:270)
api_1            | 	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
api_1            | 	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
api_1            | 	at org.springframework.web.filter.RequestContextFilter.doFilterInternal(RequestContextFilter.java:99)
api_1            | 	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:109)
api_1            | 	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
api_1            | 	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
api_1            | 	at org.springframework.web.filter.FormContentFilter.doFilterInternal(FormContentFilter.java:92)
api_1            | 	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:109)
api_1            | 	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
api_1            | 	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
api_1            | 	at org.springframework.web.filter.HiddenHttpMethodFilter.doFilterInternal(HiddenHttpMethodFilter.java:93)
api_1            | 	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:109)
api_1            | 	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
api_1            | 	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
api_1            | 	at org.springframework.boot.actuate.metrics.web.servlet.WebMvcMetricsFilter.filterAndRecordMetrics(WebMvcMetricsFilter.java:114)
api_1            | 	at org.springframework.boot.actuate.metrics.web.servlet.WebMvcMetricsFilter.doFilterInternal(WebMvcMetricsFilter.java:104)
api_1            | 	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:109)
api_1            | 	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
api_1            | 	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
api_1            | 	at org.springframework.web.filter.CharacterEncodingFilter.doFilterInternal(CharacterEncodingFilter.java:200)
api_1            | 	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:109)
api_1            | 	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
api_1            | 	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
api_1            | 	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:202)
api_1            | 	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:96)
api_1            | 	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:490)
api_1            | 	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:139)
api_1            | 	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:92)
api_1            | 	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:74)
api_1            | 	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:343)
api_1            | 	at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:408)
api_1            | 	at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:66)
api_1            | 	at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:853)
api_1            | 	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1587)
api_1            | 	at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
api_1            | 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
api_1            | 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
api_1            | 	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
api_1            | 	at java.lang.Thread.run(Thread.java:748)

```
**Expected behavior**
Delete should be successful in both Postgres and minio (file system)

**Additional Info***
Minio service has multiple failures `docker-compose -p reportportal logs --tail="all" -f  minio`

```
minio_1          | API: AssumeRoleJWTCommon()
minio_1          | Time: 11:46:07 UTC 12/13/2019
minio_1          | DeploymentID: aa73e917-a2a3-4de7-8f6a-97ff3ce0909f
minio_1          | RequestID: 15DFEBB7665143FA
minio_1          | RemoteHost: 10.94.100.158
minio_1          | Host: 10.94.102.231
minio_1          | UserAgent: Mozilla/5.0 (Windows; U; Windows NT 5.1; en-US; rv:1.8.1.14)
minio_1          | Error: Invalid STS API version , expecting 2011-06-15
minio_1          |        3: /bitnami/blacksmith-sandox/minio-2019.10.12/src/github.com/minio/minio/cmd/sts-errors.go:40:cmd.writeSTSErrorResponse()
minio_1          |        2: /bitnami/blacksmith-sandox/minio-2019.10.12/src/github.com/minio/minio/cmd/sts-handlers.go:252:cmd.(*stsAPIHandlers).AssumeRoleWithJWT()
minio_1          |        1: net/http/server.go:2007:http.HandlerFunc.ServeHTTP()
minio_1          | 
minio_1          | API: AssumeRoleJWTCommon()
minio_1          | Time: 11:46:14 UTC 12/13/2019
minio_1          | DeploymentID: aa73e917-a2a3-4de7-8f6a-97ff3ce0909f
minio_1          | RequestID: 15DFEBB90827DB8C
minio_1          | RemoteHost: 10.94.100.158
minio_1          | Host: 10.94.102.231
minio_1          | UserAgent: Mozilla/5.0 (Windows; U; Windows NT 5.1; en-US; rv:1.8.1.14)
minio_1          | Error: Invalid STS API version , expecting 2011-06-15
minio_1          |        3: /bitnami/blacksmith-sandox/minio-2019.10.12/src/github.com/minio/minio/cmd/sts-errors.go:40:cmd.writeSTSErrorResponse()
minio_1          |        2: /bitnami/blacksmith-sandox/minio-2019.10.12/src/github.com/minio/minio/cmd/sts-handlers.go:252:cmd.(*stsAPIHandlers).AssumeRoleWithJWT()
minio_1          |        1: net/http/server.go:2007:http.HandlerFunc.ServeHTTP()
minio_1          | 
minio_1          | API: AssumeRoleJWTCommon()
minio_1          | Time: 11:46:21 UTC 12/13/2019
minio_1          | DeploymentID: aa73e917-a2a3-4de7-8f6a-97ff3ce0909f
minio_1          | RequestID: 15DFEBBAA9F4E699
minio_1          | RemoteHost: 10.94.100.158
minio_1          | Host: 10.94.102.231
minio_1          | UserAgent: Mozilla/5.0 (Windows; U; Windows NT 5.1; en-US; rv:1.8.1.14)
minio_1          | Error: Invalid STS API version , expecting 2011-06-15
minio_1          |        3: /bitnami/blacksmith-sandox/minio-2019.10.12/src/github.com/minio/minio/cmd/sts-errors.go:40:cmd.writeSTSErrorResponse()
minio_1          |        2: /bitnami/blacksmith-sandox/minio-2019.10.12/src/github.com/minio/minio/cmd/sts-handlers.go:252:cmd.(*stsAPIHandlers).AssumeRoleWithJWT()
minio_1          |        1: net/http/server.go:2007:http.HandlerFunc.ServeHTTP()
```

**Comment by Yumfriez** [comment] 2019-12-20 10:50
@arunkumar-muthusamy As I can see from logs trace:
```
com.epam.ta.reportportal.exception.ReportPortalException: Incorrect Request. Unable to find file
com.epam.ta.reportportal.filesystem.distributed.minio.MinioDataStore.load(MinioDataStore.java:85)
com.epam.ta.reportportal.binary.impl.CommonDataStoreService.load(CommonDataStoreService.java:57)
com.epam.ta.reportportal.binary.impl.UserBinaryDataServiceImpl.loadUserPhoto(UserBinaryDataServiceImpl.java:100)
com.epam.ta.reportportal.core.file.impl.GetFileHandlerImpl.getUserPhoto(GetFileHandlerImpl.java:61)
```
Exception occures because User photo cannot be loaded.
So when you delete launch, attachments of its items' logs are removed successfully. 
There is, probably, some problems with user photo file

**Comment by arunkumar-muthusamy** [comment] 2019-12-20 15:21
Thanks, @Yumfriez ! BTW, i have created few users where those users does not have profile photo. Which might cause this issue. You can consider this use case for and handle the exception. 

Also, how about the error in `minio` pods?

**Comment by evjlobanova** [comment] 2020-03-31 12:53
Duplicate of https://github.com/reportportal/reportportal/issues/773

**Closed** 2020-03-31 12:54 UTC
Labels: duplicate, help wanted, v5beta
