### ISSUE TITLE
[v5]

### ISSUE THREAD

**Issue by asaflevyz** [reportportal/reportportal#1389] opened 2021-05-04 16:56 UTC
**Describe the bug**
email notification sender looks like "From: root@f7c6b1c3d13e [mailto:root@f7c6b1c3d13e]" instead the email address set in email integration plugin.

**To Reproduce**
No matter what value sender field has, it is ignored.

**Expected behavior**
Expectation is to get email notifications from sender field set in email integration plugin.

**Desktop (please complete the following information):**
 - OS: CentOS 7, RP run on Docker

**Additional context**
Report portal is install on Docker using Docker compose with external DB.

**Comment by asaflevyz** [comment] 2021-05-04 16:56
ReportPortal version is 5.2.2

**Comment by evjlobanova** [comment] 2021-05-05 03:50
@VolhaKarenko could you please recheck, if we fix this issue in the past versions?

**Comment by svettsova** [comment] 2021-05-05 05:05
@evjlobanova we have issue in the backlog related to sender name which was found in #814 

about incorrect email address - it is not reproducible for the latest version

**Comment by asaflevyz** [comment] 2021-05-06 07:33
So i understand that this is a bug that will be fixed on 5.5?
If so, what is the release date of 5.5?

Thanks.

**Comment by evjlobanova** [comment] 2021-05-12 15:09
For now, the date is not defined yet.

**Comment by asaflevyz** [comment] 2021-05-12 19:09
Thanks.

**Comment by alena-babrova** [comment] 2022-04-22 05:52
The issue is fixed in v. 5.8

**Closed by alena-babrova** 2022-04-22 05:52 UTC
Labels: bug
