### ISSUE TITLE
Add filter to widget: Most failed test-cases table (TOP-20))

### ISSUE THREAD

**Issue by shaburov** [reportportal/reportportal#907] opened 2020-04-03 14:57 UTC
The widget "Most failed test-cases table" does not contain a filter selection. 
Using only "Launch name" - This is a pain.
Let's do something more flexible...

![image](https://user-images.githubusercontent.com/15269131/78374412-7c785980-75d4-11ea-9b66-0c953e9b0f2d.png)

**Comment by evjlobanova** [comment] 2020-04-03 15:33
Duplicate of #320 
Please follow the progress on this issue in the mentioned issue

**Closed by evjlobanova** 2020-04-03 15:33 UTC
Labels: feature request
