### ISSUE TITLE
Should have option to show launch name instead of launch number

### ISSUE THREAD

**Issue by vivektamrakar91221** [reportportal/reportportal#450] opened 2018-07-31 09:59 UTC
Hi ReportPortal Team, 

I have a question over here. Is it possible to display launch name instead of launch number in 'Launch statistics chart' widget.
I am aware that we can see the launch name on tool tip of the graph but it would be great if we can customise this option for user where he can select whether he wants to see the launch name or launch number.

**Comment by evjlobanova** [comment] 2018-07-31 10:44
@Iren-Melnyk Iryna, could you please look at this request? The case is that our users print the dashboard with  widgets, and in printed report managers can`t see launch name

**Comment by DzmitryHumianiuk** [comment] 2018-07-31 20:01
@vivektamrakar91221 we still avoid it, since launch names can be very long, and this can be an issue to represent all on the widget.

we plan to change representation one day, but make it as complex change for widgets

**Comment by DzmitryHumianiuk** [comment] 2018-07-31 20:03
@vivektamrakar91221 in case if your widgets represent launch with the same name only, you can add launch name into widget name.

Does it work for you?

**Comment by Iren-Melnyk** [comment] 2018-08-06 08:34
Hello @vivektamrakar91221 
Could you please show some examples of the longest launch names?
And please clarify where do you want to see them. Do you want to see it in the app or print report?

**Comment by evjlobanova** [comment] 2020-03-26 16:36
Duplicate of #398

**Closed by evjlobanova** 2020-03-26 16:36 UTC
Labels: duplicate, enhancement
