### ISSUE TITLE
Defect types report incorrect number of test cases

### ISSUE THREAD

**Issue by rhrazdil** [reportportal/reportportal#462] opened 2018-08-21 14:47 UTC
Hello guys,

we encountered an odd issue. Report Portal's calculation of defect types started to report incorrect numbers. In the following screenshot you can see that Defect type SI indicator says it contains 2 test cases, but it actually contains 3. At the same time, TI (To Investigate) indicator says it contains 1 test case, but it is actually empty.

![rp_dt_miscalc](https://user-images.githubusercontent.com/32546791/44408196-31751400-a560-11e8-8974-8108070196e6.png)

When we tried to move those test cases back to TI, SI reported number -1.

![rp_negative_count](https://user-images.githubusercontent.com/32546791/44408485-c1b35900-a560-11e8-9e38-f751cba4bb22.png)

I'm not entirely sure what are the reproduction steps, but I believe the numbers of defect were correct until the last test case was moved from TI to SI. At that point, TI still indicated 1 test case, but was empty. But this is the first time we encountered this.

Also, please advise how to provide logs for proper investigation, we have created a dump, but its size is around 250 MB. Do you have any preferred way how to collect logs useful for analysis? 

Version of our RP instance is 4.2.2.

**Comment by DzmitryHumianiuk** [comment] 2018-08-23 21:39
Hi @rhrazdil 
it is a know issue. Appear due to concurrent access to data in database.
MongoDB doesn't support transactions in version 3.x
It will be available only with v4, which is in beta.

This is one of the reasons, in the list, why we decided to refactor ReportPortal and migrate to PostreSQL DB. Which will mitigate this issue on the core level.
But in order to be sure, we will introduce re-calculation function for launch with RP5.0

This issue can appear sometimes, but no very critical.
Plz ignore it for a while, and wait for RP 5.0

**Comment by DzmitryHumianiuk** [comment] 2018-08-23 21:40
@ringods could you please advice on 
>Also, please advise how to provide logs for proper investigation, we have created a dump, but its size is around 250 MB. Do you have any preferred way how to collect logs useful for analysis?

**Comment by DzmitryHumianiuk** [comment] 2018-08-23 21:41
@evjlobanova plz link this issue with duplicate, for incorrect statistics of Defects

**Comment by evjlobanova** [comment] 2020-03-26 17:09
Closed due to irrelevance

**Comment by HardNorth** [comment] 2020-03-27 07:49
@evjlobanova the issue is a bit outdate why you reopened it?

**Comment by evjlobanova** [comment] 2020-03-31 14:05
Duplicate of https://github.com/reportportal/reportportal/issues/724

**Closed by evjlobanova** 2020-03-31 14:05 UTC
Labels: duplicate, help wanted
