### ISSUE TITLE
Unable to locate a matching ACE

### ISSUE THREAD

**Issue by babantax** [reportportal/reportportal#1892] opened 2022-11-30 16:15 UTC
Report Portal Version 5.7.2

One user reported this error while trying to invite another existing user to his project.  

![image](https://user-images.githubusercontent.com/52815118/204850062-082d51d8-850c-4554-8401-5cc8901585a2.png)
![image](https://user-images.githubusercontent.com/52815118/204850192-dd9ae9ce-3760-4cfc-a623-7a9f2f323a1a.png)

Is not happening with others users/projects (at least not reported yet). 

Can be any data inconsistency?

**Comment by alena-babrova** [comment] 2022-12-06 16:24
Hello @babantax,

Yes, it is a known issue which is reproduced from time to time. The issue is connected with shared entity (shared dashboard/widget). The bug has already been **fixed** and will be released in the **5.8 version**.
As a workaround, please, let someone else try to invite this user. 
Or use another, more radical way - delete the user and invite them back, but make sure that the deleted user doesn't have own filters/dashboards /widgets created, otherwise they will be deleted along with the user.

I hope this information will help you!

**Comment by alena-babrova** [comment] 2023-10-02 08:23
Hello @babantax,
We have fixed the issue in the 23.1 version of ReportPortal.

**Closed by alena-babrova** 2023-10-02 08:23 UTC
Labels: bug
