### ISSUE TITLE
Show attachment's message/title  on the gallery

### ISSUE THREAD

**Issue by ulmanA** [reportportal/reportportal#338] opened 2018-01-25 19:44 UTC
Hi
on the gallery of the attachments the titles are missing
this text is importent for understand what is the purpose of the attachment.
for example,
- Test has few screenshots and the title said on which test's phase there was taken.
- Test with few log files attached. each came f4om different component of the testesd application.

thanks!

**Comment by evjlobanova** [comment] 2018-02-20 15:18
the same request from Sergey Mishanin (via skype)

**Comment by evjlobanova** [comment] 2020-04-02 14:03
duplicate of #665

**Closed by evjlobanova** 2020-04-02 14:03 UTC
Labels: Feature: LogView, enhancement
