### ISSUE TITLE
[v5] Launch View Start Time Always in UTC while Launch Widget displays local time [Timezone issue]

### ISSUE THREAD

**Issue by sspieker-cc** [reportportal/reportportal#1318] opened 2021-02-19 21:02 UTC
**Describe the bug**
Updating the timezone for the Reportportal API container was simple enough to solve, the "START TIME" column within the Launches view (regardless of the use of a filter or not) always displays results in UTC TZ (Right side of attached image).

Viewing the same run within the Launches widget display (Left side of attached image) displays the correct time/date from the current timezone (EDT in this case).

Launches view displays incorrect startime timezone information.  It looks as if there is a query that just needs to be adjusted to account for the timezone of the container, for example:

select created_at at time zone 'utc' at time zone 'america/los_angeles' from ...  with the 'america/los_angeles' being adjusted by the ENV TZ value?
https://popsql.com/learn-sql/postgresql/how-to-convert-utc-to-local-time-zone-in-postgresql

**To Reproduce**
1. Set TZ within service-api container using docker-compose or kubernetes deployment
2. Create dashboard and include Launches display widget to include launch name, tag, etc. filter to include specific launch results.
3. Import launch through XML import option as an admin user
4. Compare the results between the launches view and the dashboard launch widget to compare start time display

**Expected behavior**
Expected behavior is to have the Launches view display consistent date time information based on the TZ set in JAVA_OPTS, ENV TZ and/or container settings.

**Screenshots**
![Screen Shot 2021-02-19 at 3 48 34 PM](https://user-images.githubusercontent.com/49696592/108559919-fa675100-72c9-11eb-889f-8a142156d6d5.png)
![Screen Shot 2021-02-19 at 4 03 53 PM](https://user-images.githubusercontent.com/49696592/108561344-179d1f00-72cc-11eb-84be-349b63fcb0eb.png)

**Desktop (please complete the following information):**
 - OS: OSX, Windows, iOS, Android
 - Browser(s): All
 - Version: Various

**Additional context**
This deployment is managed through a k8s cluster and there are no RP tooling operations involved in reporting test results.  We have standardized on API calls to import ALL test results using Junit XML formatted output.  We have the same results regardless of what framework, test application or behavior of tests.  All results appear in their respective views with differing date/time stamps.

Current RP version: 5.3.2

Upgraded to version 5.3.5 and the same behavior exists

**Comment by sspieker-cc** [comment] 2021-02-19 22:24
This seems to be a similar defect to #995 
https://github.com/reportportal/reportportal/issues/995

**Comment by MaryiaRymarchyk** [comment] 2023-03-13 13:28
Hi @sspieker-cc , The issue is fixed in version 5.3.

**Closed by MaryiaRymarchyk** 2023-03-13 13:28 UTC
