### ISSUE TITLE
Compare test results

### ISSUE THREAD

**Issue by roniezr** [reportportal/reportportal#472] opened 2018-09-06 08:36 UTC
It would be nice if a user can choose two different history results and compare them
Meaning the user will choose at least two history results, click Compare and a new window will open
showing the two results side by side.
The difference should be highlighted.

**Comment by DzmitryHumianiuk** [comment] 2018-09-06 09:36
@roniezr if you have good example of what should be shown, plz share it with us

**Comment by Witos** [comment] 2019-10-09 13:59
+1

**Comment by Witos** [comment] 2019-10-10 08:17
It's duplicate of #290 I think.

**Closed** 2020-03-26 16:48 UTC
Labels: duplicate, feature request
