### ISSUE TITLE
Widget "Most failed test-cases table (TOP-20)" shows last run and not last failed run. 

### ISSUE THREAD

**Issue by SaskiaPeschutter** [reportportal/reportportal#1564] opened 2021-10-28 11:43 UTC
**Describe the bug**
The "last issue" column shows the last time the test case run instead of the time the test case failed the last time and also the link goes to the last test where the test run successfully. 

**Expected behavior**
Widget "Most failed test-cases table (TOP-20)"  links to the last failed test case and shows this as a time of "Last Issue". 

**Versions:**
 - Ubuntu, Firefox
 - Current version: API Service: 5.5.0;Index Service: 5.0.10;Authorization Service: 5.5.0;Service UI: 5.5.0;

**Comment by VolhaKarenko** [comment] 2022-02-24 12:41
The issue is fixed in version 5.7

**Closed by VolhaKarenko** 2022-02-24 12:41 UTC
Labels: bug
