### ISSUE TITLE
[v5.3.3] Auto-analysis doesn't work. 

### ISSUE THREAD

**Issue by AndreiSomovTR** [reportportal/reportportal#1246] opened 2020-12-08 07:23 UTC
**Describe the bug**
Despite a failed test was marked with some (and the same) reason of failure during at least 10 launches the test still falls into 'To Investigate' 

**To Reproduce**
1. Set up auto-analysis
2. Launch test with the failed method
3. Mark the test with the some reason of failure
4. Repeat steps 2 and 3 at least 10 times: every time pick the same reason of failure

**Expected behavior**
After test was finished with a failure, auto-analysis should mark the test with a specific type of failure

**Actual behavior**
Test is always marked as 'To Investigate'
 
**Screenshots**
![image](https://user-images.githubusercontent.com/60747505/101452815-5d8a4e00-393f-11eb-9e14-a2baf73c02fb.png)

**Desktop (please complete the following information):**
 - OS: [Windows 10]
 - Browser [chrome]
 - Version [87.0.4280.88]

**Additional context**
Auto-analysis configuration:
![image](https://user-images.githubusercontent.com/60747505/101452632-0b492d00-393f-11eb-9082-a44977bc8871.png)

RP is not installed locally it is provided to us by other team

**Comment by evjlobanova** [comment] 2020-12-16 07:00
Which version do you use?
Does the service analyzer run?
Please send us a log of service analyzer, Elastic Search, Rabbit MQ

**Comment by AndreiSomovTR** [comment] 2020-12-16 12:55
> Which version do you use?
> Does the service analyzer run?
> Please send us a log of service analyzer, Elastic Search, Rabbit MQ

1. RP version is 5.3.3
2. service analyzer is running
3. Logs is attached. ES logs is empty*

**Comment by AndreiSomovTR** [comment] 2020-12-16 12:55
[RP logs.zip](https://github.com/reportportal/reportportal/files/5702770/RP.logs.zip)

**Comment by evjlobanova** [comment] 2020-12-16 13:31
@MariyaIvanina @irynakozak2 GCould you please check logs?

**Comment by MariyaIvanina** [comment] 2020-12-16 13:38
@AndreiSomovTR Hi, Andrei! When a new analyzer version is used, it is better to generate index( click button "Generate index" at the Auto-analysis settings), as far as we are improving our algorithms and add new fields to process, that's why it is important to have an up-to-date elasticsearch index. I can see that at your settings page, the buttons are grayed out, it indicates that traefik is not working correctly. We had some issues with some traefik versions, and users whoch had 2.1.0 traefik faced the same problem with grayed out buttons, but at the version 2.0.5, it was just fine.

**Comment by AndreiSomovTR** [comment] 2020-12-16 14:23
> @AndreiSomovTR Hi, Andrei! When a new analyzer version is used, it is better to generate index( click button "Generate index" at the Auto-analysis settings), as far as we are improving our algorithms and add new fields to process, that's why it is important to have an up-to-date elasticsearch index. I can see that at your settings page, the buttons are grayed out, it indicates that traefik is not working correctly. We had some issues with some traefik versions, and users whoch had 2.1.0 traefik faced the same problem with grayed out buttons, but at the version 2.0.5, it was just fine.

Hi!
1. we use traefik:v2.0.5
2. I clicked at 'submit' button -> 'Generate Index' button became active -> I clicked 'Generate Index' button -> after I re-launched my test 15 times (every launch I set up the same reason of failure)-> As a result auto-analysis still doesn't set correct reason of failure.
3. New logs are attached, take a look please

[RP_logs_2.zip](https://github.com/reportportal/reportportal/files/5703264/RP_logs_2.zip)

**Comment by MariyaIvanina** [comment] 2020-12-16 14:55
Andrei, thank you for your logs! Has generating index finished? Has the button color returned to the active color? Could you redeploy the analyzer service with setting the environmental variable LOGGING_LEVEL: debug, it will give us more logs.

**Comment by AndreiSomovTR** [comment] 2020-12-16 15:33
> Andrei, thank you for your logs! Has generating index finished? Has the button color returned to the active color? Could you redeploy the analyzer service with setting the environmental variable LOGGING_LEVEL: debug, it will give us more logs.

I think so, 'Generate Index' button is active again at least. Here new logs:
[RP_logs_3.zip](https://github.com/reportportal/reportportal/files/5703702/RP_logs_3.zip)

**Comment by MariyaIvanina** [comment] 2020-12-17 07:52
Thank you, the logs are more helpful now. I see from the logs that index was not created for this project, and at each action of analysis it finishes with 0 results, because the index doesn't exist for this project. Could you click button "generate index" and send the logs which were printed while the index is being created? And also could say how big this project is?

**Comment by AndreiSomovTR** [comment] 2020-12-17 09:14
> Thank you, the logs are more helpful now. I see from the logs that index was not created for this project, and at each action of analysis it finishes with 0 results, because the index doesn't exist for this project. Could you click button "generate index" and send the logs which were printed while the index is being created? And also could say how big this project is?

As you requested, logs with index generation:
[RP_logs_4.zip](https://github.com/reportportal/reportportal/files/5708179/RP_logs_4.zip)
Also, could you please clarify what do you mean by 'big project'?
ECT_QED it self contains smth about 20 projects, but 'ect_qed-cocklicks' is a small part of ECT_QED and contains only 2 tests (only for for now due to debugging)

**Comment by MariyaIvanina** [comment] 2020-12-17 10:32
Thank you for your logs. What I see in the logs, that when generate index activity is run, analyzer doesn't receive launches. I can see in the logs that other projects uses analyzer and analysis/indexing works quite fine. Could you say how have you imported launches in this project, for which analysis and indexing don't work?

**Comment by AndreiSomovTR** [comment] 2020-12-17 10:42
> Thank you for your logs. What I see in the logs, that when generate index activity is run, analyzer doesn't receive launches. I can see in the logs that other projects uses analyzer and analysis/indexing works quite fine. Could you say how have you imported launches in this project, for which analysis and indexing don't work?

we run in this way: 
![image](https://user-images.githubusercontent.com/60747505/102477558-91ffb780-406d-11eb-8321-5b892bd63106.png)
after execution is completed the results exist in RP

**Comment by MariyaIvanina** [comment] 2020-12-17 11:08
@pbortnik I need your help and consultation. According to the logs:
`2020-12-17 08:34:56,023 - analyzerApp.amqpHandler - DEBUG - Started processing <Basic.Deliver(['consumer_tag=ctag1.fd25713e378f4fa5ae8f97b0d7df0c3c', 'delivery_tag=1', 'exchange=analyzer', 'redelivered=False', 'routing_key=delete'])> method <BasicProperties(['content_encoding=UTF-8', 'content_type=application/json', 'correlation_id=13533', 'delivery_mode=2', "headers={'__TypeId__': 'java.lang.Long'}", 'priority=0', 'reply_to=amq.rabbitmq.reply-to.g2dkABNyYWJiaXRAZDU4ZDMwMGQwMDc0AAAKcAAAAAIC.wrX8jbyA+/6tn1AunP4ovg=='])> props
2020-12-17 08:34:56,023 - analyzerApp.amqpHandler - DEBUG - Started processing data b'238'
2020-12-17 08:34:56,029 - analyzerApp.esclient - ERROR - Not found 238 for deleting
2020-12-17 08:34:56,029 - analyzerApp.esclient - ERROR - ES Url http://elasticsearch:9200
2020-12-17 08:34:56,029 - analyzerApp.esclient - ERROR - NotFoundError(404, 'index_not_found_exception', 'no such index [238]', 238, index_or_alias)
2020-12-17 08:34:56,030 - analyzerApp.amqpHandler - DEBUG - Finished processing <Basic.Deliver(['consumer_tag=ctag1.fd25713e378f4fa5ae8f97b0d7df0c3c', 'delivery_tag=1', 'exchange=analyzer', 'redelivered=False', 'routing_key=delete'])> method
2020-12-17 08:35:21,310 - analyzerApp.amqpHandler - DEBUG - Started processing <Basic.Deliver(['consumer_tag=ctag1.de21da9587904735b27758276971e132', 'delivery_tag=509', 'exchange=analyzer', 'redelivered=False', 'routing_key=namespace_finder'])> method <BasicProperties(['content_encoding=UTF-8', 'content_type=application/json', 'correlation_id=13534', 'delivery_mode=2', "headers={'__ContentTypeId__': 'java.lang.Object', '__TypeId__': 'java.util.ArrayList'}", 'priority=0', 'reply_to=amq.rabbitmq.reply-to.g2dkABNyYWJiaXRAZDU4ZDMwMGQwMDc0AAAKcAAAAAIC.wrX8jbyA+/6tn1AunP4ovg=='])> props
2020-12-17 08:35:21,310 - analyzerApp.amqpHandler - DEBUG - Started processing data b'[]'
2020-12-17 08:35:21,310 - analyzerApp.esclient - DEBUG - Started updating chosen namespaces
2020-12-17 08:35:21,311 - analyzerApp.esclient - DEBUG - Project id None
2020-12-17 08:35:21,311 - analyzerApp.esclient - DEBUG - Found namespaces {}
2020-12-17 08:35:21,311 - analyzerApp.esclient - DEBUG - Finished updating chosen namespaces 0.00 s
2020-12-17 08:35:21,311 - analyzerApp.amqpHandler - DEBUG - Finished processing <Basic.Deliver(['consumer_tag=ctag1.de21da9587904735b27758276971e132', 'delivery_tag=509', 'exchange=analyzer', 'redelivered=False', 'routing_key=namespace_finder'])> method
2020-12-17 08:35:21,312 - analyzerApp.amqpHandler - DEBUG - Started processing <Basic.Deliver(['consumer_tag=ctag1.7f3b028d4c9c46f6b5c4a1a136145836', 'delivery_tag=509', 'exchange=analyzer', 'redelivered=False', 'routing_key=index'])> method <BasicProperties(['content_encoding=UTF-8', 'content_type=application/json', 'correlation_id=13535', 'delivery_mode=2', "headers={'__ContentTypeId__': 'java.lang.Object', '__TypeId__': 'java.util.ArrayList'}", 'priority=0', 'reply_to=amq.rabbitmq.reply-to.g2dkABNyYWJiaXRAZDU4ZDMwMGQwMDc0AAAKcAAAAAIC.wrX8jbyA+/6tn1AunP4ovg=='])> props
2020-12-17 08:35:21,312 - analyzerApp.amqpHandler - DEBUG - Started processing data b'[]'
2020-12-17 08:35:21,313 - analyzerApp.esclient - INFO - Indexing logs for 0 launches
2020-12-17 08:35:21,313 - analyzerApp.esclient - INFO - ES Url http://elasticsearch:9200
2020-12-17 08:35:21,313 - analyzerApp.esclient - DEBUG - Delete merged logs for 0 test items
2020-12-17 08:35:21,313 - analyzerApp.esclient - INFO - Finished indexing logs for 0 launches. It took 0.00 sec.
2020-12-17 08:35:21,314 - analyzerApp.amqpHandler - DEBUG - Finished processing <Basic.Deliver(['consumer_tag=ctag1.7f3b028d4c9c46f6b5c4a1a136145836', 'delivery_tag=509', 'exchange=analyzer', 'redelivered=False', 'routing_key=index'])> method`

238 project is the one, we are talking about here. Junitcore is used for submitting launches, and they exist in RP, but when the button "Generate index" is clicked, no any launches are sent to the analyzer, that's why the index is not created and no analysis can be done. Have you faced such issues before and may be you have an idea why launches may be not sent to the analyser?

**Comment by AndreiSomovTR** [comment] 2020-12-28 14:39
> @pbortnik I need your help and consultation. According to the logs:
> `2020-12-17 08:34:56,023 - analyzerApp.amqpHandler - DEBUG - Started processing <Basic.Deliver(['consumer_tag=ctag1.fd25713e378f4fa5ae8f97b0d7df0c3c', 'delivery_tag=1', 'exchange=analyzer', 'redelivered=False', 'routing_key=delete'])> method <BasicProperties(['content_encoding=UTF-8', 'content_type=application/json', 'correlation_id=13533', 'delivery_mode=2', "headers={'**TypeId**': 'java.lang.Long'}", 'priority=0', 'reply_to=amq.rabbitmq.reply-to.g2dkABNyYWJiaXRAZDU4ZDMwMGQwMDc0AAAKcAAAAAIC.wrX8jbyA+/6tn1AunP4ovg=='])> props
> 2020-12-17 08:34:56,023 - analyzerApp.amqpHandler - DEBUG - Started processing data b'238'
> 2020-12-17 08:34:56,029 - analyzerApp.esclient - ERROR - Not found 238 for deleting
> 2020-12-17 08:34:56,029 - analyzerApp.esclient - ERROR - ES Url http://elasticsearch:9200
> 2020-12-17 08:34:56,029 - analyzerApp.esclient - ERROR - NotFoundError(404, 'index_not_found_exception', 'no such index [238]', 238, index_or_alias)
> 2020-12-17 08:34:56,030 - analyzerApp.amqpHandler - DEBUG - Finished processing <Basic.Deliver(['consumer_tag=ctag1.fd25713e378f4fa5ae8f97b0d7df0c3c', 'delivery_tag=1', 'exchange=analyzer', 'redelivered=False', 'routing_key=delete'])> method
> 
> 2020-12-17 08:35:21,310 - analyzerApp.amqpHandler - DEBUG - Started processing <Basic.Deliver(['consumer_tag=ctag1.de21da9587904735b27758276971e132', 'delivery_tag=509', 'exchange=analyzer', 'redelivered=False', 'routing_key=namespace_finder'])> method <BasicProperties(['content_encoding=UTF-8', 'content_type=application/json', 'correlation_id=13534', 'delivery_mode=2', "headers={'**ContentTypeId**': 'java.lang.Object', '**TypeId**': 'java.util.ArrayList'}", 'priority=0', 'reply_to=amq.rabbitmq.reply-to.g2dkABNyYWJiaXRAZDU4ZDMwMGQwMDc0AAAKcAAAAAIC.wrX8jbyA+/6tn1AunP4ovg=='])> props
> 2020-12-17 08:35:21,310 - analyzerApp.amqpHandler - DEBUG - Started processing data b'[]'
> 2020-12-17 08:35:21,310 - analyzerApp.esclient - DEBUG - Started updating chosen namespaces
> 2020-12-17 08:35:21,311 - analyzerApp.esclient - DEBUG - Project id None
> 2020-12-17 08:35:21,311 - analyzerApp.esclient - DEBUG - Found namespaces {}
> 2020-12-17 08:35:21,311 - analyzerApp.esclient - DEBUG - Finished updating chosen namespaces 0.00 s
> 2020-12-17 08:35:21,311 - analyzerApp.amqpHandler - DEBUG - Finished processing <Basic.Deliver(['consumer_tag=ctag1.de21da9587904735b27758276971e132', 'delivery_tag=509', 'exchange=analyzer', 'redelivered=False', 'routing_key=namespace_finder'])> method
> 
> 2020-12-17 08:35:21,312 - analyzerApp.amqpHandler - DEBUG - Started processing <Basic.Deliver(['consumer_tag=ctag1.7f3b028d4c9c46f6b5c4a1a136145836', 'delivery_tag=509', 'exchange=analyzer', 'redelivered=False', 'routing_key=index'])> method <BasicProperties(['content_encoding=UTF-8', 'content_type=application/json', 'correlation_id=13535', 'delivery_mode=2', "headers={'**ContentTypeId**': 'java.lang.Object', '**TypeId**': 'java.util.ArrayList'}", 'priority=0', 'reply_to=amq.rabbitmq.reply-to.g2dkABNyYWJiaXRAZDU4ZDMwMGQwMDc0AAAKcAAAAAIC.wrX8jbyA+/6tn1AunP4ovg=='])> props
> 2020-12-17 08:35:21,312 - analyzerApp.amqpHandler - DEBUG - Started processing data b'[]'
> 2020-12-17 08:35:21,313 - analyzerApp.esclient - INFO - Indexing logs for 0 launches
> 2020-12-17 08:35:21,313 - analyzerApp.esclient - INFO - ES Url http://elasticsearch:9200
> 2020-12-17 08:35:21,313 - analyzerApp.esclient - DEBUG - Delete merged logs for 0 test items
> 2020-12-17 08:35:21,313 - analyzerApp.esclient - INFO - Finished indexing logs for 0 launches. It took 0.00 sec.
> 2020-12-17 08:35:21,314 - analyzerApp.amqpHandler - DEBUG - Finished processing <Basic.Deliver(['consumer_tag=ctag1.7f3b028d4c9c46f6b5c4a1a136145836', 'delivery_tag=509', 'exchange=analyzer', 'redelivered=False', 'routing_key=index'])> method`
> 
> 238 project is the one, we are talking about here. Junitcore is used for submitting launches, and they exist in RP, but when the button "Generate index" is clicked, no any launches are sent to the analyzer, that's why the index is not created and no analysis can be done. Have you faced such issues before and may be you have an idea why launches may be not sent to the analyser?

@pbortnik @MariyaIvanina Hi! Any updates at this one?

**Comment by MariyaIvanina** [comment] 2020-12-28 15:09
@AndreiSomovTR could you also share the log, which is in the test item you are sending to Report portal? Thank you in advance.

**Comment by MariyaIvanina** [comment] 2020-12-28 15:28
@AndreiSomovTR Could you also check that logs you are reporting into Report portal have error log level >= 40000 (error log and more severe)? And one more thing could you check that types of test items are correct. You need to click the number of failed test items from this view
![101452815-5d8a4e00-393f-11eb-9e14-a2baf73c02fb](https://user-images.githubusercontent.com/11046087/103225185-784a5400-493a-11eb-9d69-af1fad06dae5.png)

And click this in the debug mode in the browser,so that you could see requests in the network. And check that you have the correct type "STEP" and ignore_analyzer is set to false ?
<img width="1197" alt="Screen Shot 2020-12-28 at 18 21 56" src="https://user-images.githubusercontent.com/11046087/103225165-6b2d6500-493a-11eb-99b1-182c32ee6e93.png">

**Comment by AndreiSomovTR** [comment] 2020-12-29 08:13
> @AndreiSomovTR could you also share the log, which is in the test item you are sending to Report portal? Thank you in advance.

sorry, could you please clarify what kind of logs you would like to get at this point?

**Comment by AndreiSomovTR** [comment] 2020-12-29 08:16
So, I clicked here: 
![image](https://user-images.githubusercontent.com/60747505/103269446-f0f6f200-49c6-11eb-9420-ed9eb17ef5bd.png)
and have gotten this: 
![image](https://user-images.githubusercontent.com/60747505/103269585-31567000-49c7-11eb-8706-56bd99114b51.png)

**Comment by MariyaIvanina** [comment] 2020-12-29 08:34
@AndreiSomovTR I mean logs from your tests, which you are sending into Report portal. And you can see those logs in the log view in the test item. For example, like this. And you need to use the slider to show only logs that are error or fatal. And then I could say whether your logs are ok for auto-analysis. Only error and fatal logs are used in the Auto-analysis, so if you don't have logs of a such type, then analysis won't be run for you.
![image](https://user-images.githubusercontent.com/11046087/103270680-93b07000-49c9-11eb-829d-abf93ac44e93.png)

**Comment by AndreiSomovTR** [comment] 2020-12-29 08:46
but when I clicked here:
![image](https://user-images.githubusercontent.com/60747505/103271417-46cd9900-49cb-11eb-9598-c61f4689c9a2.png)
and open item json:
type: "TEST"
ignoreAnalyzer: false

**Comment by AndreiSomovTR** [comment] 2020-12-29 08:50
> @AndreiSomovTR I mean logs from your tests, which you are sending into Report portal. And you can see those logs in the log view in the test item. For example, like this. And you need to use the slider to show only logs that are error or fatal. And then I could say whether your logs are ok for auto-analysis. Only error and fatal logs are used in the Auto-analysis, so if you don't have logs of a such type, then analysis won't be run for you.
> ![image](https://user-images.githubusercontent.com/11046087/103270680-93b07000-49c9-11eb-829d-abf93ac44e93.png)

got it, thanks. so, here my logs:
![image](https://user-images.githubusercontent.com/60747505/103271692-f60a7000-49cb-11eb-9e98-8ced2e177d9c.png)
![image](https://user-images.githubusercontent.com/60747505/103271710-0589b900-49cc-11eb-9f6b-37b30c994c4f.png)

**Comment by MariyaIvanina** [comment] 2020-12-29 10:41
@AndreiSomovTR We've understood that the problem is in your sending logs into Report portal, as far as type: "TEST", logs from such test items are not sent to the analyzer. The type should be "STEP". @pbortnik could you give a hint how this type should be set up on the AndreiSomovTR's side?

**Comment by evjlobanova** [comment] 2021-01-14 08:47
*Resolution:*

If you meet issues with not working analyzer - please check that you report the last items in structure with type STEP (via agents).  
Items with type SUITE and TEST are accounted for by the system as parent items and are not added to the Analyzer base.

**Closed by evjlobanova** 2021-01-14 08:47 UTC
Labels: Waiting Info From Requestor

**Comment by AndreiSomovTR** [comment] 2021-01-25 19:19
we had method: buildStartTestItemRq with 'rq.setType("TEST");' within. 
I changed 'rq.setType("TEST");' -> 'rq.setType("STEP");' and analyzer works fine
