### ISSUE TITLE
FR: Java Client -  Report to existing launch (aka RE-RUN for launches)

### ISSUE THREAD

**Issue by ulmanA** [reportportal/reportportal#296] opened 2017-12-13 14:41 UTC
Hi,
Please add ability to report to existing launch in the java client (I am using the TestNG agent)
Use case:
We have a project that separate it's nightly regression to few Jenkins jobs that run parallel
so it 2 executions but in the same context of "nightly regression" and we will want to see them at the same launch without coupling to the execution way (1 jvm or few).

In this case for example I want to have 1 job that will create new launch(using REST call), trigger the sub jobs parallel with the launch id as parameter and after all the jobs done it will close the launch(using REST call).
it can be passed to the client via system property rp.launchid for example.

Thanks!

**Comment by evjlobanova** [comment] 2018-01-15 15:07
@ulmanA we are planing to add a new feature `Rerun` (the description of Rerun you can find here #264 ). This functionality gives possibility to report result right in a existing launch. Does `Rerun` cover your needs?

**Comment by ulmanA** [comment] 2018-01-16 08:38
@evjlobanova  I don't think so.
Rerun will override previous results and will tagged the launch as rerun.
This use case is different.
I want to run few suites each have different Jenkins job. And all those suites will reports to the same launch.

**Comment by ulmanA** [comment] 2018-01-16 08:38
Closed by mistake.

**Comment by DzmitryHumianiuk** [comment] 2018-03-14 14:16
@ulmanA Do not confuse `Re-run` and `Re-try`

Re-try is for test cases. Basically if you run test case twice - it will be replaced within one launch.
And marked as Re-tried.

Re-run is for launches.
It will work as **Deep Merge**. Basically it will add structure of newly executed launch into existing launch.
If those launches will have Suites with same name, then original suite will be used on original run.
If new launch will have new suite, then new suite will be created in original launch.

If test case will be the same (equal parents, equal name, equal params   or   just the same uniqueID ) then it will be replaced as re-try.
Otherwise, it will be added as a new test case.


Does it fit you expectations?

**Comment by ulmanA** [comment] 2018-03-18 08:37
Re-Run is very like what I need
But,
- I don't want the tag 're-run' to be shown in case I just reporting more tests
- I don't want to override/merge suites. If suites has the same name, I expect a sequential number in the name. for example: 2 execution that report to the same launch, where every execution have the same suites, and the diff is that every execution test my application with different web browser.
The tester will be responsible to add tags or descriptions with the web-browser name
- I need ability to tell the agent to report to existing launch (give it a launchId for example)

**Closed** 2018-05-11 10:50 UTC
Labels: duplicate, feature request

**Comment by DzmitryHumianiuk** [comment] 2018-07-17 15:59
reference as duplicate of #363
