### ISSUE TITLE
Unable to setup email server notifications in 5.8.0

### ISSUE THREAD

**Issue by mkothuru** [reportportal/reportportal#2055] opened 2023-07-06 06:16 UTC
**Describe the bug**
... Unable to add integration in email server notification in 5.8.0. The host and port number used are valid as the same details was used in aolder version of report portal(5.7.4) and it seemed to work.

**Expected behavior**
Expected Behaviour: Members of the project should be receive an email for launches.
...

**Screenshots**
If applicable

**Versions:**
 - OS, Browser
 - Version of RP [find it under Login form, copy as is]

**Comment by babantax** [comment] 2023-10-03 09:20
Facing same issue. Working in 5.7.4 but not >5.8

**Comment by alena-babrova** [comment] 2024-01-23 08:48
Hello @mkothuru, @babantax,

Could you tell me please if the issue is still relevant? 
If yes, what SMTP providers do you use? Did you try with different providers? 
Maybe you can provide server logs with error details?

**Comment by alena-babrova** [comment] 2024-02-19 16:08
Dear @mkothuru, @babantax,

As we haven't received a reply from you, we'll close the issue for now.
Just in case you still have the issue, please, do not hesitate to reopen the ticket with details.

**Closed by alena-babrova** 2024-02-19 16:08 UTC
Labels: bug
