### ISSUE TITLE
Installed Jira plug - Dont see Attachments and assign info in Jira 

### ISSUE THREAD

**Issue by satish9126** [reportportal/reportportal#1534] opened 2021-09-23 16:12 UTC
Hello I Installed Jira plug and able to connect to Jira from Report portal and post bug into Jira but dont see Attachments and assign info in Jira which is selected in RP. Is their any setting we have to do on Jira to accept them from RP ?

Thanks in advance.

**Comment by evjlobanova** [comment] 2021-10-06 12:36
Could you provide more details, screens, steps for reproducing?

**Comment by Shivin89** [comment] 2021-12-02 18:08
@evjlobanova 

I am facing the same issue (attachments are not in the Jira bug)

Details RP :
Current version:API Service: 5.4.0;Index Service: 5.0.10;Authorization Service: 5.4.0;Service UI: 5.4.0;

![image](https://user-images.githubusercontent.com/22401226/144478559-8ddb7eb8-1501-4442-a5c9-b2ebe17c0222.png)

![image](https://user-images.githubusercontent.com/22401226/144478718-036567b9-2763-4763-bba8-882a74781c50.png)

![image](https://user-images.githubusercontent.com/22401226/144478818-174812e8-9284-438b-817c-aa1dd681be0f.png)

**Comment by evjlobanova** [comment] 2021-12-13 19:57
@Shivin89 do you have nested steps in the "Finance with Basic Test"?

**Comment by Shivin89** [comment] 2021-12-13 20:16
@evjlobanova  Yes, I am using the Karate UI framework with Report Portal and I am calling different features within this Finance with Basic Test" feature file .

Like Calling Login feature  (Different feature file with steps)
And doing some steps

**Comment by evjlobanova** [comment] 2021-12-13 21:17
The problem is that attachments from nested steps are not added to Jira. We will fix it in the version 5.7

**Comment by evjlobanova** [comment] 2021-12-14 19:38
Issue has been fixed in the version 5.7

**Closed by evjlobanova** 2021-12-14 19:38 UTC
Labels: help wanted, resolution:fixed
