### ISSUE TITLE
Demo report portal is not accessible via github account integration

### ISSUE THREAD

**Issue by podoliuk** [reportportal/reportportal#818] opened 2020-02-11 09:07 UTC
Hi,
demo report portal is not accessible via github account integration - receiving 403

<img width="1426" alt="rp_error" src="https://user-images.githubusercontent.com/60887082/74222940-41396880-4cbe-11ea-81bf-f64f0d203408.png">

**Comment by evjlobanova** [comment] 2020-02-18 12:48
Could you please check one more time, I have checked, and everything is good.
I close this issue, feel free to reopen it, in case it still reproduce

**Closed by evjlobanova** 2020-02-18 12:48 UTC
Labels: help wanted

**Comment by pjn2work** [comment] 2020-12-02 13:43
The same happens to me.
Already tried in 2 browsers (also incognito mode) and 2 different GitHub accounts and always get 403.
On GitHub it appears the authorization for ReportPortal

**Comment by evjlobanova** [comment] 2020-12-03 11:44
I have checked it works for me.
Please provide steps for reproducing
