### ISSUE TITLE
BDD : Scenario Outline - Duplicating Launch name in Timeline

### ISSUE THREAD

**Issue by priyankachaturvedi30** [reportportal/reportportal#1407] opened 2021-05-17 14:54 UTC
There is an issue in the timeline of the steps for the scenario outline in RP dashboard. Launch names are repeating in the timeline. 
![image](https://user-images.githubusercontent.com/50797731/118509616-d347e080-b74d-11eb-9837-82019455e4c2.png)

Consider a feature file having one such structure:
Scenario Outline: Taking Exports on cash Ladder for different balance types
        And I navigate to home page
        And I go to the cash ladder page
        And I sort ascending on transactionGrid for "Trans Ref No"
        And I verify transaction csv for "<testCaseNo>"
        Examples:
        | testCaseNo         | date       | perspectives              | perspectiveToBeSelected   | page |
        | CCY_T_R1_C1        | 11-05-2015 | Currency                  | GBP                       | 1    |
        | CCY_T_R3_C5        | 15-05-2015 | Currency                  | SGD                       | 1    |
        | CCY_T_R1_C27       | 06-06-2015 | Currency                  | GBP                       | 1    |
        | CCY_LE_T_R1_C2     | 11-05-2015 | Currency;Legal Entity     | GBPHBLEUK                 | 1    |
        | CCY_LE_T_R5_C27    | 05-06-2015 | Currency;Legal Entity     | USDHBLEUS                 | 1    |
        | CCY_LE_T_R3_C7     | 16-05-2015 | Currency;Legal Entity     | INRHBLEIN                 | 1    |
        | CCY_AC_T_R1_C2     | 11-05-2015 | Currency;Account          | GBPBSMAC1                 | 1    |
Now, for each failure that occurs in example scenario a new launch name replication happens. Is this the expected behaviour ? We are also ensuring that each scenario name is unique but still we see repetition of launch name in timeline.

**Comment by HardNorth** [comment] 2021-05-18 08:41
@pbortnik, @miracle8484, @DzmitryHumianiuk Do we build timeline by an item name or by a TC ID?

**Comment by anshu781126** [comment] 2021-05-20 06:34
Hi Team, Any update on this ?

**Comment by anshu781126** [comment] 2021-05-20 06:39
just if you can let us know that how timelines are build.

**Comment by evjlobanova** [comment] 2021-05-20 07:27
By TestCaseID

**Comment by HardNorth** [comment] 2021-05-20 08:31
@anshu781126 Which agent and agent version do you use?

**Comment by anshu781126** [comment] 2021-05-20 09:11
https://github.com/reportportal/client-java

@HardNorth

**Comment by HardNorth** [comment] 2021-05-20 09:58
@anshu781126 Once again, please specify your Agent and its version, not a link to our repository. Even if you created your own agent based on our client there are 20 different releases on Maven Central.

**Comment by bjuric** [comment] 2021-05-20 10:52
I had a look at this also, and turns out that the `codeRef` passed to report portal for each recurring scenario in the outline was the same. Appending the table/row co-ordinates to the codeRef solved the issue. This works since the java client auto generates the test case id based on the codeRef. 

A better solution however would be to nominate a column in each example data row as the "TestCaseId" and pass that value to RP directly instead of relying on auto-generation in java client.

**Comment by evjlobanova** [comment] 2021-05-20 16:35
You can choose an approach which test case id should be reported to ReportPortal 
https://reportportal.io/docs/Test-case-ID

You can report test case id via agents. All details you can find in the dev guide https://github.com/reportportal/client-java/wiki/Test-case-ID

If the test execution has test parameters, a test case ID will be generated on the base of:

Test case id in ReportPortal = reported 'TestCaseID + all test parameters

In case a user doesn't report tests with Test Case ID, the system generates it automatically:

1.) Auto-generation based on 'Code reference' and 'Parameters' If users do not report test case ID, it is generated automatically on the base of:
Test case id in ReportPortal = 'Code reference' + all test parameters

2.) Automatically based on Test Execution name, All parents name, Parameters If users do not report Test Case ID and Code reference, then test case ID is generated on the base of:
Test case id in ReportPortal = Test Case Name + All parents Name (except Launch name) + All parameters

**Comment by HardNorth** [comment] 2021-05-20 19:01
@evjlobanova I believe this is not actually what the author means. By default agents report either a feature file reference (path/to/Feature.feature:10; where '10' is a line number in an example table) either a java canonical class name + params (com.github.test.TestClass[param1, param2]). The second case happens wen a user use `StepReporter` reporter. 

The issue might be in a case when in different Example rows there are duplicate parameter values and when a Scenario Outline contains steps without parameters. Then it's possible that some steps will have the same Test Case ID. So posting a class reference + parameters as a Test Case ID wasn't such a good idea.

But what was done cannot be undone in our case, because if we change TC ID logic we will break history for those users who do not see an issue in this. Probably we can change it in next major version, E.G. in version 6 with an option to use old logic.

**Comment by bjuric** [comment] 2021-05-20 22:18
The reason why adding table and row coordinates to the codeRef is necessary in this is because it involves the execution of a Scenario Outline and the way they work. The body template of the outline is executed for each row in the examples table. So what happens is that the steps are replicated for each record, data values substituted, and then executed and sent to report portal. So it was necessary to add table and row indexes [1][1] for table 1 row 1, [1][2] for table 1 row 2, [1][3] (note outlines can have multiple examples each having their own table, so both table and row indexes are required) ..to the codeRef sent to report portal via the java client to make it unique for each execution of steps in the outline template.

Thank you @evjlobanova for passing on the details of how auto generated test case IDs work. This helped resolve the problem. Also I could not find a reference to point (2) that you mention in the dev guide link you provided, only point (1).

@HardNorth, I agree that the codeRef + parameters combination could be hit and miss.  Adding the table and row indexes to the codeRef helped in this instance, since it guarantees uniqueness. Alternatively I suspect that adding these indexes to the parameters instead would also  provide that same uniqueness.

**Comment by bjuric** [comment] 2021-05-30 00:02
Root cause of this issue was that the row data in the examples tables was not being passed to report portal as parameters for each expanded scenario. Hence it was relying purely on codeRef alone. CodeRef+Parameters fixes it. However if line numbers in the codeRef change due to changes made in the spec, then the history is de-associated since a different test case ID is auto-generated . We've come up with an alternate strategy for generating test case IDs based on approach (2) mentioned above by @evjlobanova that doesn't rely on line numbers.

**Comment by evjlobanova** [comment] 2021-06-02 07:12
I guess the first approach should work for you: explicit Test Case ID + param
For instance you can use test case id from your Test NAmagement System
![image](https://user-images.githubusercontent.com/30413511/120439127-05a13280-c337-11eb-9655-dd2284e3482e.png)

**Comment by anshu781126** [comment] 2021-06-02 09:08
We have opted for step with its hierarchy[occurrence#] + params as the basis to create testcaseID.

Marking this as closed.

**Closed** 2021-06-02 12:53 UTC
Labels: help wanted
