### ISSUE TITLE
report portal sso config

### ISSUE THREAD

**Issue by hamzarezgui** [reportportal/reportportal#1902] opened 2022-12-20 10:19 UTC
Hello,

How can we generate the metadata xml file for sso config please ?
Thank you for the help !

Regards

**Comment by DzmitryHumianiuk** [comment] 2022-12-22 18:49
@hamzarezgui i guess the sso tool should generate this, not the RP.

**Comment by alena-babrova** [comment] 2023-05-05 10:58
Hello @hamzarezgui,
Could you please tell me if the issue is still relevant for you? Have you managed to configure?

**Comment by alena-babrova** [comment] 2023-05-29 14:59
Dear @hamzarezgui,
As we haven't received a reply from you, we'll close the issue for now.
Just in case you still have the issue, please, do not hesitate to get in touch.

**Closed by alena-babrova** 2023-05-29 14:59 UTC
Labels: help wanted
