### ISSUE TITLE
Skipped scenarios are automatically changed to failed

### ISSUE THREAD

**Issue by monk-ada** [reportportal/reportportal#2230] opened 2024-02-12 15:43 UTC
Have someone noticed that sometimes skipped scenarios are changed to failed without any obvious reason?
In our framework we have rp.skipped.issue set to false however some of skipped scenarios are automatically changed to failed.
We skip scenarios that don't meet an enviroment requirements by throwing new org.testng.SkipException
The history of action tab in such cases indicates that the scenario status was changed by the user 
![image](https://github.com/reportportal/reportportal/assets/159798553/90fdd237-d617-48bf-9354-8c53511149ef)

When the issue occurs we always change status failed -> skipped manually but we won't spend time on analyzing such cases.
Has anyone noticed such an issue?
Do you have any idea or suspicions about the root cause?
ReporPortal 5.7.2

**Expected behavior**
Skipped scenarios remain skipped when reported to ReportPortal

**Versions:**
 - Version of RP 5.7.2

**Comment by alena-babrova** [comment] 2024-03-13 18:01
Hello @Admon85,

As far as I see from the screenshot provided, someone "qa_user" changed status from SKIPPED to FAILED initially. Why do you think it was made "automatically"?

Maybe you have steps to reproduce to confirm the behavior you described?

**Comment by Admon85** [comment] 2024-03-15 14:53
We use "qa_user" credentials(access token) to perform our automated tests. qa user is not used by anyone to change defect type during report analysis. 
I don't have steps to reproduce as it happens randomly.

**Comment by HardNorth** [comment] 2024-03-15 16:27
@Admon85, no, looks like I found the root cause, finally. I opened a bug in internal system, it should be fixed in the next release, if nothing happens.

**Comment by alena-babrova** [comment] 2024-04-30 08:11
Dear @monk-ada,

We have fixed the bug and released it in 24.1.1 version (api-service 5.11.1 - https://github.com/reportportal/service-api/releases/tag/5.11.1).
Please, try it out.

**Closed by alena-babrova** 2024-04-30 08:11 UTC
Labels: bug, Check: BackEnd
