### ISSUE TITLE
elastic search restarts all the time in 4.3

### ISSUE THREAD

**Issue by marklz** [reportportal/reportportal#501] opened 2018-10-18 11:14 UTC
**Describe the bug**
elastic search container restarts all the time, "docker logs" show Java exception

**Expected behavior**
elastic search container does not restart

**Screenshots**
```
[2018-10-17T11:19:50,894][INFO ][o.e.n.Node               ] [] initializing ...
[2018-10-17T11:19:50,911][WARN ][o.e.b.ElasticsearchUncaughtExceptionHandler] [] uncaught exception in thread [main]
org.elasticsearch.bootstrap.StartupException: java.lang.IllegalStateException: Failed to create node environment
        at org.elasticsearch.bootstrap.Elasticsearch.init(Elasticsearch.java:125) ~[elasticsearch-6.1.1.jar:6.1.1]
        at org.elasticsearch.bootstrap.Elasticsearch.execute(Elasticsearch.java:112) ~[elasticsearch-6.1.1.jar:6.1.1]
        at org.elasticsearch.cli.EnvironmentAwareCommand.execute(EnvironmentAwareCommand.java:86) ~[elasticsearch-6.1.1.jar:6.1.1]
        at org.elasticsearch.cli.Command.mainWithoutErrorHandling(Command.java:124) ~[elasticsearch-cli-6.1.1.jar:6.1.1]
        at org.elasticsearch.cli.Command.main(Command.java:90) ~[elasticsearch-cli-6.1.1.jar:6.1.1]
        at org.elasticsearch.bootstrap.Elasticsearch.main(Elasticsearch.java:92) ~[elasticsearch-6.1.1.jar:6.1.1]
        at org.elasticsearch.bootstrap.Elasticsearch.main(Elasticsearch.java:85) ~[elasticsearch-6.1.1.jar:6.1.1]
Caused by: java.lang.IllegalStateException: Failed to create node environment
        at org.elasticsearch.node.Node.<init>(Node.java:266) ~[elasticsearch-6.1.1.jar:6.1.1]
        at org.elasticsearch.node.Node.<init>(Node.java:245) ~[elasticsearch-6.1.1.jar:6.1.1]
        at org.elasticsearch.bootstrap.Bootstrap$5.<init>(Bootstrap.java:212) ~[elasticsearch-6.1.1.jar:6.1.1]
        at org.elasticsearch.bootstrap.Bootstrap.setup(Bootstrap.java:212) ~[elasticsearch-6.1.1.jar:6.1.1]
        at org.elasticsearch.bootstrap.Bootstrap.init(Bootstrap.java:322) ~[elasticsearch-6.1.1.jar:6.1.1]
        at org.elasticsearch.bootstrap.Elasticsearch.init(Elasticsearch.java:121) ~[elasticsearch-6.1.1.jar:6.1.1]
        ... 6 more
Caused by: java.nio.file.AccessDeniedException: /usr/share/elasticsearch/data/nodes
        at sun.nio.fs.UnixException.translateToIOException(UnixException.java:84) ~[?:?]
        at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:102) ~[?:?]
        at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:107) ~[?:?]
        at sun.nio.fs.UnixFileSystemProvider.createDirectory(UnixFileSystemProvider.java:384) ~[?:?]
        at java.nio.file.Files.createDirectory(Files.java:674) ~[?:1.8.0_151]
        at java.nio.file.Files.createAndCheckIsDirectory(Files.java:781) ~[?:1.8.0_151]
        at java.nio.file.Files.createDirectories(Files.java:767) ~[?:1.8.0_151]
        at org.elasticsearch.env.NodeEnvironment.<init>(NodeEnvironment.java:204) ~[elasticsearch-6.1.1.jar:6.1.1]
        at org.elasticsearch.node.Node.<init>(Node.java:263) ~[elasticsearch-6.1.1.jar:6.1.1]
        at org.elasticsearch.node.Node.<init>(Node.java:245) ~[elasticsearch-6.1.1.jar:6.1.1]
        at org.elasticsearch.bootstrap.Bootstrap$5.<init>(Bootstrap.java:212) ~[elasticsearch-6.1.1.jar:6.1.1]
        at org.elasticsearch.bootstrap.Bootstrap.setup(Bootstrap.java:212) ~[elasticsearch-6.1.1.jar:6.1.1]
        at org.elasticsearch.bootstrap.Bootstrap.init(Bootstrap.java:322) ~[elasticsearch-6.1.1.jar:6.1.1]
        at org.elasticsearch.bootstrap.Elasticsearch.init(Elasticsearch.java:121) ~[elasticsearch-6.1.1.jar:6.1.1]
        ... 6 more
[2018-10-17T11:19:56,043][INFO ][o.e.n.Node               ] [] initializing ...
[2018-10-17T11:19:56,076][WARN ][o.e.b.ElasticsearchUncaughtExceptionHandler] [] uncaught exception in thread [main]
org.elasticsearch.bootstrap.StartupException: java.lang.IllegalStateException: Failed to create node environment
        at org.elasticsearch.bootstrap.Elasticsearch.init(Elasticsearch.java:125) ~[elasticsearch-6.1.1.jar:6.1.1]
        at org.elasticsearch.bootstrap.Elasticsearch.execute(Elasticsearch.java:112) ~[elasticsearch-6.1.1.jar:6.1.1]
        at org.elasticsearch.cli.EnvironmentAwareCommand.execute(EnvironmentAwareCommand.java:86) ~[elasticsearch-6.1.1.jar:6.1.1]
        at org.elasticsearch.cli.Command.mainWithoutErrorHandling(Command.java:124) ~[elasticsearch-cli-6.1.1.jar:6.1.1]
        at org.elasticsearch.cli.Command.main(Command.java:90) ~[elasticsearch-cli-6.1.1.jar:6.1.1]
        at org.elasticsearch.bootstrap.Elasticsearch.main(Elasticsearch.java:92) ~[elasticsearch-6.1.1.jar:6.1.1]
        at org.elasticsearch.bootstrap.Elasticsearch.main(Elasticsearch.java:85) ~[elasticsearch-6.1.1.jar:6.1.1]
Caused by: java.lang.IllegalStateException: Failed to create node environment
        at org.elasticsearch.node.Node.<init>(Node.java:266) ~[elasticsearch-6.1.1.jar:6.1.1]
        at org.elasticsearch.node.Node.<init>(Node.java:245) ~[elasticsearch-6.1.1.jar:6.1.1]
        at org.elasticsearch.bootstrap.Bootstrap$5.<init>(Bootstrap.java:212) ~[elasticsearch-6.1.1.jar:6.1.1]
        at org.elasticsearch.bootstrap.Bootstrap.setup(Bootstrap.java:212) ~[elasticsearch-6.1.1.jar:6.1.1]
        at org.elasticsearch.bootstrap.Bootstrap.init(Bootstrap.java:322) ~[elasticsearch-6.1.1.jar:6.1.1]
        at org.elasticsearch.bootstrap.Elasticsearch.init(Elasticsearch.java:121) ~[elasticsearch-6.1.1.jar:6.1.1]
        ... 6 more
Caused by: java.nio.file.AccessDeniedException: /usr/share/elasticsearch/data/nodes
        at sun.nio.fs.UnixException.translateToIOException(UnixException.java:84) ~[?:?]
        at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:102) ~[?:?]
        at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:107) ~[?:?]
        at sun.nio.fs.UnixFileSystemProvider.createDirectory(UnixFileSystemProvider.java:384) ~[?:?]
        at java.nio.file.Files.createDirectory(Files.java:674) ~[?:1.8.0_151]
        at java.nio.file.Files.createAndCheckIsDirectory(Files.java:781) ~[?:1.8.0_151]
        at java.nio.file.Files.createDirectories(Files.java:767) ~[?:1.8.0_151]
        at org.elasticsearch.env.NodeEnvironment.<init>(NodeEnvironment.java:204) ~[elasticsearch-6.1.1.jar:6.1.1]
        at org.elasticsearch.node.Node.<init>(Node.java:263) ~[elasticsearch-6.1.1.jar:6.1.1]
        at org.elasticsearch.node.Node.<init>(Node.java:245) ~[elasticsearch-6.1.1.jar:6.1.1]
        at org.elasticsearch.bootstrap.Bootstrap$5.<init>(Bootstrap.java:212) ~[elasticsearch-6.1.1.jar:6.1.1]
        at org.elasticsearch.bootstrap.Bootstrap.setup(Bootstrap.java:212) ~[elasticsearch-6.1.1.jar:6.1.1]
        at org.elasticsearch.bootstrap.Bootstrap.init(Bootstrap.java:322) ~[elasticsearch-6.1.1.jar:6.1.1]
        at org.elasticsearch.bootstrap.Elasticsearch.init(Elasticsearch.java:121) ~[elasticsearch-6.1.1.jar:6.1.1]
        ... 6 more
[2018-10-17T11:20:01,801][INFO ][o.e.n.Node               ] [] initializing ...
[2018-10-17T11:20:01,875][WARN ][o.e.b.ElasticsearchUncaughtExceptionHandler] [] uncaught exception in thread [main]
org.elasticsearch.bootstrap.StartupException: java.lang.IllegalStateException: Failed to create node environment
        at org.elasticsearch.bootstrap.Elasticsearch.init(Elasticsearch.java:125) ~[elasticsearch-6.1.1.jar:6.1.1]
        at org.elasticsearch.bootstrap.Elasticsearch.execute(Elasticsearch.java:112) ~[elasticsearch-6.1.1.jar:6.1.1]
        at org.elasticsearch.cli.EnvironmentAwareCommand.execute(EnvironmentAwareCommand.java:86) ~[elasticsearch-6.1.1.jar:6.1.1]
        at org.elasticsearch.cli.Command.mainWithoutErrorHandling(Command.java:124) ~[elasticsearch-cli-6.1.1.jar:6.1.1]
        at org.elasticsearch.cli.Command.main(Command.java:90) ~[elasticsearch-cli-6.1.1.jar:6.1.1]
        at org.elasticsearch.bootstrap.Elasticsearch.main(Elasticsearch.java:92) ~[elasticsearch-6.1.1.jar:6.1.1]
        at org.elasticsearch.bootstrap.Elasticsearch.main(Elasticsearch.java:85) ~[elasticsearch-6.1.1.jar:6.1.1]
Caused by: java.lang.IllegalStateException: Failed to create node environment
        at org.elasticsearch.node.Node.<init>(Node.java:266) ~[elasticsearch-6.1.1.jar:6.1.1]
        at org.elasticsearch.node.Node.<init>(Node.java:245) ~[elasticsearch-6.1.1.jar:6.1.1]
        at org.elasticsearch.bootstrap.Bootstrap$5.<init>(Bootstrap.java:212) ~[elasticsearch-6.1.1.jar:6.1.1]
        at org.elasticsearch.bootstrap.Bootstrap.setup(Bootstrap.java:212) ~[elasticsearch-6.1.1.jar:6.1.1]
        at org.elasticsearch.bootstrap.Bootstrap.init(Bootstrap.java:322) ~[elasticsearch-6.1.1.jar:6.1.1]
        at org.elasticsearch.bootstrap.Elasticsearch.init(Elasticsearch.java:121) ~[elasticsearch-6.1.1.jar:6.1.1]
        ... 6 more
Caused by: java.nio.file.AccessDeniedException: /usr/share/elasticsearch/data/nodes
        at sun.nio.fs.UnixException.translateToIOException(UnixException.java:84) ~[?:?]
        at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:102) ~[?:?]
        at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:107) ~[?:?]
        at sun.nio.fs.UnixFileSystemProvider.createDirectory(UnixFileSystemProvider.java:384) ~[?:?]
        at java.nio.file.Files.createDirectory(Files.java:674) ~[?:1.8.0_151]
        at java.nio.file.Files.createAndCheckIsDirectory(Files.java:781) ~[?:1.8.0_151]
        at java.nio.file.Files.createDirectories(Files.java:767) ~[?:1.8.0_151]
        at org.elasticsearch.env.NodeEnvironment.<init>(NodeEnvironment.java:204) ~[elasticsearch-6.1.1.jar:6.1.1]
        at org.elasticsearch.node.Node.<init>(Node.java:263) ~[elasticsearch-6.1.1.jar:6.1.1]
        at org.elasticsearch.node.Node.<init>(Node.java:245) ~[elasticsearch-6.1.1.jar:6.1.1]
        at org.elasticsearch.bootstrap.Bootstrap$5.<init>(Bootstrap.java:212) ~[elasticsearch-6.1.1.jar:6.1.1]
        at org.elasticsearch.bootstrap.Bootstrap.setup(Bootstrap.java:212) ~[elasticsearch-6.1.1.jar:6.1.1]
        at org.elasticsearch.bootstrap.Bootstrap.init(Bootstrap.java:322) ~[elasticsearch-6.1.1.jar:6.1.1]
```

**Versions:**
* Ubuntu 16
* RP 4.3, though for some reason service authorization is 4.2
* Docker version 17.09.1-ce, build 19e2cf6

```
idirect@ta-reports:~/install$ docker ps
CONTAINER ID        IMAGE                                                     COMMAND                  CREATED             STATUS                          PORTS                                                                      NAMES
b8854cec4fb7        reportportal/service-analyzer:4.3.0                       "/service-analyzer"      24 hours ago        Up 24 hours                     8080/tcp                                                                   reportportal_analyzer_1
4beaf6c0fdb4        reportportal/service-index:4.2.0                          "/service-index"         24 hours ago        Up 24 hours                     8080/tcp                                                                   reportportal_index_1
4e0816dde45c        reportportal/service-api:4.3.0                            "/start.sh"              24 hours ago        Up 24 hours                     8080/tcp                                                                   reportportal_api_1
5f357ae1fe7c        consul:1.0.6                                              "docker-entrypoint..."   24 hours ago        Up 24 hours                     8300-8302/tcp, 8301-8302/udp, 8600/tcp, 8600/udp, 0.0.0.0:8500->8500/tcp   reportportal_registry_1
60cf9ad5165f        reportportal/service-authorization:4.2.0                  "/start.sh"              24 hours ago        Up 24 hours                     8080/tcp                                                                   reportportal_uat_1
5ee08e1d5269        reportportal/service-rally:4.3.0                          "/start.sh"              24 hours ago        Up 24 hours                     8080/tcp                                                                   reportportal_rally_1
07123381e203        reportportal/service-jira:4.3.0                           "/start.sh"              24 hours ago        Up 24 hours                     8080/tcp                                                                   reportportal_jira_1
04eaa59c31f2        mongo:3.4                                                 "docker-entrypoint..."   24 hours ago        Up 24 hours                     27017/tcp                                                                  reportportal_mongodb_1
c460a3454381        traefik:1.6.6                                             "/traefik --consul..."   24 hours ago        Up 24 hours                     80/tcp, 0.0.0.0:8080->8080/tcp                                             reportportal_gateway_1
73a405bd9d14        reportportal/service-ui:4.3.0                             "/service-ui"            24 hours ago        Up 24 hours                     8080/tcp                                                                   reportportal_ui_1
625ae6f30960        docker.elastic.co/elasticsearch/elasticsearch-oss:6.1.1   "/usr/local/bin/do..."   24 hours ago        Restarting (1) 26 seconds ago                                                                              reportportal_elasticsearch_1
```

**Comment by DzmitryHumianiuk** [comment] 2018-10-18 11:37
@marklz check steps in #500 
:)
similar issue

**Comment by marklz** [comment] 2018-10-18 11:45
@DzmitryHumianiuk - even manual workaround is acceptable, since constant restarts eat all CPU, and RP is now very slow...

**Comment by DzmitryHumianiuk** [comment] 2018-10-18 11:54
@marklz stop elastic container in docker. and reconfigure it

**Comment by avarabyeu** [comment] 2018-10-18 11:56
@marklz @DzmitryHumianiuk remove container, follow steps described in #500, then create container again. 
Closing as duplicate of #500

**Closed by avarabyeu** 2018-10-18 11:56 UTC
Labels: help wanted

**Comment by marklz** [comment] 2018-10-18 12:01
@avarabyeu - what specific steps?

**Comment by DzmitryHumianiuk** [comment] 2018-11-08 14:40
@marklz 
http://reportportal.io/docs/Issues-with-Analyzer:
You also might want to check official ES installation guide:
https://www.elastic.co/guide/en/elasticsearch/reference/5.4/docker.html

**Comment by sermolovich** [comment] 2019-06-04 12:05
Hello @DzmitryHumianiuk,
I have a similar issue with continuous restarting of elastic search container. I performed steps from http://reportportal.io/docs/Issues-with-Analyzer: but steps were not clear for me and looks like I was broken reportportal at all. I am not expert in Linux and docker. Who can help me with resolving of the issue or update installation guide and describe How to install RP from the beginning with correct configuration of elastic search for auto analysis.

**Comment by evjlobanova** [comment] 2019-06-04 13:20
@sermolovich could you please tell us with which step do you have troubles.

Have you performed this actions before `docker-compose -p reportportal up `?
![image](https://user-images.githubusercontent.com/30413511/58882283-8abfc580-86e4-11e9-80e3-7c8d5271c2e7.png)

**Comment by sermolovich** [comment] 2019-06-04 13:46
Hello @evjlobanova,

In the beginning I performed steps described here https://reportportal.io/docs/Deploy-ReportPortal
I didn't see 3 additional steps marked by red from your screen. Auto analysis doesn't work in that configuration. After that I navigated to http://reportportal.io/docs/Issues-with-Analyzer: and performed following steps: 

![2019-06-04_1636](https://user-images.githubusercontent.com/50665182/58883400-09b5fd80-86e7-11e9-8a08-20c4099db106.png)

Nothing was changed.

After that I begun to play with manual installation of elastic search and recreation of containers. as I am not expert here reportportal became broken. I don't remember exact steps I made.

**Comment by evjlobanova** [comment] 2019-06-04 14:10
@sermolovich 
Please send us:
screenshot of consul host:8500
docker-compose file
logs of analyzer container, ES, API

**Comment by sermolovich** [comment] 2019-06-04 15:01
@evjlobanova 
I installed report portal once again on the clean Linux OS, and I followed your correct instructions from the previous comments. But elastic search is again in restarting state.

![2019-06-04_1751](https://user-images.githubusercontent.com/50665182/58889360-746c3680-86f1-11e9-9baa-5183fe09bbb5.png)

Compose file from here without changes https://raw.githubusercontent.com/reportportal/reportportal/master/docker-compose.yml

# docker-compose -p reportportal logs --tail="all" analyzer
Attaching to reportportal_analyzer_1
analyzer_1       | 2019/06/04 14:42:01 Service Registered!
analyzer_1       | 2019/06/04 14:42:01 Starting on port 8080
analyzer_1       | [2019-06-04 14:42:09] ERROR Cannot send request to ES: Get http://elasticsearch:9200/_cluster/health: dial tcp 172.18.0.6:9200: connect: no route to host
analyzer_1       | [2019-06-04 14:42:14] ERROR Cannot send request to ES: Get http://elasticsearch:9200/_cluster/health: dial tcp 172.18.0.6:9200: connect: connection refused
analyzer_1       | [2019-06-04 14:42:19] ERROR Cannot send request to ES: Get http://elasticsearch:9200/_cluster/health: dial tcp 172.18.0.6:9200: connect: connection refused
analyzer_1       | [2019-06-04 14:42:25] ERROR Cannot send request to ES: Get http://elasticsearch:9200/_cluster/health: dial tcp 172.18.0.6:9200: connect: connection refused
analyzer_1       | [2019-06-04 14:42:30] ERROR Cannot send request to ES: Get http://elasticsearch:9200/_cluster/health: dial tcp 172.18.0.6:9200: connect: connection refused
analyzer_1       | [2019-06-04 14:42:38] ERROR Cannot send request to ES: Get http://elasticsearch:9200/_cluster/health: dial tcp 172.18.0.6:9200: connect: connection refused
analyzer_1       | [2019-06-04 14:42:43] ERROR Cannot send request to ES: Get http://elasticsearch:9200/_cluster/health: dial tcp 172.18.0.6:9200: connect: connection refused
analyzer_1       | [2019-06-04 14:42:51] ERROR Cannot send request to ES: Get http://elasticsearch:9200/_cluster/health: dial tcp 172.18.0.6:9200: connect: connection refused
analyzer_1       | [2019-06-04 14:42:56] ERROR Cannot send request to ES: Get http://elasticsearch:9200/_cluster/health: dial tcp 172.18.0.6:9200: connect: connection refused
analyzer_1       | [2019-06-04 14:43:01] ERROR Cannot send request to ES: Get http://elasticsearch:9200/_cluster/health: dial tcp 172.18.0.6:9200: connect: connection refused
analyzer_1       | [2019-06-04 14:43:06] ERROR Cannot send request to ES: Get http://elasticsearch:9200/_cluster/health: dial tcp 172.18.0.6:9200: connect: connection refused


# docker-compose -p reportportal logs --tail="all" elasticsearch
Attaching to reportportal_elasticsearch_1
elasticsearch_1  | [2019-06-04T14:42:04,882][INFO ][o.e.n.Node               ] [] initializing ...
elasticsearch_1  | [2019-06-04T14:42:05,075][WARN ][o.e.b.ElasticsearchUncaughtExceptionHandler] [] uncaught exception in thread [main]
elasticsearch_1  | org.elasticsearch.bootstrap.StartupException: java.lang.IllegalStateException: Failed to create node environment
elasticsearch_1  |      at org.elasticsearch.bootstrap.Elasticsearch.init(Elasticsearch.java:125) ~[elasticsearch-6.1.1.jar:6.1.1]
elasticsearch_1  |      at org.elasticsearch.bootstrap.Elasticsearch.execute(Elasticsearch.java:112) ~[elasticsearch-6.1.1.jar:6.1.1]
elasticsearch_1  |      at org.elasticsearch.cli.EnvironmentAwareCommand.execute(EnvironmentAwareCommand.java:86) ~[elasticsearch-6.1.1.jar:6.1.1]
elasticsearch_1  |      at org.elasticsearch.cli.Command.mainWithoutErrorHandling(Command.java:124) ~[elasticsearch-cli-6.1.1.jar:6.1.1]
elasticsearch_1  |      at org.elasticsearch.cli.Command.main(Command.java:90) ~[elasticsearch-cli-6.1.1.jar:6.1.1]
elasticsearch_1  |      at org.elasticsearch.bootstrap.Elasticsearch.main(Elasticsearch.java:92) ~[elasticsearch-6.1.1.jar:6.1.1]
elasticsearch_1  |      at org.elasticsearch.bootstrap.Elasticsearch.main(Elasticsearch.java:85) ~[elasticsearch-6.1.1.jar:6.1.1]
elasticsearch_1  | Caused by: java.lang.IllegalStateException: Failed to create node environment
elasticsearch_1  |      at org.elasticsearch.node.Node.<init>(Node.java:266) ~[elasticsearch-6.1.1.jar:6.1.1]
elasticsearch_1  |      at org.elasticsearch.node.Node.<init>(Node.java:245) ~[elasticsearch-6.1.1.jar:6.1.1]
elasticsearch_1  |      at org.elasticsearch.bootstrap.Bootstrap$5.<init>(Bootstrap.java:212) ~[elasticsearch-6.1.1.jar:6.1.1]
elasticsearch_1  |      at org.elasticsearch.bootstrap.Bootstrap.setup(Bootstrap.java:212) ~[elasticsearch-6.1.1.jar:6.1.1]
elasticsearch_1  |      at org.elasticsearch.bootstrap.Bootstrap.init(Bootstrap.java:322) ~[elasticsearch-6.1.1.jar:6.1.1]
elasticsearch_1  |      at org.elasticsearch.bootstrap.Elasticsearch.init(Elasticsearch.java:121) ~[elasticsearch-6.1.1.jar:6.1.1]
elasticsearch_1  |      ... 6 more
elasticsearch_1  | Caused by: java.nio.file.AccessDeniedException: /usr/share/elasticsearch/data/nodes
elasticsearch_1  |      at sun.nio.fs.UnixException.translateToIOException(UnixException.java:84) ~[?:?]


I don't know how to get API logs.

**Comment by evjlobanova** [comment] 2019-06-04 15:11
@Yumfriez Ivan, please help to find the problem

**Comment by sermolovich** [comment] 2019-06-06 15:31
Hello, @evjlobanova @Yanamz , do you have news for me?

**Comment by nicodn** [comment] 2020-03-10 21:12
What fixed it for me was:
`chown 1000:1000 data/elasticsearch/`

**Comment by bearclawz** [comment] 2020-05-12 09:24
> What fixed it for me was:
> `chown 1000:1000 data/elasticsearch/`

Yes! That did the trick for me on Ubuntu server in virtualbox

**Comment by rakesh-vardan** [comment] 2020-06-26 07:22
> What fixed it for me was:
> `chown 1000:1000 data/elasticsearch/`

Worked like a charm - thanks for sharing @nicodn
