### ISSUE TITLE
Deleted data is shown in widgets

### ISSUE THREAD

**Issue by ananthprasads** [reportportal/reportportal#1877] opened 2022-11-06 14:00 UTC
We have reportportal setup and initially we had configured data retention with delete "Never" (which comes with default configuration). Later we changed it 180 days. But in widgets I still see data of 8 months, if I click on that data which shows 8 months, it redirects to "No data found".

<img width="1236" alt="Screenshot 2022-11-06 at 6 22 09 PM" src="https://user-images.githubusercontent.com/53211163/200174878-aedda812-1c7a-4b8f-a9eb-95f2e2e324a7.png">

<img width="672" alt="Screenshot 2022-11-06 at 7 25 35 PM" src="https://user-images.githubusercontent.com/53211163/200174840-b41665bb-1538-45ad-935a-20b8ebedbbf6.png">

<img width="1558" alt="Screenshot 2022-11-06 at 7 27 02 PM" src="https://user-images.githubusercontent.com/53211163/200174903-d44b9517-a641-41c7-9144-eb2f6adc76ab.png">

**Comment by VolhaKarenko** [comment] 2022-11-22 14:23
Hi @ananthprasads,
As per your screenshot, it seems that the item still exists in a launch with the same name, but the link leads to the item from the last 32nd execution, where there is no such item- this is not a bug in this case, the widget should work like this, the clickable area redirects only to the items in the last launch
Regarding the wrong time in the 'last issue' column - the bug was fixed in version 5.7. Could you check, what version are you using?

**Comment by alena-babrova** [comment] 2023-09-19 08:41
Hello @ananthprasads,

Is the issue still relevant for you?

**Comment by alena-babrova** [comment] 2023-10-16 13:52
Dear @ananthprasads,
As we haven't received a reply from you, we'll close the issue for now.
Just in case you still have the issue, please, do not hesitate to get in touch.

**Closed by alena-babrova** 2023-10-16 13:52 UTC
Labels: help wanted, Waiting Info From Requestor
