### ISSUE TITLE
Sending reports to existing launches results in error

### ISSUE THREAD

**Issue by gupta-kartik** [reportportal/reportportal#2046] opened 2023-06-29 01:13 UTC
I think there might be a bug in the .net client when trying to write to the same launch.

According to the docs [here](https://github.com/reportportal/commons-net/blob/develop/docs/Configuration.md#reporting-experience), supplying the `uuid` of an existing launch to StartLaunchRequest should allow us to continue writing to the same launch:

```
var request = new StartLaunchRequest
                {
                    Name = launchName,
                    StartTime = DateTime.UtcNow,
                    Attributes = attributes,
                    Uuid = LaunchId
                };
```

The response however from Report Portal is:

```
--Inner Exception--
Response status code does not indicate success.
 InternalServerError (500) POST https://<reportportalinstance>/api/v1/<project>/launch
 {"errorCode":5000,"message":"Unclassified error [org.hibernate.exception.ConstraintViolationException: could not execute statement]"}
ReportPortal.Client.ServiceException
   at ReportPortal.Client.Resources.ServiceBaseResource.CheckSuccessStatusCode(HttpResponseMessage response, Stream stream)
   at ReportPortal.Client.Resources.ServiceBaseResource.SendHttpRequestAsync[TResponse](HttpMethod httpMethod, String uri, HttpContent httpContent, CancellationToken cancellationToken)
   at ReportPortal.Client.Resources.ServiceBaseResource.SendAsJsonAsync[TResponse,TRequest](HttpMethod httpMethod, String uri, TRequest request, CancellationToken cancellationToken)
   at ReportPortal.Client.Resources.ServiceLaunchResource.StartAsync(StartLaunchRequest request, CancellationToken cancellationToken)
````

We are using version 3.4.1 on ReportPortal.Shared. Is this a known issue? I am holding it wrong?

**Comment by DzmitryHumianiuk** [comment] 2023-07-28 21:38
@gupta-kartik @nvborisenko could guys please what is the bug here?

Sending request to StartLaunch for the started launch definitely may cause the issues.
The agree that expection handling should be better, and not cause 500 error.

The rerun for the launch should be used differently. 
https://reportportal.io/docs/dev-guides/RerunDevelopersGuide/

**Comment by DzmitryHumianiuk** [comment] 2023-07-28 21:40
@gupta-kartik  @nvborisenko , could you please explain what is expected here?

The issue seems to be with the request being sent to StartLaunch for a launch that's already started, which can definitely lead to error on server side.
However, I agree that the exception handling could be improved to prevent a 500 error. 

The rerun function for a launch should be used differently, as described in the Developer's Guide on Reruns for ReportPortal: https://reportportal.io/docs/dev-guides/RerunDevelopersGuide/ 

Could you provide more insights into this, guys?

**Comment by alena-babrova** [comment] 2024-01-23 05:19
Hello @gupta-kartik,

Could you tell me please if the issue is still relevant? 
If yes, maybe you can provide details of the requests you are trying to execute?
I've tried to reproduce it in some way the scenario using our API directly - everything is OK, even for not finished launches.

**Comment by alena-babrova** [comment] 2024-02-19 16:04
Dear @gupta-kartik,

As we haven't received a reply from you, we'll close the issue for now.
Just in case you still have the issue, please, do not hesitate to reopen the ticket with details.

**Closed by alena-babrova** 2024-02-19 16:04 UTC
Labels: bug
