### ISSUE TITLE
Unable to edit Dashboard Widgets configuration.

### ISSUE THREAD

**Issue by krishnaPedd** [reportportal/reportportal#1453] opened 2021-06-30 16:07 UTC
**Describe the bug**
I am trying to edit  Dashboard Widgets configuration but it is showing empty screen instead of displaying config page.
**Expected behavior**
I should see config page as soon as i clicked on edit [button.](url)

**Screenshots**
If applicable
<img width="1440" alt="Screenshot 2021-06-30 at 9 34 56 PM" src="https://user-images.githubusercontent.com/70696677/123994607-2965a000-d9eb-11eb-8fc8-3650cb5eadb9.png">

**Versions:**
 - OS:  Mac OS Catalina , Browser: Chrome -83
 - Version of RP [find it under Login form, copy as is]: 5.2.0

**Comment by evjlobanova** [comment] 2021-07-07 07:13
The latest version of Report Portal is 5.4.
Please update to the latest version, and try to reproduce bug

**Comment by krishnaPedd** [comment] 2021-07-20 15:29
Hi @evjlobanova,

I Upgraded Report portal to 5.4 version but still I am facing below issues with widgets.

1. I am trying to add new widget when I select widget like launches table, unique bug table upon clicking next step I am seeing blank screen with no data, PFA for the same.

I tried in both chrome and Firefox latest versions. Please check and and let me know on the issue.

<img width="1413" alt="Screen Shot 2021-07-20 at 11 20 02 AM" src="https://user-images.githubusercontent.com/70696677/126351204-2eedaf07-6464-4b4f-b70c-7ce394e05923.png">

Thanks,
Krishna

**Comment by evjlobanova** [comment] 2021-08-19 06:15
@VolhaKarenko could you please check

**Comment by VolhaKarenko** [comment] 2021-08-19 06:29
closed as a duplicate of https://github.com/reportportal/reportportal/issues/1481

**Closed by VolhaKarenko** 2021-08-19 06:29 UTC
Labels: bug, Check: Test
