### ISSUE TITLE
[v5]Can't create new filters due to UI error

### ISSUE THREAD

**Issue by cr-danzaitoun** [reportportal/reportportal#1486] opened 2021-07-31 05:38 UTC
**Describe the bug**
After long time of using RP with chrome I got to a point when ever I enter to the filters screen when trying to enter one of the filters I get an error:
**Error: Minified React error #185; visit https://reactjs.org/docs/error-decoder.html?invariant=185 for the full message or use the non-minified dev environment for full errors and additional helpful warnings.**
This is the full error : 
Error: Minified React error #185; visit https://reactjs.org/docs/error-decoder.html?invariant=185 for the full message or use the non-minified dev environment for full errors and additional helpful warnings.
    at gl (main.app.cd5218.js:398)
    at Object.enqueueSetState (main.app.cd5218.js:398)
    at t.y.setState (main.app.cd5218.js:390)
    at t.n.removeAccordion (main.app.cd5218.js:20)
    at t.n.handleAccordion (main.app.cd5218.js:20)
    at t.value (main.app.cd5218.js:20)
    at Pl (main.app.cd5218.js:398)
    at t.unstable_runWithPriority (main.app.cd5218.js:406)
    at Ka (main.app.cd5218.js:398)
    at Nl (main.app.cd5218.js:398)
![image](https://user-images.githubusercontent.com/54805002/127729911-c3a1d944-7315-4dc1-950e-f6c34f7fa672.png)
After that, I tried to work with edge and the same issue started after ~30 days of use. 
Now I working with firefox and all works again. 

**To Reproduce**
It happened only after a long time of using RP, very hard to reproduce. I can help by reproduce it on my laptop
**Expected behavior**
After this error occurred I can't work with RP. 

**Screenshots**

**Desktop (please complete the following information):**
 - OS: WIndows 1110
 - Browser chrome,edge
 - Version latest Version 92.0.4515.107 (Official Build) (64-bit)

**Comment by AmsterGet** [comment] 2021-08-13 12:08
Hello @cr-danzaitoun !
Are there any other errors in the console during this issue?
Are you trying to find a specific filter using the search bar?

**Comment by cr-danzaitoun** [comment] 2021-08-17 05:05
HI, 
Like I send in the previous message, the error showed in the chrome. and it happed to all filters type. 
currently can work with report portal on chrome or edge( i moved to firefox)
I can easily reproduce the issue, but only on my pc.

**Comment by alena-babrova** [comment] 2022-12-26 20:33
Hello @cr-danzaitou,
Could you please tell me if the issue is still relevant?
As we cannot reproduce it on our side.

**Comment by alena-babrova** [comment] 2023-01-18 13:29
As we haven't received a reply from you, we'll close the issue for now.
Just in case you still have the issue, please, do not hesitate to get in touch.

**Closed by alena-babrova** 2023-01-18 13:29 UTC
Labels: bug, Waiting Info From Requestor, Check: UI
