### ISSUE TITLE
Not able to login on Ubuntu machine (Services also not displayed in the ReportPortal UI)

### ISSUE THREAD

**Issue by srivastavajaideep** [reportportal/reportportal#755] opened 2019-11-20 04:35 UTC
Hi, 
I deployed ReportPortal on the windows machine (using docker images) and all components are running successfully (even elasticsearch and jira integration etc) but while trying to deploy it in the production environment, i am not able to even login. The services are not showing up in the UI of ReportPortal whereas the containers seem to be running fine. Please help. 

Thanks
Jaideep
 
<img width="938" alt="1" src="https://user-images.githubusercontent.com/15831063/69209541-9bbe9f00-0b7d-11ea-8b46-5b557e4fab16.PNG">
<img width="943" alt="2" src="https://user-images.githubusercontent.com/15831063/69209542-9bbe9f00-0b7d-11ea-8978-45ee5ed213cb.PNG">
<img width="619" alt="3" src="https://user-images.githubusercontent.com/15831063/69209543-9c573580-0b7d-11ea-9812-a1c9751fc9a0.PNG">

**Comment by evjlobanova** [comment] 2019-11-20 13:30
@srivastavajaideep Could you please tell us which version of ReportPortal you are trying to deploy?
@AlehB In case of future questions/answers, could you please support this request?

**Comment by AlehB** [comment] 2019-11-20 14:06
Hi @srivastavajaideep ,

**Comment by AlehB** [comment] 2019-11-20 14:09
Hi @srivastavajaideep ,

We propose to start with ReportPortal 5 instead of 4th since we are not supporting that version anymore.

Please find the link to RP5 Docker compose file below:
https://github.com/reportportal/reportportal/blob/master/docker-compose-v5.yml

Thank you,
Aleh

**Comment by srivastavajaideep** [comment] 2019-11-20 16:24
Thanks for the quick revert, i am using RP 4 version with the following configurations -  Analysis Service: 4.3.0; API Service: 4.3.0; Index Service: 4.2.0; Jira Service: 4.3.0; Rally Service: 4.3.0; Authorization Service: 4.2.0; Service UI: 4.3.0 and all were running smoothly on windows machine. I had tried sometime back with the latest versions and some services were getting restarted. Would try with the docker compose file provided by @AlehB  and revert back. Thanks

**Comment by srivastavajaideep** [comment] 2019-11-21 05:12
Hi, I tried installation with the docker compose file mentioned on a windows machine but the services are getting restarted (analyzer,service-api,postgres etc) and login fails. Please help. 
<img width="947" alt="error" src="https://user-images.githubusercontent.com/15831063/69305870-8d3eb900-0c4b-11ea-9ae9-219913622dfe.PNG">
<img width="374" alt="error1" src="https://user-images.githubusercontent.com/15831063/69305881-92036d00-0c4b-11ea-9498-96ace4e105b1.PNG">

**Comment by AlehB** [comment] 2019-11-21 08:32
Hi @srivastavajaideep ,

Please check the containers logs, starting from the db (Postgres)
It will tell you the direction to the root cause of these issues

Thank you,
Aleh

**Comment by srivastavajaideep** [comment] 2019-11-21 10:34
Still no success, some "postgres" role related issue, not sure how to fix that.  

The files belonging to this database system will be owned by user "postgres".
This user must also own the server process.

The database cluster will be initialized with locale "en_US.utf8".
The default database encoding has accordingly been set to "UTF8".
The default text search configuration will be set to "english".

Data page checksums are disabled.

fixing permissions on existing directory /var/lib/postgresql/data ... ok
creating subdirectories ... ok
selecting dynamic shared memory implementation ... posix
selecting default max_connections ... 100
selecting default shared_buffers ... 128MB
selecting default time zone ... UTC
creating configuration files ... ok
running bootstrap script ... ok
sh: locale: not found
2019-11-21 10:22:59.337 UTC [29] WARNING:  no usable system locales were found
performing post-bootstrap initialization ... ok
initdb: warning: enabling "trust" authentication for local connections
You can change this by editing pg_hba.conf or using the option -A, or
--auth-local and --auth-host, the next time you run initdb.
syncing data to disk ... ok


Success. You can now start the database server using:

    pg_ctl -D /var/lib/postgresql/data -l logfile start

waiting for server to start....2019-11-21 10:23:00.051 UTC [34] LOG:  starting PostgreSQL 12.1 on x86_64-pc-linux-musl, compiled by gcc (Alpine 8.3.0) 8.3.0, 64-bit
2019-11-21 10:23:00.054 UTC [34] LOG:  listening on Unix socket "/var/run/postgresql/.s.PGSQL.5432"
2019-11-21 10:23:00.099 UTC [35] LOG:  database system was shut down at 2019-11-21 10:22:59 UTC
2019-11-21 10:23:00.103 UTC [34] LOG:  database system is ready to accept connections
done
server started
CREATE DATABASE


/usr/local/bin/docker-entrypoint.sh: ignoring /docker-entrypoint-initdb.d/*

waiting for server to shut down....2019-11-21 10:23:00.243 UTC [34] LOG:  received fast shutdown request
2019-11-21 10:23:00.245 UTC [34] LOG:  aborting any active transactions
2019-11-21 10:23:00.246 UTC [34] LOG:  background worker "logical replication launcher" (PID 41) exited with exit code 1
2019-11-21 10:23:00.246 UTC [36] LOG:  shutting down
2019-11-21 10:23:00.268 UTC [34] LOG:  database system is shut down
done
server stopped

PostgreSQL init process complete; ready for start up.

2019-11-21 10:23:00.355 UTC [1] LOG:  starting PostgreSQL 12.1 on x86_64-pc-linux-musl, compiled by gcc (Alpine 8.3.0) 8.3.0, 64-bit
2019-11-21 10:23:00.356 UTC [1] LOG:  listening on IPv4 address "0.0.0.0", port 5432
2019-11-21 10:23:00.356 UTC [1] LOG:  listening on IPv6 address "::", port 5432
2019-11-21 10:23:00.360 UTC [1] LOG:  listening on Unix socket "/var/run/postgresql/.s.PGSQL.5432"
2019-11-21 10:23:00.405 UTC [45] LOG:  database system was shut down at 2019-11-21 10:23:00 UTC
2019-11-21 10:23:00.409 UTC [1] LOG:  database system is ready to accept connections
2019-11-21 10:23:02.641 UTC [52] WARNING:  there is no transaction in progress
2019-11-21 10:23:02.812 UTC [52] WARNING:  there is no transaction in progress
2019-11-21 10:23:09.078 UTC [59] FATAL:  role "postgres" does not exist
2019-11-21 10:23:19.561 UTC [121] FATAL:  role "postgres" does not exist

**Comment by AlehB** [comment] 2019-11-21 13:15
Definitely you cannot start RP, because of the PostreSQL issue itself

Have you adjusted the Docker Compose file in order support Docker on Windows?
![image](https://user-images.githubusercontent.com/2253605/69341074-e7567300-0c79-11ea-8a95-81b1cea0f223.png)
![image](https://user-images.githubusercontent.com/2253605/69341081-eb829080-0c79-11ea-9931-067c3bbd6811.png)

Anyway, we strongly recommend you to use Linux to work with Docker

**Comment by srivastavajaideep** [comment] 2019-11-21 13:21
Yes,I have adjusted the docker compose file and the error logs shared were on Ubuntu installation.Setup is not working on Windows machine as well (after doing changes in compose file)

**Comment by AlehB** [comment] 2019-11-21 14:58
Please check PostgreSQL environment variables on your system
This issue relates to the PostgreSQL rather than to ReportPortal
https://www.google.com/search?q=FATAL%3A+role+%22postgres%22+does+not+exist&ie=utf-8&oe=utf-8

**Comment by srivastavajaideep** [comment] 2019-11-22 13:19
Thanks for sharing the steps. I had already explored these steps and they look more relevant when we have postgres on machine and having some issue with the setting of env variables but i think in our case we are trying to install postgres through docker compose.. kindly share some other sample  docker compose file which has mongodb and jira integration. Thanks

**Comment by AlehB** [comment] 2019-11-25 12:28
Hi @srivastavajaideep,

Please find by following https://github.com/reportportal/reportportal/blob/master/docker-compose.yml. This is a Docker Compose for ReportPortal 4 with Mongo db, but we are not support it anymore, because are fully involved in ReportPortal 5 with PostreSQL. The Docker Compose I sent to you earlier (Posthres one) was tested many times and it expects to work smoothly with PostgreSQL until you have some specific issue on your side

**Comment by evjlobanova** [comment] 2019-11-25 14:11
Can I close this issue?

**Comment by srivastavajaideep** [comment] 2019-11-26 17:18
I am afraid but report portal 4 docker compose is not working for me on the Ubuntu machine neither version 5.please let me know if I need to install postgres first on the machine and then try installation with the docker compose file you guys had shared? thanks

**Comment by AlehB** [comment] 2019-11-27 09:31
Hi @srivastavajaideep,

There no need to install Postgres in advance
Please make sure you install RP correctly (docker-compose -p reportportal up -d --force-recreate), and you can also try it on another host

Best,
Aleh

**Comment by pbortnik** [comment] 2020-01-08 14:47
Hi, considering to the issue with 'postgres' role does not exists. It is an issue of docker-compose health check config. Try to use the latest docker-compose-v5 where it is fixed.

**Comment by evjlobanova** [comment] 2020-03-03 16:49
@srivastavajaideep please follow the steps described below.
If you have problems, please let us know and feel free too reopen issue

**Closed by evjlobanova** 2020-03-03 16:49 UTC
Labels: Waiting Info For Requestor, help wanted
