### ISSUE TITLE
Cannot report test results to the project with "demo" name

### ISSUE THREAD

**Issue by nvborisenko** [reportportal/reportportal#1891] opened 2022-11-30 10:07 UTC
Steps to reproduce:
- Create a new project with name "demo"
- Send test results using any agent

```
InternalServerError (500) POST http://localhost:8080/api/v1/demo/item)
 ---> ReportPortal.Client.ReportPortalException: Response status code does not indicate success: InternalServerError (500) POST http://localhost:8080/api/v1/demo/item
 ---> System.Net.Http.HttpRequestException: Response message: {"errorCode":5000,"message":"Unclassified error [Ambiguous handler methods mapped for '/v1/demo/item': {public com.epam.ta.reportportal.demodata.model.DemoDataRs com.epam.ta.reportportal.demodata.DemoDataController.generate(java.lang.String,com.epam.ta.reportportal.demodata.model.DemoDataRq,com.epam.ta.reportportal.commons.ReportPortalUser), public com.epam.ta.reportportal.ws.model.EntryCreatedAsyncRS com.epam.ta.reportportal.ws.controller.TestItemController.startRootItem(java.lang.String,com.epam.ta.reportportal.commons.ReportPortalUser,com.epam.ta.reportportal.ws.model.StartTestItemRQ)}]"}
```

**Comment by VolhaKarenko** [comment] 2022-12-16 14:39
The issue is fixed in version 5.7.5

**Closed by VolhaKarenko** 2022-12-16 14:39 UTC
Labels: bug
