### ISSUE TITLE
Custom welcome screen and email templates

### ISSUE THREAD

**Issue by sumeetm18** [reportportal/reportportal#613] opened 2019-04-24 14:11 UTC
We want to have custom welcome screen and email notification templates 
...

Can we have an option to override the values in home screen and also email notification template.
...

**Comment by evjlobanova** [comment] 2019-05-04 09:59
@sumeetm18 Could you please provide us your desired template for login screen and for e-mail?

**Comment by evjlobanova** [comment] 2019-05-15 13:38
#573

**Comment by evjlobanova** [comment] 2020-03-30 16:16
Closed as a duplicate of #573

**Closed by evjlobanova** 2020-03-30 16:16 UTC
Labels: feature request
