### ISSUE TITLE
[v5] Component Health Check Widget not working after Upgrade

### ISSUE THREAD

**Issue by vishallanke** [reportportal/reportportal#1606] opened 2021-12-13 09:13 UTC
We have upgraded from version 5.2 to the latest version 5.6.
After the upgrade, we observed that Component Health Check Widget remains in a loading state. If we have approximately 100 tests inside the filter, widgets get loaded. But if the test case count grows, then Widget remains in the loading state.
Now, we are blocked due to this
Below widget is in loading state only.
I have created new Widget and issue still exists.
![image](https://user-images.githubusercontent.com/46259109/145783821-43612ea8-8e86-4f2f-9fc7-075df9f751a8.png)

**Comment by evjlobanova** [comment] 2021-12-13 21:08
Could you please share a filter that you are using for this widget 
Please send me a screenshot with refines on All launches view

**Comment by vishallanke** [comment] 2021-12-14 07:07
@evjlobanova 
Plenty of filters, each having different criteria. If I reduce test data(launches), Widgets works, else widgets remain in loading state
![image](https://user-images.githubusercontent.com/46259109/145949358-90e94a75-b324-44cd-838e-e7b664237d9d.png)

![image](https://user-images.githubusercontent.com/46259109/145949384-0d5d4b9e-0290-453f-9f79-580c66f410fd.png)

![image](https://user-images.githubusercontent.com/46259109/145949531-082f9866-0f0f-4573-9d35-5164f5339e2e.png)

**Comment by vishallanke** [comment] 2021-12-14 07:16
One observations - ALLLAUNCHES filter works which has too much of data. But, if I add Attribute, then it wont work
![image](https://user-images.githubusercontent.com/46259109/145950759-ebef4849-3e16-47f0-aca1-badb2473027b.png)

**Comment by vishallanke** [comment] 2021-12-14 08:10
I think that I have found the root cause of this issue in the newer version :) This issue is not there in the older version. It's not about data but it's about attribute keys. 
![image](https://user-images.githubusercontent.com/46259109/145951673-6c2dee82-441d-426c-ad44-7511fe559748.png)

We have integrated various project types in the report portal including security ,performance tests, cypress, robot, python and many other. When we started a year ago, we tried sending` type:Cypress, type:SecDevOps `as a part of Launch attributes. However, `attribute key/value without any, with any, all `does not work well for us because we have different requirements inside the dashboard based upon products and many other attribute keys.

So, 
Security Git Pipeline will add 
`SecDevOps:true` as Launch Attribute. Performance project will add `Performance:true` inside Launch attributes and so on. However, the performance pipeline will not add `SecDevOps Key inside LaunchAttribute.` There will not be this key and this is the root cause. This works well in the previous version 5.2 but not working in the latest release.

Please check below. `SecDevOps `key is not there. We have shared base` Keys and Values `with every project. It's mandatory for every project in Git to use these Key and Value pairs as Launch Attributes For Products, PipelienId, Component etc.. However, every Git project can add its own` Key Value as Launch attribute`s on top of that. And this is not working.

![image](https://user-images.githubusercontent.com/46259109/145957951-6281787c-dcec-4ca8-81ee-3470e38c6abc.png)


Please let me know your opinion

**Comment by evjlobanova** [comment] 2021-12-14 16:34
In version 5.6 we have changed filters for attribute key and for attribute value 
Now it works as a composite filter for attributes.
The component health check does not process your old filter correctly. 
You need to edit filter , and save it one more time
Could you please try, and let me know if it helps

**Comment by vishallanke** [comment] 2021-12-15 05:07
It does not work 
It is because each Launch inside filter contains at-least one `Key:Value` which is not there in other Launches
, for example, our Git Security Job/Tests will send `SecDevOps:true `as Launch Attributes. `SecDevOps:true`  attributes won't be available for Automated Tests or Performance Tests and so on.

If report portal filter/ launch contains at-lease one different attributes than other , then Component Heal Table does not work

**Comment by evjlobanova** [comment] 2021-12-22 13:52
@VolhaKarenko Olya, have you met such behavior?

**Comment by VolhaKarenko** [comment] 2021-12-24 09:51
The issue is reproducible, bug is added to backlog

**Comment by DzmitryHumianiuk** [comment] 2022-08-23 00:07
@VolhaKarenko please close if it fixed

**Comment by VolhaKarenko** [comment] 2022-08-23 04:57
The issue is fixed in version 5.7

**Closed by VolhaKarenko** 2022-08-23 04:57 UTC
