### ISSUE TITLE
[v5] SAML integrations duplicating after edit

### ISSUE THREAD

**Issue by IharBletskoTR** [reportportal/reportportal#1192] opened 2020-10-29 11:10 UTC
SAML integrations duplicating after editing with changing integration name
Reproducing:

1. Add integration as usual
![image](https://user-images.githubusercontent.com/68950579/97560511-cea91e00-19ef-11eb-9944-0dd42cce143a.png)
![image](https://user-images.githubusercontent.com/68950579/97560549-dd8fd080-19ef-11eb-94c5-d4f8e89623b7.png)
2. After saving integration select saved integration and press Configure.
3. Change provider name (NAME-CHANGED in this case) and other settings and save.
4. Logout.
5. Login again and in SAML section now have two integrations.

They showing and selecting as a whole in the SAML login page
![image](https://user-images.githubusercontent.com/68950579/97560730-247dc600-19f0-11eb-9d07-072942216b6f.png)

**Expected behavior**
Changing edited integration without duplicating.

**Comment by VolhaKarenko** [comment] 2020-10-29 12:39
The issue is reproducible, bug is added to backlog

**Comment by VolhaKarenko** [comment] 2022-09-28 04:48
Fixed in version 5.4

**Closed by VolhaKarenko** 2022-09-28 04:48 UTC
Labels: bug
