### ISSUE TITLE
Performace problem when check only failed tests

### ISSUE THREAD

**Issue by babantax** [reportportal/reportportal#1839] opened 2022-09-07 10:31 UTC
CPU consumption skyrockets when we click on view failed tests (see screenshot).
This query takes very long time to be processed (sometimes like one ore two minutes)
Sometimes connection fails

**Screenshots**
![image](https://user-images.githubusercontent.com/52815118/188855856-b52e1578-ddf2-4dd0-b0c3-5bf883fa8719.png)
![image](https://user-images.githubusercontent.com/52815118/190963408-b583df0d-7ec2-4326-921d-07ed4be4f754.png)
![image](https://user-images.githubusercontent.com/52815118/188856499-9e14be8f-25c0-498f-9ea5-a46c63dcd2b3.png)
![image](https://user-images.githubusercontent.com/52815118/188856939-235aeb43-cb74-4faf-b0bb-eb68099f648a.png)

**Versions:**
 - K8S
 - Version of RP 5.7.0

**Comment by DzmitryHumianiuk** [comment] 2022-09-08 19:39
@irynakozak2 ^

**Comment by DzmitryHumianiuk** [comment] 2022-09-08 22:13
@babantax check if the database makes indexing.

**Comment by babantax** [comment] 2022-09-12 06:44
Hi @DzmitryHumianiuk,
How can I check that? What I can do if indexing is not happening?

**Comment by irynakozak2** [comment] 2022-09-13 07:51
@babantax hi, could you please connect to the PostgreSQL database and share the active queries while the issue is reproducing? Also please share your instances specification for the cluster and database: how many CPUs, Memory do you have for that also please make sure that you have applied the suggested [optimal performance configuration for the PostgreSQL database](https://reportportal.io/docs/Optimal-Performance-Hardware%3E5-postgresql-performance-tuning).
I suppose it's a known issue that we have already fixed in the upcoming 5.8 version, but I need to check the DB queries to be sure.

**Comment by DzmitryHumianiuk** [comment] 2022-09-16 21:33
@babantax ^^

**Comment by babantax** [comment] 2022-09-19 07:17
Hello,
We have the DB in AWS with this resources:
![image](https://user-images.githubusercontent.com/52815118/190966983-ea3f06a0-4f02-4f7c-ac62-77e8680eefd2.png)
The problem can be that we just need to upgrade the resources?

**Comment by irynakozak2** [comment] 2022-09-19 11:46
@babantax I guess not really but it's based on your workload. To verify this, please enable the free Performance Insights for the Database and send the DB queries while the issue is reproducing to check if it's related to our fixed performance issue or if the problem is somewhere else.

**Comment by irynakozak2** [comment] 2022-09-28 14:27
Hi @babantax !
Are there any updates regarding the DB queries sharing from the Performance Insights?

**Comment by babantax** [comment] 2022-09-30 10:37
Hi @irynakozak2 
Thanks for your asking. I activated the Performance Insights some days ago but I´m not able to see any long query or something strange
![image](https://user-images.githubusercontent.com/52815118/193251898-08c44de2-3eb4-4bbc-b148-7c2080614e0f.png)

**Comment by babantax** [comment] 2022-10-03 09:07
Good morning,
Today we are facing very slow performace. This is what I get in the performance Insights:
![image](https://user-images.githubusercontent.com/52815118/193540251-66682ac1-3205-4f55-a87c-1b334591aed7.png)
![image](https://user-images.githubusercontent.com/52815118/193540428-e89443a6-f37d-4e3a-a56f-d1b416f4e6c9.png)
![image](https://user-images.githubusercontent.com/52815118/193540533-999ed8bc-86e4-4142-9433-040df3e7f3fb.png)
![image](https://user-images.githubusercontent.com/52815118/193540648-057e66d1-5941-4ad0-9bbe-71277e60b54b.png)

Any idea what can be happening?

Thanks!

**Comment by irynakozak2** [comment] 2022-10-04 00:45
@babantax hi, thank you for the details.
For the "with filtered" query: as I mentioned, It's a known issue of the 5.7+ version, and it's already fixed. The fix will be available in v5.8. The reason for high resource utilization was too much additional data selected during clicking items by statistics. We have done the specific refactoring of that PostgreSQL query, and have verified on our side, that the issue isn't reproduced.

My recommendation is to review and apply the [optimal performance configuration for the PostgreSQL database](https://reportportal.io/docs/Optimal-Performance-Hardware%3E5-postgresql-performance-tuning).

**Comment by babantax** [comment] 2022-10-04 06:43
Thanks a lot for the support. Looking forward to update to v5.8 :)

**Comment by MaryiaRymarchyk** [comment] 2024-01-22 11:46
Hi @babantax as fix already in life - issue will be closed. 
If you have any concern, please feel free to reopen or create a new issue.

**Closed by MaryiaRymarchyk** 2024-01-22 11:46 UTC
Labels: bug, Check: Performance
