### ISSUE TITLE
Integration with Google Oauth

### ISSUE THREAD

**Issue by Kanaduchi** [reportportal/reportportal#266] opened 2017-11-08 08:48 UTC
Our company uses Google oauth to authenticate to all internal services. So it will be great to add support Google oauth in ReportPortal.

We do not use github, so integration with github is not suitable to us

Maybe this request can be included into Roadmap 4.0?

**Comment by DzmitryHumianiuk** [comment] 2017-11-08 16:25
@Kanaduchi hi,
there are not so many companies, among current users, who need this.
so this definitely should go into back log, but with low priority.

Anyway, you or your team can still contribute to it.
And this will make it available for everyone!

**Comment by surevs** [comment] 2019-05-15 08:12
is there any update on this request using google oauth or can it be handled other way around - please advise.

**Comment by DzmitryHumianiuk** [comment] 2019-05-20 15:58
@surevs we plan to release SAML based auth pretty soon.
if google auth supports SAML, than it will be the option.

Does it?

**Comment by surevs** [comment] 2019-05-20 17:59
Sure, @DzmitryHumianiuk - Thanks so much for the update - Based on the link https://support.google.com/a/answer/6087519?hl=en it looks like there should be few workaround - we will be eagerly waiting for to get our hands on it 👍

**Comment by DzmitryHumianiuk** [comment] 2019-08-09 08:15
https://github.com/reportportal/reportportal/issues/566

**Comment by evjlobanova** [comment] 2020-04-02 13:01
Duplicate of #877 
You can follow up on your request progress in the mentioned issue

**Closed by evjlobanova** 2020-04-02 13:01 UTC
Labels: Feature: Authorization, feature request
