### ISSUE TITLE
[v5] Year in footer copyright text is not up to date

### ISSUE THREAD

**Issue by Shakevg** [reportportal/reportportal#1182] opened 2020-10-19 12:36 UTC
**Describe the bug**
Year in footer copyright text is not up to date: 2018

**To Reproduce**
Login to Report Portal v5.3

**Expected behavior**
Up to date Year: 2020

**Screenshots**
![image](https://user-images.githubusercontent.com/42133199/96451730-b3d0ef80-1220-11eb-8d8d-24a6d9105904.png)

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser chrome
 - Version 86

**Comment by e-olga** [comment] 2020-10-20 13:14
@Shakevg , @evjlobanova , the ticket is added to RP backlog.

Regards,
Olga

**Comment by VolhaKarenko** [comment] 2020-10-28 13:27
The issue is fixed in version 5.3.3

**Closed by VolhaKarenko** 2020-10-28 13:27 UTC
