### ISSUE TITLE
Launch duration chart label "seconds"

### ISSUE THREAD

**Issue by egilsdq** [reportportal/reportportal#871] opened 2020-02-28 18:36 UTC
**Describe the bug**
When using Launch duration chart, label at bottom of chart is "seconds" but actual is "minutes".

**Expected behavior**
Show "minutes" if axis values is in minutes.

**Screenshots**
![image](https://user-images.githubusercontent.com/15646224/75576929-8fde5500-5a69-11ea-95ed-0a6f2d826496.png)

**Versions:**
 - Windows 10, Microsoft Edge (Version 80.0.361.62)
 - Version of RP 5.0

**Comment by VolhaKarenko** [comment] 2020-07-06 11:21
The issue is reproducible on version 5.3 as well. The same is true for other values, e.g. "hours". Bug is added to Jira.

**Comment by VolhaKarenko** [comment] 2020-08-05 06:14
The issue is fixed in version 5.3

**Closed by VolhaKarenko** 2020-08-05 06:14 UTC
Labels: bug
