### ISSUE TITLE
Report Portal is not displaying the cucumber steps under the scenarios

### ISSUE THREAD

**Issue by nitin19982232** [reportportal/reportportal#2281] opened 2024-05-24 07:48 UTC
Hello Team,
I'm new to the report portal. We've set up the Java + Cucumber framework with the report portal using the report portal builder class, without employing any reportportal.properties file. However, upon triggering the launches, the report portal displays the scenario names and the pass or fail count. However, we're unable to see the individual steps under each scenario. Is there any additional configuration required for this?

**Comment by alena-babrova** [comment] 2024-06-25 07:31
Hello @nitin19982232,

Could you please tell me if the issue is still relevant for you?
Have you followed the [instructions](https://github.com/reportportal/agent-java-cucumber#step-reporter)?

**Comment by alena-babrova** [comment] 2024-07-23 08:21
Hello @nitin19982232,

As we haven't received a reply from you, we'll close the issue for now.
Just in case you still have the issue, please, do not hesitate to get in touch.

**Closed by alena-babrova** 2024-07-23 08:21 UTC
Labels: help wanted
