### ISSUE TITLE
[Widgets]  incorrect time calculation in "Project activity" 

### ISSUE THREAD

**Issue by admizh** [reportportal/reportportal#21] opened 2016-12-03 14:11 UTC
![2016-12-03_18-02-22](https://cloud.githubusercontent.com/assets/6014483/20859837/d8ffde32-b983-11e6-8bc7-18d1c59476c1.png)

**Comment by admizh** [comment] 2016-12-07 01:48
Same issue for investigation history, i see "6 hours ago" - should be current time  
![2016-12-07_5-43-43](https://cloud.githubusercontent.com/assets/6014483/20951638/615cb3e0-bc40-11e6-9fa1-688f16506914.gif)

**Comment by e-olga** [comment] 2017-03-21 08:23
Hi admizh,
I was not able to reproduce the issue above. Looks the RP shows correct time of actions both for item on LOG view 
![issue_21_screen_item](https://cloud.githubusercontent.com/assets/22497746/24138258/9952564e-0e28-11e7-9b3e-66b85e70a290.png)
and on Project activity panel
![issue_21_screen_widget](https://cloud.githubusercontent.com/assets/22497746/24138263/a00bb46c-0e28-11e7-8b3a-71fddde5574c.png)
@admizh Could you please check the issue again on your side and let us know the result?

**Comment by DzmitryHumianiuk** [comment] 2017-03-21 09:29
@e-olga please double check it in 2.7 version
It's an old bug

**Comment by e-olga** [comment] 2017-03-21 09:42
@DzmitryHumianiuk The issue actually was checked in RP v 2.7.

**Comment by e-olga** [comment] 2017-03-21 10:24
@admizh Could you please check whether the time on server is synchronized with your local time?
Next command could be used: 
docker exec -it [container id] date

**Comment by DzmitryHumianiuk** [comment] 2017-07-06 15:46
@admizh up

please re-open if still appears

**Closed by DzmitryHumianiuk** 2017-07-06 15:46 UTC
Labels: bug
