### ISSUE TITLE
Cucumber Java Agent – Steps are sporadically missing from the test’s logs

### ISSUE THREAD

**Issue by talgreen1** [reportportal/reportportal#307] opened 2017-12-31 11:04 UTC
I’m using the cucumber Java agent (ver. 3.0.1) and the cucumber plugin “com.epam.reportportal.cucumber.ScenarioReporter”

Most of the time the report is OK – contains all the tests and each test contains all the log messages.
But – for some tests (sporadically) the first log message is missing, and for some other tests – all the log messages are missing.

Also – I’m sometime getting an exception with the message:
Start time of child ['Sun Dec 31 09:46:31 UTC 2017'] item should be same or later than start time ['Sun Dec 31 09:46:31 UTC 2017'] of the parent item/launch '5a48b1f92ab79c00018b233d'

Full stack trace is below.

I’m attaching a sample project- 
[cucumber_report_portal.zip](https://github.com/reportportal/reportportal/files/1595128/cucumber_report_portal.zip)
You need to run the “TestNGRunner” class as TestNG class.

Stack trace:
```
[I/O dispatcher 1] ERROR com.epam.reportportal.service.ReportPortal - ReportPortal execution error
com.epam.reportportal.exception.ReportPortalException: Report Portal returned error
Status code: 406
Status message: Not Acceptable
Error Message: Start time of child ['Sun Dec 31 09:46:31 UTC 2017'] item should be same or later than start time ['Sun Dec 31 09:46:31 UTC 2017'] of the parent item/launch '5a48b1f92ab79c00018b233d'
Error Type: CHILD_START_TIME_EARLIER_THAN_PARENT

	at com.epam.reportportal.service.ReportPortalErrorHandler.handleError(ReportPortalErrorHandler.java:62)
	at com.epam.restendpoint.http.DefaultErrorHandler.handle(DefaultErrorHandler.java:56)
	at com.epam.restendpoint.http.HttpClientRestEndpoint$1$1.completed(HttpClientRestEndpoint.java:547)
	at com.epam.restendpoint.http.HttpClientRestEndpoint$1$1.completed(HttpClientRestEndpoint.java:518)
	at rp.org.apache.http.concurrent.BasicFuture.completed(BasicFuture.java:119)
	at rp.org.apache.http.impl.nio.client.DefaultClientExchangeHandlerImpl.responseCompleted(DefaultClientExchangeHandlerImpl.java:177)
	at rp.org.apache.http.nio.protocol.HttpAsyncRequestExecutor.processResponse(HttpAsyncRequestExecutor.java:436)
	at rp.org.apache.http.nio.protocol.HttpAsyncRequestExecutor.inputReady(HttpAsyncRequestExecutor.java:326)
	at rp.org.apache.http.impl.nio.DefaultNHttpClientConnection.consumeInput(DefaultNHttpClientConnection.java:265)
	at rp.org.apache.http.impl.nio.client.InternalIODispatch.onInputReady(InternalIODispatch.java:81)
	at rp.org.apache.http.impl.nio.client.InternalIODispatch.onInputReady(InternalIODispatch.java:39)
	at rp.org.apache.http.impl.nio.reactor.AbstractIODispatch.inputReady(AbstractIODispatch.java:114)
	at rp.org.apache.http.impl.nio.reactor.BaseIOReactor.readable(BaseIOReactor.java:162)
	at rp.org.apache.http.impl.nio.reactor.AbstractIOReactor.processEvent(AbstractIOReactor.java:337)
	at rp.org.apache.http.impl.nio.reactor.AbstractIOReactor.processEvents(AbstractIOReactor.java:315)
	at rp.org.apache.http.impl.nio.reactor.AbstractIOReactor.execute(AbstractIOReactor.java:276)
	at rp.org.apache.http.impl.nio.reactor.BaseIOReactor.execute(BaseIOReactor.java:104)
	at rp.org.apache.http.impl.nio.reactor.AbstractMultiworkerIOReactor$Worker.run(AbstractMultiworkerIOReactor.java:588)
	at java.lang.Thread.run(Thread.java:748)
```

**Comment by avarabyeu** [comment] 2018-01-15 13:55
@talgreen1 Thank you for demo project!
@pbortnik could you please execute attached demo project against 4.0.x version?

**Comment by pbortnik** [comment] 2018-01-18 08:58
Seems to be a duplicate of #188 and it have been already fixed.

**Comment by pbortnik** [comment] 2018-01-18 11:31
Close for now

**Closed by pbortnik** 2018-01-18 11:31 UTC
Labels: bug, component:agent
