### ISSUE TITLE
History Display: Allow format()-string or other control over text fields

### ISSUE THREAD

**Issue by NeuroDuck** [reportportal/reportportal#966] opened 2020-05-13 21:27 UTC
See:
[History Display](https://files.slack.com/files-pri/T2GRWUYAX-F0139GNH6HK/can_the_test_run_modify_these_fields.png)

We are using v5.1 with pytest-reportportal v5.0.3.

Can ReportPortal allow us to specify a unique string to be specified in the Blue-circle areas in the History display?

As you can imagine, we would like to display the build# that was tested in place of "Execution #5", along with the date, etc.

And for the test_name, it is displaying:

    file_name::class_name::test_name

but test_name is getting cut off.  So could just the test_name be selected to be displayed, i.e., under the History Display's "Options" button?

**Comment by evjlobanova** [comment] 2020-05-14 06:52
Partly duplicate of #325

**Comment by evjlobanova** [comment] 2020-05-14 06:56
@NeuroDuck please add screenshots to this request. 
What do you mean under: Blue-circle areas in the History display?
Please add screenshots for: "test_name is getting cut of"
What do you mean under: "the test_name be selected to be displayed, i.e., under the History Display's "Options" button?"

**Comment by MaryiaRymarchyk** [comment] 2024-03-07 07:54
@NeuroDuck  as no response and requirement is not clear - ticket will be closed.
If this still relevant or any concern remains, please feel free to reopen or create a new issue.

**Closed by MaryiaRymarchyk** 2024-03-07 07:54 UTC
Labels: feature request, Feature: BuildReport
