### ISSUE TITLE
Service-api has ".AuthUtils$SerialUidReplacingInputStream : Potentially Fatal Deserialization Operation." error after upgraded to v5.7.3

### ISSUE THREAD

**Issue by sjyzheng** [reportportal/reportportal#1970] opened 2023-03-27 21:34 UTC
Hi Team,

We have just upgraded our RP system to v5.7.3 with k8s. It is working fine, and new launches are created and can shown in RP.

However, in service-api's log, we can see lots of errors. Can you please advice how to fix it? Thanks!

> 2023-03-27 21:24:37.399 ERROR 1 --- [io-8585-exec-19] .AuthUtils$SerialUidReplacingInputStream : Potentially Fatal Deserialization Operation.
> 
> java.io.InvalidClassException: Overriding serialized class version mismatch: local serialVersionUID = 550 stream serialVersionUID = 520
> 	at com.epam.ta.reportportal.auth.util.AuthUtils$SerialUidReplacingInputStream.readClassDescriptor(AuthUtils.java:105)
> 	at java.base/java.io.ObjectInputStream.readNonProxyDesc(ObjectInputStream.java:1992)
> 	at java.base/java.io.ObjectInputStream.readClassDesc(ObjectInputStream.java:1870)
> 	at java.base/java.io.ObjectInputStream.readOrdinaryObject(ObjectInputStream.java:2201)
> 	at java.base/java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1687)
> 	at java.base/java.io.ObjectInputStream.readObject(ObjectInputStream.java:489)
> 	at java.base/java.io.ObjectInputStream.readObject(ObjectInputStream.java:447)
> 	at java.base/java.util.ArrayList.readObject(ArrayList.java:929)
> 	at java.base/jdk.internal.reflect.GeneratedMethodAccessor188.invoke(Unknown Source)
> 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
> 	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
> 	at java.base/java.io.ObjectStreamClass.invokeReadObject(ObjectStreamClass.java:1046)
> 	at java.base/java.io.ObjectInputStream.readSerialData(ObjectInputStream.java:2357)
> 	at java.base/java.io.ObjectInputStream.readOrdinaryObject(ObjectInputStream.java:2228)
> 	at java.base/java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1687)
> 	at java.base/java.io.ObjectInputStream.defaultReadFields(ObjectInputStream.java:2496)
> 	at java.base/java.io.ObjectInputStream.readSerialData(ObjectInputStream.java:2390)
> 	at java.base/java.io.ObjectInputStream.readOrdinaryObject(ObjectInputStream.java:2228)
> 	at java.base/java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1687)
> 	at java.base/java.io.ObjectInputStream.defaultReadFields(ObjectInputStream.java:2496)
> 	at java.base/java.io.ObjectInputStream.readSerialData(ObjectInputStream.java:2390)
> 	at java.base/java.io.ObjectInputStream.readOrdinaryObject(ObjectInputStream.java:2228)
> 	at java.base/java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1687)
> 	at java.base/java.io.ObjectInputStream.readObject(ObjectInputStream.java:489)
> 	at java.base/java.io.ObjectInputStream.readObject(ObjectInputStream.java:447)
> 	at com.epam.ta.reportportal.auth.util.AuthUtils.deserializeSafely(AuthUtils.java:69)
> 	at com.epam.ta.reportportal.auth.CombinedTokenStore.readAuthentication(CombinedTokenStore.java:68)
> 	at org.springframework.security.oauth2.provider.token.store.JwtTokenStore.readAuthentication(JwtTokenStore.java:70)
> 	at com.epam.ta.reportportal.auth.CombinedTokenStore.readAuthentication(CombinedTokenStore.java:55)
> 	at com.epam.ta.reportportal.auth.CombinedTokenStore$$FastClassBySpringCGLIB$$753697c.invoke(<generated>)
> 	at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:218)
> 	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.invokeJoinpoint(CglibAopProxy.java:783)
> 	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:163)
> 	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:753)
> 	at org.springframework.transaction.interceptor.TransactionInterceptor$1.proceedWithInvocation(TransactionInterceptor.java:123)
> 	at org.springframework.transaction.interceptor.TransactionAspectSupport.invokeWithinTransaction(TransactionAspectSupport.java:388)
> 	at org.springframework.transaction.interceptor.TransactionInterceptor.invoke(TransactionInterceptor.java:119)
> 	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186)
> 	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:753)
> 	at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:698)
> 	at com.epam.ta.reportportal.auth.CombinedTokenStore$$EnhancerBySpringCGLIB$$57045c47.readAuthentication(<generated>)
> 	at org.springframework.security.oauth2.provider.token.DefaultTokenServices.loadAuthentication(DefaultTokenServices.java:242)
> 	at org.springframework.security.oauth2.provider.token.DefaultTokenServices$$FastClassBySpringCGLIB$$5a1f25c.invoke(<generated>)
> 	at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:218)
> 	at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:689)
> 	at org.springframework.security.oauth2.provider.token.DefaultTokenServices$$EnhancerBySpringCGLIB$$7b5c82e7.loadAuthentication(<generated>)
> 	at org.springframework.security.oauth2.provider.authentication.OAuth2AuthenticationManager.authenticate(OAuth2AuthenticationManager.java:87)
> 	at org.springframework.security.oauth2.provider.authentication.OAuth2AuthenticationProcessingFilter.doFilter(OAuth2AuthenticationProcessingFilter.java:154)
> 	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:336)
> 	at org.springframework.security.web.authentication.logout.LogoutFilter.doFilter(LogoutFilter.java:103)
> 	at org.springframework.security.web.authentication.logout.LogoutFilter.doFilter(LogoutFilter.java:89)
> 	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:336)
> 	at org.springframework.security.web.header.HeaderWriterFilter.doHeadersAfter(HeaderWriterFilter.java:90)
> 	at org.springframework.security.web.header.HeaderWriterFilter.doFilterInternal(HeaderWriterFilter.java:75)
> 	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:117)
> 	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:336)
> 	at org.springframework.security.web.context.SecurityContextPersistenceFilter.doFilter(SecurityContextPersistenceFilter.java:110)
> 	at org.springframework.security.web.context.SecurityContextPersistenceFilter.doFilter(SecurityContextPersistenceFilter.java:80)
> 	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:336)
> 	at org.springframework.security.web.context.request.async.WebAsyncManagerIntegrationFilter.doFilterInternal(WebAsyncManagerIntegrationFilter.java:55)
> 	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:117)
> 	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:336)
> 	at org.springframework.security.web.FilterChainProxy.doFilterInternal(FilterChainProxy.java:211)
> 	at org.springframework.security.web.FilterChainProxy.doFilter(FilterChainProxy.java:183)
> 	at org.springframework.web.filter.DelegatingFilterProxy.invokeDelegate(DelegatingFilterProxy.java:354)
> 	at org.springframework.web.filter.DelegatingFilterProxy.doFilter(DelegatingFilterProxy.java:267)
> 	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:189)
> 	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162)
> 	at org.springframework.web.filter.RequestContextFilter.doFilterInternal(RequestContextFilter.java:100)
> 	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:117)
> 	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:189)
> 	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162)
> 	at org.springframework.web.filter.FormContentFilter.doFilterInternal(FormContentFilter.java:93)
> 	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:117)
> 	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:189)
> 	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162)
> 	at org.springframework.boot.actuate.metrics.web.servlet.WebMvcMetricsFilter.doFilterInternal(WebMvcMetricsFilter.java:96)
> 	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:117)
> 	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:189)
> 	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162)
> 	at org.springframework.web.filter.CharacterEncodingFilter.doFilterInternal(CharacterEncodingFilter.java:201)
> 	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:117)
> 	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:189)
> 	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162)
> 	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:202)
> 	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:97)
> 	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:542)
> 	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:143)
> 	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:92)
> 	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:78)
> 	at org.apache.catalina.valves.RemoteIpValve.invoke(RemoteIpValve.java:764)
> 	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:346)
> 	at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:374)
> 	at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:65)
> 	at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:887)
> 	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1684)
> 	at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
> 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
> 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
> 	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
> 	at java.base/java.lang.Thread.run(Thread.java:829)
>

**Comment by MaryiaRymarchyk** [comment] 2023-04-10 11:31
Hello @sjyzheng , thank you for contacting us. It is known issue (internal ticket id EPMRPP-82199)
Root cause of error is trying to deserialize data with new version of spring security, that has been serialized with old version of spring security. 
Fix in code required, it is waiting his time in our backlog.  It also can be fixed by script, or as an option: Remove old auth data.

**Comment by grant-mccarriagher** [comment] 2023-04-17 16:21
@MaryiaRymarchyk Can you clarify what you mean by script or as an option? We're seeing huge spikes of this in our instance of RP, and it's lining up with the API timing out when reporting test data.

What exactly would we need to do to remove old auth data? Thanks.

**Comment by irynakozak2** [comment] 2023-04-18 11:22
> @MaryiaRymarchyk Can you clarify what you mean by script or as an option? We're seeing huge spikes of this in our instance of RP, and it's lining up with the API timing out when reporting test data.
> 
> What exactly would we need to do to remove old auth data? Thanks.

@grant-mccarriagher Hi! One possible option is to regenerate access tokens for each user at the instance in the user profile. We assume it would be a workaround to fix the issue, but we haven't tested it yet. If you have a such possibility and not really high amount of users on your ReportPortal instance, you can try to test that option.

But still, we are really sorry for causing that issue and plan to fix it entirely in the code in the upcoming versions.

Waiting for your reply.

**Comment by grant-mccarriagher** [comment] 2023-04-18 15:44
Thanks, we're not seeing the error anymore after using a different user/access token for our test suites.

It was just a red herring in regards to the API timing out though, which seems to be another issue.

**Comment by irynakozak2** [comment] 2023-04-18 16:06
@grant-mccarriagher Thank you for the feedback. I will close that issue for now.
By the way, Timeout issues are possibly caused by a lack of CPU/RAM resources for API service or the whole ReportPortal installation. It requires much more detail on your usage and configuration setup, so if the issue with timeout is still actual for you, please create a separate issue on that topic. Thank you!

**Closed by irynakozak2** 2023-04-18 16:06 UTC
Labels: bug

**Comment by janmekota** [comment] 2023-05-05 09:18
> 
> @grant-mccarriagher Hi! One possible option is to regenerate access tokens for each user at the instance in the user profile. We assume it would be a workaround to fix the issue, but we haven't tested it yet. If you have a such possibility and not really high amount of users on your ReportPortal instance, you can try to test that option.

Hello @irynakozak2 
is it possible to regenerate access tokens over the API, please? Or somehow in batch for all users?

**Comment by APiankouski** [comment] 2023-06-08 09:54
@janmekota you can use POST {youDomain}/uat/sso/me/apitoken API for regenerate you api
No any batch operation for all user

**Comment by Pikaboo48** [comment] 2023-09-27 04:22
Hii, we are also experiencing the same deserialization issue in version 5.7.4., we tried to regenerate the API tokens without any success and we are also facing hikari pool connection timeouts. Ideas? thank you :unicorn:

**Comment by MaryiaRymarchyk** [comment] 2023-09-27 06:14
Hi @Pikaboo48, have a look here - https://reportportal.io/blog/Deserialization-issue-workaround.

**Comment by Pikaboo48** [comment] 2023-09-27 07:52
Thank you @MaryiaRymarchyk , but we dont use docker compose, we use helm deployment, is there a workaround for the helm chart values for rp 5.7.4 please?

**Comment by APiankouski** [comment] 2023-09-27 08:05
Hi @Pikaboo48, you can use this latest helm chart
https://github.com/reportportal/kubernetes/tree/reportportal-5.8.1/reportportal

**Comment by Pikaboo48** [comment] 2023-09-27 09:24
@APiankouski thank you! however we do not want to use s3 storage just yet, that's why we like the architecture of RP 5.7.4 where you can still use minio or filesystem. Is there a workaround for non s3 storage users?

![image](https://github.com/reportportal/reportportal/assets/127962362/97336213-5ef1-488e-a1ed-5e3b592d26e5)

**Comment by DzmitryHumianiuk** [comment] 2023-10-05 20:40
@Pikaboo48 yes, you still can use minIO instead.

**Comment by Pikaboo48** [comment] 2023-10-06 05:55
@DzmitryHumianiuk sweet! and could you please tell me which version of RP i should use? and which versions of the dependencies (Rabbit, Minio, ES, Postgres) i should install?

Is there a "How to" for helm charts if i want to keep using minio? i was not lucky so far to make it work on my own permanently, eventually something always crashed. 

Thank you for hope! :smile_cat:
