### ISSUE TITLE
Duplicated error logs after upgrading ReportPortal to version 23.2

### ISSUE THREAD

**Issue by fslev** [reportportal/reportportal#2148] opened 2023-10-05 07:30 UTC
It seems that after upgrading to ReportPortal 23.2 (from 23.1), each failed step contains the assertion error duplicated 11 times.
![image](https://github.com/reportportal/reportportal/assets/17047317/a2b0040b-04ba-4315-850b-b7830a3ae552)

![image](https://github.com/reportportal/reportportal/assets/17047317/b04f5f32-bc10-44a7-8f65-6626b06a844d)
This issue does not reproduce with version 23.1.

**Comment by MaryiaRymarchyk** [comment] 2023-10-05 12:49
Hello @fslev as we have not faced such behavior could you bring more details to it.
What agent and it's version do you use for the reporting?
Is it always reproducible (all test items, all log levels) ?
Any other details you think might be helpful to reproduce?

**Comment by fslev** [comment] 2023-10-06 11:49
Hi @MaryiaRymarchyk 
I am using `agent-java-cucumber6` version 5.2.0 for sending report data to ReportPortal.
It is always reproducible. On all levels

**Comment by MaryiaRymarchyk** [comment] 2023-10-09 14:09
@fslev  issue can be caused by agent, can you try the latest version?

**Comment by fslev** [comment] 2023-10-09 15:03
@MaryiaRymarchyk I've posted above that I am using agent-java-cucumber6 version 5.2.0, which is the latest version inside Maven Central Repo.
By using same agent with previous version of ReportPortal 23.1, everything works fine

**Comment by HardNorth** [comment] 2023-10-09 15:16
@fslev Do you have access to the instance DB? What's in the `log` table for the item, how many rows do you see there?

**Comment by fslev** [comment] 2023-10-10 10:37
Hi @HardNorth 
Data is persisted 11 times inside the `log` table.
For example, take a look inside this screenshot:
![image](https://github.com/reportportal/reportportal/assets/17047317/b8fd4707-e69a-41a1-b917-cde110adf236)
You can see the log is duplicated 11 times, and also quite interesting is the fact that the uuid is also duplicated.

**Comment by HardNorth** [comment] 2023-10-20 09:55
@fslev Got this reproduced locally, yes, it looks like we need a fix.

**Comment by fslev** [comment] 2023-10-20 10:55
Nice  ! 
Thank you !

**Comment by alena-babrova** [comment] 2023-10-23 06:54
Dear @fslev,
The bug is registered in our backlog. We are going to fix it in the next release (23.3).
Thanks for highlighting it!

**Comment by alena-babrova** [comment] 2023-10-25 13:01
Hello @fslev,
Good news: we've fixed the issue and released as a hotfix 😊
So now the version with the fix is already available - please, use reportportal/service-api:5.10.1.
https://github.com/reportportal/service-api/releases/tag/5.10.1

**Closed by alena-babrova** 2023-10-25 13:01 UTC
Labels: bug

**Comment by fslev** [comment] 2023-10-25 13:44
Thank you !
