### ISSUE TITLE
[BUG] - Widget "Overall Statistic" 

### ISSUE THREAD

**Issue by Miriambnzdn** [reportportal/reportportal#1786] opened 2022-07-25 15:21 UTC
Hi,
I have been working with RP for 2 months and found a bug. 
I created a dashboard and set up a "Global Statistics" widget. 
<img width="952" alt="Capture d’écran 2022-07-25 à 17 12 04" src="https://user-images.githubusercontent.com/94960638/180814527-571758ea-f1c0-4a9c-bf9c-48451fb4a07a.png">

But when I try to access the various bugs from the widget, I get this error message. It's as if the launch has been deleted.

<img width="1440" alt="Capture d’écran 2022-07-25 à 17 09 42" src="https://user-images.githubusercontent.com/94960638/180813795-577847c6-d036-4530-990f-f8f6d5a2f48b.png">

This bug is also present when I try to access the automation bug or system issue. 
When I click on the name, I can see the launch and the step without any problem. 

Someone reproduce this behave ? 

Thank you.

**Comment by Miriambnzdn** [comment] 2022-08-24 10:21
??

**Comment by alena-babrova** [comment] 2022-10-03 18:03
Hello @Miriambnzdn 
Unfortunately, we cannot reproduce the same behaviour on our side.

Is the issue still relevant? 
If it is maybe you have more details on this case?

Thank you

**Comment by alena-babrova** [comment] 2022-10-30 14:38
As we haven't received a reply from you, we'll close the issue for now.
Just in case you still have the issue, please, do not hesitate to get in touch.

**Closed by alena-babrova** 2022-10-30 14:38 UTC
Labels: bug, Check: Test
