### ISSUE TITLE
When starting the analysis, the 'services-api' breaks. The error that appears is com.rabbitmq.client.ChannelContinuationTimeoutException.

### ISSUE THREAD

**Issue by Zegnet** [reportportal/reportportal#2196] opened 2023-12-20 21:24 UTC
**Describe the bug**
With auto-analysis turned on, after executing and classifying the first test, when I execute the same scenario to reproduce the same error, Report Portal cannot apply the classification and suggest an error type. As a result, it shows an unhealthy status for both the UI and API services.

**Expected behavior**
When classifying the last error or a group of errors with the same exceptions, I expect Report Portal's machine learning to identify and suggest or classify the error type.

**Screenshots**
If applicable

**Versions:**
 -  OS: Oracle Linux Server (Fedora) 
 - Version of RP:  I am using Docker Compose version 3.8.

[reportportal log - api services.txt](https://github.com/reportportal/reportportal/files/13732629/reportportal.log.-.api.services.txt)

**Comment by Zegnet** [comment] 2024-01-08 16:02
Hello, can anyone help me with fixing the problem or support? I getting the same error when running any test analysis.

**Comment by irynakozak2** [comment] 2024-02-28 09:19
@Zegnet Hi! Sorry for the late response. Based on the logs, the issue can be with the `service-analyzer` itself - the connection to RabbitMQ isn't properly established, or there is an issue with the deployment.
Could you please share the next information for further investigation:

1. ReportPortal version.
2. docker compose file.
3. service-analyzer, service-analyzer-train logs.

**Comment by ninamazurenka** [comment] 2024-03-28 12:50
Hi @Zegnet ! 
Any updates or comments from your side?

**Comment by irynakozak2** [comment] 2024-04-16 11:43
@Zegnet Hi! 
Long time no hear from you, so I close the issue for now. If the problem is still relevant and reproducible for you even on the latest released ReportPortla version, please consider creating a new one with the detailed information in the list above in my latest comment. 
Thank you for your contribution to the ReportPortal!

**Closed by irynakozak2** 2024-04-16 11:43 UTC
Labels: bug, Waiting Info From Requestor, Check: Performance
