### ISSUE TITLE
APIMADMIN Suite data visible on APIM Suite.

### ISSUE THREAD

**Issue by gauravsharma771077** [reportportal/reportportal#2278] opened 2024-05-22 12:30 UTC
**Describe the bug**
We have 2 suite with name.
1) APIM - 99 cases
2) APIMADMIN  - 25 cases
When we upload the report for APIM suite , it's showing count of APIMADMIN in report portal.
...

**Expected behavior**
Both suite APIM and APIADMIN tables must be individually
...

**Screenshots**
If applicable

<img width="737" alt="Screenshot 2024-05-22 at 5 58 40 PM" src="https://github.com/reportportal/reportportal/assets/144100097/41e18b64-ad8e-4a7e-b56b-3cc9fb060eec">

**Comment by Kozovskaya** [comment] 2024-05-23 11:15
Hello @gauravsharma771077 
Launch statistics chart is build based on the filter applied. Could you please check you filter conditions?
![image](https://github.com/reportportal/reportportal/assets/106231727/79d20f55-a326-4688-a4a6-ff82ba84e0fa)

**Comment by gauravsharma771077** [comment] 2024-05-23 12:19
Hi @Kozovskaya ,
I checked with multiple filter, chart is working for me but issue is it's showing data in single chart for both the filter. 
<img width="914" alt="Screenshot 2024-05-23 at 5 43 32 PM" src="https://github.com/reportportal/reportportal/assets/144100097/2de71dd5-5ae6-4062-9c8f-ec0b5149f92a">

I think it's causing issues due to similar name APIM in both the filter.

**Comment by mbryl6** [comment] 2024-05-23 13:45
Hello @gauravsharma771077,
Could you please show the full view of the APIM filter, from 'Filters' screen? I've tried to reproduce this case on our environment, reporting 2 launches APIM and APIMADMIN respectively with their own suites, test and steps and wasn't able to reproduce this issue.

**Comment by gauravsharma771077** [comment] 2024-05-27 05:07
Hi @mbryl6,
Please find the attached screenshot below.
<img width="1415" alt="Screenshot 2024-05-27 at 10 36 12 AM" src="https://github.com/reportportal/reportportal/assets/144100097/633671b7-90aa-412a-8fc8-7c87df427f7d">

**Comment by Kozovskaya** [comment] 2024-05-27 06:26
Hello @gauravsharma771077 
Based on the screenshot above, if you are trying to create the widget using the APIM filter it will include both launches - APIM and APIMADMIN. The filter APIM has a condition that launch **name should contain** , but if you choose that launch name should be **equal**, then only one launch will be taken into consideration.

**Comment by gauravsharma771077** [comment] 2024-05-27 06:33
Hi @Kozovskaya,
I tried equal to condition as well but this was not working for me.
![Uploading Screenshot 2024-05-27 at 12.00.42 PM.png…]()

**Comment by gauravsharma771077** [comment] 2024-05-29 11:47
Any update ?

**Comment by Kozovskaya** [comment] 2024-05-29 12:38
Hello @gauravsharma771077,
unfortunately the issue is not reproducable on our side. 
Could you please make a small video:
1) how you create the widget using Filter with launch name='APIM'
2) when the widget is created, drill down to the widget data by clicking on the bar on the widget confirming that the widget consists not only from tests from APIM launch but also from APIMADMIN launch.
Maybe this will help us to understand what does wrong.
Thanks in advance

**Comment by Kozovskaya** [comment] 2024-06-11 08:17
@gauravsharma771077 hello,
is the issue still reproducable on your side?

**Comment by Kozovskaya** [comment] 2024-06-20 05:50
@gauravsharma771077 I will close the issue as not reproduceble at our side. 
In case the issue is still relevant - don't hesitate to reopen it and provide more information about the issue.

**Closed by Kozovskaya** 2024-06-20 05:50 UTC
Labels: bug, Check: Test
