### ISSUE TITLE
[v5] Widget table column width (Unique bugs table)

### ISSUE THREAD

**Issue by shaburov** [reportportal/reportportal#911] opened 2020-04-05 14:04 UTC
Current version: API Service: 5.0.0;Index Service: 5.0.5;Authorization Service: 5.0.0;Service UI: 5.0.0;

Expected **FOUND IN** Alignment
![image](https://user-images.githubusercontent.com/15269131/78500504-7b276800-775f-11ea-964f-8643fb06f0f6.png)

**Comment by evjlobanova** [comment] 2020-04-06 08:06
Connected with #906

**Comment by svettsova** [comment] 2020-10-14 06:00
The issue is fixed in 5.3.3

**Closed by svettsova** 2020-10-14 06:00 UTC
Labels: bug, component:ui
