### ISSUE TITLE
Automatically remove old build - Not working

### ISSUE THREAD

**Issue by 765119** [reportportal/reportportal#1262] opened 2020-12-29 15:25 UTC
RP version - 5.3.2
Describe the bug
I have set up 'Keep launches' setting as 1 week, but older builds are not being deleted automatically.

Expected behavior
As per documentation, all builds older than the specified duration should get deleted automatically

Screenshots
<img width="818" alt="Screen Shot 2020-12-29 at 9 23 32 AM" src="https://user-images.githubusercontent.com/73659561/103294556-b6398d80-49b7-11eb-9508-982c775469b1.png">

**Comment by pprraashant** [comment] 2021-01-07 11:59
yes I am also facing same issue with  5.3.2 . it reached me to dead point in storage and was unable to bring the docker postgres service up . until i have increased the storage of mounted storage. 

Most of the data is consumed in logs and  test_items if anyone have queries to delete them please update here also i see delete from UI is also not helping much we have around 55 gb of data from last 3 months only

**Comment by code255255** [comment] 2021-01-07 19:38
I reinstalled the report portal 3 times so far when memory is full, any update on this ticket?

**Comment by evjlobanova** [comment] 2021-01-15 11:14
Duplicate of #1231 
Please follow the progress on this issue in the mentioned ticket

**Closed by evjlobanova** 2021-01-15 11:14 UTC
Labels: bug
