### ISSUE TITLE
[v5] Very poor scroll performance

### ISSUE THREAD

**Issue by qtis** [reportportal/reportportal#867] opened 2020-03-24 08:10 UTC
**Describe the bug**
Very poor scroll performance for launch items accessed via "passed" or "failed" link.

**To Reproduce**
Open launch by clicking on passed or failed items count from launch list. Try to scroll using mouse wheel. It is easier to notice poor performance when you have more items in the launch items page. For me it was more than 50, so first page showed 50 items).

**Expected behavior**
Scrolling is smooth, feels like with native scrollbar.

**Screenshots**
![image](https://user-images.githubusercontent.com/16225254/77403403-e31d9c00-6db8-11ea-8214-9dfc7ac7b046.png)

![image](https://user-images.githubusercontent.com/16225254/77402656-aac98e00-6db7-11ea-9423-a3a7dc20bff7.png)
(Check additional context section)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser Chrome
 - Version 80.0.3987.149

**Additional context**
_Possible issue found?_
It looks like JS scroll handler is registering too many times. If I'd open inspector and check how many scroll subscribers there are on "scrolling-content" element - I'd see loads. Clicking remove on nearly all of them would increase performance to the one expected (smooth and feels like native).

**Comment by evjlobanova** [comment] 2020-03-24 10:10
@e-olga @VolhaKarenko could you please check, if you can reproduce this issue?

**Comment by evjlobanova** [comment] 2020-06-29 14:25
https://reportportal.io/docs/How-to-resolve
@qtis please try to check points described in the article. 
Could you please let us know if it helps

**Comment by qtis** [comment] 2020-06-29 14:27
nope, not server issue, javascript/frontend bug

**Comment by evjlobanova** [comment] 2020-06-29 14:35
@qtis thank you for information
@DiscoElevator Maxim could you please share your vision on how this bug can be resolved

**Comment by DiscoElevator** [comment] 2020-06-29 14:39
Could be possibly fixed by setting `enableEventListeners` property to `false` for popper. I don't think we really need scroll/resize listeners here. But it needs to be double-checked to make sure it won't break anything.

**Comment by VolhaKarenko** [comment] 2020-10-07 09:09
Jira ticket is created

**Comment by VolhaKarenko** [comment] 2020-10-29 14:39
The issue is fixed in version 5.3.3

**Closed by VolhaKarenko** 2020-10-29 14:39 UTC
Labels: bug, component:ui
