### ISSUE TITLE
Clone dashboard

### ISSUE THREAD

**Issue by ksuglotova** [reportportal/reportportal#194] opened 2017-07-21 14:55 UTC
Received from @ kostia.izotov Slack / reportportal / general

Can I clone a dashboard? 
**Use case:** there's a dashboard, I need another 10 similar ones but with slightly different filters (for other environments, suites, tests - Selenium/Rest/Unit) and shared dashboard shows the same launches. I need information about tests on higher and lower environments with different statistics.

**Comment by evjlobanova** [comment] 2020-04-02 13:25
Duplicate of #784

**Closed by evjlobanova** 2020-04-02 13:25 UTC
Labels: Feature: BuildReport, enhancement, feature request
