### ISSUE TITLE
[v5]If I delete all projects I can't login anymore

### ISSUE THREAD

**Issue by b1zzu** [reportportal/reportportal#838] opened 2020-02-27 08:49 UTC
**Describe the bug**

I deleted all Projects using the `superadmin` user and then I couldn't login anymore

```
An error occurred while connecting to server: You do not have enough permissions. Project role 'null' not found. Did you use correct Role Name?
```

**To Reproduce**

**Expected behavior**

To be able to login or somehow recreate a project using the ui.

**Desktop:**
 - OS: Fedora
 - Browser chrome

**Comment by DzmitryHumianiuk** [comment] 2020-02-27 13:26
Well, i would say it's expected :)
no projects - no permission to see anything.

but we definitely should think of natural way to process it.

**Comment by b1zzu** [comment] 2020-02-28 10:21
Hi, I understand that's a strange situation, but having at least the possibility to create a new project if there are no one will be nice

**Comment by DzmitryHumianiuk** [comment] 2020-02-28 11:59
@b1zzu there should be a mechanism to keep personal project always available.
Login to RP, where there is no any project, should create personal space for user (personal project).

if it is not - than it is a bug.

**Comment by b1zzu** [comment] 2020-02-28 12:43
@DzmitryHumianiuk maybe it's not doing it for the admin user, or the mechanism is in place only for the user accessing using external authentication (github, sso, ..)

**Comment by DzmitryHumianiuk** [comment] 2020-03-02 14:13
@b1zzu looks like for external authes only.
@e-olga @evjlobanova please double check and consider as a bug if occurs.

**Comment by e-olga** [comment] 2020-03-04 07:21
Good day,
@b1zzu, @DzmitryHumianiuk , the issue is fixed in version 5.1.

Regards,
Olga

**Closed** 2020-03-04 08:19 UTC
