### ISSUE TITLE
Not Receiving Email of report after adding Notification rule

### ISSUE THREAD

**Issue by paresh-celigo** [reportportal/reportportal#2221] opened 2024-02-05 07:39 UTC
Hi Team,
I have added Notification rule from 2 months till 3 days back it was able to send report mail and was working fine, but Now its not sending mail without any changes in report portal,
Can you please help me with issue...

**Comment by ShivaPotlapelli** [comment] 2024-02-05 07:41
facing same issue here as well. can we address this asap

**Comment by alena-babrova** [comment] 2024-02-05 12:32
Hello @paresh-celigo,

Please provide more details:
- What is the status of Email Server integration? 
- What SMTP provider do you use? Did you try with different providers?
- Maybe you can provide server logs with error details?

**Comment by paresh-celigo** [comment] 2024-02-06 06:09
Hi @alena-babrova  here is the details:
![image](https://github.com/reportportal/reportportal/assets/141011973/8e750c52-324d-4716-be35-3a6f5365a661)

**Comment by vitaliirymar** [comment] 2024-02-06 09:50
We use TLS and port 587. Also we use our org SMTP server e.g.: `smtp.send.net`. Need to fond out where is the root cause and don't know how to start the troubleshooting.

**Comment by alena-babrova** [comment] 2024-02-06 09:56
Dear @vitaliirymar,

Did your Email Server integration work before? 
Do you have an error when you are trying to configure the integration or emails are not being sent?
Please provide some screenshots and error logs from API service.

**Comment by ShivaPotlapelli** [comment] 2024-02-07 09:32
@vitaliirymar 
please find the api logs
[api.txt](https://github.com/reportportal/reportportal/files/14191594/api.txt)
please find error logs
2024-02-06 20:49:31.110 ERROR 1 --- [585-exec-352582] c.e.t.r.c.e.rest.RestExceptionHandler    : Handled error:2024-02-06 20:49:31.110 ERROR 1 --- [585-exec-352582] .t.r.c.e.r.ReportPortalExceptionResolver : ReportPortalExceptionResolver > Validation failed for argument [3] in public com.epam.ta.reportportal.ws.model.EntryCreatedAsyncRS com.epam.ta.reportportal.ws.controller.TestItemController.startChildItem(java.lang.String,com.epam.ta.reportportal.commons.ReportPortalUser,java.lang.String,com.epam.ta.reportportal.ws.model.StartTestItemRQ): [Field error in object 'startTestItemRQ' on field 'name': rejected value [TC_C26220 with /flows/{{C26220FlowId}}/{{C26220ImportId}}/requests/thisisathousandcharaterwordkeyweareaddingthiskeytogetkeyistoolongerrorwhichisas3keyweaddmorecharaterssothekeylengthcanbeyouknowthousandcharaterlengthifyouhavesomethingtoaddyouadditheretoosincewewontbeabletoaddthousandcharaterwithoutaddjunkheremaybethewordingneedtobenonviolentbutyoucanaddanycharatersyouwantuntilitcrossthethousandcxharatermarkaddsomegoodstuffsoifsomeoonereadsittheycanthinkitsagoodideainsteadofwhatthepuckiamkeeponwritingitanditdidntevencrossfivehundreadcharaterhowmuchdoineedtoaddittomakeitathousandcharaterwhyisitsohardtowriteitmaybeishouldhaveusedsomeonlinetextgeneratetogetthetextbutwellialreadystartedsoishouldfinishwhatistarteddoyouthinkicancompletethiswhoknowslethopewehaveaproperkeyatthendofthedaymaybeishouldmentionedthisindsuthatiworkonwritingathousandcharterwordformytestcasesmaybetheythinkiworkhardandpromotemeahaitnotthateasytodothiskindofjobiwonderifthereisjobtowritestufflikethisandpostitinonlineijustcheckcharatercountandthisisnearathousandcharaterithinkwecanclosethisconversationsoonmaybethisthelastlineletcountthecharaterstheend]; codes [NotBlankWithSize.startTestItemRQ.name,NotBlankWithSize.name,NotBlankWithSize.java.lang.String,NotBlankWithSize]; arguments [org.springframework.context.support.DefaultMessageSourceResolvable: codes [startTestItemRQ.name,name]; arguments []; default message [name],1024,1]; default message [Field ''{0}'' should have size from ''{2}'' to ''{1}''.]]2024-02-06 20:49:31.110 ERROR 1 --- [585-exec-352582] c.e.t.r.c.e.rest.DefaultErrorResolver    : Validation failed for argument [3] in public com.epam.ta.reportportal.ws.model.EntryCreatedAsyncRS com.epam.ta.reportportal.ws.controller.TestItemController.startChildItem(java.lang.String,com.epam.ta.reportportal.commons.ReportPortalUser,java.lang.String,com.epam.ta.reportportal.ws.model.StartTestItemRQ): [Field error in object 'startTestItemRQ' on field 'name': rejected value [TC_C26220 with /flows/{{C26220FlowId}}/{{C26220ImportId}}/requests/thisisathousandcharaterwordkeyweareaddingthiskeytogetkeyistoolongerrorwhichisas3keyweaddmorecharaterssothekeylengthcanbeyouknowthousandcharaterlengthifyouhavesomethingtoaddyouadditheretoosincewewontbeabletoaddthousandcharaterwithoutaddjunkheremaybethewordingneedtobenonviolentbutyoucanaddanycharatersyouwantuntilitcrossthethousandcxharatermarkaddsomegoodstuffsoifsomeoonereadsittheycanthinkitsagoodideainsteadofwhatthepuckiamkeeponwritingitanditdidntevencrossfivehundreadcharaterhowmuchdoineedtoaddittomakeitathousandcharaterwhyisitsohardtowriteitmaybeishouldhaveusedsomeonlinetextgeneratetogetthetextbutwellialreadystartedsoishouldfinishwhatistarteddoyouthinkicancompletethiswhoknowslethopewehaveaproperkeyatthendofthedaymaybeishouldmentionedthisindsuthatiworkonwritingathousandcharterwordformytestcasesmaybetheythinkiworkhardandpromotemeahaitnotthateasytodothiskindofjobiwonderifthereisjobtowritestufflikethisandpostitinonlineijustcheckcharatercountandthisisnearathousandcharaterithinkwecanclosethisconversationsoonmaybethisthelastlineletcountthecharaterstheend]; codes [NotBlankWithSize.startTestItemRQ.name,NotBlankWithSize.name,NotBlankWithSize.java.lang.String,NotBlankWithSize]; arguments [org.springframework.context.support.DefaultMessageSourceResolvable: codes [startTestItemRQ.name,name]; arguments []; default message [name],1024,1]; default message [Field ''{0}'' should have size from ''{2}'' to ''{1}''.]]2024-02-07 03:43:40.907 ERROR 1 --- [585-exec-355834] c.e.t.r.c.e.rest.RestExceptionHandler    : Handled error:2024-02-07 03:43:40.908 ERROR 1 --- [585-exec-355834] .t.r.c.e.r.ReportPortalExceptionResolver : ReportPortalExceptionResolver > Validation failed for argument [3] in public com.epam.ta.reportportal.ws.model.EntryCreatedAsyncRS com.epam.ta.reportportal.ws.controller.TestItemController.startChildItem(java.lang.String,com.epam.ta.reportportal.commons.ReportPortalUser,java.lang.String,com.epam.ta.reportportal.ws.model.StartTestItemRQ): [Field error in object 'startTestItemRQ' on field 'name': rejected value [TC_C26214 with /flows/{{C26214flowId}}/{{C26214exportId}}/requests/asdfghjk123456vhk245asdfghjk123456vhk245asdfghjk123456vhk245asdfghjk123456vhk245asdfghjk123456vhk245asdfghjk123456vhk245asdfghjk123456vhk245asdfghjk123456vhk245asdfghjk123456vhk245asdfghjk123456vhk245asdfghjk123456vhk245asdfghjk123456vhk245asdfghjk123456vhk245asdfghjk123456vhk245asdfghjk123456vhk245asdfghjk123456vhk245asdfghjk123456vhk245asdfghjk123456vhk245asdfghjk123456vhk245asdfghjk123456vhk245asdfghjk123456vhk245asdfghjk123456vhk245asdfghjk123456vhk245asdfghjk123456vhk245asdfghjk123456vhk245asdfghjk123456vhk245asdfghjk123456vhk245asdfghjk123456vhk245asdfghjk123456vhk245asdfghjk123456vhk245asdfghjk123456vhk245asdfghjk123456vhk245asdfghjk123456vhk245asdfghjk123456vhk245asdfghjk123456vhk245asdfghjk123456vhk245asdfghjk123456vhk245asdfghjk123456vhk245asdfghjk123456vhk245asdfghjk123456vhk245asdfghjk123456vhk245asdfghjk123456vhk245asdfghjk123456vhk245asdfghjk123456vhk245asdfghjk123456vhk245asdfghjk123456vhk245asdfghjk123456vhk245asdfghjk123456vhk245asdfghjk123456vhk245asdfghjk123456vhk245]; codes [NotBlankWithSize.startTestItemRQ.name,NotBlankWithSize.name,NotBlankWithSize.java.lang.String,NotBlankWithSize]; arguments [org.springframework.context.support.DefaultMessageSourceResolvable: codes [startTestItemRQ.name,name]; arguments []; default message [name],1024,1]; default message [Field ''{0}'' should have size from ''{2}'' to ''{1}''.]]2024-02-07 03:43:40.908 ERROR 1 --- [585-exec-355834] c.e.t.r.c.e.rest.DefaultErrorResolver    : Validation failed for argument [3] in public com.epam.ta.reportportal.ws.model.EntryCreatedAsyncRS com.epam.ta.reportportal.ws.controller.TestItemController.startChildItem(java.lang.String,com.epam.ta.reportportal.commons.ReportPortalUser,java.lang.String,com.epam.ta.reportportal.ws.model.StartTestItemRQ): [Field error in object 'startTestItemRQ' on field 'name': rejected value [TC_C26214 with /flows/{{C26214flowId}}/{{C26214exportId}}/requests/asdfghjk123456vhk245asdfghjk123456vhk245asdfghjk123456vhk245asdfghjk123456vhk245asdfghjk123456vhk245asdfghjk123456vhk245asdfghjk123456vhk245asdfghjk123456vhk245asdfghjk123456vhk245asdfghjk123456vhk245asdfghjk123456vhk245asdfghjk123456vhk245asdfghjk123456vhk245asdfghjk123456vhk245asdfghjk123456vhk245asdfghjk123456vhk245asdfghjk123456vhk245asdfghjk123456vhk245asdfghjk123456vhk245asdfghjk123456vhk245asdfghjk123456vhk245asdfghjk123456vhk245asdfghjk123456vhk245asdfghjk123456vhk245asdfghjk123456vhk245asdfghjk123456vhk245asdfghjk123456vhk245asdfghjk123456vhk245asdfghjk123456vhk245asdfghjk123456vhk245asdfghjk123456vhk245asdfghjk123456vhk245asdfghjk123456vhk245asdfghjk123456vhk245asdfghjk123456vhk245asdfghjk123456vhk245asdfghjk123456vhk245asdfghjk123456vhk245asdfghjk123456vhk245asdfghjk123456vhk245asdfghjk123456vhk245asdfghjk123456vhk245asdfghjk123456vhk245asdfghjk123456vhk245asdfghjk123456vhk245asdfghjk123456vhk245asdfghjk123456vhk245asdfghjk123456vhk245asdfghjk123456vhk245asdfghjk123456vhk245]; codes [NotBlankWithSize.startTestItemRQ.name,NotBlankWithSize.name,NotBlankWithSize.java.lang.String,NotBlankWithSize]; arguments [org.springframework.context.support.DefaultMessageSourceResolvable: codes [startTestItemRQ.name,name]; arguments []; default message [name],1024,1]; default message [Field ''{0}'' should have size from ''{2}'' to ''{1}''.]]

**Comment by alena-babrova** [comment] 2024-02-08 07:47
Hello @vitaliirymar,

Could you please answer my questions:
Did your Email Server integration work before?
Do you have an error when you are trying to configure the integration or emails are not being sent on launch finish?

**Comment by ShivaPotlapelli** [comment] 2024-02-08 07:53
@alena-babrova please update us on the above error

**Comment by alena-babrova** [comment] 2024-02-08 07:56
@ShivaPotlapelli thank for your update.

Please, answer on my questions that I've asked two times. 

As for the logs - what action did you do when the error happened? Because at the first glance I don't see any SMTP related errors there.

**Comment by vitaliirymar** [comment] 2024-02-08 08:13
> Hello @vitaliirymar,
> 
> Could you please answer my questions:
> Did your Email Server integration work before?
> Do you have an error when you are trying to configure the integration or emails are not being sent on launch finish?

Hi @alena-babrova 
This is the first time integration, and we've never seen email notifications.
Had no time to check logs yet. Now, when you provided the service, I know where to check. Will update, when I have the information.

**Comment by alena-babrova** [comment] 2024-02-08 08:20
Dear @vitaliirymar,
I would suggest checking the following flow:
1. Make sure that you have valid SMTP credentials (you can log in using them in your email account)
2. Try to make Email integration in ReportPortal with correct port/SSL or TLS
3. If error happens, make a screenshot and attach here. Also, go to API service and provide logs

If Email integration is successful, **make sure you have notification rules configured correctly** (Project Settings -> Notifications).

**Comment by vitaliirymar** [comment] 2024-02-08 08:25
> Dear @vitaliirymar,
> I would suggest checking the following flow:
> 1. Make sure that you have valid SMTP credentials (you can log in using them in your email account)
> 2. Try to make Email integration in ReportPortal with correct port/SSL or TLS
> 3. If error happens, make a screenshot and attach here. Also, go to API service and provide logs
> 
> If Email integration is successful, **make sure you have notification rules configured correctly** (Project Settings -> Notifications).

@alena-babrova 
1. This company smtp integration doesn't require credentials.
2. We don't face errors during integration configuration. 
3. Ok.
Rules are configured correctly.

**Comment by alena-babrova** [comment] 2024-02-11 17:48
@vitaliirymar,
So sounds like Configuration step is successful and is without any errors.
Then we need to see what error happens on Launch Finish (because emails are configured to be sent on Launch Finish event).
Please, provide the api-service's **log when finishing a launch** - so that we can investigate what is wrong with sending.

**Comment by alena-babrova** [comment] 2024-02-11 17:50
#@alena-babrova please update us on the above error

ShivaPotlapelli,
as for the error log you provided, you can see that the problem is in the length of the names of your test items. By default, ReportPortal does not allow names of Tests/Steps with the length more than 1024 symbols.

**Comment by ShivaPotlapelli** [comment] 2024-02-12 05:37
@alena-babrova all this days it worked and all of sudden do u thin its because of names of the test ..i don't think its because of that.

**Comment by alena-babrova** [comment] 2024-02-12 08:45
@ShivaPotlapelli,

I'm just trying to help you based on the information you provided. At the moment I don't know what happens as well, except the fact with "long names".
I still don't have any evidence of SMTP errors in logs.

**Comment by ShivaPotlapelli** [comment] 2024-02-14 08:49
@alena-babrova I need a way to get back the things working as usual..at the moment am not able to delete the rules as well..to establish them from scratch..am struck up on this..we wanted to stop using report portal because of this imp bug
@DzmitryHumianiuk / @alena-babrova / [Pink-Bumblebee](https://github.com/Pink-Bumblebee)

**Comment by ShivaPotlapelli** [comment] 2024-02-16 07:09
@DzmitryHumianiuk / @alena-babrova / [Pink-Bumblebee](https://github.com/Pink-Bumblebee) can one of u lookinto

**Comment by alena-babrova** [comment] 2024-02-16 08:37
Dear @ShivaPotlapelli,

Let's try once again. 
Please, comment on the steps to understand where the issue is:
1. You have successfully configured Email Integration (it has green "connected" status)
2. You've configured an appropriate Notifications rule (e.g., always to send notification for any Launch finish, recipient with valid email is specified)
3. You are trying to post test results (Launches) and they are posted successfully, you can see the results listed on the Launches page in ReporPortal. Launch is in finished stated.
4. Has the recipient which is mentioned in the notification rule from #2 received an email?
If there is no email, then we need the logs from the "api-service" for **the moment when Launch gets finished** to see whether the SMTP sending was initiated and if there are any errors related to it.

Please, go through the steps and validate/comment each of them.
Without having the full picture and details, it's hard to tell where the issue is.

**Comment by ShivaPotlapelli** [comment] 2024-02-19 03:58
@alena-babrova Thanks for your reply and responding to my previous responses quickly.
Its because of SMTP errors in logs and api service pods being used 90% limit
we can close this now

**Comment by alena-babrova** [comment] 2024-02-19 09:33
Dear @ShivaPotlapelli,

Thank you for the update. And it's good to know that the issue is resolved on your side.

**Comment by alena-babrova** [comment] 2024-02-19 09:35
Dear @vitaliirymar,

Could you tell me please if the issue is still relevant for you or we can close the ticket?

**Comment by vitaliirymar** [comment] 2024-02-19 09:55
Dear @alena-babrova ! Can't find any logs related to smtp. What can be keywords there? SMTP? Email? exchange? message?

**Comment by alena-babrova** [comment] 2024-02-19 10:35
Dear @vitaliirymar,

Please, try to go through the instruction above (https://github.com/reportportal/reportportal/issues/2221#issuecomment-1947962286) and provide as many details as possible. It might us to find the root cause of your issue.

**Comment by vitaliirymar** [comment] 2024-02-20 09:41
@alena-babrova see this error. But I doubt it is related to smtp. Also I see the results in ReportPortal.
2024-02-20 09:28:56.224 ERROR 1 --- [8585-exec-15668] .AuthUtils$SerialUidReplacingInputStream : Potentially Fatal Deserialization Operation.
java.io.InvalidClassException: Overriding serialized class version mismatch: local serialVersionUID = 550 stream serialVersionUID = 520
at com.epam.ta.reportportal.auth.util.AuthUtils$SerialUidReplacingInputStream.readClassDescriptor(AuthUtils.java:105)
at java.base/java.io.ObjectInputStream.readNonProxyDesc(ObjectInputStream.java:1992)
at java.base/java.io.ObjectInputStream.readClassDesc(ObjectInputStream.java:1870)
at java.base/java.io.ObjectInputStream.readOrdinaryObject(ObjectInputStream.java:2201)
at java.base/java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1687)
at java.base/java.io.ObjectInputStream.readObject(ObjectInputStream.java:489)
at java.base/java.io.ObjectInputStream.readObject(ObjectInputStream.java:447)
at java.base/java.util.TreeSet.readObject(TreeSet.java:524)
at java.base/jdk.internal.reflect.GeneratedMethodAccessor229.invoke(Unknown Source)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:566)
at java.base/java.io.ObjectStreamClass.invokeReadObject(ObjectStreamClass.java:1046)
at java.base/java.io.ObjectInputStream.readSerialData(ObjectInputStream.java:2357)
at java.base/java.io.ObjectInputStream.readOrdinaryObject(ObjectInputStream.java:2228)
...

**Comment by alena-babrova** [comment] 2024-02-20 10:01
Dear @vitaliirymar, yes, you are right. This error is related to switching to new Spring security. We have fixed the issue starting from version 24.1 (it will be released soon).
Anyway, this error log is not related to your issue.

Please, try to find out what is going on when launch finishes (number 4 from my instruction).

**Comment by vitaliirymar** [comment] 2024-02-21 17:46
@alena-babrova, can't find any relevant logs for email notifications. Checking Azure Firewall and NSG rules for the SMTP server.

**Comment by alena-babrova** [comment] 2024-02-22 16:03
Dear @vitaliirymar,

Plan A:
Let's try to exclude the parts that are OK in order to narrow down the search area where the issue may be. Could I ask you to:
1. Provide screenshot with successful set up of email integration
2. Provide screenshot with notification rules (how they are configured)
3. Show on the screenshot that you have at least one finished Launch which matches at least one rule.


Plan B:
Also, I would suggest making a testing on your end with different SMTP provider. E.g. use any other valid email account with authentication for integration - will it work for different email account?
This way we will know if the problem is in ReportPortal or maybe it is related to your system/network configuration.

Other than that - it's hard to tell where the problem is since we don't have any logs with errors.

Thanks!

**Comment by vitaliirymar** [comment] 2024-02-22 16:05
@alena-babrova added also authentication to the configuration and now there is an error in log:
2024-02-22 15:45:35.501 ERROR 1 --- [stener-exec2832] c.e.t.r.c.e.h.l.LaunchNotificationRunner : Unable to send email.
org.springframework.mail.MailSendException: Failed messages: com.sun.mail.smtp.SMTPSendFailedException: 550 MIME message is missing 'From' header
 Can it be related to the non-email value in Sender email field?
 
![image](https://github.com/reportportal/reportportal/assets/102508788/dd63363f-5f16-4c1e-bf5f-7ac489ad688b)

**Comment by alena-babrova** [comment] 2024-02-22 17:23
@vitaliirymar,
Please try using full email address in the "Sender email" field instead of just username.

**Closed** 2024-02-24 11:28 UTC
Labels: bug

**Comment by vitaliirymar** [comment] 2024-02-27 15:35
Hi @alena-babrova ! The issue is fixed by adding a real email to `Default sender name`

**Comment by alena-babrova** [comment] 2024-02-28 10:05
Dear @vitaliirymar,
Yes, you are right. Seems like we have a validation bug on the "Email integration" form - "Sender email" should be a required field.
I have created a ticket to fix that in the nearest release.

Thank you for your contribution!
