### ISSUE TITLE
Access without password

### ISSUE THREAD

**Issue by mva730** [reportportal/reportportal#164] opened 2017-07-03 09:17 UTC
As RP user I want to share test launch statistics with my customer. But to get this information customers should have login and password. It would be nice to have public board with statistics

**Comment by avarabyeu** [comment] 2017-07-06 10:22
the same situation with reportportal/reportportal#166
We think about making another version of authorization service that does not require login at all. But in this case you will have no users and no projects at all. Would it be convenient to you?

**Comment by evjlobanova** [comment] 2017-11-13 09:41
This issue is closed as a duplicate of #2

**Closed** 2017-11-13 09:42 UTC
Labels: duplicate, feature request
