### ISSUE TITLE
Expression '\Users' is replaced with spaces

### ISSUE THREAD

**Issue by fasterfish** [reportportal/reportportal#80] opened 2017-02-27 12:36 UTC
As a report portal user:

Given I have .Net/Java client
When I send log message 'C:\Users\UserName\Desktop\Something'
Then I want to receive message correctly on report portal

Actual: I receive next message 'C:      \UserName\Desktop\Something'

The expression '\Users' is replaced with spaces at the report portal.

**Comment by avarabyeu** [comment] 2017-02-28 08:15
@fasterfish Unfortunately, cannot reproduce an issue. Could you please share some unit test in java to be able to reproduce? 
Logger type? Logger configuration? Version? 
Thanks!

**Comment by iKozzz** [comment] 2017-03-01 09:46
Hey. I'm using logback
`private static final Logger LOGGER = LoggerFactory.getLogger("binary_data_logger");`

sending to RP 
`LOGGER.info("Blablabla\Users")`

and result on RP is logged as:
`"Blablabla "`


pom dependencies:
`        <dependency>
            <groupId>com.epam.reportportal</groupId>
            <artifactId>logger-java-logback</artifactId>
            <version>2.6.0</version>
        </dependency>
`
and
`
        <dependency>
            <groupId>ch.qos.logback</groupId>
            <artifactId>logback-classic</artifactId>
            <version>1.1.3</version>
        </dependency>
`

**Comment by avarabyeu** [comment] 2017-03-01 12:03
[Compilation error](http://prntscr.com/eemlb8)

**Comment by iKozzz** [comment] 2017-03-01 14:08
Nice, actually i was using
import org.slf4j.Logger;
import org.slf4j.LoggerFactory
with Logback

just realized. And after I have changed logger to `import org.apache.log4j.Logger` I started to get compilation error

**Comment by avarabyeu** [comment] 2017-03-01 14:43
This is not related to frameworks, this is just unescaped symbol in string literal

**Comment by nvborisenko** [comment] 2017-03-01 15:11
API returns correct log message, UI shows this message incorrectly: [http://prntscr.com/eep6i1](url)

**Comment by avarabyeu** [comment] 2017-03-02 12:54
@lexecon Alexey, could you please check on UI side

**Comment by lexecon** [comment] 2017-03-16 08:16
Fixed in version 3.0

**Closed** 2017-03-16 08:22 UTC
Labels: bug
