### ISSUE TITLE
[v5] LDAP Auth fails with error "There is no PasswordEncoder mapped for the id “null”"

### ISSUE THREAD

**Issue by rkumarrb** [reportportal/reportportal#954] opened 2020-05-07 14:24 UTC
**Describe the bug**
After configuring the LDAP, When tried to login, it throws the error There is no PasswordEncoder mapped for the id “null”"

In the logs, we can see that it is able to find the user and when logins with credentials, it fails.

**To Reproduce**

Configure LDAP with Report portal 5.1 and try logging in with LDAP user

**Expected behavior**
Report portal should log in when correct credentials provided

**Screenshots**
Login page

![image](https://user-images.githubusercontent.com/6379299/81305478-5ec36780-904c-11ea-8769-278fde39eeeb.png)

LDAP Configuration page

![image](https://user-images.githubusercontent.com/6379299/81305759-b5c93c80-904c-11ea-981e-c3eeb7c8c450.png)

**Desktop (please complete the following information):**
 - OS: [e.g. iOS]: Mac OS
 - Browser [e.g. chrome, safari]: Chrome
 - Version [e.g. 22] :  81.0.4044.129

**Smartphone (please complete the following information):**

**Additional context**

**Comment by s-reimer** [comment] 2020-05-11 15:59
Here's a stack trace from the UAT container
```
java.lang.IllegalArgumentException: There is no PasswordEncoder mapped for the id "null"
	at org.springframework.security.crypto.password.DelegatingPasswordEncoder$UnmappedIdPasswordEncoder.matches(DelegatingPasswordEncoder.java:250) ~[spring-security-core-5.2.2.RELEASE.jar!/:5.2.2.RELEASE]
	at org.springframework.security.crypto.password.DelegatingPasswordEncoder.matches(DelegatingPasswordEncoder.java:198) ~[spring-security-core-5.2.2.RELEASE.jar!/:5.2.2.RELEASE]
	at com.epam.reportportal.auth.integration.ldap.LdapAuthProvider$1.matches(LdapAuthProvider.java:110) ~[classes!/:na]
	at org.springframework.security.ldap.authentication.PasswordComparisonAuthenticator.isPasswordAttrCompare(PasswordComparisonAuthenticator.java:121) ~[spring-security-ldap-5.2.2.RELEASE.jar!/:5.2.2.RELEASE]
	at org.springframework.security.ldap.authentication.PasswordComparisonAuthenticator.authenticate(PasswordComparisonAuthenticator.java:109) ~[spring-security-ldap-5.2.2.RELEASE.jar!/:5.2.2.RELEASE]
	at org.springframework.security.ldap.authentication.LdapAuthenticationProvider.doAuthentication(LdapAuthenticationProvider.java:187) ~[spring-security-ldap-5.2.2.RELEASE.jar!/:5.2.2.RELEASE]
	at org.springframework.security.ldap.authentication.AbstractLdapAuthenticationProvider.authenticate(AbstractLdapAuthenticationProvider.java:85) ~[spring-security-ldap-5.2.2.RELEASE.jar!/:5.2.2.RELEASE]
	at com.epam.reportportal.auth.EnableableAuthProvider.authenticate(EnableableAuthProvider.java:49) ~[classes!/:na]
	at org.springframework.security.authentication.ProviderManager.authenticate(ProviderManager.java:175) ~[spring-security-core-5.2.2.RELEASE.jar!/:5.2.2.RELEASE]
	at org.springframework.security.oauth2.provider.password.ResourceOwnerPasswordTokenGranter.getOAuth2Authentication(ResourceOwnerPasswordTokenGranter.java:75) ~[spring-security-oauth2-2.4.0.RELEASE.jar!/:na]
	at org.springframework.security.oauth2.provider.token.AbstractTokenGranter.getAccessToken(AbstractTokenGranter.java:76) ~[spring-security-oauth2-2.4.0.RELEASE.jar!/:na]
	at org.springframework.security.oauth2.provider.token.AbstractTokenGranter.grant(AbstractTokenGranter.java:71) ~[spring-security-oauth2-2.4.0.RELEASE.jar!/:na]
	at org.springframework.security.oauth2.provider.CompositeTokenGranter.grant(CompositeTokenGranter.java:42) ~[spring-security-oauth2-2.4.0.RELEASE.jar!/:na]
	at org.springframework.security.oauth2.config.annotation.web.configurers.AuthorizationServerEndpointsConfigurer$4.grant(AuthorizationServerEndpointsConfigurer.java:587) ~[spring-security-oauth2-2.4.0.RELEASE.jar!/:na]
	at org.springframework.security.oauth2.provider.endpoint.TokenEndpoint.postAccessToken(TokenEndpoint.java:136) ~[spring-security-oauth2-2.4.0.RELEASE.jar!/:na]
	at jdk.internal.reflect.GeneratedMethodAccessor226.invoke(Unknown Source) ~[na:na]

```

It looks like this bug might be caused by upgrading from Spring Security 4 to Spring Security 5.

The encoded password sent to the PasswordEncoder constructed in [LdapAuthProvider](https://github.com/reportportal/service-authorization/blob/cdd1e8219688d016747534447ff803ed0a07472c/src/main/java/com/epam/reportportal/auth/integration/ldap/LdapAuthProvider.java#L110) seems to be missing the leading encoder id so the [DelegatingPasswordEncoder](https://github.com/spring-projects/spring-security/blob/master/crypto/src/main/java/org/springframework/security/crypto/password/DelegatingPasswordEncoder.java#L195) uses the [default encoder](https://github.com/spring-projects/spring-security/blob/master/crypto/src/main/java/org/springframework/security/crypto/password/DelegatingPasswordEncoder.java#L250) which throws this exception. 

This exact exception is thrown for all Password Encoder types available from the UI dropdown, leading me to believe that this is a bug.

Baeldung documents this exact error as a common problem when upgrading to Spring Security 5 https://www.baeldung.com/spring-security-5-default-password-encoder#springSecurity4

> If we use the same configuration under Spring Security 5, we'd get the following error:
> java.lang.IllegalArgumentException: There is no PasswordEncoder mapped for the id "null"
> The error tells us that the given password couldn't be decoded since no password encoder was configured for our in-memory authentication.

**Comment by Yumfriez** [comment] 2020-07-21 14:16
@evjlobanova @svettsova Probably we have to check it on our instances

**Comment by VolhaKarenko** [comment] 2020-08-03 09:54
Verified on version 5.3- not reproducible. @s-reimer please upgrade your RP version and let us know if the issue is still valid

**Comment by akolomiiets** [comment] 2020-09-30 10:20
Hi,
same issue with 5.3.1 k8s setup

**Comment by VolhaKarenko** [comment] 2020-09-30 12:16
A ticket in Jira is created for the issue

**Comment by akolomiiets** [comment] 2020-10-01 12:29
I deleted and create LDAP integration with Password encoder type "No" what resolve issue

**Comment by evjlobanova** [comment] 2020-10-27 08:49
@Yumfriez @akolomiiets Can we close this issue?

**Comment by pbortnik** [comment] 2021-03-04 16:46
Hi guys, @s-reimer @rkumarrb, @akolomiiets,
As a workaround, could you please try to provide in the parameter "passwordAttribute" : "userpassword" when you select another encoding type.
![image](https://user-images.githubusercontent.com/8058828/109998388-3a92ee80-7d22-11eb-87f4-f34616e969cb.png)

And give us a feedback after try.

**Closed** 2021-06-17 09:45 UTC
Labels: Check: BackEnd

**Comment by guptakapil** [comment] 2021-08-02 17:06
Two things helped me:

1. Manager DN (Which is the user which can query LDAP) 
2. Manager Password

After this I removed the integration and added it back. that worked!
