### ISSUE TITLE
ReportPortal AI/ML Feature is not working for with Build: 5.6.0

### ISSUE THREAD

**Issue by sharmadeepak43** [reportportal/reportportal#1808] opened 2022-08-09 05:08 UTC
**AI/ML is not working for the launches**
The AI/ML feature is not working for the failed test cases in report-portal.
The data set for ML in the previous launch is not reflecting for the next run.

**AI/ML feature should work as expected. The data set for the ML in previous launch is not reflecting next launch.**

Please refer the screenshot below -

<img width="1053" alt="Screenshot 2022-08-09 at 10 28 49 AM" src="https://user-images.githubusercontent.com/73647467/183568736-aa51672c-2398-4eeb-a94b-482bb12d2b6b.png">

**Versions:**
 - OS - MAC, Browser -Chrome
 - Version of RP - 5.6.0

**Comment by VolhaKarenko** [comment] 2022-11-03 15:58
Hi @sharmadeepak43, 
For now, I can guess 2 reasons for your case:
1. The logs of the failed test don't match the logs of previously failed tests or match by less than 40% 
2. The logs of previously failed tests were not saved to the ElasticSearch for some reason - please try generating the index ('Project settings' -> 'Auto-analysis' tab -> click 'Generate index' button)
By the way, [here is](https://reportportal.io/docs/ML-Suggestions) very informative documentation to read about the ML suggestions.
Could you please check once again and let me know if the issue is still relevant?

**Comment by dsharma8x8** [comment] 2022-11-16 08:44
Hi @VolhaKarenko 

Thanks for the response. Please find below response - 

1. The logs of the failed test don't match the logs of previously failed tests or match by less than 40% -:  **We have compared the previous and current launches, and the accuracy of logs matching is 100%. The test cases are failing with similar reason.**
2. The logs of previously failed tests were not saved to the ElasticSearch for some reason - please try generating the index ('Project settings' -> 'Auto-analysis' tab -> click 'Generate index' button) -:  **Index was already generated, though I generate it again. How we can check if the tests were not saved to the ElasticSearch in RP ??**

Can you please confirm if the attached screenshot of accuracy mode is correct. 
<img width="1130" alt="Screenshot 2022-11-16 at 2 12 50 PM" src="https://user-images.githubusercontent.com/78587439/202131316-ceea7be7-3603-4c3a-bcf6-f6e46aaf754b.png">

Please keep me posted if you have some other suggestions as well. Thanks!!

**Comment by VolhaKarenko** [comment] 2022-11-16 16:23
Hello @dsharma8x8,
Yes, the accuracy mode looks fine. All error logs are saved to the ElasticSearch as soon as a launch is finished, so there is no need to generate the index regularly, I was just thinking that some temporary failure could happen to the analyzer or API services so the logs were not saved.
To check the logs in ElasticSearch you can send the API request (using the data from the compose file): 
GET {{analyzerHost}}:{{analyzerPort}}/{{project_id}}/_search

One more thing I noticed is that 'Base for Auto Analysis' is set as 'Launches with the same name'. Are your previous and current launches named the same?
Also, please check the health of the analyzer container.

**Comment by MaryiaRymarchyk** [comment] 2023-03-13 05:57
Hi @dsharma8x8, do you have updates here?
Is the issue still relevant?

**Comment by MaryiaRymarchyk** [comment] 2023-04-03 10:55
Hi @dsharma8x8, 
long time no hear from you, so we'll close the issue for now.
Just in case you still have the issue, please, provide more details.

**Closed by MaryiaRymarchyk** 2023-04-03 10:55 UTC
Labels: bug, Waiting Info From Requestor
