### ISSUE TITLE
Typo on Log In page

### ISSUE THREAD

**Issue by batallo** [reportportal/reportportal#1721] opened 2022-04-18 21:59 UTC
**Describe the bug**
Typo on "_Current version:_" section on the Log In page

**Steps to reproduce**

1. Open https://reportportal.epam.com or https://rp.epam.com page
2. Verify "_EPAM Authorization Service:_" section

**Actual result**  
Redundant letter **s** in "_Authorization_"

**Screenshots**
![image](https://user-images.githubusercontent.com/79911099/163877171-a45ab98f-bf78-43f5-9cea-1bb91fa5b7da.png)

**Versions:**
 Current version: API Service: 5.6.3; Jobs Service: 5.6.3; EPAM Authorizsation Service: 5.6.3; Service UI: 5.6.0;

**Comment by batallo** [comment] 2022-04-18 22:00
My apologize, if this duplicates previously sent via mail bug report

**Comment by VolhaKarenko** [comment] 2022-04-19 14:29
The issue is fixed in 5.7

**Closed by VolhaKarenko** 2022-04-19 14:29 UTC
Labels: bug
