### ISSUE TITLE
[v5] Data corruption when performing batch "Link Issue"

### ISSUE THREAD

**Issue by dagansandler** [reportportal/reportportal#1183] opened 2020-10-19 20:32 UTC
**Describe the bug**
Data corruption when performing batch "Link Issue" on failures - Duplicate entries are created in the `ticket` table and subsequent actions fail - for example: api requests to `PUT /api/v1/{projectName}/item` with the same `ticketId` fail with the response:
```
{
  "errorCode": 5000,
  "message": "Unclassified error [query did not return a unique result: 10]"
}
``` 

**To Reproduce**
- In the UI, Mark multiple failed tests and select "Link Issue" from the Actions drop down:
- Link a jira issue that wasn't linked before - meaning it does not have an existing entry in the "ticket" table.
- Note that multiple entries are created in the "ticket" table.
- Perform a "PUT" request to on `/api/v1/{projectName}/item` with example request body: 
```
{
  "issues": [
    {
      "issue": {
        "autoAnalyzed": true,
        "comment": "comment",
        "externalSystemIssues": [
          {
            "btsProject": "AA",
            "btsUrl": "jira",
            "ticketId": "AA-000",
            "url": "jira/AA-000"
          }
        ],
        "ignoreAnalyzer": false,
        "issueType": "pb_001"
      },
      "testItemId": "12345678"
    }
  ]
}
```
**NOTE: ticketId in above payload should match the ticket Id that was linked in the batch operation**

**Expected behavior**
Only one entry should be created in the "ticket" table and subsequent requests should not fail.

**Screenshots**
![image](https://user-images.githubusercontent.com/1357456/96506634-a63b5a00-1260-11eb-8a46-c29c7d3dd42f.png)

**Additional context**
Error log from api service:
```2020-10-13 15:24:20.765 ERROR 1 --- [io-8585-exec-52] c.e.t.r.c.e.rest.RestExceptionHandler    : Handled error:
javax.persistence.NonUniqueResultException: query did not return a unique result: 10
	at org.hibernate.internal.ExceptionConverterImpl.convert(ExceptionConverterImpl.java:128)
	at org.hibernate.query.internal.AbstractProducedQuery.getSingleResult(AbstractProducedQuery.java:1581)
	at org.hibernate.query.criteria.internal.compile.CriteriaQueryTypeQueryAdapter.getSingleResult(CriteriaQueryTypeQueryAdapter.java:111)
	at org.springframework.data.jpa.repository.query.JpaQueryExecution$SingleEntityExecution.doExecute(JpaQueryExecution.java:196)
	at org.springframework.data.jpa.repository.query.JpaQueryExecution.execute(JpaQueryExecution.java:88)
	at org.springframework.data.jpa.repository.query.AbstractJpaQuery.doExecute(AbstractJpaQuery.java:154)
	at org.springframework.data.jpa.repository.query.AbstractJpaQuery.execute(AbstractJpaQuery.java:142)
	at org.springframework.data.repository.core.support.RepositoryFactorySupport$QueryExecutorMethodInterceptor.doInvoke(RepositoryFactorySupport.java:618)
	at org.springframework.data.repository.core.support.RepositoryFactorySupport$QueryExecutorMethodInterceptor.invoke(RepositoryFactorySupport.java:605)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186)
	at org.springframework.data.projection.DefaultMethodInvokingMethodInterceptor.invoke(DefaultMethodInvokingMethodInterceptor.java:80)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186)
	at org.springframework.transaction.interceptor.TransactionAspectSupport.invokeWithinTransaction(TransactionAspectSupport.java:353)
	at org.springframework.transaction.interceptor.TransactionInterceptor.invoke(TransactionInterceptor.java:99)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186)
	at org.springframework.dao.support.PersistenceExceptionTranslationInterceptor.invoke(PersistenceExceptionTranslationInterceptor.java:139)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186)
	at org.springframework.data.jpa.repository.support.CrudMethodMetadataPostProcessor$CrudMethodMetadataPopulatingMethodInterceptor.invoke(CrudMethodMetadataPostProcessor.java:149)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186)
	at org.springframework.aop.interceptor.ExposeInvocationInterceptor.invoke(ExposeInvocationInterceptor.java:93)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186)
	at org.springframework.aop.framework.JdkDynamicAopProxy.invoke(JdkDynamicAopProxy.java:212)
	at com.sun.proxy.$Proxy266.findByTicketId(Unknown Source)
	at com.epam.ta.reportportal.core.item.impl.UpdateTestItemHandlerImpl.lambda$collectTickets$29(UpdateTestItemHandlerImpl.java:413)
	at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193)
	at java.util.HashMap$KeySpliterator.forEachRemaining(HashMap.java:1556)
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:482)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:472)
```

**Comment by VolhaKarenko** [comment] 2020-11-19 12:29
The issue is fixed in version 5.1

**Closed by VolhaKarenko** 2020-11-19 12:29 UTC
Labels: Check: Test
