### ISSUE TITLE
not possible to select jira (or any bug tracking system) 

### ISSUE THREAD

**Issue by tarek-vader** [reportportal/reportportal#360] opened 2018-02-22 17:13 UTC
hi, am logged in as admin, i want to configure jira, but its not possible..
its stated , "To configure Bug Tracking System, please deploy appropriate micro-service" how do i fix this?

![image](https://user-images.githubusercontent.com/35951996/36553192-fb798b84-17fb-11e8-8561-cce19f70656d.png)

**Comment by avarabyeu** [comment] 2018-02-22 21:01
@tarek-vader have you started jira service? is it started successfully?

**Comment by tarek-vader** [comment] 2018-02-23 10:48
hi again, now i can see that jira available, acutally i didnt do anything new..
but i see not possible to interact with external system
![image](https://user-images.githubusercontent.com/35951996/36590603-7af97e44-188f-11e8-9952-5b728c4ca3e7.png)

**Comment by avarabyeu** [comment] 2018-02-23 11:02
@tarek-vader could you please send us the response from 
http://your_server/composite/health and http://your_server/composite/info

**Comment by evjlobanova** [comment] 2018-02-23 11:02
@tarek-vader could you please the following thing:
1. Check a rightness of link to Jira:
f.e. *https://jira.*.com* should be written as *https://jira.*.com/jira*

2. Check if your jira account is not expired. 
Log in Jira using basic authorization, i.e. enter your credentials in login form. In case of captcha, fill all required data and login jira. If it is ok, please try to connect to Jira from RP once again.

Try this, and let us know the results.

**Comment by tarek-vader** [comment] 2018-02-23 11:32
great ,  it worked)))

health:

{"API":{"build":{"branch":"pre-3.3.2-5adc6534243105c5f9061fd663b5b0c591749d55","description":"ReportPortal API Service","name":"API Service","repo":"reportportal/service-api","version":"3.3.2"},"extensions":{"analytics":{"all":{"enabled":true}},"bugtracking":["jira"],"instanceId":"06f27944-4558-467a-8687-5da5e4eacee1"},"metadata":{"activitiesEventType":["create_dashboard","update_dashboard","delete_dashboard","create_widget","update_widget","delete_widget","create_filter","update_filter","delete_filter","update_defect","delete_defect","create_bts","update_bts","delete_bts","start_launch","finish_launch","delete_launch","update_project","post_issue","attach_issue","update_item","create_user","start_import","finish_import"],"activitiesObjectType":["project","defect_type","testItem","launch","externalSystem","dashboard","user","widget","userFilter"],"keepLogsDelay":["2 weeks","1 month","3 months","6 months"]}},"CONSUL":{"status":"UNKNOWN"},"GATEWAY":{"status":"UNKNOWN"},"INDEX":{"status":"UP"},"JIRA":{"description":"Spring Cloud Consul Discovery Client","status":"UP"},"UAT":{"description":"Spring Cloud Consul Discovery Client","status":"UP"},"UI":{"status":"UP"}}

Info:
{"API":{"build":{"branch":"pre-3.3.2-5adc6534243105c5f9061fd663b5b0c591749d55","description":"ReportPortal API Service","name":"API Service","repo":"reportportal/service-api","version":"3.3.2"},"extensions":{"analytics":{"all":{"enabled":true}},"bugtracking":["jira"],"instanceId":"06f27944-4558-467a-8687-5da5e4eacee1"},"metadata":{"activitiesEventType":["create_dashboard","update_dashboard","delete_dashboard","create_widget","update_widget","delete_widget","create_filter","update_filter","delete_filter","update_defect","delete_defect","create_bts","update_bts","delete_bts","start_launch","finish_launch","delete_launch","update_project","post_issue","attach_issue","update_item","create_user","start_import","finish_import"],"activitiesObjectType":["project","defect_type","testItem","launch","externalSystem","dashboard","user","widget","userFilter"],"keepLogsDelay":["2 weeks","1 month","3 months","6 months"]}},"INDEX":{"build":{"branch":"4688413","build_date":"2017-08-04T21:53:30+0300","name":"Service Index","repo":"reportportal/service-index","version":"3.1.1"}},"JIRA":{"build":{"branch":"master-a9330f13bf028aaba16dc40af94d7063785175e6","description":"ReportPortal Jira Integration","name":"Jira Service","repo":"reportportal/service-jira","version":"3.3.0"}},"UAT":{"auth_extensions":{},"build":{"branch":"master-831a496cd9f635e705d2b5da0f3a0fd43ef75d48","description":"Unified Authorization Trap for all ReportPortal's Services","name":"Authorization Service","repo":"reportportal/service-authorization","version":"3.3.0"},"metadata":{"project_roles":["OPERATOR","CUSTOMER","MEMBER","PROJECT_MANAGER"]}},"UI":{"build":{"branch":"e8342a2","build_date":"2017-11-17T18:28:10+0300","name":"Service UI","repo":"reportportal/service-ui","version":"3.3.2"}}}

**Comment by schandrakandi** [comment] 2018-02-28 10:34
Hi How did you fix the issue? i am facing the same error

**Comment by evjlobanova** [comment] 2018-02-28 10:36
@tarek-vader could you please share your experience with @schandrakandi ?

**Comment by shaburov** [comment] 2018-03-07 19:46
If I'm not mistaken this error occurs if the user does not have permission to access the selected project or specified the project name instead of the project key.
![image](https://user-images.githubusercontent.com/15269131/37114444-6ad621e2-2259-11e8-8d96-a607ffcdef08.png)

**Comment by tarek-vader** [comment] 2018-03-15 23:06
hi, i think the jira-service needs sometimes to start up...so specially if you freshly start your ubunto machine..jira service was not accessible directly..i needs few minutes to start up..this is my experience..

**Comment by braindonor** [comment] 2018-03-29 16:12
I'm seeing the same message.    In my case I believe that it is caused by trying connect to jira with ssl when reportportal is not configured with ssl.

I was able to connect to a non-ssl jira successfully.     I'm going to try to reconfigure my reportportal to use ssl and attempt to connect to the ssl jira again.

**Comment by DzmitryHumianiuk** [comment] 2018-08-06 08:33
@tarek-vader @braindonor did you find solution?
Does it work for you?

**Comment by DarthRumata** [comment] 2018-08-22 11:34
I fix it for me by deleting Rally container from docker-compose and rebuild.

**Comment by braindonor** [comment] 2018-08-22 11:55
Yes, setting reportportal to ssl enabled me to successfully connect to Jira (configured with ssl).

**Comment by DarthRumata** [comment] 2018-08-22 12:13
@braindonor How can I understand that JIRA is configured with ssl. And how do you set reportportal to ssl?

**Comment by DarthRumata** [comment] 2018-08-22 12:27
@braindonor I added cert to cacerts store as you mentioned in #405 but it still returns me error:
 <meta name="application-name" content="JIRA" data-name="jira" data-version="1001.0.0-SNAPSHOT">
</head>
<body id="jira" class="aui-layout aui-style-default page-type-message"  data-version="1001.0.0-SNAPSHOT" >
    <div class="aui-page-panel"><div class="aui-page-panel-inner">
            <section class="aui-page-panel-content">
                    <header class="aui-page-header"><div class="aui-page-header-inner">
                            <div class="aui-page-header-main">
                                    <h1>Unauthorized (401)</h1>
                                </div>
                        </div></header>
                    <div class="aui-message aui-message-warning warning">
                            <p>Encountered a <code>&quot;401 - Unauthorized&quot;</code> error while loading this page.</p>
                            <p><a href="/secure/MyJiraHome.jspa">Go to Jira home</a></p>
                        </div>
                </section>
        </div></div>
</body>
</html>

**Comment by DzmitryHumianiuk** [comment] 2018-08-23 09:28
@DarthRumata just see at Jira address. If it starts with `https` - then it's under SSL

**Comment by DarthRumata** [comment] 2018-08-28 14:01
Resolved by using JIRA API Token as password.
https://confluence.atlassian.com/cloud/api-tokens-938839638.html

**Comment by DzmitryHumianiuk** [comment] 2018-08-28 14:08
@DarthRumata Ahahah! awesome!

@evjlobanova plz save it for FAQ page.
SSL instance of JIRA (even cloud version) can be accessed by JIRA API token, used instead of password

**Comment by evjlobanova** [comment] 2020-03-20 14:01
In version 5.0 we have implemented Jira as a plugin.
Also versions 5.0 can operate with the latest Jira versions.

**Closed by evjlobanova** 2020-03-20 14:01 UTC
Labels: help wanted, question
