### ISSUE TITLE
API Page supports only port 8080

### ISSUE THREAD

**Issue by rkumarrb** [reportportal/reportportal#953] opened 2020-05-07 14:14 UTC
**Describe the bug**
API(/ui/#api) page supports only port 8080. We hosted Report portal in K8 and our service using different port and we were not able to use API page to try the apis. It throws the error "TypeError: NetworkError when attempting to fetch resource."

**Expected behavior**
Report portal should auto detect the port in use and use the same for API or it should provide option to the user to change it

**Screenshots**
![image](https://user-images.githubusercontent.com/6379299/81304686-5f0f3300-904b-11ea-9151-85b82f215762.png)

**Versions:**
 - OS, Browser : Mac, Chrome and Firefox
 - Version of RP [find it under Login form, copy as is] : 5.1

**Comment by alena-babrova** [comment] 2022-12-26 20:17
Hello @rkumarrb
Could you please tell me if the issue is still relevant?

**Comment by alena-babrova** [comment] 2023-01-18 13:28
As we haven't received a reply from you, we'll close the issue for now.
Just in case you still have the issue, please, do not hesitate to get in touch.

**Closed by alena-babrova** 2023-01-18 13:28 UTC
Labels: bug, Waiting Info From Requestor

**Comment by rambangaru** [comment] 2023-01-18 14:34
it is not relevant anymore, the latest version has fix.
