### ISSUE TITLE
Launches order displayed in back order on Launch statistics chart

### ISSUE THREAD

**Issue by silverio82** [reportportal/reportportal#2393] opened 2024-10-31 00:53 UTC
Launches order displayed in back order on "Launch statistics chart" widget

![image](https://github.com/user-attachments/assets/bac9b32c-01d8-4007-906a-8c403bc340d1)

Build 5.12.0

**Comment by Pink-Bumblebee** [comment] 2024-10-31 05:25
Hello @silverio82 , thank you for highlight. 
By the way, are you using firefox?

**Comment by Kozovskaya** [comment] 2024-10-31 07:54
Duplicate of https://github.com/reportportal/reportportal/issues/2381

**Comment by silverio82** [comment] 2024-10-31 12:32
@Pink-Bumblebee nope. I use Chrome on Mac

**Comment by silverio82** [comment] 2024-10-31 12:33
As mentioned it is a duplicate of https://github.com/reportportal/reportportal/issues/2381

**Closed** 2024-10-31 12:33 UTC
Labels: bug
