### ISSUE TITLE
[v5]  In step level when applied sort Asc/Des on Defect Type column it throws an error

### ISSUE THREAD

**Issue by darshanraut123** [reportportal/reportportal#1489] opened 2021-08-03 08:43 UTC
**Describe the bug**
When we navigate to the page inside scenario level where the list of steps are available,
if we apply sort on a column named "Defect Type", it throws an error with a popup [Attching the sortError.txt file]
FYI: On other all columns the sort is working fine.

**To Reproduce**
Attached is the GIF file for the same with all steps.

**Expected behavior**
The sort should be applied on the Defect Type column without an error popup.

**Desktop :
 - OS: [Windows 10]
 - Browser [chrome]
 - Version [Version 91.0.4472.164 (Official Build) (64-bit)]

BUILD : Build: 5.3.5
Gif and error stack trace : 
![Bug](https://user-images.githubusercontent.com/56134448/127985620-6e83fda0-ef9d-4af0-9eda-cfdf05f66c4d.gif)
[sortError.txt](https://github.com/reportportal/reportportal/files/6922747/sortError.txt)

Darshan Raut
darshanraut123@live.com

**Comment by irynakozak2** [comment] 2021-08-04 13:54
Please, update ReportPortal to the latest version and recheck the behavior. Not reproducible in our regular environments.

**Comment by evjlobanova** [comment] 2021-08-19 06:45
Hello @darshanraut123 this is a known issue 
As far as it requires significant refactoring, we put away this fix for a while

**Comment by evjlobanova** [comment] 2021-08-19 06:46
Closed as a duplicate of #1298
Please follow the progress in the mentioned issue

**Closed by evjlobanova** 2021-08-19 06:46 UTC
Labels: bug
