### ISSUE TITLE
ReportPortal Exсeption status 406 -REPORTING_ITEM_ALREADY_FINISHED

### ISSUE THREAD

**Issue by msgdinesh** [reportportal/reportportal#703] opened 2019-09-09 18:57 UTC
![image](https://user-images.githubusercontent.com/50930635/64558078-a8668180-d308-11e9-9315-d43020f08a35.png)

Client version:
 API Service: 4.3.4; Index Service: 4.2.0; Jira Service: 4.3.0; Rally Service: 4.3.0; Authorization Service: 4.2.0; Service UI: 4.3.6;

Tool: 
SOAP UI version 5.2.1

Listener Files:
![image](https://user-images.githubusercontent.com/50930635/64558175-ef547700-d308-11e9-8ee0-59fe938673b6.png)

Pom File Listener defn:
![image](https://user-images.githubusercontent.com/50930635/64558322-33477c00-d309-11e9-8c7e-33bcad600cc9.png)

Test Initiation:
Jenkins scheduled Job from GIT.

Note:
when the suite is triggered locally using the SOAPUI desktop version , no error is triggered.

**Comment by DzmitryHumianiuk** [comment] 2019-09-10 15:02
@msgdinesh this might be a specific of SOAP you runner in GIT.

could you please try it against beta version?
at http://beta.demo.reportportal.io
login with github credentials.

beta version has APIv5, which has this constrain removed (i mean, error 406)

**Comment by evjlobanova** [comment] 2020-03-31 09:57
@msgdinesh I closed this issue, but if the problem is still actual, feel free to reopen it.

**Closed by evjlobanova** 2020-03-31 09:57 UTC
Labels: bug, component:agent
