### ISSUE TITLE
Error Message: Start time of child ['Wed Jul 19 12:53:49 UTC 2017'] item should be same or later than start time ['Wed Jul 19 12:53:49 UTC 2017'] of the parent item/launch '596f565d2ab79c0007b48b46' Error Type: CHILD_START_TIME_EARLIER_THAN_PARENT

### ISSUE THREAD

**Issue by dkozlov** [reportportal/reportportal#188] opened 2017-07-19 12:57 UTC
Periodically I receive following error messages:

Status code: 406
Status message: 
Error Message: Start time of child ['Wed Jul 19 12:53:49 UTC 2017'] item should be same or later than start time ['Wed Jul 19 12:53:49 UTC 2017'] of the parent item/launch '596f565d2ab79c0007b48b46'
Error Type: CHILD_START_TIME_EARLIER_THAN_PARENT

	at io.reactivex.internal.functions.Functions$14.accept(Functions.java:229)
	at io.reactivex.internal.functions.Functions$14.accept(Functions.java:226)
	at io.reactivex.internal.operators.maybe.MaybeCallbackObserver.onError(MaybeCallbackObserver.java:81)
	at io.reactivex.internal.operators.maybe.MaybeSubscribeOn$SubscribeOnMaybeObserver.onError(MaybeSubscribeOn.java:96)
	at io.reactivex.internal.operators.maybe.MaybeCache.onError(MaybeCache.java:103)
	at io.reactivex.internal.operators.maybe.MaybeFlatten$FlatMapMaybeObserver$InnerObserver.onError(MaybeFlatten.java:125)
	at io.reactivex.internal.operators.maybe.MaybeFlatten$FlatMapMaybeObserver$InnerObserver.onError(MaybeFlatten.java:125)
	at io.reactivex.internal.operators.maybe.MaybeMap$MapMaybeObserver.onError(MaybeMap.java:94)
	at io.reactivex.internal.operators.maybe.MaybePeek$MaybePeekObserver.onErrorInner(MaybePeek.java:147)
	at io.reactivex.internal.operators.maybe.MaybePeek$MaybePeekObserver.onError(MaybePeek.java:134)
	at io.reactivex.internal.operators.maybe.MaybePeek$MaybePeekObserver.onErrorInner(MaybePeek.java:147)
	at io.reactivex.internal.operators.maybe.MaybePeek$MaybePeekObserver.onError(MaybePeek.java:134)
	at io.reactivex.internal.operators.maybe.MaybeFlatten$FlatMapMaybeObserver.onError(MaybeFlatten.java:103)
	at io.reactivex.internal.operators.maybe.MaybeSubscribeOn$SubscribeOnMaybeObserver.onError(MaybeSubscribeOn.java:96)
	at io.reactivex.internal.operators.maybe.MaybeCache.onError(MaybeCache.java:103)
	at io.reactivex.internal.operators.maybe.MaybeCreate$Emitter.onError(MaybeCreate.java:94)
	at com.epam.restendpoint.http.HttpClientRestEndpoint$1$1.completed(HttpClientRestEndpoint.java:569)
	at com.epam.restendpoint.http.HttpClientRestEndpoint$1$1.completed(HttpClientRestEndpoint.java:518)
	at rp.org.apache.http.concurrent.BasicFuture.completed(BasicFuture.java:119)
	at rp.org.apache.http.impl.nio.client.DefaultClientExchangeHandlerImpl.responseCompleted(DefaultClientExchangeHandlerImpl.java:177)
	at rp.org.apache.http.nio.protocol.HttpAsyncRequestExecutor.processResponse(HttpAsyncRequestExecutor.java:436)
	at rp.org.apache.http.nio.protocol.HttpAsyncRequestExecutor.inputReady(HttpAsyncRequestExecutor.java:326)
	at rp.org.apache.http.impl.nio.DefaultNHttpClientConnection.consumeInput(DefaultNHttpClientConnection.java:265)
	at rp.org.apache.http.impl.nio.client.InternalIODispatch.onInputReady(InternalIODispatch.java:81)
	at rp.org.apache.http.impl.nio.client.InternalIODispatch.onInputReady(InternalIODispatch.java:39)
	at rp.org.apache.http.impl.nio.reactor.AbstractIODispatch.inputReady(AbstractIODispatch.java:114)
	at rp.org.apache.http.impl.nio.reactor.BaseIOReactor.readable(BaseIOReactor.java:162)
	at rp.org.apache.http.impl.nio.reactor.AbstractIOReactor.processEvent(AbstractIOReactor.java:337)
	at rp.org.apache.http.impl.nio.reactor.AbstractIOReactor.processEvents(AbstractIOReactor.java:315)
	at rp.org.apache.http.impl.nio.reactor.AbstractIOReactor.execute(AbstractIOReactor.java:276)
	at rp.org.apache.http.impl.nio.reactor.BaseIOReactor.execute(BaseIOReactor.java:104)
	at rp.org.apache.http.impl.nio.reactor.AbstractMultiworkerIOReactor$Worker.run(AbstractMultiworkerIOReactor.java:588)
	at java.lang.Thread.run(Thread.java:748)
Caused by: com.epam.reportportal.exception.ReportPortalException: Report Portal returned error
Status code: 406
Status message: 
Error Message: Start time of child ['Wed Jul 19 12:53:49 UTC 2017'] item should be same or later than start time ['Wed Jul 19 12:53:49 UTC 2017'] of the parent item/launch '596f565d2ab79c0007b48b46'
Error Type: CHILD_START_TIME_EARLIER_THAN_PARENT

**Comment by nvborisenko** [comment] 2017-07-19 17:35
It seems the server doesn't accept start time of child even when start time of child equals start time of parent. All agents in .Net add 1ms to avoid this limitation.

**Comment by avarabyeu** [comment] 2017-07-19 19:24
@dkozlov agent type and version?

**Comment by dkozlov** [comment] 2017-07-20 10:46
@avarabyeu https://github.com/reportportal/agent-java-cucumber 

<dependency>
  <groupId>com.epam.reportportal</groupId>
  <artifactId>agent-java-cucumber</artifactId>
  <version>3.0.0-BETA-1</version>
</dependency>

**Comment by avarabyeu** [comment] 2017-07-31 20:28
@dkozlov could you please try the latest version which is 3.0.0 (not a beta)

**Comment by avarabyeu** [comment] 2017-08-06 22:12
@dkozlov Is this issue still reproduced with latest version?

**Comment by dkozlov** [comment] 2017-08-15 09:27
@avarabyeu I could not check agent-java-cucumber 3.0.0 because this issue blocked by https://github.com/reportportal/agent-java-cucumber/issues/5

**Comment by SKharlanov** [comment] 2017-08-21 10:19
Reproduced for me with
`               <dependency>
			<groupId>com.epam.reportportal</groupId>
			<artifactId>agent-java-cucumber</artifactId>
			<version>3.0.0</version>
		</dependency>`

**Comment by avarabyeu** [comment] 2017-08-22 09:25
@SKharlanov could you please try again? reportportal/reportportal#221 is fixed.

**Comment by SKharlanov** [comment] 2017-10-17 13:18
@avarabyeu 
It reproduced again with
<dependency> <groupId>com.epam.reportportal</groupId> <artifactId>agent-java-cucumber</artifactId> <version>3.0.1</version> </dependency>

**Comment by DzmitryHumianiuk** [comment] 2017-10-27 16:06
@avarabyeu what is label `next`?

**Comment by avarabyeu** [comment] 2017-11-10 12:52
@DzmitryHumianiuk see waffle.io

**Comment by Savostytskyi** [comment] 2018-01-04 13:34
I faced with same issue when I using ScenarioReporter for cucumber. And I've found what the problem is. It happens bacause:
`	protected void beforeFeature(Feature feature) {
                ...
		rq.setStartTime(Calendar.getInstance().getTime());
                ...
	}`
of AbstractReporter class executing before initialization of parent item in ScenarioReporter class:
`	protected Supplier<Maybe<String>> rootSuiteId = Suppliers.memoize(new Supplier<Maybe<String>>() {
		@Override
		public Maybe<String> get() {
			................................
			rq.setStartTime(Calendar.getInstance().getTime());
			................................
		}
	});`
to solve this problem you should just init `**rootSuiteId**` before `**beforeFeature(...)** ` method will be executed

**Comment by avarabyeu** [comment] 2018-01-04 14:32
@Savostytskyi thank you! will you be able to fix it and submit PR?

**Comment by Savostytskyi** [comment] 2018-01-05 17:00
@avarabyeu Yes, no problem it's very small fix, [PR](https://github.com/reportportal/agent-java-cucumber/pull/8) created

**Comment by avarabyeu** [comment] 2018-01-19 19:24
@Savostytskyi can we close the issue?

**Comment by Savostytskyi** [comment] 2018-01-22 08:47
@avarabyeu I think yes, for me it works fine.

**Comment by dkozlov** [comment] 2018-02-27 10:15
@avarabyeu Unfortunately I can not test this issue now

**Closed** 2018-02-28 11:33 UTC
Labels: bug, component:agent, next
