### ISSUE TITLE
Post Bug: add possibility to add own description for created issue

### ISSUE THREAD

**Issue by DzmitryHumianiuk** [reportportal/reportportal#108] opened 2017-04-26 12:30 UTC
Add possibility to add own description for created issue,
not only included log of test fail

**Comment by avarabyeu** [comment] 2017-09-12 15:38
duplicate of #reportportal/reportportal#67

**Comment by avarabyeu** [comment] 2017-09-12 15:39
closing in favor of reportportal/reportportal#67

**Closed by avarabyeu** 2017-09-12 15:39 UTC
Labels: enhancement
