### ISSUE TITLE
Reportportal not getting the execution data when installed in Remote machine

### ISSUE THREAD

**Issue by priyankab1983** [reportportal/reportportal#2256] opened 2024-04-08 10:36 UTC
Reportportal is installed in the remotemachine. the automation code is selenium+java+cucumber6+testng. Used the configuration for cucumber6 for reportportal configuration. However the execution is not started, the error seen -                                                                    
com.epam.reportportal.exception.InternalReportPortalClientException: Wait for Launch start timed out

	at com.epam.reportportal.utils.Waiter.till(Waiter.java:126)
	at com.epam.reportportal.service.launch.SecondaryLaunch.waitForLaunchStart(SecondaryLaunch.java:57)
	at com.epam.reportportal.service.launch.SecondaryLaunch.start(SecondaryLaunch.java:89)
	at com.epam.reportportal.cucumber.AbstractReporter$1.get(AbstractReporter.java:137)
	at com.epam.reportportal.cucumber.AbstractReporter$1.get(AbstractReporter.java:128)
	at com.epam.reportportal.utils.MemoizingSupplier.get(MemoizingSupplier.java:47)
	at com.epam.reportportal.cucumber.AbstractReporter.getLaunch(AbstractReporter.java:177)
	at com.epam.reportportal.cucumber.AbstractReporter.beforeLaunch(AbstractReporter.java:184)
	at com.epam.reportportal.cucumber.ScenarioReporter.beforeLaunch(ScenarioReporter.java:59)
	at com.epam.reportportal.cucumber.AbstractReporter.lambda$getTestRunStartedHandler$32(AbstractReporter.java:776)
	at io.cucumber.core.eventbus.AbstractEventPublisher.send(AbstractEventPublisher.java:51)
	at io.cucumber.core.eventbus.AbstractEventBus.send(AbstractEventBus.java:12)
	at io.cucumber.core.runtime.SynchronizedEventBus.send(SynchronizedEventBus.java:47)
	at io.cucumber.core.runtime.CucumberExecutionContext.emitTestRunStarted(CucumberExecutionContext.java:88)
	at io.cucumber.core.runtime.CucumberExecutionContext.startTestRun(CucumberExecutionContext.java:58)
	at io.cucumber.testng.TestNGCucumberRunner.<init>(TestNGCucumberRunner.java:123)
	at io.cucumber.testng.AbstractTestNGCucumberTests.setUpClass(AbstractTestNGCucumberTests.java:27)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
	at org.testng.internal.invokers.MethodInvocationHelper.invokeMethodConsideringTimeout(MethodInvocationHelper.java:69)
	at org.testng.internal.invokers.ConfigInvoker.invokeConfigurationMethod(ConfigInvoker.java:390)
	at org.testng.internal.invokers.ConfigInvoker.invokeConfigurations(ConfigInvoker.java:325)
	at org.testng.internal.invokers.TestMethodWorker.invokeBeforeClassMethods(TestMethodWorker.java:180)
	at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:122)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1541)
	at org.testng.TestRunner.privateRun(TestRunner.java:848)
	at org.testng.TestRunner.run(TestRunner.java:621)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:443)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:437)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:397)
	at org.testng.SuiteRunner.run(SuiteRunner.java:336)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1280)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1200)
	at org.testng.TestNG.runSuites(TestNG.java:1114)
	at org.testng.TestNG.run(TestNG.java:1082)
	at com.intellij.rt.testng.IDEARemoteTestNG.run(IDEARemoteTestNG.java:66)
	at com.intellij.rt.testng.RemoteTestNGStarter.main(RemoteTestNGStarter.java:109)

**Comment by alena-babrova** [comment] 2024-04-30 07:55
Hello @priyankab1983,

Could you please tell me if the issue is still relevant?
Have you checked that you configured your client appropriately?
https://github.com/reportportal/agent-java-cucumber

**Comment by alena-babrova** [comment] 2024-05-15 09:45
Dear @priyankab1983,

As we haven't received a reply from you, we'll close the issue for now.
Just in case you still have the issue, please, do not hesitate to get in touch.

**Closed by alena-babrova** 2024-05-15 09:45 UTC
Labels: help wanted
