### ISSUE TITLE
XML result not loading

### ISSUE THREAD

**Issue by BrijeshKrishnan** [reportportal/reportportal#1975] opened 2023-04-04 08:54 UTC
I was trying to load the xml result (via UI) of nunit execution to reportportal, it says "Launch null not found, did you use correct launch ID?"
Sample xml i tried is also available [here](https://github.com/x97mdr/pickles/blob/master/src/Pickles/Pickles.Test/results-example-nunit.xml)

reportportal: Build: 5.6.0© Report Portal 2023 All rights reserved

**Comment by MaryiaRymarchyk** [comment] 2023-04-05 13:44
Hi @BrijeshKrishnan,
first of all i would recommend you to use latest version of Report Portal which is [5.7.4](https://github.com/reportportal/reportportal/releases/tag/5.7.4)
The second point - try to use other naming  (e.g. results -> testcase, failure - >error etc.) 
When i upload the file to our internal server with naming like you do - it fails with same error, but when i change the names - it works fine.
Let me know if it helps or you need further support.

**Comment by BrijeshKrishnan** [comment] 2023-04-06 05:50
i have changed the xml as you mentioned for testing but no success. 

`<?xml version="1.0" encoding="utf-8" standalone="no"?>


<test-results
name="c:\dev\pickles-results-harness\Pickles.TestHarness\Pickles.TestHarness.NUnit\bin\Debug\Pickles.TestHarness.NUnit.dll"
total="4" errors="0" failures="1" not-run="0" inconclusive="0" ignored="0" skipped="0" invalid="0" date="2012-01-14"
time="10:43:31">
  <environment nunit-version="2.5.10.11092" clr-version="2.0.50727.5448"
               os-version="Microsoft Windows NT 6.1.7601 Service Pack 1" platform="Win32NT" cwd="c:\dev\pickles-results-harness"
               machine-name="BUMBLEBEE" user="camejef" user-domain="BUMBLEBEE" />
  <culture-info current-culture="en-US" current-uiculture="en-US" />
  <test-suite type="Assembly"
              name="c:\dev\pickles-results-harness\Pickles.TestHarness\Pickles.TestHarness.NUnit\bin\Debug\Pickles.TestHarness.NUnit.dll"
              executed="True" result="Failure" success="False" time="0.732" asserts="0">
    <testcase>
      <test-suite type="Namespace" name="Pickles" executed="True" result="Failure" success="False" time="0.725"
                  asserts="0">
        <testcase>
          <test-suite type="Namespace" name="TestHarness" executed="True" result="Failure" success="False" time="0.725"
                      asserts="0">
            <testcase>
              <test-suite type="TestFixture" name="AdditionFeature" description="Addition" executed="True"
                          result="Failure" success="False" time="0.724" asserts="0">
                <testcase>
                  <test-suite type="ParameterizedTest" name="AddingSeveralNumbers" description="Adding several numbers"
                              executed="True" result="Success" success="True" time="0.157" asserts="0">
                    <categories>
                      <category name="tag2" />
                    </categories>
                    <testcase>
                      <test-case
name="Pickles.TestHarness.AdditionFeature.AddingSeveralNumbers(&quot;60&quot;,&quot;70&quot;,&quot;130&quot;,System.String[])"
executed="True" result="Success" success="True" time="0.137" asserts="1" />
                      <test-case
name="Pickles.TestHarness.AdditionFeature.AddingSeveralNumbers(&quot;40&quot;,&quot;50&quot;,&quot;90&quot;,System.String[])"
executed="True" result="Success" success="True" time="0.009" asserts="1" />
                    </testcase>
                  </test-suite>
                  <test-case name="Pickles.TestHarness.AdditionFeature.AddTwoNumbers" description="Add two numbers"
                             executed="True" result="Success" success="True" time="0.004" asserts="0">
                    <categories>
                      <category name="tag1" />
                    </categories>
                  </test-case>
                  <test-case name="Pickles.TestHarness.AdditionFeature.FailToAddTwoNumbers"
                             description="Fail to add two numbers" executed="True" result="Failure" success="False" time="0.028" asserts="0">
                    <categories>
                      <category name="tag1" />
                    </categories>
                    <error>
                      <message><![CDATA[]]></message>
                      <stack-trace>
                        <![CDATA[at Pickles.TestHarness.xUnit.Steps.ThenTheResultShouldBePass(Int32 result) in C:\dev\pickles-results-harness\Pickles.TestHarness\Pickles.TestHarness.NUnit\Steps.cs:line 26
at lambda_method(Closure , IContextManager , Int32 )
at TechTalk.SpecFlow.Bindings.MethodBinding.InvokeAction(IContextManager contextManager, Object[] arguments, ITestTracer testTracer, TimeSpan& duration)
at TechTalk.SpecFlow.Bindings.StepDefinitionBinding.Invoke(IContextManager contextManager, ITestTracer testTracer, Object[] arguments, TimeSpan& duration)
at TechTalk.SpecFlow.Infrastructure.TestExecutionEngine.ExecuteStepMatch(BindingMatch match, Object[] arguments)
at TechTalk.SpecFlow.Infrastructure.TestExecutionEngine.ExecuteStep(StepArgs stepArgs)
at TechTalk.SpecFlow.Infrastructure.TestExecutionEngine.OnAfterLastStep()
at TechTalk.SpecFlow.TestRunner.CollectScenarioErrors()
at Pickles.TestHarness.AdditionFeature.ScenarioCleanup() in C:\dev\pickles-results-harness\Pickles.TestHarness\Pickles.TestHarness.NUnit\Addition.feature.cs:line 0
at Pickles.TestHarness.AdditionFeature.FailToAddTwoNumbers() in c:\dev\pickles-results-harness\Pickles.TestHarness\Pickles.TestHarness.NUnit\Addition.feature:line 18
]]>
                      </stack-trace>
                    </error>
                  </test-case>
                </testcase>
              </test-suite>
            </testcase>
          </test-suite>
        </testcase>
      </test-suite>
    </testcase>
  </test-suite>
</test-results>`

Now it says `Test Item null  not found, did you use correct test item ID? `

Wondering as this is the default nunit report xml, reportportal does not support the default nunit xml import ?

**Comment by MaryiaRymarchyk** [comment] 2023-04-06 13:17
Hi @BrijeshKrishnan , unfortunately i haven't find the cause of errors  yet.
Probably this info will be useful regarding  nunit integration - https://github.com/reportportal/example-net-nunit
I'll continue investigation of the errors when i finished with project tasks.

**Comment by DzmitryHumianiuk** [comment] 2023-10-26 01:25
@MaryiaRymarchyk please take this issue into the upcoming sprint.

**Comment by MaryiaRymarchyk** [comment] 2023-10-26 04:06
@DzmitryHumianiuk @BrijeshKrishnan ticket has been created for the next sprint.

**Comment by IvanKustau** [comment] 2023-11-27 13:18
@BrijeshKrishnan I've checked https://github.com/BrijeshKrishnan/reportportalerror
I can see here, that the XML still contains tags with '-' symbol and it's inconsistent.
I updated file that you've sent to us first, edited tags and import works for me. You can check it here:
https://github.com/IvanKustau/xmlrepo/blob/main/results-example-nunit.xml

**Comment by Kozovskaya** [comment] 2024-02-28 14:36
@BrijeshKrishnan taking into account the above update from @IvanKustau I'm closing the issue. If the issue is still relevant - feel free to open it.

**Closed by Kozovskaya** 2024-02-28 14:36 UTC
Labels: enhancement, Feature: Import
