### ISSUE TITLE
Display test case names in email notification

### ISSUE THREAD

**Issue by araqsa** [reportportal/reportportal#1336] opened 2021-03-10 07:32 UTC
![image](https://user-images.githubusercontent.com/80383201/110592473-c0d08a00-8193-11eb-893c-9053e25cc110.png)
In the report portal notification email our client wants to see test case names with statuses besides the total amount of failed and passed tests. 
Is it possible to add test case names for only one of our test suites ? Because in other test suites we have more than 40 tests and it may seem weird.

**Comment by Kozovskaya** [comment] 2024-02-28 15:17
Closed as duplicate of https://github.com/reportportal/reportportal/issues/2211

**Closed by Kozovskaya** 2024-02-28 15:17 UTC
Labels: feature request, Feature:Notification
