### ISSUE TITLE
Email Notifications are not getting generated

### ISSUE THREAD

**Issue by roopalN** [reportportal/reportportal#1563] opened 2021-10-28 10:32 UTC
**Describe the bug**
Email Notifications fails

**To Reproduce**
Include few valid/existing email Ids as notification subscriber list under email notifications settings for a project
Include 1-2 invalid/non-existing users
Notifications won't be generating at all

**Expected behavior**
Valid users should get notifications for set conditions (launch, launch with specific names etc)

**Desktop (please complete the following information):**
 - Windows
 - Chrome
 - Version [latest]

**Comment by roopalN** [comment] 2021-11-24 05:54
Please tag this as BUG

**Comment by evjlobanova** [comment] 2021-11-25 22:26
Hello @roopalN 
You are right, this is a bug
But the fix is not trivial, it will be fixed after Notification refactoring.

The problem is that when you update 1 rule, the system sends an update for the whole list with notifications rules.

I can propose a workaround for you, you can send a request via API, and add to API call all notification rules and send update

**Comment by roopalN** [comment] 2021-12-06 11:57
@evjlobanova thanks for reverting back, workaround and considering this for upcoming patch release. For now, we are ensuring to keep only valid emails Id as sender and recipient list.

**Comment by alena-babrova** [comment] 2022-11-08 15:05
Hello @roopalN 

We have made significant changes in Notification logic, so now the issue you described should be resolved.
The fix will be available starting from version 5.8.
Please, wait for the 5.8 release. And don't hesitate if you have any questions.

**Closed by alena-babrova** 2022-11-08 15:05 UTC
Labels: bug
