### ISSUE TITLE
Fixed/Resolved Issue Metric

### ISSUE THREAD

**Issue by priyankachaturvedi30** [reportportal/reportportal#1039] opened 2020-06-30 10:31 UTC
Is there a way through which we can capture the fixed/resolved issues over successive launches? 

If there was some issue that got fixed/resolved over successive launches, can we somehow track it? Can we have some mechanism that could populate me with the data related to the issues which are fixed?

**Comment by evjlobanova** [comment] 2020-06-30 10:56
@priyankachaturvedi30  Could you please add details on your use case?

Now we have defect types
Link to BTS
Defect comments 
Attributes

Each of these things can be used for marking issues if they are resolved or not.

Link to BTS, Defect type and Defect comment can be added by Auto-Analysis

**Comment by priyankachaturvedi30** [comment] 2020-06-30 12:11
Yes, so suppose I have my test suite with over 1000+ cases, and my build gets executed on a daily basis and reports get generated which we do the analysis on. Over subsequent runs, there may be multiple issues which are getting fixed. If I want to generate a report capturing information about such issues which are no longer present, can this be achieved through report portal? Just thought, like if we have some way to flag those issue as "fixed" maybe and then get a report, it would be great to track down the fixed issues that are no longer present directly through the portal.

**Comment by priyankachaturvedi30** [comment] 2020-07-02 12:37
As described in one of the features - to track down open issues via widget, on similar lines I propose to track down closed/fixed issues via widget if feasible. Please suggest 
![image](https://user-images.githubusercontent.com/50797731/86359435-9fc3ab00-bc8e-11ea-9b9c-1ae92a38c3c4.png)
.

**Comment by evjlobanova** [comment] 2020-07-08 06:41
We are planning to resolve this issue with adding a possibility to choose status on the widget. Description is here #333
Does it cover your need?

**Comment by priyankachaturvedi30** [comment] 2020-07-14 11:19
This is helpful @evjlobanova . Just a few thoughts around - 
1. Would it be possible to have some widget with information related to bug status? - This will help in getting the issue status summary at the launch level.
2.  Also, Can there be a flag or some highlighter to indicate if the current launch has some issue AA for which the JIRA status is Closed/Resolved? - This would let the user quickly understand that the issue has been reoccurred and needs attention.
3. Like we have a Different launches comparison chart, can we have a similar chart at a test case level, providing details about the 2 launches? - Currently, this chart shows high-level information in % form, which is not much useful (in my use-case) - If some drilled down details information related to the categorization of issues(Count/number of PB, AB, SI ; Jira ID's etc.) is reflected here that would be much more useful.

Please share your thoughts around the above. Thanks much.

**Comment by evjlobanova** [comment] 2020-07-14 11:52
Connected with #1049 1049

**Comment by evjlobanova** [comment] 2020-07-14 11:53
Part of the #333

**Comment by evjlobanova** [comment] 2020-07-14 11:55
@priyankachaturvedi30 I close this issue as a duplicate of #333  
All information regarding BTS widgets, we will be collecting in the mentioned issue.

**Closed by evjlobanova** 2020-07-14 11:55 UTC
Labels: Waiting Info From Requestor, feature request
