### ISSUE TITLE
Almost all long executions contain 433 response

### ISSUE THREAD

**Issue by CaBocuk** [reportportal/reportportal#428] opened 2018-06-13 08:40 UTC
If we have to run regression tests (~3.5h) - almost every execution contains at least one 433 response what makes launch to finish only by timeout and has status INTERRUPTED.

**Statistics:**
Since April 19 only **3 Launches** of 70+ finished without INTERRUPTED status

**We use:** 
- EPAM RP endpoint
- agent-java-testng 4.2.0
- logger-java-log4j 4.0.1
- overrided RP listener which looks like
```Java
public class CustomReportPortalListener extends ReportPortalTestNGListener {

    @Override
    public void onTestFailure (ITestResult result) {
        logEverything(result);
        super.onTestFailure(result);
    }

    @Override
    public void onConfigurationFailure (ITestResult result) {
        logEverything(result);
        super.onConfigurationFailure(result);
    }

    private static void logEverything (ITestResult result) {
        Model.log();
        result.setThrowable(detectThrowable(result.getThrowable()));

        String errorMsg = String.format("Test failed.\nURL: %s\nException: %s\nStack trace:\n%s", url(),
                                        result.getThrowable().getMessage(),
                                        Throwables.getStackTraceAsString(result.getThrowable()));
        SendScreenshot.with(errorMsg, Level.ERROR);
    }
}
```

**Example of exception**
```
[18:28:12] rp-io-18 ERROR (SubscriptionUtils.java:49) - Start test item completed with error 
rp.org.apache.http.NoHttpResponseException: rp.epam.com:443 failed to respond
	at rp.org.apache.http.impl.conn.DefaultHttpResponseParser.parseHead(DefaultHttpResponseParser.java:141) ~[client-java-4.0.8.jar:?]
	at rp.org.apache.http.impl.conn.DefaultHttpResponseParser.parseHead(DefaultHttpResponseParser.java:56) ~[client-java-4.0.8.jar:?]
	at rp.org.apache.http.impl.io.AbstractMessageParser.parse(AbstractMessageParser.java:259) ~[client-java-4.0.8.jar:?]
	at rp.org.apache.http.impl.DefaultBHttpClientConnection.receiveResponseHeader(DefaultBHttpClientConnection.java:163) ~[client-java-4.0.8.jar:?]
	at rp.org.apache.http.impl.conn.CPoolProxy.receiveResponseHeader(CPoolProxy.java:165) ~[client-java-4.0.8.jar:?]
	at rp.org.apache.http.protocol.HttpRequestExecutor.doReceiveResponse(HttpRequestExecutor.java:273) ~[client-java-4.0.8.jar:?]
	at rp.org.apache.http.protocol.HttpRequestExecutor.execute(HttpRequestExecutor.java:125) ~[client-java-4.0.8.jar:?]
	at rp.org.apache.http.impl.execchain.MainClientExec.execute(MainClientExec.java:272) ~[client-java-4.0.8.jar:?]
	at rp.org.apache.http.impl.execchain.ProtocolExec.execute(ProtocolExec.java:185) ~[client-java-4.0.8.jar:?]
	at rp.org.apache.http.impl.execchain.RetryExec.execute(RetryExec.java:89) ~[client-java-4.0.8.jar:?]
	at rp.org.apache.http.impl.execchain.RedirectExec.execute(RedirectExec.java:111) ~[client-java-4.0.8.jar:?]
	at rp.org.apache.http.impl.client.InternalHttpClient.doExecute(InternalHttpClient.java:185) ~[client-java-4.0.8.jar:?]
	at rp.org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:83) ~[client-java-4.0.8.jar:?]
	at rp.org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:108) ~[client-java-4.0.8.jar:?]
	at rp.org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:56) ~[client-java-4.0.8.jar:?]
	at com.epam.reportportal.restendpoint.http.HttpClientRestEndpoint$1.subscribe(HttpClientRestEndpoint.java:493) [client-java-4.0.8.jar:?]
	at io.reactivex.internal.operators.maybe.MaybeCreate.subscribeActual(MaybeCreate.java:45) [rxjava-2.1.6.jar:?]
	at io.reactivex.Maybe.subscribe(Maybe.java:3727) [rxjava-2.1.6.jar:?]
	at io.reactivex.internal.operators.maybe.MaybeCache.subscribeActual(MaybeCache.java:77) [rxjava-2.1.6.jar:?]
	at io.reactivex.Maybe.subscribe(Maybe.java:3727) [rxjava-2.1.6.jar:?]
	at io.reactivex.internal.operators.maybe.MaybeSubscribeOn$SubscribeTask.run(MaybeSubscribeOn.java:54) [rxjava-2.1.6.jar:?]
	at io.reactivex.internal.schedulers.ScheduledDirectTask.call(ScheduledDirectTask.java:38) [rxjava-2.1.6.jar:?]
	at io.reactivex.internal.schedulers.ScheduledDirectTask.call(ScheduledDirectTask.java:26) [rxjava-2.1.6.jar:?]
	at java.util.concurrent.FutureTask.run(FutureTask.java:264) [?:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1135) [?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) [?:?]
	at java.lang.Thread.run(Thread.java:844) [?:?]
[18:28:12] rp-io-18 ERROR (SubscriptionUtils.java:96) - [44] ReportPortal Finish test item execution error
rp.org.apache.http.NoHttpResponseException: rp.epam.com:443 failed to respond
	at rp.org.apache.http.impl.conn.DefaultHttpResponseParser.parseHead(DefaultHttpResponseParser.java:141) ~[client-java-4.0.8.jar:?]
	at rp.org.apache.http.impl.conn.DefaultHttpResponseParser.parseHead(DefaultHttpResponseParser.java:56) ~[client-java-4.0.8.jar:?]
	at rp.org.apache.http.impl.io.AbstractMessageParser.parse(AbstractMessageParser.java:259) ~[client-java-4.0.8.jar:?]
	at rp.org.apache.http.impl.DefaultBHttpClientConnection.receiveResponseHeader(DefaultBHttpClientConnection.java:163) ~[client-java-4.0.8.jar:?]
	at rp.org.apache.http.impl.conn.CPoolProxy.receiveResponseHeader(CPoolProxy.java:165) ~[client-java-4.0.8.jar:?]
	at rp.org.apache.http.protocol.HttpRequestExecutor.doReceiveResponse(HttpRequestExecutor.java:273) ~[client-java-4.0.8.jar:?]
	at rp.org.apache.http.protocol.HttpRequestExecutor.execute(HttpRequestExecutor.java:125) ~[client-java-4.0.8.jar:?]
	at rp.org.apache.http.impl.execchain.MainClientExec.execute(MainClientExec.java:272) ~[client-java-4.0.8.jar:?]
	at rp.org.apache.http.impl.execchain.ProtocolExec.execute(ProtocolExec.java:185) ~[client-java-4.0.8.jar:?]
	at rp.org.apache.http.impl.execchain.RetryExec.execute(RetryExec.java:89) ~[client-java-4.0.8.jar:?]
	at rp.org.apache.http.impl.execchain.RedirectExec.execute(RedirectExec.java:111) ~[client-java-4.0.8.jar:?]
	at rp.org.apache.http.impl.client.InternalHttpClient.doExecute(InternalHttpClient.java:185) ~[client-java-4.0.8.jar:?]
	at rp.org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:83) ~[client-java-4.0.8.jar:?]
	at rp.org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:108) ~[client-java-4.0.8.jar:?]
	at rp.org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:56) ~[client-java-4.0.8.jar:?]
	at com.epam.reportportal.restendpoint.http.HttpClientRestEndpoint$1.subscribe(HttpClientRestEndpoint.java:493) [client-java-4.0.8.jar:?]
	at io.reactivex.internal.operators.maybe.MaybeCreate.subscribeActual(MaybeCreate.java:45) [rxjava-2.1.6.jar:?]
	at io.reactivex.Maybe.subscribe(Maybe.java:3727) [rxjava-2.1.6.jar:?]
	at io.reactivex.internal.operators.maybe.MaybeCache.subscribeActual(MaybeCache.java:77) [rxjava-2.1.6.jar:?]
	at io.reactivex.Maybe.subscribe(Maybe.java:3727) [rxjava-2.1.6.jar:?]
	at io.reactivex.internal.operators.maybe.MaybeSubscribeOn$SubscribeTask.run(MaybeSubscribeOn.java:54) [rxjava-2.1.6.jar:?]
	at io.reactivex.internal.schedulers.ScheduledDirectTask.call(ScheduledDirectTask.java:38) [rxjava-2.1.6.jar:?]
	at io.reactivex.internal.schedulers.ScheduledDirectTask.call(ScheduledDirectTask.java:26) [rxjava-2.1.6.jar:?]
	at java.util.concurrent.FutureTask.run(FutureTask.java:264) [?:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1135) [?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) [?:?]
	at java.lang.Thread.run(Thread.java:844) [?:?]
```

**Comment by evjlobanova** [comment] 2018-06-13 08:45
@avarabyeu could you please look at this issue?

**Comment by avarabyeu** [comment] 2018-07-19 10:18
@CaBocuk we've pushed several adjustments for apache http client. Could you please check whether it helps with 4.2.1-BETA version? It's released and available in public

**Comment by avarabyeu** [comment] 2018-07-23 08:42
>rp.org.apache.http.NoHttpResponseException: The target server failed to respond
which is really better :) 
Could you please try to increase connection timeout settings. Let us know if you need some assistance with that, it can be implemented via custom listener

**Comment by CaBocuk** [comment] 2018-07-24 09:57
@avarabyeu I've configured
```
rp.io.pool.size=50
rp.max.connections.per.route=25
```

But exceptions remained the same. Could you recommend exact values that I should try?

**Comment by DzmitryHumianiuk** [comment] 2019-06-02 09:50
Version 5 will bring updates, which can eliminate root cause of this issues

**Comment by DzmitryHumianiuk** [comment] 2019-10-11 21:42
@CaBocuk we found the issue roots.
It was related to Apache http client specifics.
Time to live for connection pool was just a bit longer then connection ttl on server.
 Fixed in latest v5 beta

@CaBocuk could you please double check at beta instance?

**Closed** 2020-03-03 16:58 UTC
Labels: bug
